### ISSUE TITLE
BatchJobHelper missing in PHP lib?

### ISSUE THREAD

**Issue by josipjelic** [googleads/googleads-php-lib#101]
I'm trying to get use of BatchJobService... However docs are referring to BatchJobHelper which seems to be missing from the lib.

Form the docs:
>The good news is that your client library of choice will have a utility that handles constructing and sending the request for you. The example below uses the BatchJobHelper utility from the Java client library.

Can anyone help me construct proper request and sent it to uploadUrl? Tnx.

**Comment by fiboknacky** [comment]
We're currently developing the utility classes for using BatchJobService.
Sorry for this inconvenience.

**Comment by josipjelic** [comment]
Wow that's great, any ETA on that?

**Comment by bpsenthil** [comment]
$batchJobService = $user->GetService('BatchJobService', ADWORDS_VERSION);
   $operation1 = new BatchJobOperation();
   $operation1->operand = new BatchJob();
   $operation1->operator = 'ADD';
   $operations1[] = $operation1;

  $job = $batchJobService->mutate($operations1);
   echo '<br>batch_job_service';
    
    print_r($job);
   

Senthil Kumar [5:59 PM]
And this one was response : 
---------------------------------------

Senthil Kumar [5:59 PM]
BatchJobReturnValue Object
(
   [value] => Array
       (
           [0] => BatchJob Object
               (
                   [id] => 1061049
                   [status] => AWAITING_FILE
                   [progressStats] => 
                   [uploadUrl] => TemporaryUrl Object
                       (
                           [url] => https://www.googleapis.com/upload/storage/v1/b/batch-job-upload-prod-ebe9b43/o?uploadType=resumable&upload_id=AEnB2UqvyMZP-JoJYD7eoTUc--IORC5TfP0akss-aLSbuvtIroyrdLruUadEbR__xyhlkdrxqYcQD2Z55UJjtJt8JSFbk3xNgw
                           [expiration] => 20151113 025321 America/Los_Angeles
                       )

                   [downloadUrl] => 
                   [processingErrors] => 
               )

       )

   [ListReturnValueType] => BatchJobReturnValue
   [_parameterMap:ListReturnValue:private] => Array
       (
           [ListReturnValue.Type] => ListReturnValueType
       )

)

**Comment by fiboknacky** [comment]
We're working on it, but no ETA at this time. 
I'll reply to this issue once it has been released.

**Comment by fiboknacky** [comment]
This is now available in [v7.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/7.0.0).

**Comment by konstantinnikiforov** [comment]
can't find BatchJobHelper in v7.0.0. Can you point me on a file path and exact line where this class has defined there?

**Comment by fiboknacky** [comment]
Hello @konstantinnikiforov,

Sorry for this confusion, but It's named [BatchJobUtils](https://github.com/googleads/googleads-php-lib/blob/daf1a1bfa6bef01317da7860fc59bcfe7635e52e/src/Google/Api/Ads/AdWords/Util/v201509/BatchJobUtils.php) in this library. 
You can also find how to use this util class at [AddCompleteCampaignsUsingBatchJob.php](https://github.com/googleads/googleads-php-lib/blob/daf1a1bfa6bef01317da7860fc59bcfe7635e52e/examples/AdWords/v201509/CampaignManagement/AddCompleteCampaignUsingBatchJob.php)

I highly recommend you to use our latest release [v8.1.0](https://github.com/googleads/googleads-php-lib/releases/tag/8.1.0).

Cheers,
Knack

**Comment by konstantinnikiforov** [comment]
thank you @fiboknacky
