### ISSUE TITLE
to get Tracking Urls from my DFP account page  using DFP api

### ISSUE THREAD

**Issue by manishkvaish** [googleads/googleads-php-lib#104]
can we get the Tracking Urls from my DFP account page  using DFP api

**Comment by vtsao** [comment]
@manishkvaish since this isn't a PHP client library specific issue, general DFP API questions are better asked on the DFP API forums:
https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api

Please post your question there and we can better assist you. Thanks.
