### ISSUE TITLE
Cannot call constructor

### ISSUE THREAD

**Issue by fiatux** [googleads/googleads-php-lib#107]
When I run `BasicOperations/AddCampaigns.php` example on v201509, I get `Cannot call constructor` error on `CampaignService.php (line 7602)` when I comment out the line, campaigns are created.

**Comment by vtsao** [comment]
Knack can you PTAL when you have a chance.

**Comment by fiboknacky** [comment]
Hello @fiatux,

I can run the code without getting any errors.
Could you please provide more detail about your code and environment?
Do you use the latest version of client lib and what PHP version do you use?

Thanks,
Knack

**Comment by fiatux** [comment]
I am using 5.5.21

It works as follow, please note that parent construct caller is commented out:
```
public function __construct($positiveGeoTargetType = null, $negativeGeoTargetType = null, $SettingType = null) {
      //parent::__construct();
      $this->positiveGeoTargetType = $positiveGeoTargetType;
      $this->negativeGeoTargetType = $negativeGeoTargetType;
      $this->SettingType = $SettingType;
    }
```

**Comment by fiboknacky** [comment]
Hello @fiatux,

One thing I can think of now is your parent class of GeoTargetTypeSetting, which is Setting, might be hidden by another class with the same name in your system.
That error indicate that your class has no constructor, which is not possible, if [Setting](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/v201509/CampaignService.php#L3810) is properly declared

Could you please try using something like [get_class_vars](http://php.net/manual/en/function.get-class-vars.php) to see the structure of **Setting**?
And did you run our client lib examples as is? or did you mix them with other projects / frameworks in your workspace?

It may worth downloading a tar file from [release page](https://github.com/googleads/googleads-php-lib/releases/tag/8.0.0) and trying running the example from that extracted directory.

Best,
Knack

**Comment by fiatux** [comment]
That may be it because I have a class named Setting in my system, which brings us the namespacing problem. When will this SDK have a proper namespace scope so that users won't experience this kind of stuff?

**Comment by fiboknacky** [comment]
We are rewriting the client library, which will support namespacing, but no ETA yet. 
Please stay tuned at #4 for updates.
