### ISSUE TITLE
Please support Composer

### ISSUE THREAD

**Issue by starrychloe** [googleads/googleads-php-lib#108]
This library doesn't appear to work with Composer. See

http://stackoverflow.com/questions/34297226/how-do-i-instantiate-an-object-in-another-namespace-in-yii

and

http://stackoverflow.com/questions/31353444/how-do-i-require-a-file-or-class-in-a-vendor-library-in-yii2-that-is-not-already

**Comment by vtsao** [comment]
There is a Composer file for this library, is it broken?
https://github.com/googleads/googleads-php-lib/blob/master/composer.json

We are also in the process of updating this library to conform to PSR-4 and be more modern in general. Please follow this issue for updates:
https://github.com/googleads/googleads-php-lib/issues/4
