### ISSUE TITLE
Can I run this libary on local machine?

### ISSUE THREAD

**Issue by ALTELMA** [googleads/googleads-php-lib#109]
I cannot get refresh token, because an error 'uri_redirect_mismatch'.
I already create Ouath2. I do something wrong?

Please advice me, please.

**Comment by fiboknacky** [comment]
Hi Phongthorn,

Have you followed our [get started guide](https://developers.google.com/adwords/api/docs/guides/start)?
From this [post](http://stackoverflow.com/questions/11485271/google-oauth-2-authorization-error-redirect-uri-mismatch), it's likely that you've not set up client id and secret correctly.

I recommend you to check your settings, especially those written in this [section](https://developers.google.com/adwords/api/docs/guides/authentication#create_a_client_identifier_and_client_secret) strictly.
Also, please ensure you put in valid [auth.ini](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/auth.ini) too.

If you need any further help, please let me know.

Knack

**Comment by ALTELMA** [comment]
I apologized for unclear questions. I will access to DFP and I already from below list.

1. Already created credentials. I have client_id and client_secret.
2. Turn on API access in Dfp admin.
3. Store client_id, client_secret at "googleads-php-lib/src/Google/Api/Ads/Dfp/auth.ini"
4. I need refresh token, spend 1-2 to research how to get it.
5. Try to run GetRefreshToken.php in browser, before run I comment this.

if (__FILE__ != realpath($_SERVER['PHP_SELF'])) {
  return;
}

6. I cannot get refresh_token. I get auth_url and run directly see the result "redirect_uri_mismatch" and more detail

"The redirect URI in the request: urn:ietf:wg:oauth:2.0:oob can only be used by a Client ID for native application. It is not allowed for the &#39;WEB&#39; client type. You can create a Client ID for native application in the Credentials section of the Google Developers Console."

Advice or leads me, please.
Thank you.

**Comment by vtsao** [comment]
The error is pretty clear, you'll need to create a client ID and secret of type "installed application" on the Google Developer console (it may also be called "other").

You must run the GetRefreshToken.php example in a command line, it will not work in the browser.

Thanks,
Vincent

**Comment by Editea** [comment]
> The error is pretty clear, you'll need to create a client ID and secret of type "installed application" on the Google Developer console (it may also be called "other").
> 
> You must run the GetRefreshToken.php example in a command line, it will not work in the browser.
> 
> Thanks,
> Vincent

Wow, at first I didn't found that "installed application" type, but then you said it can called "other" and you just save my life. Thanks!!!
