### ISSUE TITLE
This package support PR-0?

### ISSUE THREAD

**Issue by ALTELMA** [googleads/googleads-php-lib#110]
Sorry for newbie question. Now I use this package on laravel 5.1 and I don't know how to use in on laravel. Can suggest me, please.

**Comment by vtsao** [comment]
I'm not familiar with Laravel and if it needs some special requirements then we do not currently support it. We don't currently support PSR-4 in this library, but are working on it (see #4 for updates).

We do however support Composer - https://github.com/googleads/googleads-php-lib/blob/master/composer.json.
