### ISSUE TITLE
Empty function used.

### ISSUE THREAD

**Issue by amnartb** [googleads/googleads-php-lib#111]
Hi,

php 5.4.4

I got "Fatal error: Can't use method return value in write context in \googleads\googleads-
php-lib\src\Google\Api\Ads\AdWords\Util\XmlDeserializer.php on line 182" 
when I changed to "googleads-php-lib-v7.0.0".

Same case as issues [#49](https://github.com/googleads/googleads-php-lib/issues/49)

Please change.

**Comment by fiboknacky** [comment]
We'll fix this soon, thanks for reporting.

**Comment by fiboknacky** [comment]
Fixed with release version [8.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/8.0.0)
