### ISSUE TITLE
Fatal error: Can't use method return value in write context in XmlDeserializer.php

### ISSUE THREAD

**Issue by denisoftus** [googleads/googleads-php-lib#114]
Hi, getting: 
Fatal error: Can't use method return value in write context in /adwords/googleads-php-lib/src/Google/Api/Ads/AdWords/Util/XmlDeserializer.php on line 182

Issue described here: http://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context 

It seems only fixed in PHP 5.5+, doesn't work with PHP 5.3

**Comment by fiboknacky** [comment]
This is already tracked in #111.
Thanks for reporting.

**Comment by denisoftus** [comment]
Thanks, sorry I didn't recognised it from the headline. Will monitor 111 for fix.
