### ISSUE TITLE
BatchJobService upload containing objects with "&" can't be serialized

### ISSUE THREAD

**Issue by g3r3ly** [googleads/googleads-php-lib#116]
I have an XML product feed, which I was trying to process with BatchJobService, but in many cases an exception was thrown, saying "unterminated entity reference". This happened before the objects were uploaded to AdWords, so I took a look at the XmlSerializer utility, because I traced back the issue to ConvertObjectToElement method, line 83:

$element->nodeValue = self::ConvertObjectToNodeValue($object);

This assigning failes in case of an object wich has attributes containing the '&' character. I have used htmlspecialchars($string, ENT_XML1, 'UTF-8') on those fields, so the exception is not thrown anymore.

Shouldn't this be handled by the util class?

**Comment by fiboknacky** [comment]
Will look into this. Thanks for reporting.

**Comment by fiboknacky** [comment]
Fixed with release version [8.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/8.0.0)
