### ISSUE TITLE
PHP Fatal error:  require_once(): Failed opening required '/home/oleg/share/crm/vendor/googleads/googleads-php-lib/src/Google/Api/Ads/AdWords/Lib/../v201502/ConversionTrackerService.php'

### ISSUE THREAD

**Issue by olegkrivtsov** [googleads/googleads-php-lib#117]
Hi, our company uses this library for uploading offline conversions. Recently, we started to receive the following PHP error:

PHP Fatal error:  require_once(): Failed opening required '/home/oleg/share/crm/vendor/googleads/googleads-php-lib/src/Google/Api/Ads/AdWords/Lib/../v201502/ConversionTrackerService.php' (include_path='/home/oleg/share/crm/vendor/googleads/googleads-php-lib/src:.:/usr/share/php:/usr/share/pear') in /home/oleg/share/crm/vendor/googleads/googleads-php-lib/src/Google/Api/Ads/AdWords/Lib/AdWordsSoapClientFactory.php on line 69

PHP Stack trace:
PHP   1. {main}() /home/oleg/share/crm/public/index.php:0
PHP   2. Zend\Mvc\Application->run() /home/oleg/share/crm/public/index.php:18
PHP   3. Zend\EventManager\EventManager->trigger() /home/oleg/share/crm/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php:313
PHP   4. Zend\EventManager\EventManager->triggerListeners() /home/oleg/share/crm/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:207
PHP   5. call_user_func() /home/oleg/share/crm/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:468
PHP   6. Zend\Mvc\DispatchListener->onDispatch() /home/oleg/share/crm/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:468
PHP   7. Zend\Mvc\Controller\AbstractController->dispatch() /home/oleg/share/crm/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php:113
PHP   8. Zend\EventManager\EventManager->trigger() /home/oleg/share/crm/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php:116
PHP   9. Zend\EventManager\EventManager->triggerListeners() /home/oleg/share/crm/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:207
PHP  10. call_user_func() /home/oleg/share/crm/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:468
PHP  11. Zend\Mvc\Controller\AbstractActionController->onDispatch() /home/oleg/share/crm/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:468
PHP  12. Application\Controller\ConsoleController->uploadOfflineConversionsAction() /home/oleg/share/crm/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php:83
PHP  13. Application\Service\GoogleAdWordsManager->uploadOfflineConversions() /home/oleg/share/crm/module/Application/src/Application/Controller/ConsoleController.php:326
PHP  14. Application\Service\GoogleAdWordsManager->initAdWordsUser() /home/oleg/share/crm/module/Application/src/Application/Service/GoogleAdWordsManager.php:42
PHP  15. AdWordsUser->GetService() /home/oleg/share/crm/module/Application/src/Application/Service/GoogleAdWordsManager.php:104
PHP  16. AdsUser->GetServiceSoapClient() /home/oleg/share/crm/vendor/googleads/googleads-php-lib/src/Google/Api/Ads/AdWords/Lib/AdWordsUser.php:228
PHP  17. SoapClientFactory->GenerateSoapClient() /home/oleg/share/crm/vendor/googleads/googleads-php-lib/src/Google/Api/Ads/Common/Lib/AdsUser.php:129
PHP  18. AdWordsSoapClientFactory->DoRequireOnce() /home/oleg/share/crm/vendor/googleads/googleads-php-lib/src/Google/Api/Ads/Common/Lib/SoapClientFactory.php:84

Previously the code worked correctly. Can you please advice?

**Comment by vtsao** [comment]
Knack PTAL.

**Comment by fiboknacky** [comment]
Hello olegkrivtsov,

v201502 was already sunset and not supported.
Please migrate to use v201509 instead.

Migration to v201509 can be found [here](https://developers.google.com/adwords/api/docs/guides/migration/v201509).

For your information, as [AdWords API schedule has been adjusted](http://googleadsdeveloper.blogspot.com/2016/01/new-release-schedule-for-adwords-api.html), we may have January 2016 release soon, but v201509 is still supported for a few months.

Knack
AdWords API Team
