### ISSUE TITLE
Dynamic Refresh Token

### ISSUE THREAD

**Issue by fiatux** [googleads/googleads-php-lib#118]
While handling more than Adwords Account, how should I set refresh_token of AdwordsUser during a request?

From what I understand I can keep client ID, client Secret and developer token as static, but I need to change client customer ID and refresh token for each Adwords Account. If that's right what is the best way to achieve this?

**Comment by vtsao** [comment]
You should create a new AdWordsUser for each account you're managing. You can set everything you need in the AW user constructor:
https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/Lib/AdWordsUser.php#L94

Hope this helps.
