### ISSUE TITLE
XmlSerializer.php issue at line 128 with PHP 5.3.3

### ISSUE THREAD

**Issue by chiragvels** [googleads/googleads-php-lib#119]
Hello,

This library is not supporting XmlSerializer.php with PHP 5.3.3 and lower.
The line 128 strval(htmlspecialchars($object, ENT_XML1, 'UTF-8')); is not supporting.

Giving error undefined constant.

So i think readme needs to update PHP 5.4.0 or higher version.

As per php here http://php.net/htmlspecialchars  the ENT_XML1 was added only after 5.4.0 	

Thanks

**Comment by vtsao** [comment]
@fiboknacky we need to not use ENT_XML1.

**Comment by vtsao** [comment]
Fixed in https://github.com/googleads/googleads-php-lib/releases/tag/8.1.0.
