### ISSUE TITLE
Report download with experimental

### ISSUE THREAD

**Issue by ThatCheck** [googleads/googleads-php-lib#120]
Hi, 
I'm trying to integrate PSR-4 update from the googleads-php-lib. I have no problem when I use it to manage campaign etc. But now I'm trying to download some report like "KEYWORDS_PERFORMANCE_REPORT" . And I don't see any class to do this. 

Did I miss something?

Thanks.

**Comment by vtsao** [comment]
Hey there, thanks for trying out the new beta library. We haven't yet ported over the reporting utilities for AdWords yet, but will soon.

**Comment by vtsao** [comment]
We've added AdWords reporting utils to the beta version of this library now:
https://github.com/googleads/googleads-php-lib/tree/experimental
