### ISSUE TITLE
Can not set NetwordSearchParameter (Network Search Parameter, Network Setting)

### ISSUE THREAD

**Issue by db-ryan** [googleads/googleads-php-lib#121]
Everything is working fine but when I try to set the NetworkSearchParameter to only use Google Search results it doesn't seem to return the correct values.

My code is

$networkSearchParameter = new NetworkSearchParameter();
$networkSearchParameter->networkSetting = 'targetGoogleSearch';
$selector->searchParameters[] = $networkSearchParameter;

Is there something I am missing here?  The documentation/examples on this are unclear and this is for the TargetingIdeaService.

Thanks.

**Comment by db-ryan** [comment]
Also tried:
$networkSearchParameter = new NetworkSearchParameter();
$networkSetting = new NetworkSetting();
$networkSetting->targetGoogleSearch = true;
$networkSearchParameter->networkSetting = $networkSetting;
$selector->searchParameters[] = $networkSearchParameter;

**Comment by db-ryan** [comment]
And:
$networkSetting = new NetworkSetting();
$networkSetting->targetGoogleSearch = true;
$selector->networkSetting = $networkSetting

**Comment by vtsao** [comment]
Knack can you PTAL.

**Comment by db-ryan** [comment]
I was able to get this solved with some help from the forum...I really couldn't find this info anywhere online so maybe it would be nice for future googlers?
``
	// Show results only from Google Search
	$networkSearchParameter = new NetworkSearchParameter();
	$networkSetting = new NetworkSetting();
	$networkSetting->targetGoogleSearch = true;
	$networkSetting->targetSearchNetwork = false;
	$networkSetting->targetPartnerSearchNetwork = false;
	$networkSetting->targetContentNetwork = false;
	$networkSearchParameter->networkSetting = $networkSetting;
	$selector->searchParameters[] = $networkSearchParameter;
``

**Comment by fiboknacky** [comment]
Hello,

The information about how to set `NetworkSearchParameter` to only use Google Search is documented in this [Generating Targeting Ideas](https://developers.google.com/adwords/api/docs/guides/targeting-idea-service#select_the_right_network) guide.
Feel free to give a feedback if you think it's not clear enough. :)
Though the code example is in Java, you can port to PHP easily, I think.

As another suggestion, I saw you tried to set the value of member variable in a wrong way in your original post.
```$networkSearchParameter->networkSetting = 'targetGoogleSearch';```

You could look up in the class declaration and see how many / what types of member variables the class has in the `src/Google/Api/Ads/AdWords/{version}/`.
For example, `NetworkSearchParameter` can be found in [TargetingIdeaService.php](https://github.com/googleads/googleads-php-lib/blob/44d3be6e670a1f310de09d37d5640c43d6d9239b/src/Google/Api/Ads/AdWords/v201506/TargetingIdeaService.php#L7545).
Its member variable `networkSetting` is actually of [type `NetworkSetting`](https://github.com/googleads/googleads-php-lib/blob/44d3be6e670a1f310de09d37d5640c43d6d9239b/src/Google/Api/Ads/AdWords/v201506/TargetingIdeaService.php#L7552).
Then, you can search for that [class declaration](https://github.com/googleads/googleads-php-lib/blob/44d3be6e670a1f310de09d37d5640c43d6d9239b/src/Google/Api/Ads/AdWords/v201506/TargetingIdeaService.php#L1406) to see how the class is composed.

Hope this help.
Knack

**Comment by db-ryan** [comment]
Many thanks,

I didn't realize that some of the documentation for the PHP library would
be found there.

"One of the most common mistakes is not specifying the
NetworkSearchParameter." -This makes me feel pretty dumb.

One suggestion:
It might be nice to show an implementation of this in one of the PHP
examples such as
/examples/AdWords/v201509/Optimization/GetKeywordIdeas.php.  It is
difficult to track down these details in the documentation.

Best,
Ryan

ᐧ

**Comment by fiboknacky** [comment]
Thanks for feedback.
We'll take that into consideration.
