### ISSUE TITLE
Class 'ReportUtils' not found - composer

### ISSUE THREAD

**Issue by marcinrosinski** [googleads/googleads-php-lib#122]
Hi there,

looks like something is broken in 8.1.0 as getting: `Class 'ReportUtils' not found` - all works fine in previous version, any ideas?

**Comment by marcinrosinski** [comment]
just checked, same issue in 7.0.0 to reproduce try:

```
$user = new AdWordsUser(ADWORDS_AUTH_INI_PATH);
ReportUtils::DownloadReportWithAwql($reportQuery, $filePath, $user, $reportFormat, $options);
```

works in 6.6.0 but not above, tested under composer

**Comment by fiboknacky** [comment]
Hello @marcinrosinski 

Please see the discussion in #113 and [README.md](https://github.com/googleads/googleads-php-lib/blob/master/README.md) if you use composer.

Cheers,
Knack
