### ISSUE TITLE
Xml Deserializer Issue

### ISSUE THREAD

**Issue by networxdevelopers** [googleads/googleads-php-lib#123]
I am trying to use the new Batch Job Service for the API in PHP. I am sending both CampaignCriterion and NegativeCampaignCriterion to adwords.  Both are getting updating in adwords correctly.

However, when I try to parse the XML file using the XmlDeserializer(Google/Api/Ads/AdWords/Util/XmlDeserializer.php) , I am getting a fatal error when it tries parsing a  'CampaignCriterion'.

PHP Fatal error:  Call to a member function getProperty() on a non-object in /home/cmeltzer/ng/composer/vendor/googleads/googleads-php-lib/src/Google/Api/Ads/AdWords/Util/XmlDeserializer.php on line 126

It seems like 'CampaignCriterion' doesn't have a parent class; 'NegativeCampaignCriterion' does have a parent class so it works. 

Please let me what to do with this issue. 

XML from adwords:
<?xml version="1.0" encoding="UTF-8"?><mutateResponse xmlns="https://adwords.google.com/api/adwords/cm/v201509"><rval><result><CampaignCriterion><campaignId>340921242</campaignId><isNegative>false</isNegative><criterion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Proximity"><id>176369273322</id><type>PROXIMITY</type><Criterion.Type>Proximity</Criterion.Type><geoPoint><latitudeInMicroDegrees>32076994</latitudeInMicroDegrees><longitudeInMicroDegrees>-110898754</longitudeInMicroDegrees></geoPoint><radiusDistanceUnits>MILES</radiusDistanceUnits><radiusInUnits>80.0</radiusInUnits></criterion><CampaignCriterion.Type>CampaignCriterion</CampaignCriterion.Type></CampaignCriterion></result><index>0</index></rval></mutateResponse>

**Comment by fiboknacky** [comment]
Thanks for reporting this issue.
We'll fix this and update this thread once finished.

**Comment by fiboknacky** [comment]
This is now fixed with [v8.2.0](https://github.com/googleads/googleads-php-lib/releases/tag/8.2.0)
