### ISSUE TITLE
ErrorException: the 'CN_match' SSL context option is deprecated in favor of 'peer_name'

### ISSUE THREAD

**Issue by opaessens** [googleads/googleads-php-lib#125]
While playing with your example from the docs, an error exception occured.

> ErrorException: the 'CN_match' SSL context option is deprecated in favor of 'peer_name'

The code from your example:

```
$oAuth2Credential = new \Google\AdsApi\Common\Util\SimpleGoogleCredential();
$oAuth2Credential->fromFile();

$builder = new \Google\AdsApi\AdWords\AdWordsSessionBuilder();
$session = $builder->fromFile()->withOAuth2Credential($oAuth2Credential)->build();

$adWordsServices = new \Google\AdsApi\AdWords\AdWordsServices();

$campaignService = $adWordsServices->get($session, 'CampaignService', 'v201601', 'cm');
```

Changing SSL settings in Common/AdsServicesSoapClientFactory.php from:

```
if ($soapSettings->getSslVerifyHost() !== null) {
        $contextOptions['ssl']['CN_match'] = parse_url($session->getEndpoint(), PHP_URL_HOST);
}

```

to

```
if ($soapSettings->getSslVerifyHost() !== null) {
        $contextOptions['ssl']['peer_name'] = parse_url($session->getEndpoint(), PHP_URL_HOST);
}
```

solves the issue. But I'm not sure if this leads to other issues :-)

Running an Vagrant/Homestead box:

> Linux homestead 3.16.0-23-generic #31-Ubuntu SMP Tue Oct 21 17:56:17 UTC 2014 x86_64
with 
> PHP 5.6.6-1+deb.sury.org~utopic+1

No SSL activated on vHost.

**Comment by vtsao** [comment]
Thanks for reporting this, fixing SSL issues is one of our next major things to do with the experimental version. So I'll look into this.

**Comment by vtsao** [comment]
SSL has been enabled by default in the beta version of this client library (we won't be fixing the current version as we're focusing efforts on getting the beta version to stable). Please check out the [changelog](https://github.com/googleads/googleads-php-lib/blob/experimental/CHANGELOG.md) for details.
