### ISSUE TITLE
Example script doesn't work properly

### ISSUE THREAD

**Issue by Em-PredragMilosevic** [googleads/googleads-php-lib#126]
Hi, 

In example script <code>examples/Dfp/v201602/CustomTargetingService/GetAllCustomTargetingKeysAndValues.php
</code>, $statementBuilder offset should be set to 0 after do-while loop.

Script currently doesn't fetch all values because $statementBuilder makes requests with offset from previous loops.

**Comment by vtsao** [comment]
Thanks for reporting this, will look into it.

**Comment by vtsao** [comment]
This will be fixed in the next release.

**Comment by Em-PredragMilosevic** [comment]
Thanks

**Comment by fiboknacky** [comment]
[v8.2.0](https://github.com/googleads/googleads-php-lib/releases/tag/8.2.0) fixed this issue.
