### ISSUE TITLE
BatchJobService - DUPLICATE_ADGROUP_NAME - Xml Deserializer Issue

### ISSUE THREAD

**Issue by janakprajapati** [googleads/googleads-php-lib#127]
Hi,

We noticed that, the ConvertXmlToObject() function of the XmlDeserializer class is not processing the errorList object correctly in case the error response is regarding DUPLICATE_ADGROUP_NAME. While processing, it throws an Exception ("Property _parameterMap does not exist") instead.

Here is the BatchJobService (XML) response for your reference,

`<?xml version="1.0" encoding="UTF-8"?><mutateResponse xmlns="https://adwords.google.com/api/adwords/cm/v201601"><rval><errorList><errors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="AdGroupServiceError"><fieldPath>operations[0].operand.name</fieldPath><trigger>Adgroup Name Here</trigger><errorString>AdGroupServiceError.DUPLICATE_ADGROUP_NAME</errorString><ApiError.Type>AdGroupServiceError</ApiError.Type><reason>DUPLICATE_ADGROUP_NAME</reason></errors></errorList><index>0</index></rval></mutateResponse>`

Please let me know if I am missing anything.

Thanks,
Janak

**Comment by fiboknacky** [comment]
Hi Janak,

Thanks for reporting.
We're fixing this and will let you know once it's fixed.

Best,
Knack

**Comment by fiboknacky** [comment]
Hi Janak,

Could you please check if you have included the [report classes](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/Util/v201601/ReportClasses.php) when you deserialize this XML payload?
Its [ApiError](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/Util/v201601/ReportClasses.php#L37), though having the same name as other ApiError classes, such as [that of AdGroupService](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/v201601/AdGroupService.php#L768) doesn't contain the _parameterMap variable.

So far, I've found that some people include report classes during deserializing batch job responses and got this error.

Best,
Knack

**Comment by janakprajapati** [comment]
Hi Knack,

I checked, we are not including the ReportClasses.php file in our class (we have implemented specific wrapper class for Adwords API which we use in our apps). Following is the list of files we have included in our class file. Our class extends the AdWordsUser class. The "api/google_v201601/" is specific path on our the system where we have installed the library code.

require_once 'api/google_v201601/AdWords/Lib/AdWordsUser.php';
require_once 'api/google_v201601/AdWords/Util/v201601/ReportUtils.php';
require_once 'api/google_v201601/Common/Util/ChoiceUtils.php';
require_once 'api/google_v201601/Common/Util/OgnlUtils.php';
require_once 'api/google_v201601/Common/Util/MediaUtils.php';
require_once 'api/google_v201601/Common/Util/ErrorUtils.php';
require_once 'api/google_v201601/AdWords/Util/XmlDeserializer.php';
require_once 'api/google_v201601/AdWords/Util/XmlSerializer.php';
require_once 'api/google_v201601/AdWords/Util/v201601/BatchJobUtils.php';

Do you see anything wrong? Do you need any more details? please let me know.

Thanks,
Janak

**Comment by fiboknacky** [comment]
Hi Janak,

require_once 'api/google_v201601/AdWords/Util/v201601/ReportUtils.php';

This does include ReportClasses.php, which contains class ApiError.
This hides class ApiError needed for deserialization of BatchJobUtils.

Best Regards,
----
Thanet (Knack) Praneenararat
Developer Programs Engineer
Google Inc.
Tokyo, Japan

**Comment by janakprajapati** [comment]
Hi Knack,

I see that, we are including ReportUtils.php class file along with other required class files in our implementation. This class file itself includes the ReportClasses.php file in it.

We have implemented our own class file which includes specific functions for Adwords API related services that we want to use in our apps. In this file, on the top, we have included all the required files from the Adwords API library. Here is the list,

require_once 'api/google_v201601/AdWords/Lib/AdWordsUser.php';
require_once 'api/google_v201601/AdWords/Util/v201601/ReportUtils.php';
require_once 'api/google_v201601/Common/Util/ChoiceUtils.php';
require_once 'api/google_v201601/Common/Util/OgnlUtils.php';
require_once 'api/google_v201601/Common/Util/MediaUtils.php';
require_once 'api/google_v201601/Common/Util/ErrorUtils.php';
require_once 'api/google_v201601/AdWords/Util/XmlDeserializer.php';
require_once 'api/google_v201601/AdWords/Util/XmlSerializer.php';
require_once 'api/google_v201601/AdWords/Util/v201601/BatchJobUtils.php';

As you know, the ReportUtils.php is required for the API Reports. We have written specific php function in this class for preparing the Report request and downloading it. We can't remove the ReportUtils.php from our class file so, what will be a good solution to this issue?

One way is to include the ReportUtils.php file only in the specific function and not on the top of the class file. I see that it works but, not sure if that will create any other issues in our implementation. Please let me know your thoughts.

Thanks,
Janak

**Comment by fiboknacky** [comment]
Hello Janak,

I'm afraid that until #4 (namespacing support) gets resolved, the best solution for now is as you said:
> One way is to include the ReportUtils.php file only in the specific function and not on the top of the class file.

This shouldn't create any other issues. It's just no so convenient for you.

Cheers,
Knack

**Comment by janakprajapati** [comment]
Hi Knack,

Thanks for your quick reply. Appreciated.

Cheers,
Janak
