### ISSUE TITLE
AdPolicyError.POLICY_ERROR - BatchJobService - XmlDeserializer

### ISSUE THREAD

**Issue by janakprajapati** [googleads/googleads-php-lib#129]
Hi,

We are getting the following exception with AdPolicyError.POLICY_ERROR through new BatchJobService.

`Property _parameterMap does not exist`

We have already notified (#127) about similar issue with DUPLICATE_ADGROUP_NAME type error. Also, few other members have notified same issue with other error types. Basically, the issue is with the XmlDeserializer.

We are stuck in the migration process on our system due to this issue. Can the API team give us a time frame by which we can expect the fix in the PHP library?

Thanks,
Janak

**Comment by vtsao** [comment]
Knack can you PTAL.

**Comment by fiboknacky** [comment]
Hello Janak,

As I commented in #127, could you please check if you have included the report classes when you deserialize this XML payload?
Its ApiError, though having the same name as other ApiError classes, such as that of AdGroupService doesn't contain the _parameterMap variable.

So far, I've found that some people include report classes during deserializing batch job responses and got this error.

Best,
Knack
