### ISSUE TITLE
Uncaught SoapFault exception

### ISSUE THREAD

**Issue by Hujjat** [googleads/googleads-php-lib#130]
Hi,

I am new to adwords api. I use the following code but I get error. I have Test account

`<?php 
require_once 'Google/Api/Ads/AdWords/Lib/AdWordsUser.php';

$username = "myemail@gmail.com";
$password = "mypassword";
$currencyCode = "USD";
$developerToken = "$username++$currencyCode";

$user = new AdWordsUser(null, $username, $password, $developerToken);
$user->SetDefaultServer("https://sandbox.google.com/api/adwords/o/v201603"); 
$user->SetClientId(null);

$managedCustomerService = $user->GetService('ManagedCustomerService', 'v201603');
$selector = new Selector();
$selector->fields = array('Login', 'CustomerId', 'Name');
$page = $managedCustomerService->get($selector);
 
$accounts = array();
foreach ($page->entries as $account) {
    if ($account->customerId > 0) {
        $accounts[] = $account;
    }
}
 
foreach ($accounts as $account) {
    print "Customer ID: {$account->customerId}\n";
}
`

I just created a new php file in src directory and the above code inside.
Now I get the following errors.

`( ! ) Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://sandbox.google.com/api/adwords/o/v201603/api/adwords/mcm/v201603/ManagedCustomerService?wsdl' : failed to load external entity "https://sandbox.google.com/api/adwords/o/v201603/api/adwords/mcm/v201603/ManagedCustomerService?wsdl" in C:\wamp\www\Keygen\src\Google\Api\Ads\Common\Lib\AdsSoapClient.php:154 Stack trace: #0 C:\wamp\www\Keygen\src\Google\Api\Ads\Common\Lib\AdsSoapClient.php(154): SoapClient->SoapClient('https://sandbox...', Array) #1 C:\wamp\www\Keygen\src\Google\Api\Ads\AdWords\Lib\AdWordsSoapClient.php(51): AdsSoapClient->__construct('https://sandbox...', Array, Object(AdWordsUser), 'ManagedCustomer...', 'https://adwords...') #2 C:\wamp\www\Keygen\src\Google\Api\Ads\AdWords\v201603\ManagedCustomerService.php(4470): AdWordsSoapClient->__construct('https://sandbox...', Array, Object(AdWordsUser), 'ManagedCustomer...', 'https://adwords...') #3 C:\wamp\www\Keygen\src\Google\Api\Ads\Common\Lib\SoapClientFactory. in C:\wamp\www\Keygen\src\Google\Api\Ads\Common\Lib\AdsSoapClient.php on line 154`

Please help me.

**Comment by fiboknacky** [comment]
Hello Hujjat,

You shouldn't set up the server like that. It's the invalid URL, so the exception was thrown.
I highly recommend you to start from our [examples directories](https://github.com/googleads/googleads-php-lib/tree/master/examples/AdWords), e.g., [GetCampaigns](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201603/BasicOperations/GetCampaigns.php).
In this way, you can get the idea about how the AdWordsUser object should be used.
README.md is a good place to start with too.
In particular, the [Basic Usage](https://github.com/googleads/googleads-php-lib#basic-usage) section is what you want.

Also, your developer token is not just a username ++ currency code.
Please review our [Get Started](https://developers.google.com/adwords/api/docs/guides/start) guide from the start to get the idea about OAuth2, developer token, refresh token, etc.

Cheers,
Knack
