### ISSUE TITLE
Missing parameter type declarations in PHPDoc

### ISSUE THREAD

**Issue by hakimio** [googleads/googleads-php-lib#131]
"@param $serviceName the service name" should be replaced by "@param string $serviceName the service name" in AdwordsUser->LoadService() function definition.

Also, this bug is present in most of the service classes - parameter types are missing.

**Comment by fiboknacky** [comment]
Thanks for reporting. We'll look into this.

**Comment by vtsao** [comment]
Fixed with release 9.0.0:
https://github.com/googleads/googleads-php-lib/releases/tag/9.0.0
