### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by vedebel** [googleads/googleads-php-lib#132]
Hello,

I have an error like "Too many open files" when background process which makes requests to Adwords API is running for a long time. I watched opened file descriptors with **lsof** utility and found that the process  incrementaly opens new connections to Google servers but doesn't fully close them.

There is small log after couple of minutes of process running. You can see that many connections are established.
[adwords.lsof.txt](https://github.com/googleads/googleads-php-lib/files/225315/adwords.lsof.txt)

**Comment by fiboknacky** [comment]
What codes have you run? Could you please share your snippet?
And in what environments (e.g., Apache in Linux) is your program running on?

**Comment by vedebel** [comment]
This problem was detected on Linux (CentOS 7, Ubuntu 14.04), PHP 7.0.5.
Script runs as background process (cli-mode).

A huge amount of methods is called creating campaigns, ad groups, ads, keywords. Not sure if I can give you just a snippet.

**Comment by fiboknacky** [comment]
Thanks for information.
I've never got reports about this before.
But as you said that it's a huge number of methods, it is expected to have a lot of connections occurring via SOAP calls.

Have you tried raising up the limits as suggested in [this post](http://stackoverflow.com/a/14749074)?

**Comment by vedebel** [comment]
Yes, I raised fs.file-max to 1 000 000 and user limit to 500 000, but it is not enough if I have couple of processes that run for a long time.

Is there a way to close connection after request or reuse it?

**Comment by vedebel** [comment]
I created some kind of cache for services and it looks good.
I use creating service client if it is in cache or create it and add in cache.

**Comment by fiboknacky** [comment]
The connection is handled by PHP's [SoapClient](http://php.net/manual/en/class.soapclient.php).
As far as I've researched so far, there is no method that we can use to explicitly close the connection.

But your idea of caching looks good. We should reuse the service clients when possible.

**Comment by fiboknacky** [comment]
Hi @vedebel,

Are you still faced with the issue?
If there's anything we can help, please let us know.

Knack
