### ISSUE TITLE
We got CLIENT_NOT_AUTHORIZED error from the AdWords API. 

### ISSUE THREAD

**Issue by litan1106** [googleads/googleads-php-lib#133]
We got CLIENT_NOT_AUTHORIZED error from the AdWords API. 

We are managing the client's account and it's active.

Response Code: 400
Error Message: Report download failed. Underlying errors are 
Type = 'LoasAuthenticationError.CLIENT_NOT_AUTHORIZED', Trigger = '<null>', FieldPath = ''.

**Comment by dklimkin** [comment]
It looks like a temporary problem on our side. This issue should now be resolved.
