### ISSUE TITLE
access_type=offline not enough for getting refresh token on subsequent calls

### ISSUE THREAD

**Issue by omergisha** [googleads/googleads-php-lib#135]
Hi,
I got stuck on this for a few hours.

In `GoogleCredential->getAuthorizationUrl()` you can set the `$offline` parameter as true to set the query parameter `'access_type=offline'`.
This is done in order to get the refresh token, as in the documentation:

> **Offline access**
> 
> It is common for an AdWords API client application to request offline access. For example, your AdWords API client application may want to run batch jobs when your user is not physically online browsing your website.
> 
> To request offline access for a Web application type, make sure you set the access_type parameter to offline. 

And in the PHPDOC `@param boolean $offline whether or not to request offline access (aka a refresh token), false by default`

This does not work if the authorization was already given in a previous request.
In order to get the refresh token I had to supply an array `['approval_prompt' => 'force']` in the `$params` parameter.

If this could be done automatically when offline access is requested, it would be nice. Or maybe add `$force_prompt` as a parameter.

Thanks.

**Comment by vtsao** [comment]
Hey, thanks for reporting this. We're working on replacing the OAuth2 code in the experimental library with the Google auth PHP library instead:
https://github.com/google/google-auth-library-php

so we won't be making any changes to this code.
