### ISSUE TITLE
Can I make a seo key generator with this lib?

### ISSUE THREAD

**Issue by Hujjat** [googleads/googleads-php-lib#136]
Hi,
Sorry if I am asking a question not an issue.
I have search a lot to make a site like http://keywordtool.io/. And I come to this library. 
I am a php developer. I want to know, can I make a system to let people search words and than it should query the word list with price per click, popularity etc... using this library or not?. I mean alike to keywordtool.io. 

Please help. 
thanks :)

**Comment by vtsao** [comment]
Hello:

No, this library is for the AdWords and DFP SOAP APIs.

Thanks,
Vincent
