### ISSUE TITLE
throw new ReportDownloadException

### ISSUE THREAD

**Issue by tomarius2000** [googleads/googleads-php-lib#137]
For Adwords PHP API Library in this file: adwords/lib/Google/Api/Ads/AdWords/Util/v201603/ReportUtils.php there are bunch of these: throw new ReportDownloadException ("blahblah") but ReportDownloadException __construct requires two arguments: public function __construct($error, $httpCode)

Here is the constructor:
public function __construct($error, $httpCode) { parent::__construct($error); $this->httpCode = $httpCode; }
And this is how is being called:
throw new ReportDownloadException('The client customer ID must be ' . 'specified for report downloads.');   (line 332: https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/Util/v201603/ReportUtils.php)

You'll get this warning:
PHP Warning:  Missing argument 2 for ReportDownloadException::__construct(), called in lib/Google/Api/Ads/AdWords/Util/v201603/ReportUtils.php on line 332 and defined in lib/Google/Api/Ads/AdWords/Util/ReportDownloadException.php on line 39

The easiest fix if to change the constructor:
public function __construct($error, $httpCode=null) { parent::__construct($error); $this->httpCode = $httpCode; }

**Comment by vtsao** [comment]
Knack, PTAL.

**Comment by fiboknacky** [comment]
Thanks for reporting. We'll fix this soon.

**Comment by fiboknacky** [comment]
This is fixed in version [9.1.0](https://github.com/googleads/googleads-php-lib/releases/tag/9.1.0)
