### ISSUE TITLE
Warning: include_once(string.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by AkaneKuriyama** [googleads/googleads-php-lib#140]
Hi, 
I'm trying to get the report to a Non-existent account for the test of the error processing.
There is an error message.

```
Warning: include_once(string.php): failed to open stream: No such file or directory in /usr/local/lib/php/Zend/Loader.php on line 134
```

Development environment

```
PHP 5.3.8
CentOS release 5.6

adwords API version : v201605
Report Type : ACCOUNT_PERFORMANCE_REPORT
package : GoogleApiAdsAdWordsUtil 
method : DownloadReport
```

Please help me.

Regards,
Akane

**Comment by fiboknacky** [comment]
Hello Akane,

Could you please provide more information as follows:

- Have you run our example file as is?
- If not, could you provide more detail about how you incorporate our lib to your system, e.g., the contents of file that you ran and got this error, how did you use the DownloadReport method.

Best,
Thanet, AdWords API Team

**Comment by AkaneKuriyama** [comment]
We did this in reference
https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201605/Targeting/AddCampaignTargetingCriteria.php

```
define('ADWORDS_VERSION', 'v201605');

set_include_path(implode(PATH_SEPARATOR, array(
	realpath(APPLICATION_PATH . '/../library/GoogleApi/src'),
	get_include_path(),
)));

require_once 'Google/Api/Ads/AdWords/Lib/AdWordsUser.php';
require_once 'Google/Api/Ads/AdWords/Util/' . ADWORDS_VERSION . '/ReportUtils.php';

$this->_user->LoadService('ReportDefinitionService', ADWORDS_VERSION);

$selector = new Selector();
$selector->fields = array('AccountDescriptiveName', 'Impressions', 'Cost');

// Create report definition.
$reportDefinition = new reportDefinition();
$reportDefinition->selector = $selector;
$reportDefinition->reportName = 'Account performance report #' . uniqid();
$reportDefinition->dateRangeType = 'THIS_MONTH';
$reportDefinition->reportType = 'ACCOUNT_PERFORMANCE_REPORT';
$reportDefinition->downloadFormat = 'XML';

// Set additional options.
$options = array('version' => ADWORDS_VERSION);

$reportUtils = new ReportUtils();
$res = $reportUtils->DownloadReport($reportDefinition, $filePath, $this->_user, $options);
```

**Comment by AkaneKuriyama** [comment]
Is probably an error occurred here...

```
src/Google/Api/Ads/AdWords/Util/XmlDeserializer.php
ConvertElementToObject method
```

**Comment by fiboknacky** [comment]
Thanks for more information.
I guess you copied a wrong link, right?
Your file seems to be copied from [DownloadCriteriaReport.php](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201605/Reporting/DownloadCriteriaReport.php)

From what you've posted, I can't see any mistakes.
What happened if you run our [DownloadCriteriaReport](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201605/Reporting/DownloadCriteriaReport.php) example?
You can modify it to use `ACCOUNT_PERFORMANCE_REPORT` as you wish to do.

In addition, could you please copy the full SOAP log (by removing your private info like your developer token) and your the message, and paste it here?

Thanks in advance.
Knack, AdWords API Team

**Comment by AkaneKuriyama** [comment]
Thank you for reply! 
I'm sorry the link is wrong.You are right.

Is this the SOAP log ?
report_download.log

```
[Jun 14 2016 16:26:52.000000 - ERROR] POST /api/adwords/reportdownload/v201605 HTTP/1.1^M
User-Agent: curl, gzip^M
Host: adwords.google.com^M
Accept: */*^M
Accept-Encoding: gzip^M
Authorization: Bearer ***
developerToken: ***
clientCustomerId: ***^M
Content-Length: 521^M
Expect: 100-continue^M
Content-Type: multipart/form-data; boundary=----------------------------1f523e15258b

Parameters:
__rdxml: <?xml version="1.0" encoding="UTF-8"?>
<reportDefinition><selector><fields>AccountDescriptiveName</fields><fields>Impressions</fields><fields>Cost</fields></selector><reportName>Account performance report #575fb1b7a4fda</reportName><reportType>ACCOUNT_PERFORMANCE_REPORT</reportType><dateRangeType>THIS_MONTH</dateRangeType><downloadFormat>XML</downloadFormat></reportDefinition>

Response Code: 400
Error Message: Report download failed. Underlying errors are
Type = 'AuthorizationError.USER_PERMISSION_DENIED', Trigger = '<null>', FieldPath = ''.
```

**Comment by fiboknacky** [comment]
Hi Akane,

It seems your OAuth credentials don't match the client ID you specified, or any of its manager accounts.
Could you please check your credentials and our [guide](https://github.com/googleads/googleads-java-lib/wiki/API-access-using-own-credentials-(installed-application-flow)#step-2---setting-up-the-client-library) again?

Cheers,
Knack

**Comment by AkaneKuriyama** [comment]
Hi Knack,

Thank you for advice.
Sample code has running successfully.
Problem was a different place.
Thank you very much!!><

Regards,
Akane

**Comment by fiboknacky** [comment]
Hello Akane,

I'm glad to hear that.
Feel free to ask for help if you have questions in the future.

Cheers,
Knack
