### ISSUE TITLE
Non-static method ReportUtils::DownloadReportWithAwql() should not be called statically

### ISSUE THREAD

**Issue by starrychloe** [googleads/googleads-php-lib#141]
I updated to the latest version of Google API v201605, but now I get this error when fetching a report. 

PHP Deprecated Warning 'yii\base\ErrorException' with message 'Non-static method ReportUtils::DownloadReportWithAwql() should not be called statically, assuming $this from incompatible context'

It still shows a static method call in the documentation. 

https://developers.google.com/adwords/api/docs/samples/php/reporting#download-a-criteria-performance-report-with-awql

```
// Download report.
  ReportUtils::DownloadReportWithAwql($reportQuery, $filePath, $user,
      $reportFormat, $options);
```

**Comment by fiboknacky** [comment]
Hello,

In [v10.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/10.0.0), we've refactored and changed the method to non-static.
So, please refer to the [updated example](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201605/Reporting/DownloadCriteriaReportWithAwql.php#L70) bundled with the release.

As for the documentation, sorry for your inconvenience, we'll update them accordingly soon.

Best,
Thanet, AdWords API Team
