### ISSUE TITLE
Document ReportUtils Change in v10.0.0

### ISSUE THREAD

**Issue by markrogoyski** [googleads/googleads-php-lib#146]
ReportUtils changed from static functions to instantiating and object and calling an object method for DownloadReport. This change is not documented in the v10.0.0 release notes and should be documented since it is a breaking change.

For example, up until v9.1.0 you could do:
ReportUtils::DownloadReport($reportDefinition, $filePath, $user, $options);

In v10.0.0, you now need to do:
$reportUtils = new ReportUtils();
$reportUtils->DownloadReport($reportDefinition, $filePath, $user, $options);

For reference, here are some relevant git diffs of ReportUtils.php showing the changes:

```
-  /**
-   * The ReportUtils class is not meant to have any instances.
-   */
-  private function __construct() {}
+  public function __construct(AdsUtilityRegistry $adsUtilityRegistry = null) {

-  public static function DownloadReport($reportDefinition, $path = null,
+  public function DownloadReport($reportDefinition, $path = null,
```

**Comment by fiboknacky** [comment]
I've updated the ChangeLog.md accordingly.
Thanks for giving feedback to us.

Knack
