### ISSUE TITLE
INVALID_BILLING_ACCOUNT_ID_FORMAT

### ISSUE THREAD

**Issue by AkaneKuriyama** [googleads/googleads-php-lib#148]
Hi,

I would like to ask you the following questions;

Im using BudgetOrderService,
I get an error that INVALID_BILLING_ACCOUNT_ID_FORMAT.

The billingAccountId item of BudgetOrder now specifies a 16 -digit number in the format of xxxx-xxxx-xxxx-xxxx. 
I have got the number using the BudgetOrderService.getBillingAccounts
but the number does not contain dash(-).
I have to add a dash for the number by myself?
Or do you have other way?

Please advice.

```
using version : v201605

i looked reference
https://developers.google.com/adwords/api/docs/reference/?
```
Regards,
Akane

**Comment by fiboknacky** [comment]
Hello Akane,

Could you please post in the [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api) instead?
This seems like an issue of the API server rather than the PHP client lib.

Thanks in advance.

Best,
Knack
