### ISSUE TITLE
ReportDownloadException when set any value to ReportDefinition::$includeZeroImpressions

### ISSUE THREAD

**Issue by jareacz** [googleads/googleads-php-lib#149]
Hello,

I'm using your php client and I've just upgraded to v201605. I wanna try your example for downloading reports [here](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201605/Reporting/DownloadCriteriaReport.php) but when I run this script, `ReportDownloadException` is thrown. I've noticed that if variable `ReportDefinition::$includeZeroImpressions` has different value then NULL, this exception is thrown.

So, where is the problem, please?

Full text of exception is:

`Report download failed. Underlying errors are Type = 'ReportDownloadError.INVALID_REPORT_DEFINITION_XML', Trigger = 'Invalid ReportDefinition Xml: cvc-complex-type.2.4.d: Invalid content was found starting with element 'includeZeroImpressions'. No child element is expected at this point.', FieldPath = ''. 
`
My code:
```
                $this->adWordsUser->LoadService('ReportDefinitionService', 'v201605');

		$selector = new \Selector();
		$selector->fields = array('CampaignId', 'AdGroupId', 'Id', 'Criteria',
			'CriteriaType', 'Impressions', 'Clicks', 'Cost');
		$selector->predicates[] = new \Predicate('Status', 'NOT_IN', array('PAUSED'));
		$reportDefinition = new \ReportDefinition();
		$reportDefinition->selector = $selector;
		$reportDefinition->reportName = 'Criteria performance report #' . uniqid();
		$reportDefinition->dateRangeType = 'LAST_7_DAYS';
		$reportDefinition->reportType = 'CRITERIA_PERFORMANCE_REPORT';
		$reportDefinition->downloadFormat = 'CSV';
		$reportDefinition->includeZeroImpressions = false;
		$options = array('version' => 'v201605');

		$reportUtils = new \ReportUtils();
		var_dump($reportUtils->DownloadReport($reportDefinition, NULL, $this->adWordsUser, $options));
```

If I remove this line: `$reportDefinition->includeZeroImpressions = false;` or set this variable to NULL, everything is OK.

**Comment by vtsao** [comment]
Knack PTAL.

**Comment by fiboknacky** [comment]
Hello,

The includeZeroImpressions of ReportDefinition object has been deprecated already in v201603.
Please see our [release notes](https://developers.google.com/adwords/api/docs/reference/#reporting-v201603).

If you wish to set the includeZeroImpressions value, please do it via HTTP headers, as described in [our example](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201605/Reporting/DownloadCriteriaReport.php#L73).

Best,
Knack

**Comment by jareacz** [comment]
Ok, thanks, I haven't noticed.
