### ISSUE TITLE
Request headers

### ISSUE THREAD

**Issue by neshala** [googleads/googleads-php-lib#153]
In the latest version of AdWords API some fields has been removed from XML and moved to HTTP Header request.

Here is quote from the reference

> The includeZeroImpressions field has been removed from the XML report definition schema. Use the includeZeroImpressions HTTP header instead.

So far i have used includeZeroImpressions like this:
`// Create report definition.

            $reportDefinition = new ReportDefinition();
            $reportDefinition->reportName = "ADGROUP_PERFORMANCE_REPORT_YESTERDAY";
            $reportDefinition->dateRangeType = 'YESTERDAY';
            $reportDefinition->reportType = 'ADGROUP_PERFORMANCE_REPORT';
            $reportDefinition->downloadFormat = 'CSV';
            $reportDefinition->includeZeroImpressions = true;`

From now on, i can't use 
`$reportDefinition->includeZeroImpressions = true;`

According to the docs i have to send it via HTTP header.

Is there some way to do this using this PHP Lib in order to send this headers?
https://developers.google.com/adwords/api/docs/guides/reporting#request-headers

**Comment by neshala** [comment]
Ok i found the solution by looking at examples:

$options['includeZeroImpressions'] = true;

Please delete and close this issue.

Thanks

**Comment by fiboknacky** [comment]
Hi Nenad,

Glad you find the solution already.
Feel free to ask in the future if you run into any issues.

Best,
Knack
