### ISSUE TITLE
Add real "Parallel Report Download" example to experimental branch

### ISSUE THREAD

**Issue by hakimio** [googleads/googleads-php-lib#157]
The "Parallel Report Download" example in the master branch doesn't actually download reports in parallel because Report Utils are not thread safe. However, as far as I understand, it should be possible to do it using the experimental version of the library. It would be nice if an example of how it should be done was added to the new version.

**Comment by fiboknacky** [comment]
Hello @hakimio 

Sorry for late response.
The example was named so to be consistent with client libs of other languages.
Currently, we have no plan to support doing report download in parallel, but we'll keep your suggestion in mind.

Best,
Knack
