### ISSUE TITLE
BatchJob Processing: XmlDeserializer ignores arrays with one element

### ISSUE THREAD

**Issue by blacktemplar** [googleads/googleads-php-lib#158]
When using BatchJobService I get wrong deserialization if the result object contains arrays with only one element. In this case the deserialized object does not contain the array but directly the element of the array.

Easiest example to reproduce is manipulate examples/AdWords/v201607/CampaignManagement/AddCompleteCampaignsUsingBatchJob.php
such that it only adds one operation to the batch job, for example by commenting lines 69-89

If you call now AddCompleteCampaignUsingBatchJobExample with your user it will finish but throw warnings of this form: 

Notice: Undefined property: Operand::$errorList in examples/AdWords/v201607/CampaignManagement/AddCompleteCampaignsUsingBatchJob.php on line 156

By debugging you can see that $mutateResponse->rval is not an array containing one element but directly the response of the one mutate request.

This is only an example the problem also occurres for arrays deeper in the result structure. For example I got the same problem for an Ad Group which has one label. In this case the labels array of the ad group was not there.

I hope the problem is clear. With this problem its impossible for me to migrate from the MutateJobService to the BatchJobServic, but I need to since v201601's sunset date is in 5 days!

**Comment by vtsao** [comment]
Knack can you PTAL.

**Comment by vtsao** [comment]
Fixed in 12.0.0 release:
https://github.com/googleads/googleads-php-lib/releases/tag/12.0.0
