### ISSUE TITLE
Class name conflict

### ISSUE THREAD

**Issue by tgreenpubco** [googleads/googleads-php-lib#159]
Hi folks, I've run into a conflict between this library and another using the same class name of Logger

Fatal error: Cannot redeclare class Logger in /inc/googleads-php-lib/src/Google/Api/Ads/Common/Util/Logger.php on line 46

The other library is http://logging.apache.org/log4php/

Would be nice to get these two to play together but I'm not entirely sure how to do so.
I believe namespaces could come into play.

**Comment by vtsao** [comment]
Hey @tgreenpubco, we're in the process of releasing a new version of this client library that uses namespaces and conforms to most of the PSR's.

Please check it out in our [experimental branch](https://github.com/googleads/googleads-php-lib/tree/experimental) and follow #4.

For the current client library, we won't be making any namespace changes as our efforts will be focused on bringing the new one to stable and replacing the current one with it.
