### ISSUE TITLE
get-keyword-ideas KEYWORD_TEXT return string “array”

### ISSUE THREAD

**Issue by schevgeny** [googleads/googleads-php-lib#161]
We are building an API app and trying to recieve keyword volume.
We are using code from example:
https://developers.google.com/adwords/api/docs/samples/php/optimization#get-keyword-ideas
This code worked 1-august-2016.
Text, which we send in a query: http://prntscr.com/cbm627.
Then, we avoid an array of phrases that returned: http://prntscr.com/cbm6is
Now we receive only one answer independently of number of phrases in request: KEYWORD_TEXT contains just text “array” (without any real content, only one word).
And we expect to get answer like that: http://prntscr.com/cbm7lg
[soap resp fail.txt](https://github.com/googleads/googleads-php-lib/files/446678/soap.resp.fail.txt)

**Comment by fiboknacky** [comment]
Hello @schevgeny 

I'll take a look and get back to you later.
First, let me confirm something.

You've executed the same code, which worked on 1 Aug, but now it worked differently.
Is this correct?

Could you please share how you modified the file https://developers.google.com/adwords/api/docs/samples/php/optimization#get-keyword-ideas?
Do you run the file as is or use different inputs?

Thanks in advance.

Best,
Knack

**Comment by schevgeny** [comment]
> You've executed the same code, which worked on 1 Aug, but now it worked differently.
Is this correct?
Yes.

@fiboknacky

method:
https://docs.google.com/document/d/15NeexQIPC3fbC-Qu1SHJ0hMgDuNmavPfvK3xbsM5OQM/edit?usp=sharing

**Comment by schevgeny** [comment]
I've fixed it.
I was putting to queries in array with md5 in key, and it was not working.
I am putting array with numerik key and it works now.

Thx

**Comment by fiboknacky** [comment]
Thanks for your update and sorry for the delay.
