### ISSUE TITLE
Got 400, OAuth2Exception: error" : "invalid_request

### ISSUE THREAD

**Issue by litan1106** [googleads/googleads-php-lib#162]
OAuth2Exception {#350 ▼
#message: """
{\n
"error" : "invalid_request"\n
}
"""
#code: 400
#file: "src/Google/Api/Ads/Common/Util/SimpleOAuth2Handler.php"

**Comment by kwitte** [comment]
Same issue here.

auth.ini is apparently out of date.

"installed application" is no longer even a type.  Google's choices now offered are:

- Web application
- Android Learn more
- Chrome App Learn more
- iOS Learn more
- PlayStation 4
- Other

**Comment by vtsao** [comment]
Hi @litan1106 - I'll need some more information. Are you using existing OAuth2 credentials that were previously working and have stopped working? Or are you trying to create new ones? Which version of the client library are you using?

@kwitte can you describe your situation in more detail as well? The documentation in auth.ini is out of date, yes, and thanks for reporting it, I'll look into fixing it. It's now known as "other" in the dev console.

Thanks,
Vincent

**Comment by kwitte** [comment]
Hi @vtsao 
Something appears to be down on the Google oauth server farm.  Requests are being dropped:

http://youtu.be/LyMyQ1_4Pgs

Example above:

http://ec2-54-151-19-137.us-west-1.compute.amazonaws.com/googleads-php-lib-10.1.0/examples/Dfp/v201605/LineItemService/GetLineItemNameByLineItemId.php?id=275562727

Refresh the example a couple times, and you'll occasionally get a number (a line item name looked up by the given line item id).

(for this application, I assumed "Other" and created a client_id for this in dev console.  I am able to successfully generate a refresh_token for this client_id and client_secret sometimes, other times it randomly fails with "invalid_request". However, when it doesn't fail and the refresh token is provided, and subsequently entered into auth.ini, API calls are intermittently either working or dropping with "invalid_request".)

**Comment by alancoleman** [comment]
Hi Everyone,

I'm receiving the same intermittent error in my logs (See below).

Our  OAuth2 Credentials do still seem to be working apart from the intermittent issue.

**Library:** googleads-php-lib-10
**Version**: v201605

**Time of first error:** 30-Aug-2016 10:15:03 America/Denver
**Time of most recent error:**  01-Sep-2016 02:20:04 America/Denver

Thank you.

> [30-Aug-2016 13:15:04 America/Denver] PHP Fatal error:  Uncaught exception 'OAuth2Exception' with message '{
  "error" : "invalid_request"
}' in /home2/adwordsl/public_html/app/googleads-php-lib-10/src/Google/Api/Ads/Common/Util/SimpleOAuth2Handler.php:133
Stack trace:
#0 /home2/adwordsl/public_html/app/googleads-php-lib-10/src/Google/Api/Ads/Common/Util/SimpleOAuth2Handler.php(96): SimpleOAuth2Handler->MakeRequest('https://account...', Array)
#1 /home2/adwordsl/public_html/app/googleads-php-lib-10/src/Google/Api/Ads/Common/Util/OAuth2Handler.php(116): SimpleOAuth2Handler->RefreshAccessToken(Array)
#2 /home2/adwordsl/public_html/app/googleads-php-lib-10/src/Google/Api/Ads/Common/Lib/AdsSoapClient.php(452): OAuth2Handler->GetOrRefreshAccessToken(Array)
#3 /home2/adwordsl/public_html/app/googleads-php-lib-10/src/Google/Api/Ads/Common/Lib/AdsSoapClient.php(199): AdsSoapClient->GenerateHttpHeaders()
#4 /home2/adwordsl/public_html/app/googleads-php-lib-10/src/Google/Api/Ads/AdWords/Lib/AdWordsSoapClient.php(86): AdsSoapClient->__soapCall('get', Array)
#5 /home2/adwords in /home2/adwordsl/public_html/app/googleads-php-lib-10/src/Google/Api/Ads/Common/Util/SimpleOAuth2Handler.php on line 133

**Comment by litan1106** [comment]
@kwitte is the experimental API oauth works fine for you?

**Comment by vtsao** [comment]
I'm looking into it. Are you guys using AdWords or DFP? Can you give me an example of what service you're calling? I'll try to reproduce.

**Comment by litan1106** [comment]
I am calling the AdWords API - CustomerService using the v12.0.0 php library.

// constructor stuff
$this->adWordsUser = $adWordsUser;
// Set our AdWords auth.ini
$adWordsUser->__construct($authenticationIniPath = base_path('adwords-auth.ini'));

// method stuff
$this->adWordsUser->LogAll();
$this->adWordsUser->SetClientCustomerId($cid);

// Get the Manage Customer Service
$managedCustomerService = $this->adWordsUser->GetService('CustomerService', 'v201607');

try {
    $result = $managedCustomerService->getCustomers();

    dd($result);
} catch (Exception $e) {
    dd($e);
}

**Comment by kwitte** [comment]
@litan1106 Yes sir!
Thank you.

**Comment by vtsao** [comment]
To confirm - this is happening when you're running code from a local machine right? And not just an AWS instance or something like that?

**Comment by kwitte** [comment]
@vtsao Never tried from my local machine yesterday.   All my 10.1.0 calls were always from the same single AWS instance (no caching, multi-host DNS records, or load balancing -- just a bare instance).  My experimental API install is running on a different AWS instance.  You are a hero for offering to look into this for everyone.

**Comment by litan1106** [comment]
@vtsao I have two vps instances running in the cloud. And one local instances running in a vagrant. They all got the same error in every other request. OAuth2Exception: error" : "invalid_request"

I tried the same request for 5 times, 1 of 5 request worked and got the data from AdWords API. Other 4 requests failed with OAuth2Exception: error" : "invalid_request"

**Comment by vtsao** [comment]
Thanks for the info all. I'm still unable to reproduce the issue. But since it seems like it's specific to the PHP client library (and works in the experimental version), the only thing I can see so far is that the OAuth2Handler is using an older access token OAuth2 endpoint:
https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/Common/Util/OAuth2Handler.php#L43

Can you guys try manually updating it to this one:
https://www.googleapis.com/oauth2/v4/token

for now and see if these issues stop?

Reference: https://developers.google.com/identity/protocols/OAuth2InstalledApp#refresh

**Comment by kwitte** [comment]
@vtsao I get "Error 400 (Not Found)" after I supply GetRefreshToken.php with the new success code provided by the URL it directs me to.  But I only changed the ACCESS_ENDPOINT.  Should I change AUTHORIZE_ENDPOINT as well?

![screen shot 2016-09-01 at 9 35 31 am](https://cloud.githubusercontent.com/assets/142748/18175811/b6d7f290-7027-11e6-8b36-afede67b1acb.png)

**Comment by litan1106** [comment]
@vtsao I got 400 after I changed   

const ACCESS_ENDPOINT = 'https://www.googleapis.com/oauth2/v4/token';

**Comment by litan1106** [comment]
curl 'https://www.googleapis.com/oauth2/v4/token' -d 'grant_type=refresh_token&refresh_token=<insert_refresh_token_here>&client_id=<insert_client_id_here>&client_secret=<insert_client_secret_here>

I tried the curl with my credential. It worked for me and I got access token from it.

{
 "access_token": "xxxx",
 "token_type": "Bearer",
 "expires_in": 3600
}

**Comment by litan1106** [comment]
I did ten of the curl request, I got access token without error.

{
 "access_token": "xxx",
 "token_type": "Bearer",
 "expires_in": 3600
}

**Comment by vtsao** [comment]
Thanks @litan1106 it might be a CurlUtils issue with the client library. Let me examine that.

**Comment by vtsao** [comment]
What version of PHP are you guys using?

**Comment by kwitte** [comment]
my 10.1.0 API on a server running PHP 5.3.10-1ubuntu3.8 with Suhosin-Patch (cli)

**Comment by litan1106** [comment]
I am running 12.0.0 with AdWords V201607

"googleads/googleads-php-lib": "~12.0.0",

**Comment by vtsao** [comment]
@litan1106 what version of PHP specifically are you running?

**Comment by litan1106** [comment]
@vtsao PHP 7.0.5-2+deb.sury.org~trusty+1

**Comment by vtsao** [comment]
Which region are you guys located in, or where are your servers based?

**Comment by gregoryagrant** [comment]
same issue here I am rrunning 12.0.0 with adwords v201607 php 5.6 and having random oath issues, sometimes it works fine other times it fails with 400 issue. I am hosting on ec2

**Comment by kwitte** [comment]
@vtsao my 10.1.0 API on an EC2 server running in us-west-1.  My experimental API (which has not yet experienced any issues) runs on an EC2 server running in us-east-1.

**Comment by vtsao** [comment]
@gregoryagrant can you try making some requests from your local machine to see if you encounter this error as well? I'm still unable to reproduce this issue, so trying to isolate variables.

**Comment by gregoryagrant** [comment]
the weird thing is, it works on my local windows 10 machine running php on xamp and I cannot reproduce this issue. The server it is running on is running Ubuntu 14.0 serving the application over apache 2

**Comment by vtsao** [comment]
Can you try curling to:
https://accounts.google.com/o/oauth2/token

curl 'https://accounts.google.com/o/oauth2/token' -d 'grant_type=refresh_token&refresh_token=&client_id=&client_secret=

from your EC2 instance and see if you can reproduce.

**Comment by gregoryagrant** [comment]
{
  "access_token" : "got the data here",
  "token_type" : "Bearer",
  "expires_in" : 3600
}

**Comment by kwitte** [comment]
@vtsao Your curl command works flawlessly. Meanwhile, on same 10.1.0 server, _LineItemService_ call from yesterday (after undoing your v4 endpoint suggestion) still yields intermittent errors.

**Comment by gregoryagrant** [comment]
yeah that is what is bugging me. And the errors are random. It does not happen after each call, it's like these 3 work then the other one dies with oauth issue.

**Comment by vtsao** [comment]
Can one of you run a tcpdump on a request that is failing and we will inspect it. You can send it to us at dfpapi-support@google.com.

**Comment by litan1106** [comment]
@vtsao I did ten curl requests with the same credentials. No error.

curl 'https://accounts.google.com/o/oauth2/token' -d 'grant_type=refresh_token&refresh_token=&client_id=&client_secret=

**Comment by vtsao** [comment]
Thanks for the information all, we're still investigating this.

**Comment by markvaneijk** [comment]
I had yesterday multiple times the "invalid_request" error with OAuth2Exception, while sending thousands of API requests that day.

But today it's going smooth again. So maybe it was just a occasional hick up on the Google servers?

**Comment by alancoleman** [comment]
The last error I received was yesterday - 01-Sep-2016 17:20:04 America/Denver

like @markvaneijk I'm running requests continually throughout the day and as yet haven't received the error.

**Comment by litan1106** [comment]
Thanks for the help. The issue has been fixed by the Google Team.

**Comment by ivycheung** [comment]
Thank you! I have no admin rights to test anything other than my own code so I had to twiddle my thumbs and hope everyone could resolve this.

**Comment by vtsao** [comment]
Thanks for everybody's patience on this and helping out with providing us with information. This was caused by something we were rolling out on our end, that has been reverted now.

This client library also wasn't handling the HTTP POST correctly for refreshing an access token. It was sending the HTTP POST as form-data, when it should have just been a regular POST. That's been fixed in the 13.0.0 release:
https://github.com/googleads/googleads-php-lib/releases/tag/13.0.0

Would highly recommend updating to this release.
