### ISSUE TITLE
Report download failed (http error code 0)

### ISSUE THREAD

**Issue by hakimio** [googleads/googleads-php-lib#163]
Recently we started getting random "Report download failed" errors without any error type set (the errors started to appear yesterday - 7th of September). 
Does this happen because of request time-out or some other reason?

**Comment by dklimkin** [comment]
Hi Hakimio,

Is this for AdWords API? What version are you using?

**Comment by hakimio** [comment]
Yes, it is for AdWords API. v201607.

**Comment by dklimkin** [comment]
Please report the issue on the AdWords API forum as this is likely not a library issue:

  https://groups.google.com/forum/#!forum/adwords-api

I recommend attaching the log files for a failed call (please make sure to remove sensitive details like developer token and auth token).
