### ISSUE TITLE
SimpleOAuth2Handler need to change how http_build_query is done

### ISSUE THREAD

**Issue by MarthinusBotha** [googleads/googleads-php-lib#165]
Greetings,

The following will ensure that users won't get any "grant_type parameter not found" errors if you change the following in the method `SimpleOAuth2Handler::MakeRequest($url, $params):`

`$this->curlUtils->SetOpt($ch, CURLOPT_POSTFIELDS, http_build_query($params));`

to

`$this->curlUtils->SetOpt($ch, CURLOPT_POSTFIELDS, http_build_query($params, '', '&'));`

The reason for this change is that this http_build_query on PHP 5.6 in my project generated with `&amp;` instead of `&`. Once I made this change on my side within the file the error got resolved.

**Comment by vtsao** [comment]
Hello:

The default for the arg separator for PHP should be '&':
http://php.net/manual/en/ini.core.php#ini.sect.data-handling

it shouldn't be tied to PHP's version. Can you check your php.ini file and ensure that this property hasn't been overridden to "&amp;"?

Thanks,
Vincent

**Comment by vtsao** [comment]
@MarthinusBotha can you please confirm the above? I'm going to close this for now, but if there is still an issue, let me know and we can discuss. Thanks.
