### ISSUE TITLE
Can only install one of: symfony/serializer

### ISSUE THREAD

**Issue by drupalroller** [googleads/googleads-php-lib#166]
I have the following problem when I try to install on my mac os:

`$ php composer.phar require googleads/googleads-php-lib:dev-experimental
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: symfony/serializer[3.0.x-dev, v2.8.0].
    - Can only install one of: symfony/serializer[v2.8.0, 3.0.x-dev].
    - Can only install one of: symfony/serializer[3.0.x-dev, v2.8.0].
    - Can only install one of: symfony/serializer[3.0.x-dev, 2.8.x-dev].
    - googleads/googleads-php-lib dev-experimental requires symfony/serializer ~3.0.3 -> satisfiable by symfony/serializer[3.0.x-dev].
    - Installation request for googleads/googleads-php-lib dev-experimental -> satisfiable by googleads/googleads-php-lib[dev-experimental].
    - Installation request for symfony/serializer ~2.8 -> satisfiable by symfony/serializer[2.8.x-dev, v2.8.0].

Installation failed, reverting ./composer.json to its original content.`

Where is the problem?
Thank you,

**Comment by vitorarjol** [comment]
Check the `minimum-stability` option of your composer.json file. If it's set to `stable`, you can  try to use the `dev`option.
```
"minimum-stability": "dev"
```

**Comment by drupalroller** [comment]
Is because of drupa 8.1, there are some conflicts with it. I will try to solve it. Thankyou,

**Comment by vtsao** [comment]
I will close this then since it sounds like a Drupal issue rather than an issue with the Composer file for the beta library.
