### ISSUE TITLE
How about namespaces?

### ISSUE THREAD

**Issue by mikemeier** [googleads/googleads-php-lib#167]
I try to implement DFP, found this library and then I see, that there are no namespaces. Not even prefixed class-names. What is this? 2010? ;-(

**Comment by shakaran** [comment]
Hi @mikemeier there are some progress in experimental branch https://github.com/googleads/googleads-php-lib/tree/experimental see issue #4

**Comment by vtsao** [comment]
Thanks @shakaran. That's correct, we have a beta branch of this library currently in development and plan to move it to stable soon. The beta branch uses modern PHP development practices and adheres to various PSR's. Namespacing being one of them.

As @shakaran pointed out, please follow #4 for updates. Thanks.
