### ISSUE TITLE
[QUESTION] How to fetch all ip blocked in a campaign

### ISSUE THREAD

**Issue by shakaran** [googleads/googleads-php-lib#172]
I develop a script using BatchJobService and [CampaignCriterionOperation](https://developers.google.com/adwords/api/docs/reference/v201607/CampaignCriterionService.CampaignCriterionOperation) for add ips to be excluded in a adwords campaign.

My problem is that I get a list of ips every day, and I have to erase all the ips already excluded in the adwords campaign and then add one each time to the list.

But [CampaignCriterionOperation](https://developers.google.com/adwords/api/docs/reference/v201607/CampaignCriterionService.CampaignCriterionOperation) doesn't have a "LIST" operation or "CLEAR" operation.

So how I can get at least the list or current ip already blocked for a campaign? So I can after delete one per one and add the needed.

**Comment by fiboknacky** [comment]
Hi shakaran,

As this is more related to the AdWords API product, could you please ask the questions on the [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api) instead?
There are people who moderate the forum actively.

Thanks in advance.

Best,
Thanet, AdWords API Team
