### ISSUE TITLE
SoapFault in AdsSoapClient.php line 215

### ISSUE THREAD

**Issue by fonko** [googleads/googleads-php-lib#178]
Im using laravel with this api and im getting this error, i have asked the guy that build adwords libs for laravel and he told me to ask here, does anyone have similar error than me? im really lost here.

SoapFault in AdsSoapClient.php line 215:
Unmarshalling Error: cvc-elt.4.3: Type 'ns1:Money' is not validly derived from the type definition, 'string', of element 'ns1:deliveryMethod'.

![error2](https://cloud.githubusercontent.com/assets/2717577/19494789/0fcd9f18-9557-11e6-94f4-61ab52c07143.PNG)

**Comment by fiboknacky** [comment]
Hello @fonko,

Could you please share your code as well?
What did you try to do?

Thanks.
Knack

**Comment by fonko** [comment]
yes sorry, here is the code i have used:

http://pastebin.com/HDXkkZs7

the problem seems to be when runing "mutate". I have it debugged and this is the step that throws the error:

 $campaignReturnValue = $campaignService->mutate($operations);

**Comment by fiboknacky** [comment]
Hello @fonko,

In line 60,
`$campaign->budget = new Budget('123', 'default budget', 'DAILY', new Money(10000), 'STANDARD');`
You put the wrong order of parameters.
The `new Money(10000)` should be the third parameter, not the fourth.
Please confirm [Money class definition](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/v201609/CampaignService.php#L722).

Thanks!
Knack
