### ISSUE TITLE
Setting log path without settings.ini

### ISSUE THREAD

**Issue by komirad** [googleads/googleads-php-lib#179]
I would like to set the log path using a function like `storage_path('logs')`. Currently, this is not possible as the settings must be in settings.ini file.

I've tried using `$adWordsUser->LoadSettings()` function but it doesn't allow me to null the `$settingsIniPath` param (throws unable to open stream exception).

The `$logsDirectory` is private, so I cannot set it directly.

**Comment by vtsao** [comment]
Hi @komirad thanks for the feedback. You're right, unfortunately there's no way to do this programmatically. We won't be adding support for this as our efforts are currently being focused on getting our experimental version of this library to stable so we can release it:
https://github.com/googleads/googleads-php-lib/tree/experimental

The experimental library uses [Monolog](https://github.com/Seldaek/monolog) for logging, which supports what you're looking for.
