### ISSUE TITLE
[Experimental] No way to set OAuth2 access token

### ISSUE THREAD

**Issue by hakimio** [googleads/googleads-php-lib#180]
While stable branch of the library allows to do both - set and get the OAuth2 access token, experimental branch only seems to allow getting it.

It's possible to get the access token and its expiration time using "adWordsSession->getOAuth2Credential()->getLastReceivedToken()". However OAuth2TokenBuilder class only allows setting refresh token but not the access token.

Would it be possible to have an ability to set access token and its expiration time using experimental version of the library?

**Comment by vtsao** [comment]
Hey @hakimio, this is actually possible in the beta library. The beta library uses our auth library.

When setting the OAuth2 credentials in the AW session:
https://github.com/googleads/googleads-php-lib/blob/experimental/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L159

you can create an instance of OAuth2.php and set it:
https://github.com/google/google-auth-library-php/blob/master/src/OAuth2.php#L1174

then you can set the access token on the OAuth2 object yourself.

Can you clarify your use case for wanting to set the access token yourself? Are you managing refreshing the access token outside of this library, and if so, can you explain why? Just wondering if the library is missing something that can help you with this. Thanks.

**Comment by hakimio** [comment]
I am creating a web app where I want to reuse same access token between requests until it expires instead of getting a new one every time. AFAIK, that's the way it should work.

I instantiate AdwordsSession fields from Configuration object which I manually create instead of using *.ini  config file. It would be great if I could include access token and expiration time in that Configuration object (under "OAUTH2" section) the same way I can include refresh token there.

It seems you have a leaky abstraction layer in the experimental library version.
To set access token I have to instantiate 3rd party OAuth2 object myself, to set cURL options when downloading report data I have to instantiate Guzzle Client (which btw results in logging functionality loss).

Also, I am wondering if it really makes sense to accept and return interfaces instead of actual implementations in a lot of methods. For example, can you actually use more than one FetchAuthTokenInterface implementation in AdWordsSessionBuilder? It's a bit annoying that you have to add annotations everywhere yourself telling what's the actual object type to get decent auto-completion in the IDE.

**Comment by vtsao** [comment]
> I am creating a web app where I want to reuse same access token between requests until it expires instead of getting a new one every time. AFAIK, that's the way it should work.

This is actually how the library current works (both the existing and beta libraries). The access token is only refreshed when it's about to expire. See this class for details (beta library):
https://github.com/googleads/googleads-php-lib/blob/experimental/src/Google/AdsApi/Common/OAuth2TokenRefresher.php#L57

We recommend you let the library take care of refreshing access tokens for you in this way.

**Comment by hakimio** [comment]
Between requests AdWordsSession object is not the same. It's recreated every time. How can it already have the access token to check if it's expired or not? Am I missing something?

**Comment by vtsao** [comment]
Okay, didn't realize you meant HTTP requests to your website. How about reusing the same AdWords session object for a web session, instead of creating a new one every time your page is hit?

**Comment by hakimio** [comment]
In my case, there are multiple users using the same agency's MCC account and as a result refresh token. If I just serialize AdWords session in a web session, it will be one access token per user. If I store access token in my DB, it can be shared between multiple users.

Anyway, can you explain why you are against being able to include access token in Configuration object used to initialize AdWords session?

**Comment by vtsao** [comment]
> Anyway, can you explain why you are against being able to include access token in Configuration object used to initialize AdWords session?

I'm not necessarily opposed to this, I wanted to understand your use case better, which was unclear at first. I'm also looking into if this level of convenience is appropriate for how common/rare this use case is. Because as mentioned before, you can create an OAuth2 object and set it there.

Will get back to you on this. Thanks.
