### ISSUE TITLE
Error at the end

### ISSUE THREAD

**Issue by rafaelfayosoliver** [googleads/googleads-php-lib#190]
I went through the whole process and at the end, when I write in the terminal the authorization code from Google website, an error ocurred: "Your OAuth2 Credentials are incorrect"

**Comment by fiboknacky** [comment]
Hello @rafaelfayosoliver 

I assume that you use AdWords API. Please correct me if I'm wrong.

Could you please describe how you got client ID and client secret? 
Did you follow the step described [here](https://github.com/googleads/googleads-php-lib/wiki/API-access-using-own-credentials-(installed-application-flow)#step-1---creating-oauth2-credentials)?

There are also detailed steps described in [our webpage](https://developers.google.com/adwords/api/docs/guides/authentication) as well.
As an alternative way to get refresh token, you can use [OAuth2 Playground ](https://developers.google.com/adwords/api/docs/guides/authentication#oauth2_playground) too, if this is more convenient and easier for you.

Cheers,
Thanet, AdWords API Team

**Comment by rafaelfayosoliver** [comment]
Thanks, I solved the problem. It was something I was doing wrong

2016-12-05 7:03 GMT+01:00 Thanet Praneenararat <notifications@github.com>:
