### ISSUE TITLE
Old library end of life (EOL) support.

### ISSUE THREAD

**Issue by vtsao** [googleads/googleads-php-lib#193]
This issue tracks the support plan and timeline for the [old library](https://github.com/googleads/googleads-php-lib/tree/deprecated) before it reaches end of life (EOL). The old library will be sunset at the end of **July 2017** where it will no longer be updated and we will no longer offer support for it.

| | 11/2016 | 12/2016 | 01/2017 | ... | 7/2017 | 8/2017 | ... |
| --- | --- | --- | --- | ---| --- | --- | --- |
| **Old library** | Stable | Deprecated | Deprecated | ... | Sunset end of month | N/A | ... |
| **New library** | Beta | Stable release | Stable | ... | Stable | Stable | ... |

In the meantime, the old library will continue to receive **reduced support** until it reaches EOL. The new library was released as [25.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/25.0.0) to allow releases to still be made for the old library, which are versions < 25.0.0.

For the old library, we will still do the following:

- Bug fixes will still be made.
- Updates to support new AdWords and DFP API version releases and sunsets.
- [Releases](https://github.com/googleads/googleads-php-lib/releases) will still be made.

And no longer be doing the following:

- Adding new examples, features, or utilities, unless they are absolutely necessary.
- Accepting pull requests.

**Comment by fiboknacky** [comment]
All supported versions of the deprecated library are sunset, so I close this issue.
