### ISSUE TITLE
Generate and publish PHPDoc for new library.

### ISSUE THREAD

**Issue by vtsao** [googleads/googleads-php-lib#194]
Generate PHPDoc for new library and publish to [gh-pages](https://github.com/googleads/googleads-php-lib/tree/gh-pages) branch.

**Comment by fiboknacky** [comment]
PHPDoc is now generated, so I close this.

**Comment by ElectricFiras** [comment]
where is the documentation ?

**Comment by fiboknacky** [comment]
Please see the [README file](https://github.com/googleads/googleads-php-lib#documentation).
