### ISSUE TITLE
Adwords v201609 missing ErrorUtils.php class.

### ISSUE THREAD

**Issue by jeffersoncechinel** [googleads/googleads-php-lib#198]
I'm not able to handle partial errors because I cannot find ErrorUtils class anywhere in the v201609 library. There is an example in documentation of how to use this class but I cannot find it.

Example of usage: https://developers.google.com/adwords/api/docs/samples/php/error-handling

**Comment by fiboknacky** [comment]
Hello @jeffersoncechinel 

The link you provide is actually based on the old version (e.g., [v15.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/15.0.0)). We've recently launched the new version (v25.0.0) that supports namespacing and other features.

In [v25.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/25.0.0), we don't provide `ErrorUtils` anymore as there are a small number of usages across the library.
Instead, we provide `getSourceOperationIndex` as a function inside the [HandlePartialFailures.php](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201609/ErrorHandling/HandlePartialFailures.php#L121)

I'll make sure the sample page that you provide gets updated as soon as possible.
Please let me know if there is anything still unclear.

Cheers,
Knack

**Comment by jeffersoncechinel** [comment]
Thank you!
