### ISSUE TITLE
LineItemService Examples?

### ISSUE THREAD

**Issue by socialknowledge** [googleads/googleads-php-lib#199]
It seems many have disappeared in the latest commit?  What happened?

**Comment by vtsao** [comment]
Hi @socialknowledge we've completely rewritten this library and are still porting DFP examples over from the old library to the new one. Please reference the old library's examples for now if something is not available in the new library's examples. Thanks.

https://github.com/googleads/googleads-php-lib/blob/master/UPGRADING.md#examples
