### ISSUE TITLE
composer satisfiable conflicted with google/apiclient ^2.0

### ISSUE THREAD

**Issue by litan1106** [googleads/googleads-php-lib#200]
composer satisfiable conflicted with google/apiclient ^2.0

 Problem 1
    - google/apiclient v2.1.0 requires google/auth ^0.11 -> satisfiable by google/auth[v0.11.1, v0.11.0].
    - google/apiclient v2.0.0 requires google/auth 0.8 -> satisfiable by google/auth[v0.8].
    - Can only install one of: google/auth[v0.7, v0.11.1].
    - googleads/googleads-php-lib 25.0.0 requires google/auth ^0.7 -> satisfiable by google/auth[v0.7].
    - Installation request for google/apiclient ^2.0 -> satisfiable by google/apiclient[v2.0.0, v2.1.0].

**Comment by vtsao** [comment]
Similar to issue #210, updating this lib's dep on google-auth to ^0.11.0 should fix this, I'll do that. Thanks for filing this.

**Comment by vtsao** [comment]
This issue is fixed in [release v25.1.0](https://github.com/googleads/googleads-php-lib/releases/tag/25.1.0).
