### ISSUE TITLE
DFP docs are not updated 

### ISSUE THREAD

**Issue by dysfunct** [googleads/googleads-php-lib#201]
Hey all - I'm running into some issues getting some basic reporting set up, and noticed that the public docs are pretty out of date with what's currently in the code here.

If you take a look at the docs at https://developers.google.com/doubleclick-publishers/docs/reporting#creating_the_reportjob, notice that in many cases direct property access is still being suggested, as opposed to getters and setters. There are also method names that seem to have been arbitrarily changed, such as in `ReportDownloader`, `waitForReportReady` vs `waitForReportToFinish`.

I'm using some combination of suggestions from those docs (with updated methods etc) and the examples within the repo, and most functionality seems to work fine (such as pulling all line items) but generating reports and getting them to complete isn't working - after creating a report, it fails 100% of the time with no useful information. Even running the exact code from the example fails. Here's what I end up with every time:

```
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'Cannot download report 1834929753 because it has a status of FAILED.' in /srv/Encyclopedia-Scripts/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Dfp/Util/v201611/ReportDownloader.php:146
Stack trace:
#0 /srv/Encyclopedia-Scripts/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Dfp/Util/v201611/ReportDownloader.php(116): Google\AdsApi\Dfp\Util\v201611\ReportDownloader->getDownloadUrl('CSV_DUMP')
#1 /srv/Encyclopedia-Scripts/dfp/get_prebid_unit_data.php(85): Google\AdsApi\Dfp\Util\v201611\ReportDownloader->downloadReport('CSV_DUMP', '/tmp/delivery-r...')
#2 {main}
  thrown in /srv/Encyclopedia-Scripts/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Dfp/Util/v201611/ReportDownloader.php on line 146
```

Any kick in the right direction would be helpful!

**Comment by vtsao** [comment]
Hi @dysfunct we're still working on updating the Developer Site docs that you linked to reference the new ads PHP client library.

Can you post your code for the report you're trying to run and I'll take a look? Also post the report job ID. Thanks.

**Comment by dysfunct** [comment]
Hey @vtsao thanks for the follow up. With regards to my specific issue, it turned out to be an easy fix. The initial code as well as the subsequent changes are detailed in this StackOverflow question: https://stackoverflow.com/questions/41388640/google-dfp-api-reportservice-is-failing-with-no-notable-error-message/

The long and short of it is that filters using `LIKE` need to have `%` around the search string (not documented). This is particularly problematic because fetching a saved query that was generated in the DFP UI will not contain `%` around the query and will fail when fetched and run programmatically.

**Comment by vtsao** [comment]
Thanks, will look into the PQL LIKE issue with saved queries. Also FYI our official support channels are outlined here:
https://github.com/googleads/googleads-php-lib/blob/master/README.md#getting-support

you'll get responses from our support team if you post on our API forums for future issues.
