### ISSUE TITLE
Config file path issue

### ISSUE THREAD

**Issue by chiragvels** [googleads/googleads-php-lib#202]
Hello,

As per Doc we can pass custom path to get oauth2creadentials

$oAuth2Credential = (new OAuth2TokenBuilder())
        ->fromFile($path)
        ->build();

But when we pass path it is only taking basename from path we passed and under doc it mentioned that If you specified the path "/config/ads/ads_props.ini" and it doesn't exist, we will try to find "ads_props.ini" in your home directory.

I am passing path as 
$path = 'Sites/adwords-lib/vendor/googleads/googleads-php-lib/examples/AdWords/v201609/adsapi_php.ini';

So it must take entire path instead only base name at /googleads-php-lib/src/Google/AdsApi/Common/ConfigurationLoader.php

the fromFile function might have this
        $home = $this->environmentalVariables->getHome();
        $homeConfigIniFilePath = $home
            . DIRECTORY_SEPARATOR
            . pathinfo($configIniFilePath, PATHINFO_DIRNAME)
            . DIRECTORY_SEPARATOR
            . pathinfo($configIniFilePath, PATHINFO_BASENAME);
Instead 
        $home = $this->environmentalVariables->getHome();
        $homeConfigIniFilePath = $home
            . DIRECTORY_SEPARATOR
            . pathinfo($configIniFilePath, PATHINFO_BASENAME);

Also there is nooption to pass my custom customerId and refreshtoken.

How I can pass same If I have more than 10 Adwords Account to manage?

Thanks,

**Comment by sylvainmtl68** [comment]
While digging more in the code, I realized the library wasn't looking for the HOME variable in the environment ($_ENV), but in the $_SERVER environment.

In my case, the server doesn't populate the HOME variable in the $_SERVER array, so I had to force it my self at the beginning of my script, like this:  

$_SERVER['HOME']=dirname(dirname(__FILE__));

Then the new library would know where to look as the "HOME" directory.   So, you can easily use the same trick I'm pretty sure it would work for you too.

**Comment by chiragvels** [comment]
@sylvainmtl68 Let me try same, currently I was putting ini file to my cwd, and it is working, but my way is not the correct way.

**Comment by chiragvels** [comment]
Hello Team,

It was mistake by me, Its working fine Now.
I need to pass $path under Adwords Session builder also.

$session = (new AdWordsSessionBuilder())
        ->fromFile(**$path**)
        ->withOAuth2Credential($oAuth2Credential)
        ->build();

Thanks,
