### ISSUE TITLE
Class 'AdWordsSessionBuilder' not found : Composer failed AutoLoad

### ISSUE THREAD

**Issue by Tzarn** [googleads/googleads-php-lib#204]
Hello,
Since the  recent update I have been getting this issue whenever I have attempted to instantiate the class:

production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'AdWordsSessionBuilder' not found in <.....PATH.....>

Before the recent update it was working fine. By including it Composer's classmap it was auto-loaded properly however after the recent update I have been experiencing a number of issues related to the recognition of those classes.

**Comment by vtsao** [comment]
Hi @Tzarn to confirm - did you include googleads/googleads-php-lib as a dependency in your project's Composer file?

**Comment by vtsao** [comment]
Hi @Tzarn did that help? I'm closing this issue for now, please re-open if you're still having issues. Thanks.

**Comment by honeyonsys** [comment]
is this issue resolved? what is the solution. @vtsao i have checked that googleads/googleads-php-lib is there as a dependency.

**Comment by fiboknacky** [comment]
Hello,

Do you face with the same exact error?
If so, could you clarify how you installed this library please?

Best,
Knack

**Comment by honeyonsys** [comment]
@fiboknacky I installed it using composer. But i got lot of error while installing it i used
composer update googleads/googleads-php-lib (it starts updating but give me error for some part)
then tried
composer require googleads/googleads-php-lib (it install but i still have example directory missing )
I have config my adsapi_php.ini file in the home directory
Note: i still dont know know that my googleads/googleads-php-lib is installed properly or not

**Comment by fiboknacky** [comment]
Hello @honeyonsys 

If you'd like to try by running some examples, please follow [this section](https://github.com/googleads/googleads-php-lib#running-examples).
`examples/` is not installed when you install the lib using `composer require`, but the library should be installed properly if you don't face with any errors during the process.

It looks like you'd like to try examples too, so could you please try fetching examples as I mentioned above first?

Best,
Knack

**Comment by honeyonsys** [comment]
Follow the instruction to run example from  [this section.](https://github.com/googleads/googleads-php-lib#running-examples)

RUN this command: `$ php examples/AdWords/v201705/BasicOperations/GetCampaigns.php`

Got following error: 

Warning: require(/home/USERNAME/public_html/adwords/vendor/googleads/googleads-php-lib/examples/AdWords/v201705/BasicOperations/../../../../vendor/autoload.php): failed to open stream: No such file or directory in /home/USERNAME/public_html/adwords/vendor/googleads/googleads-php-lib/examples/AdWords/v201705/BasicOperations/GetCampaigns.php on line 19

Fatal error: require(): Failed opening required '/home/USERNAME/public_html/adwords/vendor/googleads/googleads-php-lib/examples/AdWords/v201705/BasicOperations/../../../../vendor/autoload.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/USERNAME/public_html/adwords/vendor/googleads/googleads-php-lib/examples/AdWords/v201705/BasicOperations/GetCampaigns.php on line 19

**Comment by fiboknacky** [comment]
OK, looks good. The next step is to set up your client customer ID accordingly.
[This guide](https://developers.google.com/adwords/api/docs/guides/first-api-call) might be useful to you too.

Knack

**Comment by honeyonsys** [comment]
i have already set that up on adsapi_php.ini

**Comment by fiboknacky** [comment]
What does your `adsapi_php.ini` look like?
From the SOAP log, it seems client customer ID is not set yet or do you just blind it to 000-000-0000?

**Comment by honeyonsys** [comment]
I have copied the text from [adsapi_php.ini](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/adsapi_php.ini) and replace client_id, token, Customer Id etc

I have inserted actual customer ID not 000-000-0000 that i put here only :P

**Comment by fiboknacky** [comment]
OK. So everything looks good. :-)
Do you have anything that I can help further?

**Comment by honeyonsys** [comment]
but my main issue is still exist i am getting Class 'AdWordsSessionBuilder' not found where i have $user = (new AdWordsSessionBuilder())->fromFile();

**Comment by fiboknacky** [comment]
> but my main issue is still exist i am getting Class 'AdWordsSessionBuilder' not found where i have $user > = (new AdWordsSessionBuilder())->fromFile();

You've installed the library using `composer require`, right?
Could you please clarify how the files are organized in your Laravel project?

The error message looks like the autoloading isn't configured properly.

Knack

**Comment by honeyonsys** [comment]
project/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Adwords
do i write whole directory structure?

**Comment by fiboknacky** [comment]
The path to the library looks fine.

Just in case, do you also include "use" statement like [in this example](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201705/BasicOperations/GetCampaigns.php#L23)?
Could you please show the full error message? Is the same as the original post here?

Best,
Knack

**Comment by honeyonsys** [comment]
I have put all these



use Google\AdsApi\AdWords\AdWordsServices;
use Google\AdsApi\AdWords\AdWordsSession;
use Google\AdsApi\AdWords\AdWordsSessionBuilder;
use Google\AdsApi\AdWords\v201705\cm\CampaignService;
use Google\AdsApi\AdWords\v201705\cm\OrderBy;
use Google\AdsApi\AdWords\v201705\cm\Paging;
use Google\AdsApi\AdWords\v201705\cm\Selector;
use Google\AdsApi\AdWords\v201705\cm\SortOrder;
use Google\AdsApi\Common\OAuth2TokenBuilder;


and got this errro now:

InvalidArgumentException in ConfigurationLoader.php line 71: Config file not found as specified: 'adsapi_php.ini'. Home directory could not be located so it was not searched.

**Comment by honeyonsys** [comment]
somehow i manage to update the code by following the sample reference from [here](https://developers.google.com/adwords/api/docs/samples/php/reporting)

Now getting this error: 
Config file not found as specified: 'adsapi_php.ini'. Home directory could not be located so it was not searched.

**Comment by fiboknacky** [comment]
Hi @honeyonsys,

Could you confirm if your `adsapi_php.ini` is already in the home directory?
If it's hard to locate, you can specify a path to that file by using the [`fromFile()`](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L94) method as well.

Best,
Knack

**Comment by honeyonsys** [comment]
Solved. i put the path in fromFile('../../adsapi_php.ini') and its working
