### ISSUE TITLE
"old libraries MapUtils" in the sample code

### ISSUE THREAD

**Issue by josedacosta** [googleads/googleads-php-lib#206]
You have "old libraries" in the sample code ...
Look at this search "master" branch :
https://github.com/googleads/googleads-php-lib/search?q=MapUtils

"old libraries" :
https://github.com/googleads/googleads-php-lib/blob/5eea2f7fb65fd07f0413eb2e33bc2e7563c43078/UPGRADING.md#utilities

**Comment by vtsao** [comment]
Thanks for pointing this out, we'll get this fixed.

**Comment by vtsao** [comment]
This issue is fixed in [release v25.1.0](https://github.com/googleads/googleads-php-lib/releases/tag/25.1.0).
