### ISSUE TITLE
setClientCustomerId function in AdwordsSession is missing

### ISSUE THREAD

**Issue by CodeChiller** [googleads/googleads-php-lib#209]
Hi,

is there any reason why the setClientCustomerId() and setReportSettings function are not available in [AdwordsSession.php](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSession.php)?

The counterpart class [AdwordsSession.java](https://github.com/googleads/googleads-java-lib/blob/master/modules/ads_lib/src/main/java/com/google/api/ads/adwords/lib/client/AdWordsSession.java) in googleads-java-lib contains such functions.

Viet

**Comment by chiragvels** [comment]
Hi @CodeChiller ,
It is available with AdWordsSessionBuilder.php 
You can set same like
$session = (new AdWordsSessionBuilder())
          ->fromFile()
          ->withOAuth2Credential($oAuth2Credential)
          ->withClientCustomerId($clientCustomerId)
          ->build();

Hope this helps!

Thanks,

**Comment by vtsao** [comment]
Thanks @chiragvels. @CodeChiller yes, we generally recommend building a new session for each client customer ID. Does that work for your use case? If you need to manage a large number of client customers, then you could also keep the builder around.

**Comment by litan1106** [comment]
so we should build a new AdWordsSessionBuilder for each client customer ID request?

**Comment by vtsao** [comment]
@litan1106 yes, or keep the session builder around if you know you need to build a new session with a different CCID on a regular basis.
