### ISSUE TITLE
About BatchJob Delegate

### ISSUE THREAD

**Issue by kim-uen** [googleads/googleads-php-lib#214]
I found the null point error  of the method call of  getBatchJobsUtilLogger() on the constructor.
It seems that there are no the instance property of AdwordsSession.
How can I avoid this error ?
 ``
Google\Api\AdsApi\AdWords\BatchJobs\v201609\BatchJobsDelegate.php

```
 public function __construct(
      AdWordsSession $session = null,
      Client $httpClient = null,
      $mutateResultClassName = null
  ) {
    if ($httpClient === null) {
      $stack = HandlerStack::create();
      $stack->before(
          'http_errors',
          GuzzleLogMessageHandler::log(
              $this->session->getBatchJobsUtilLogger())
      );
      $this->httpClient = new Client(['handler' => $stack]);
    } else {
      $this->httpClient = $httpClient;
    }
```

**Comment by fiboknacky** [comment]
Hello @kim-uen 

It's a known issue, which is part of #197.
We're releasing a patch soon, so please follow up #197 instead.

Thanks for reporting.

Best,
Knack

**Comment by kim-uen** [comment]
Hello @fiboknacky 

Thank you for your support.
I am waitng for release patch.

Best Regards,
Kim
