### ISSUE TITLE
Fatal error: Uncaught exception 'Google\AdsApi\AdWords\v201609\cm\ApiException'

### ISSUE THREAD

**Issue by hiakong** [googleads/googleads-php-lib#223]
I install via composer, then I run the examples/AdWords/v201609/BasicOperations/AddCampaigns.php,then show the error like  below.

Fatal error: Uncaught exception 'Google\AdsApi\AdWords\v201609\cm\ApiException' with message '[QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED @ ; trigger:'<null>']' in /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php:39 Stack trace: #0 /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(39): ReflectionClass->newInstanceArgs(Array) #1 /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(162): Google\AdsApi\Common\Util\Reflection->createInstance('Google\\AdsApi\\A...', '[QuotaCheckErro...') #2 /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(126): Google\AdsApi\Common\AdsSoapClient->parseApiExceptionFromSoapFault(Object(SoapFault)) #3 /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201609/cm/BudgetService.php(113): Google\AdsApi\Common\AdsSoapClient->__soapCall('mutate', Array) #4 /home/wwwroo in /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php on line 39

**Comment by fiboknacky** [comment]
Hello @hiakong 

The error indicates that your developer token hasn't been approved yet.
I guess you've not completed the process of signup for using the AdWords API yet (or just applied but the developer token hasn't been granted).
You can find more info at [this page](https://developers.google.com/adwords/api/docs/common-errors).

If you have more questions about AdWords API in general, another option is to post your questions in [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api), which have more people monitoring.

Cheers,
Knack
