### ISSUE TITLE
isAccessTokenExpired class

### ISSUE THREAD

**Issue by JokerMM** [googleads/googleads-php-lib#224]
in the old versions in oauth2 there is a class named isAccessTokenExpired in the new version i cant find the right code for the same reason that why i open this issue

thanks for help

**Comment by vtsao** [comment]
Hey @JokerMM for the new lib we're using the OAuth2 credential object from the [Google PHP Auth library](https://github.com/google/google-auth-library-php). Which are instances of FetchAuthTokenInterface.

Our library automatically refreshes access tokens for you. But if you're managing refreshing access tokens yourself, then you can have a look at the util we use to determine if an access token is expiring or not.

https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/Util/OAuth2TokenRefresher.php#L57

Closing this issue, but please comment if you have further questions.

Thanks,
Vincent
