### ISSUE TITLE
isAccessTokenExpired class 2

### ISSUE THREAD

**Issue by JokerMM** [googleads/googleads-php-lib#225]
thanks @vtsao.

 continuing for my last issue #224
(i cant comment on it )

i need to refresh access token myself cause i want to send it with all Credentials to my controllers in laravel (using envelope) for requesting data from adwords  so i need new access token or valid one passed to my controllers each time i call it.
in the new library is there any features to help me with that or no?? stay on what i do ??

**Comment by vtsao** [comment]
Hi @JokerMM in my previous [response](https://github.com/googleads/googleads-php-lib/issues/224#issuecomment-273299790) I linked you to the new library's `OAuth2TokenRefresher` utility which should help you with that.

Please take a look at that utility and let me know if you have further questions. Thanks.

**Comment by vtsao** [comment]
Closing this as it's been 18 days without an update. Please re-open if you're still running into issues.
