### ISSUE TITLE
Predicate 3rd parameter is restricted to array

### ISSUE THREAD

**Issue by ptheofan** [googleads/googleads-php-lib#227]
This is not a bug per say, but it is a bit funny and unexpected. Predicate constructor 3rd param is restricted to array.

```php
class Predicate {
    public function __construct($field = null, $operator = null, array $values = null)`
}
```

So picture the following statement

```php
new Predicate('PlaceholderTypes', PredicateOperator::EQUALS, [EAdWordsSiteLinksFeed::PLACEHOLDER_SITELINKS]),
```

given I'm using EQUALS, I'd expect to pass in a single value. Passing an array just feels funny (bad semantics). However I would array for IN operator (which looks great).

**Comment by fiboknacky** [comment]
Hello Paris,

Thanks for your comment.
We generate the classes based on the WSDL file [here](https://developers.google.com/adwords/api/docs/reference/v201609/CampaignService.Predicate#values).
As the parameter is an array of string, it's thus generated with the type array restriction.
It would be funny when you use `EQUALS`, but it works as intended. :-)

Cheers,
Knack
