### ISSUE TITLE
Getting Quality Score with getQualityInfo()

### ISSUE THREAD

**Issue by minasm** [googleads/googleads-php-lib#229]
Hello,
I am trying to get the keyword Quality Score. In old library, it was easier:P
Now I am using library v201609.
When I try to reach it with this method
`getQualityInfo()`
I am retrieving the data

```
0 => array (size=4)
 'keywordId' => int 39330000 'keywordText' => string 'KeywordsText' (length=17) 'keywordMatchType' => string 'EXACT' (length=5) 'qualityScore' => object(Google\AdsApi\AdWords\v201609\cm\QualityInfo)[55] 
protected 'qualityScore' => int 4

```
So all good, but I want to reach the qualityScore and get it into an array. How can I reach it? I found a get`QualityScore()` but it is not helping at all.

Thanks for your advice!

**Comment by fiboknacky** [comment]
Hello @minasm 

Sure. Happy to help. :-)
By the way, I'm afraid I don't follow what you said.
In the old library, I believe that we didn't generate classes that have getters.
For example, [`qualityInfo`](https://github.com/googleads/googleads-php-lib/blob/deprecated/src/Google/Api/Ads/AdWords/v201609/AdGroupCriterionService.php#L735) in the old library doesn't have a getter.
On the other hand, in the main branch, we do have [getQualityInfo()](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/v201609/cm/BiddableAdGroupCriterion.php#L286), which returns `QualityInfo` with [getQualityScore()](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/v201609/cm/QualityInfo.php#L28).

So, what you need to do would be just:
`$biddableAdGroupCriterion->getQualityInfo()->getQualityScore()` to get your quality score in integer.

Best,
Knack

**Comment by minasm** [comment]
Thank you @fiboknacky,
I was trying to convert an example for [GetKeywords](https://github.com/googleads/googleads-php-lib/blob/deprecated/examples/AdWords/v201609/BasicOperations/GetKeywords.php) in the library but that did not help:)

p.s.: I said old library was easier because all could handle in one shot:)
```

class GetKeywords {
  
    const PAGE_LIMIT = 500;

    public static function getData(AdWordsServices $adWordsServices,
                                      AdWordsSession $session, $adGroupId) {
        $adGroupCriterionService =
            $adWordsServices->get($session, BiddableAdGroupCriterion::class);

        // Create a selector to select all keywords for the specified ad group.
        $selector = new Selector();
        $selector->setFields(
            ['Id',]);
        //$selector->setOrdering([new OrderBy('Id', SortOrder::ASCENDING)]);
        /*
        $selector->setPredicates([
            new Predicate('AdGroupId', PredicateOperator::IN, [$adGroupId]),
            new Predicate('CriteriaType', PredicateOperator::IN,
                [CriterionType::KEYWORD])
        ]);
        */
        $selector->setPaging(new Paging(0, self::PAGE_LIMIT));

        $totalNumEntries = 0;
        do {
            // Retrieve keywords one page at a time, continuing to request pages
            // until all keywords have been retrieved.
            $page = $adGroupCriterionService->get($selector);

            // Print out some information for each keyword.$
            if ($page->getEntries() !== null) {
                $totalNumEntries = $page->getTotalNumEntries();
                foreach ($page->getEntries() as $adGroupCriterion) {

                    $keywords[] = [
                       'keywordId'=>$adGroupCriterion->getCriterion()->getId(),
                        'qualityScore'=>$adGroupCriterion->getQualityInfo()->getQualityScore()
                    ];

                }
                return $keywords;
            }

            $selector->getPaging()->setStartIndex(
                $selector->getPaging()->getStartIndex() + self::PAGE_LIMIT);
        } while ($selector->getPaging()->getStartIndex() < $totalNumEntries);


    }

    public static function main($clientId,$clientSecret,$refreshToken,$developerToken,$clientCustomerId,$adGroupId) {
        // Generate a refreshable OAuth2 credential for authentication.
        $oAuth2Credential = (new OAuth2TokenBuilder())
            ->withClientId($clientId)
            ->withClientSecret($clientSecret)
            ->withRefreshToken($refreshToken)
            ->build();

        $clientSession = (new AdWordsSessionBuilder())
            ->withClientCustomerId($clientCustomerId)
            ->withDeveloperToken($developerToken)
            ->withOAuth2Credential($oAuth2Credential)
            ->build();
        $keywords = GetKeywords2::getData(new AdWordsServices(), $clientSession, $adGroupId);
        return $keywords;
    }
}
```

This is the error I am having. Surely I am missing something..but all the examples on `BiddableAdGroupCriterion` were setting.

`Fatal error: Call to undefined method Google\AdsApi\AdWords\v201609\cm\BiddableAdGroupCriterion::setStreamContext() in /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClientFactory.php on line 88`

**Comment by fiboknacky** [comment]
Hello,

This line is wrong:
`$adGroupCriterionService = $adWordsServices->get($session, BiddableAdGroupCriterion::class);`

It seems you've unintentionally modified this line?
From the [GetKeywords](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201609/BasicOperations/GetKeywords.php#L46) example, that line is:
`$adGroupCriterionService = $adWordsServices->get($session, AdGroupCriterionService::class);`

Best,
Knack

**Comment by minasm** [comment]
@fiboknacky,
I was trying to figure out how to use BiddableAdGroupCriterion :)

`$adGroupCriterion->getQualityInfo()->getQualityScore()` this line causes me the error.
If I use 
`$adGroupCriterion->getQualityInfo()` than all good but cannot get to the int value.
So I think I cannot use that example to get the QS anyhow?


```

class GetKeywords {

    const AD_GROUP_ID = 'XXXXXXX';
    const PAGE_LIMIT = 500;

    public static function runExample(AdWordsServices $adWordsServices,
                                      AdWordsSession $session, $adGroupId) {
        $adGroupCriterionService =
            $adWordsServices->get($session, AdGroupCriterionService::class);

        // Create a selector to select all keywords for the specified ad group.
        $selector = new Selector();
        $selector->setFields(
            ['Id', 'CriteriaType', 'KeywordMatchType', 'KeywordText']);
        $selector->setOrdering([new OrderBy('KeywordText', SortOrder::ASCENDING)]);
        $selector->setPredicates([
            new Predicate('AdGroupId', PredicateOperator::IN, [$adGroupId]),
            new Predicate('CriteriaType', PredicateOperator::IN,
                [CriterionType::KEYWORD])
        ]);
        $selector->setPaging(new Paging(0, self::PAGE_LIMIT));

        $totalNumEntries = 0;
        do {
            // Retrieve keywords one page at a time, continuing to request pages
            // until all keywords have been retrieved.
            $page = $adGroupCriterionService->get($selector);

            // Print out some information for each keyword.
            if ($page->getEntries() !== null) {
                $totalNumEntries = $page->getTotalNumEntries();
                foreach ($page->getEntries() as $adGroupCriterion) {
                    printf(
                        "Keyword with text '%s', match type '%s', criteria type '%s', "
                        . "and ID %d was found.\n",
                        $adGroupCriterion->getCriterion()->getText(),
                        $adGroupCriterion->getCriterion()->getMatchType(),
                        $adGroupCriterion->getCriterion()->getType(),
                        $adGroupCriterion->getCriterion()->getId(),
                        $adGroupCriterion->getQualityInfo()->getQualityScore()
                    );
                }
            }

            $selector->getPaging()->setStartIndex(
                $selector->getPaging()->getStartIndex() + self::PAGE_LIMIT);
        } while ($selector->getPaging()->getStartIndex() < $totalNumEntries);

        printf("Number of results found: %d\n", $totalNumEntries);
    }

    public static function main($clientId,$clientSecret,$refreshToken,$developerToken,$clientCustomerId) {
        // Generate a refreshable OAuth2 credential for authentication.
        // Generate a refreshable OAuth2 credential for authentication.
        $oAuth2Credential = (new OAuth2TokenBuilder())
            ->withClientId($clientId)
            ->withClientSecret($clientSecret)
            ->withRefreshToken($refreshToken)
            ->build();

        // Construct an API session configured from a properties file and the OAuth2
        // credentials above.
        $clientSession = (new AdWordsSessionBuilder())
            ->withClientCustomerId($clientCustomerId)
            ->withDeveloperToken($developerToken)
            ->withOAuth2Credential($oAuth2Credential)
            ->build();
        self::runExample(
            new AdWordsServices(), $clientSession, intval(self::AD_GROUP_ID));
    }
}

```

**Comment by fiboknacky** [comment]
Hello,

> $adGroupCriterion->getQualityInfo()->getQualityScore() this line causes me the error.
Could you please specify what the error you got?

And please note that sometimes the quality score might not be available.
We suggest to use reporting's [`QualityScore`](https://developers.google.com/adwords/api/docs/appendix/reports/all-reports#qualityscore) to get metrics like this instead. :-)

Best,
Knack

**Comment by minasm** [comment]
@fiboknacky that was fast:)

Well, for me it was accurate however, I could not reach the qualityScore integer.
I'll give the reports a try now. Hope it's easier to handle:P

`qualityScore' => 
        object(Google\AdsApi\AdWords\v201609\cm\QualityInfo)[71]
          protected 'qualityScore' => int 5`

**Comment by fiboknacky** [comment]
Hello @minasm 

I'm happy to help, but unfortunately, I can't get what you say by "could not reach the qualityScore integer".
What happens when you try to run `$adGroupCriterion->getQualityInfo()->getQualityScore()`?
What is the error message you got?

Cheers,
Knack

**Comment by minasm** [comment]
@fiboknacky,

You're right, this is my error.
`Fatal error: Call to a member function getQualityScore() on null on line 415`

And line 415 is  `'qualityScore'=>$adGroupCriterion->getQualityInfo()->getQualityScore()` 

Thanks,

**Comment by fiboknacky** [comment]
Hi @minasm 

That's what I guessed. :) 
As I mentioned in the previous reply, `QualtyInfo` might not be returned sometimes.
So, you have to ensure to check the null case as well.

Best,
Knack

**Comment by minasm** [comment]
@fiboknacky  LOL! you are a genius 👍 
Just tested with another AdGroup, all keywords having a QS defined and it worked like a charm!
Ok, now I am heading to Reports then. Let me learn it now.

Thank you for your great efforts on help!
