### ISSUE TITLE
Adwords Api Reports 

### ISSUE THREAD

**Issue by JokerMM** [googleads/googleads-php-lib#231]
Hi 
How can I call a report in adwords api without download it
i need just to read it and use it as array or object 
for example same reports in [this example file](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201609/Reporting/DownloadCriteriaReportWithAwql.php)

thanks

**Comment by pankamilr** [comment]
if you set $filePath to null than you can store report results to a variable and do anything you want with it. 

`$results = $reportUtils->DownloadReport('ACCOUNT_PERFORMANCE_REPORT', $filePath, $clientID, $options);`

Results are in XML so firstly you have to parse it.

**Comment by JokerMM** [comment]
in [this file](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/Reporting/ReportDownloadResult.php) of the api there is a function "getAsString" i try it but it not work 

@pankamilr i try your answer but there is a different between my file and your answer but when i put the $filePath to null it give an error 

`Details: [fieldPath: ; trigger: <null>; errorString: AuthorizationError.USER_PERMISSION_DENIED]  `

**Comment by pankamilr** [comment]
@JokerMM my example is for older version of api (i'm using v13), but I think your error message shows that you're giving wrong AdwordsUser in $AdwordsUser variable (I've update my previous answer). Check again.

**Comment by JokerMM** [comment]
``` php
class reportsController extends Controller
{
    /**
     * Show the profile for the given user.
     *
     * @param  int  $id
     * @return Response
     */
	 
	   const PAGE_LIMIT = 50;

    public function getIndex()
    {	
		$client = \Request::get('google_api_client'); 
		
        if( ! $client instanceOf oauth2 )
        {

            App::abort(500, 'Oops ! Missing GClient parameter in route. See log for details.');

            Log::error( 'Client in route paramaters is not an instance of Google_Client');
            Log::debug( 'Google Client class is : ' . get_class($client) );
            Log::debug( 'Route was : ' . Route::getCurrentRoute() );

        }
		
		
		$reportQuery = 'SELECT CampaignId, AdGroupId, Id, Criteria, CriteriaType, '
        . 'Impressions, Clicks, Cost FROM CRITERIA_PERFORMANCE_REPORT '
        . 'WHERE Status IN [ENABLED, PAUSED] DURING LAST_MONTH';


		$reportSettings = (new ReportSettingsBuilder())
			->fromFile()
			->includeZeroImpressions(false)
			->build();

		$session = (new AdWordsSessionBuilder())
			->fromFile()
			->withOAuth2Credential($client)
			->withReportSettings($reportSettings)
			->build();
			
		$reportFormat = 'XML';
		$reportDownloader = new ReportDownloader($session);
		$reportDownloadResult = $reportDownloader->downloadReportWithAwql(
		$reportQuery, $reportFormat);
		
		$datatest =  $reportDownloadResult->getAsString();	
		

		
		$data['datatest'] = $datatest;
		
        return view('child.reports', $data);
    }
}
```

@pankamilr this is my controller 
i pass the oauth2 from another controller using middleware (laravel 5.3)
for the user its a manager user and it work when i call the same example and it work 
it work also when i get campaigns from the same account in two way the selector and WithAwql

**Comment by JokerMM** [comment]
it works its my mistake i let the code read from 'adsapi_php.ini' the ClientCustomerId and i need to change it in $session it will be ->
```php
$session = (new AdWordsSessionBuilder())
			->fromFile()
			->withClientCustomerId('000-000-0000')
			->withOAuth2Credential($client)
			->withReportSettings($reportSettings)
			->build();
```

that is my code must be.

so after i parse the results with this:
```php
$xml=simplexml_load_string($datatest) or die("Error: Cannot create object");

print_r($xml); 
```
it work like a charm 👍 

if you can put this file in the example for other people to use it 
((of corse after you make it readable hahaha))

@pankamilr @vtsao 
if you want close this issue i m done here

thanks a lot

**Comment by vtsao** [comment]
@pankamilr thanks for helping! @JokerMM glad it's working.
