### ISSUE TITLE
Adwords BatchJobService(v201605) FILE_FORMAT_ERROR.

### ISSUE THREAD

**Issue by wuwenhuang** [googleads/googleads-php-lib#232]
I receive a FILE_FORMAT_ERROR when creating AdGroups using BatchJobService. this is the body that i passed in:

```
<?xml version="1.0" encoding="UTF-8"?>
<ns1:mutate xmlns:ns1="https://adwords.google.com/api/adwords/cm/v201605">
   <operations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <AdGroupOperation xsi:type="ns1:AdGroupOperation">
         <operand xsi:type="ns1:AdGroup">
            <id>-1</id>
            <campaignId>749463505</campaignId>
            <name>Batch Ad Group Birthday Template.-1</name>
            <biddingStrategyConfiguration xsi:type="ns1:BiddingStrategyConfiguration">
               <bids xsi:type="ns1:CpcBid">
                  <bid xsi:type="ns1:Money">
                     <microAmount>10000000</microAmount>
                  </bid>
               </bids>
            </biddingStrategyConfiguration>
         </operand>
         <operator>ADD</operator>
      </AdGroupOperation>
   </operations>
   <operations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <AdGroupOperation xsi:type="ns1:AdGroupOperation">
         <operand xsi:type="ns1:AdGroup">
            <id>-2</id>
            <campaignId>749463505</campaignId>
            <name>Batch Ad Group Ad Group #2.-2</name>
            <biddingStrategyConfiguration xsi:type="ns1:BiddingStrategyConfiguration">
               <bids xsi:type="ns1:CpcBid">
                  <bid xsi:type="ns1:Money">
                     <microAmount>10000000</microAmount>
                  </bid>
               </bids>
            </biddingStrategyConfiguration>
         </operand>
         <operator>ADD</operator>
      </AdGroupOperation>
   </operations>
</ns1:mutate>
```

THIS RETURNS : 
```
BatchJob Object
(
    [id] => 443301003
    [status] => CANCELED
    [progressStats] => ProgressStats Object
        (
            [numOperationsExecuted] => 0
            [numOperationsSucceeded] => 0
            [estimatedPercentExecuted] => 0
            [numResultsWritten] => 0
        )

    [uploadUrl] => 
    [downloadUrl] => TemporaryUrl Object
        (
            [url] => https://batch-job-download-prod-ebe9b43.storage.googleapis.com/121807096/443301003.results.xml?GoogleAccessId=926043054183-rbu1gkdushnqrfcf47gser4u8qse2ig4@developer.gserviceaccount.com&Expires=1489091452&Signature=g%2BMGktxCveoOcM1zxSxgsbuXHd%2BZ7yzPWVdnJs1Q2MUxemkvFZpR%2BXA6XtRwHYk730dGcugfWycDEWPhP0Lsu4WwNlHyfwZGQvgvY96jNi5wc93nz7Tc%2BLfujcyrdfOi%2BrPqtAKWzky21mipSq6Bo6MhYxPwWWskB9SWPwuH1UEhI593NtiQ%2BdOOUyTQzUVC9foENnZS6K1HuERUxSpEIStWmDLPVFpz2FNnZ2RULKc%2Bb6Ivtx5pB7pJ42ZiKRcznDrKohquLFYuIzHlJhvmeWDTF27H%2Bvqc7961Q%2Fq1LTBfPaTjl6Ofz46A00ZaL0JRP%2Bb9fWVfJf0QRse%2BehONrw%3D%3D
            [expiration] => 20170309 153052 America/Toronto
        )

    [processingErrors] => Array
        (
            [0] => BatchJobProcessingError Object
                (
                    [reason] => FILE_FORMAT_ERROR
                    [fieldPath] => 
                    [trigger] => 
                    [errorString] => BatchJobProcessingError.FILE_FORMAT_ERROR
                    [ApiErrorType] => BatchJobProcessingError
                    [_parameterMap:ApiError:private] => Array
                        (
                            [ApiError.Type] => ApiErrorType
                        )

                )

        )

    [diskUsageQuotaBalance] => 
)
```

**Comment by fiboknacky** [comment]
Hello @wuwenhuang 

Could you please tell what version of the library you used and whether it's a main branch or deprecated branch?

From what I see now, the parts that have an issue are `<operations>` tags.
Yours looks like this:
```xml
<operations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <AdGroupOperation xsi:type="ns1:AdGroupOperation">
```
However, the correct one should look like this:
```xml
 <operations xsi:type="ns1:AdGroupOperation">
```

Best,
Knack

**Comment by wuwenhuang** [comment]
Im using 13.1.0

**Comment by wuwenhuang** [comment]
what is the stable version to use for v201605

**Comment by fiboknacky** [comment]
Hello,

If you prefer to use deprecated branch, please update to [v15.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/15.0.0).
Though we recommend to use the main branch, [v25.1.0](https://github.com/googleads/googleads-php-lib/releases/tag/25.1.0).

Best,
Knack

**Comment by wuwenhuang** [comment]
okay, im trying to use v201609, which is new version. and branch v25.1.0.

one quick question, i found out that in branch v25.1.0, from the Image()->setData(), which needs to passed in base64Binary class(), that is not in the Google\AdsApi\AdWords\v201609\cm. is that class missing?

**Comment by fiboknacky** [comment]
Hello @wuwenhuang 

That should be just a string.
You can refer to the [UploadImage](https://github.com/googleads/googleads-php-lib/blob/5eea2f7fb65fd07f0413eb2e33bc2e7563c43078/examples/AdWords/v201609/Misc/UploadImage.php#L42) example to see how you can use `setData()`.

Best,
Knack

**Comment by wuwenhuang** [comment]
Tried to use the new v201609. still giving me this FILE_FORMAT_ERROR

---------------- BATCH JOB RESULT -----------------
Google\AdsApi\AdWords\v201609\cm\BatchJob Object
(
    [id:protected] => 443975783
    [status:protected] => CANCELED
    [progressStats:protected] => Google\AdsApi\AdWords\v201609\cm\ProgressStats Object
        (
            [numOperationsExecuted:protected] => 0
            [numOperationsSucceeded:protected] => 0
            [estimatedPercentExecuted:protected] => 0
            [numResultsWritten:protected] => 0
        )

    [uploadUrl:protected] => 
    [downloadUrl:protected] => Google\AdsApi\AdWords\v201609\cm\TemporaryUrl Object
        (
            [url:protected] => https://batch-job-download-prod-ebe9b43.storage.googleapis.com/121807096/443975783.results.xml?GoogleAccessId=926043054183-rbu1gkdushnqrfcf47gser4u8qse2ig4@developer.gserviceaccount.com&Expires=1489260905&Signature=pYT%2BapTDppWmAeUyw6Zmqi347HDZxPjjuK2VDfr%2F6pqGoe6oJFJWLRWvMu46oBrGLJTxwDra8rSLv%2Bfw5Kk7g3kOnH3e2Mr9Y7Wjr4MK%2FdseQv7WOjZb2k4Rk99UNRmCIlR4GKtnOynMIv%2Fr2gA9hbQXt%2Fage0LoCMqWdxe85JDoFWqmAZByTDGzXYdNTJP4ZH9GlL41oM5ciI0by7CMMlAEn0oe19dBa6%2Bc1OHwwUoD7Lx81AuVXNDbUO348eYvGtxo4TTan7B47uayYtzCoq5aPmGl%2FdFz8W2KNfb9TxsUzOfYD0mCuHQfmbqwxHBso0Xh1Kei4IK6vqocDVJAKg%3D%3D
            [expiration:protected] => 20170311 143505 America/Toronto
        )

    [processingErrors:protected] => Array
        (
            [0] => Google\AdsApi\AdWords\v201609\cm\BatchJobProcessingError Object
                (
                    [reason:protected] => FILE_FORMAT_ERROR
                    [fieldPath:protected] => 
                    [trigger:protected] => 
                    [errorString:protected] => BatchJobProcessingError.FILE_FORMAT_ERROR
                    [ApiErrorType:protected] => 
                    [ApiError.Type] => BatchJobProcessingError
                )

        )

    [diskUsageQuotaBalance:protected] => 
)

**Comment by fiboknacky** [comment]
Hello,

Could you share your code snippet as well?
It seems your uploaded XML is this:
```xml
<ns1:mutate xmlns:ns1="https://adwords.google.com/api/adwords/cm/v201609" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <operations>
    <item key="0" xsi:type="ns1:AdGroupOperation">
      <operand>
        <id>36450282222</id>
        <name>Birthday Template</name>
        <biddingStrategyConfiguration>
          <biddingStrategyType>MANUAL_CPC</biddingStrategyType>
          <biddingStrategySource>CAMPAIGN</biddingStrategySource>
          <bids xsi:type="ns1:CpcBid">
            <bid xsi:type="ns1:Money">
              <microAmount>3000000</microAmount>
            </bid>
            <cpcBidSource>ADGROUP</cpcBidSource>
          </bids>
        </biddingStrategyConfiguration>
      </operand>
      <operator>ADD</operator>
    </item>
  </operations>
</ns1:mutate>
```

Note that this part is not correct:
```xml
<operations>
    <item key="0" xsi:type="ns1:AdGroupOperation">
```

It should be just `<operations xsi:type="ns1:AdGroupOperation">`.

Best,
Knack

**Comment by wuwenhuang** [comment]
okay got it working
