### ISSUE TITLE
Bracket errors in GetDeliveryForecastForLineItems

### ISSUE THREAD

**Issue by Code-Working** [googleads/googleads-php-lib#238]
Hello,

I've found an error in GetDeliveryForecastForLineItems examples in both versions [201611](https://github.com/googleads/googleads-php-lib/blob/master/examples/Dfp/v201611/ForecastService/GetDeliveryForecastForLineItems.php#L43) and [201702](https://github.com/googleads/googleads-php-lib/blob/master/examples/Dfp/v201702/ForecastService/GetDeliveryForecastForLineItems.php#L43) in line 42/43:

    $forecast = $forecastService->getDeliveryForecastByIds(
        [$lineItemId1, $lineItemId2), new DeliveryForecastOptions()];

I guess this should rather be:

    $forecast = $forecastService->getDeliveryForecastByIds(
        [$lineItemId1, $lineItemId2], new DeliveryForecastOptions());

Regards
Code-Working

**Comment by vtsao** [comment]
Thanks for reporting this, will fix it soon.

**Comment by fiboknacky** [comment]
This is fixed with [v25.3.0](https://github.com/googleads/googleads-php-lib/releases/tag/25.3.0).
