### ISSUE TITLE
No Ability To Revoke API Access In Web App

### ISSUE THREAD

**Issue by nhtahoe** [googleads/googleads-php-lib#239]
When using the library as a Web App with offline access, users grant access and we receive a refresh token. What if a user want to remove access? According to the documentation at https://developers.google.com/identity/protocols/OAuth2WebServer, there should be something like a $client->revokeToken(); method in the library, but I have not been able to find one. Am I missing something? Telling the user to go to https://myaccount.google.com/u/2/permissions to remove the app themselves is not adequate.

**Comment by vtsao** [comment]
Hi @nhtahoe this library depends on the [Google PHP Auth library](https://github.com/google/google-auth-library-php) for all OAuth2 actions, so I would recommend creating an issue on their repo for this.
