### ISSUE TITLE
Testing OfflineConversionFeed

### ISSUE THREAD

**Issue by nicolangr** [googleads/googleads-php-lib#240]
I'm trying to test OfflineConversionFeed but i can't access my landing pages with a valid gclid. If i create new capaign and i click on banner i will be redirect on my website landing page without any gclid.
Are anyone knowing how to test it?

**Comment by fiboknacky** [comment]
Hello @nicolangr 

Would you mind posting this question in [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api) instead as this question is general (not directly related to PHP client library) and people would benefit from your questions as well?

Thanks in advance.

Best,
Knack
