### ISSUE TITLE
insert google api call into database

### ISSUE THREAD

**Issue by JokerMM** [googleads/googleads-php-lib#242]
what is the best way to insert a data call from google and insert it into database.

my google call is : 
```php
$reportQuery = 'SELECT CampaignName, CampaignId, '
       . 'Conversions, Cost, Clicks, Impressions, AveragePosition, CostPerConversion, MonthOfYear , Year  FROM CAMPAIGN_PERFORMANCE_REPORT '
        . 'WHERE CampaignStatus IN [ENABLED, PAUSED] AND Cost != 0 DURING 20160101,20161231 ';

	$reportSettings = (new ReportSettingsBuilder())
			->fromFile()
			->includeZeroImpressions(false)
			->build();

		$session = (new AdWordsSessionBuilder())
			->fromFile()
			->withClientCustomerId('XXX-XXX-XXXX')   
			->withOAuth2Credential($client)
			->withReportSettings($reportSettings)
			->build();

	$reportFormat = 'XML';
		$reportDownloader = new ReportDownloader($session);
		$reportDownloadResult = $reportDownloader->downloadReportWithAwql(
		$reportQuery, $reportFormat);
		
		$datatest =  $reportDownloadResult->getAsString();	
```

I use the getAsString but it is really hard to work with and need a lot of code and time till its done so i'm asking the expert if there is another way to do it ???

Thanks

**Comment by fiboknacky** [comment]
Hello @JokerMM 

If I understand correctly, you may want something like [AwReporting](https://github.com/googleads/aw-reporting)?
Unfortunately, this is not available in PHP and you would need to parse the data by your own.

Please let me know if I understand your question incorrectly.

Best,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity.
