### ISSUE TITLE
File is missing

### ISSUE THREAD

**Issue by sonelal752** [googleads/googleads-php-lib#244]
require '../../../../vendor/autoload.php';

Where is the file?

This file is missing from googleads-php-lib-master folder.

**Comment by fiboknacky** [comment]
Hello @sonelal752 

The `autoload.php` file refers to the [one](https://getcomposer.org/doc/01-basic-usage.md#autoloading) when you use Composer to install any libraries.
The `autoload.php` file will be generated inside the `vendor` directory.

Can you find the `vendor` directory in your project directory?
Could you show how your project directory is organized?

Cheers,
Knack

**Comment by robolmos** [comment]
I had a similar issue when trying to run the GetRefreshToken.php script. To fix it I needed to update the require line with additional parent-dir double-dot references. Working version:

require '../../../../../vendor/autoload.php';

My environment was setup via composer from this repo's README. The layout within the project "home" directory:

adsapi_php.ini composer.json composer.lock vendor

The path to the GetRefreshToken.php script:

vendor/googleads/googleads-php-lib/examples/Auth/GetRefreshToken.php

**Comment by fiboknacky** [comment]
I'll have a look at this.
Possibly we need to add one more `../` for this.

Thanks.
Knack

**Comment by sudhyer** [comment]
Hi,

URL: http://localhost/googleads/vendor/googleads/googleads-php-lib/examples/Auth/GetRefreshToken.php

when I am running above URL then getting these types of error on screen.
"Enter your OAuth2 client ID here: Enter your OAuth2 client secret here: Select the ads API you're using: [0] AdWords [1] DFP [2] Both Please enter a valid number for the ads API you're using: [0] AdWords [1] DFP [2] Both Please enter a valid number for the ads API you're using: [0] "

**Comment by fiboknacky** [comment]
Hi @sudhyer 

Let's answer in another issue (#302) you've created.

Best,
Knack

**Comment by fiboknacky** [comment]
This is fixed in [v28.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/28.0.0).
