### ISSUE TITLE
How to set CUSTOM_DATE for reporting?

### ISSUE THREAD

**Issue by mahirsumer** [googleads/googleads-php-lib#245]
Hi,

How can i set min and max date for reporting custom daterange (v201609)

**Comment by fiboknacky** [comment]
Hello @mahirsumer 

Please set the [DateRange](https://developers.google.com/adwords/api/docs/reference/v201609/CampaignService.DateRange) in the [Selector](https://developers.google.com/adwords/api/docs/reference/v201609/CampaignService.Selector) you pass to the [ReportDefinition](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/Reporting/v201609/ReportDefinition.php).

As a PHP code, you can do something like this:
```php
$selector->setDateRange(new DateRange('20170101', '20170101'));
```
And you need to modify this [line](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201609/Reporting/DownloadCriteriaReportWithSelector.php#L55) to use `CUSTOM_DATE` instead.
```php
$reportDefinition->setDateRangeType(ReportDefinitionDateRangeType::CUSTOM_DATE);
```

Finally, please don't forget to import `DateRange` using `use` as well. :-)

Cheers,
Knack

**Comment by mahirsumer** [comment]
Thanks for help :)
