### ISSUE TITLE
\Google\AdsApi\AdWords\v201609\cm\BatchJobService::mutate returns null

### ISSUE THREAD

**Issue by Askold123** [googleads/googleads-php-lib#249]
I'm trying to mutate operations using code from this example - https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201609/CampaignManagement/AddCompleteCampaignsUsingBatchJob.php

and I got  `Call to a member function getValue() on null` in  https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201609/CampaignManagement/AddCompleteCampaignsUsingBatchJob.php#L84

The requestId is 000549d4b4b5c4f90a3717c9060807f6

**Comment by fiboknacky** [comment]
Hello @Askold123 

From the SOAP request, you've not added anything:
```xml
<ns1:mutate>
      <ns1:operations>
        <ns1:operator>ADD</ns1:operator>
        <ns1:operand/>
      </ns1:operations>
    </ns1:mutate>
```
That's why there's nothing returned back.
Could you please clarify how you modified our example?

Thanks!
Knack

**Comment by Askold123** [comment]
Thanks for response!
I found a mistake in my code. The reason was that I was setting Google\AdsApi\AdWords\AdWordsSession::$isValidateOnly in other part of my application
