### ISSUE TITLE
Access level to AdsSoapClient::__construct() must be public

### ISSUE THREAD

**Issue by SonicGD** [googleads/googleads-php-lib#25]
Fatal error: Access level to AdsSoapClient::__construct() must be public (as in class SoapClient) or weaker in googleads-php-lib-master/src/Google/Api/Ads/Common/Lib/AdsSoapClient.php on line 47

**Comment by gitazem** [comment]
what's progress is on hhvm support ?

**Comment by gitazem** [comment]
what's progress on this issue support ?

**Comment by vtsao** [comment]
We currently don't have any plans to support HHVM at this time.

**Comment by litan1106** [comment]
I hope that there is support for hhvm later.
