### ISSUE TITLE
Ad units creation via the API

### ISSUE THREAD

**Issue by renshuki** [googleads/googleads-php-lib#250]
Hello everyone,

Thank you for the creation of this library.
I would like to know if there is a way to create ad units by using the API. I looked to the documentation but I didn't find any info about that. I will be grateful for any help you can provide.

Thank you :smile:

**Comment by fiboknacky** [comment]
Hello @renshuki 

I'm glad that this library looks promising to you. :-)
Could you please clarify what you mean by "ad units"? Do you mean [an ad in AdWords](https://support.google.com/adwords/answer/1722117?hl=en&ref_topic=3119117)?

Best,
Knack

**Comment by fiboknacky** [comment]
Sorry for confusion. I think you meant the [DFP ad unit](https://support.google.com/dfp_premium/answer/177203?hl=en)?

**Comment by renshuki** [comment]
Hi Knack,

Thank you for your quick reply.
I currently have a DFP account and I manage a large number of ad units for
a website. Here is some information about DFP ad units
<https://support.google.com/dfp_premium/answer/177203?hl=en>.
When I publish a new article on my website I would like to create
automatically ad units for the page. I'm wondering if it's possible achieve
that with the API library you provide.

Thank you for your help!

Cheers,
Renshuki


Le 2017年3月6日(月) à 19:21, Thanet Knack Praneenararat <
notifications@github.com> a écrit :

Hello @renshuki <https://github.com/renshuki>

I'm glad that this library looks promising to you. :-)
Could you please clarify what you mean by "ad units"? Do you mean an ad in
AdWords
<https://support.google.com/adwords/answer/1722117?hl=en&ref_topic=3119117>?

Best,
Knack

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/googleads/googleads-php-lib/issues/250#issuecomment-284357057>,
or mute the thread

**Comment by vtsao** [comment]
Hi @renshuki please see our example here for how to create DFP ad units using this client library:
https://github.com/googleads/googleads-php-lib/blob/master/examples/Dfp/v201702/InventoryService/CreateAdUnits.php

Documentation can also be found here:
https://developers.google.com/doubleclick-publishers/docs/reference/v201702/InventoryService#createAdUnits

Thanks,
Vincent

**Comment by renshuki** [comment]
Hi Vincent,  
I didn't found this doc. It's exactly what I am looking for. Awesome!
I'll try to implement that into my website.
Thank you so much :smile:
