### ISSUE TITLE
No "createRemoveOperation" method

### ISSUE THREAD

**Issue by jrdnrc** [googleads/googleads-php-lib#252]
In the `Google\AdsApi\AdWords\Shopping\v201702\ProductPartitions` class, there is no `createRemoveOperation`, to allow modification of the partition tree.

I believe I need the 'remove' functionality so that I can remove a criterion and add the criterion back with the changed values.

Happy to submit a PR with the necessary changes.

**Comment by fiboknacky** [comment]
Hello @jrdnhannah 

Originally we separated this class, which was once a helper class in Shopping related examples, to reduce the size of examples. 
But we definitely welcome your contribution as well so please feel free to submit a PR at any time. :)

Best,
Knack

**Comment by jrdnhannah** [comment]
Yeah I saw it in the examples, and was pleased it made it into the codebase. I have submitted my PR.

Thanks @fiboknacky

**Comment by fiboknacky** [comment]
Both two methods are available in `ProductPartitions` already so this is resolved.
