### ISSUE TITLE
setClientCustomerID for PHP

### ISSUE THREAD

**Issue by PT-BBalazs** [googleads/googleads-php-lib#257]
This might not be the best place to ask, since this is most likely not a bug, but how can you possibly set the Client Customer ID dynamically in PHP? Consider the Sample Use Cases:
[Sample use Cases](https://developers.google.com/adwords/api/docs/guides/samples-use-cases)

Here, you can see that all libraries, including Java, C#, etc. have a variant of setClientCustomerID. CTRL+F on the page for "many client customer accounts" to jump to the exact location. In the case of PHP, no such a thing is listed. Is there any way to set the client customer account dynamically in the PHP library? Can you point us in the right direction?

**Comment by fiboknacky** [comment]
Hello @PT-BBalazs 

Feel free to ask any questions if that is related to this library. We'd like to hear from you. :)

Regarding your question,
> but how can you possibly set the Client Customer ID dynamically in PHP? 

In this new library, we try to improve the class design overall, and as `AdWordsSession` is aimed to represent a session for using AdWords API, it makes sense to us that one session is equivalent to one client customer ID.
If you would like to create a session for different client customer IDs, you can do so by using [AdWordsSessionBuilder](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php) to generate a new one using [withClientCustomerId()](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L209).

Best,
Knack

**Comment by shawnbayer** [comment]
How does someone get the [withClientCustomerId()](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L209) after authenticating with the OAuth2 object through a standard [web flow](https://github.com/googleads/googleads-php-lib/wiki/API-access-on-behalf-of-your-clients-(web-flow))?

**Comment by JokerMM** [comment]
Hi @shawnbayer 
you can get the ClientCustomerId from the adwords page [the guide is here](https://support.google.com/adwords/answer/1704344?co=ADWORDS.IsAWNCustomer%3Dfalse&hl=en)
after that you put it in the code or the google call 

if you dont have authorize on the account or you dont have access to the data it not work

**Comment by shawnbayer** [comment]
Hi @JokerMM,
I know where I could get it in the account. I'm wondering how do I pull this info from the OAuth web flow so a user doesn't have to go and find this piece of text in their Adwords account?

**Comment by hakimio** [comment]
@shawnbayer There is an example called "GetAccountHierarchy". Check it out.

**Comment by PT-BBalazs** [comment]
Just a quick reply. Thanks for the information, we have managed to get everything running perfectly. Thanks for the help.

**Comment by shawnbayer** [comment]
In case anyone finds this in the future, here is what I did to get it working to allow me to pull the information:

` 
require_once(__DIR__."/vendor/autoload.php");
use Google\AdsApi\AdWords\AdWordsServices;
use Google\AdsApi\AdWords\AdWordsSessionBuilder;
use Google\AdsApi\AdWords\v201702\mcm\CustomerService;
use Google\AdsApi\AdWords\v201702\mcm\Customer;
use Google\AdsApi\Common\OAuth2TokenBuilder;
use Google\Auth\OAuth2;

$oauth2 = new OAuth2([
        'authorizationUri' => 'https://accounts.google.com/o/oauth2/v2/auth',
        'tokenCredentialUri' => 'https://www.googleapis.com/oauth2/v4/token',
        'redirectUri' => 'http://example.com/google-file.php',
        'clientId' => '*****',
        'clientSecret' => '*****',
        'scope' => 'https://www.googleapis.com/auth/adwords'
    ]);

if(!isset($_GET['code'])){
        
        $oauth2->setState(sha1(openssl_random_pseudo_bytes(1024)));
        $_SESSION['oauth2state'] = $oauth2->getState();

        
        $config = ['access_type' => 'offline'];
        header('Location: '.$oauth2->buildFullAuthorizationUri($config));
}   
elseif(empty($_GET['state']) || ($_GET['state'] !== $_SESSION['oauth2state'])){
        unset($_SESSION['oauth2state']);
        exit('Invalid state.');
}
else{
        $oauth2->setCode($_GET['code']);
        $authToken = $oauth2->fetchAuthToken();
        $refreshToken = $authToken['refresh_token'];

        $clientId = '*****';
        $clientSecret = '*****';
        $developerToken = '*****';

        $tokenBuild = new OAuth2TokenBuilder();
        $tokenBuild->withClientId($clientId)->withClientSecret($clientSecret)->withRefreshToken($refreshToken);
        $oAuth2Credential = $tokenBuild->build();

        $session = (new AdWordsSessionBuilder())->withDeveloperToken($developerToken)->withOAuth2Credential($oAuth2Credential)->build();
        $adWordsServices = new AdWordsServices();
        $customerService = $adWordsServices->get($session, CustomerService::class);
        $customers = $customerService->getCustomers();

        foreach($customers as $c){
            $adwordsCurrencyCode = $c->getCurrencyCode();
            $adwordsClientId = $c->getCustomerId();
            $adwordsDescriptiveName = $c->getDescriptiveName();
        }
}`

**Comment by fiboknacky** [comment]
Hi @PT-BBalazs,

It seems you have an answer now, so I'll close this one.
Thanks everyone for the reply too.

Knack
