### ISSUE TITLE
Composer installation failed (like #210 but another packages are conflicting)

### ISSUE THREAD

**Issue by ivanoff4egs** [googleads/googleads-php-lib#258]
Hello.
The issue looks like [#210](https://github.com/googleads/googleads-php-lib/issues/210), but it has already closed.
Installation flow:

> php composer.phar require googleads/googleads-php-lib
Using version ^25.4 for googleads/googleads-php-lib
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for googleads/googleads-php-lib ^25.4 -> satisfiable by googleads/googleads-php-lib[25.4.0].
    - Conclusion: remove phpdocumentor/reflection-docblock 2.0.4
    - Conclusion: don't install phpdocumentor/reflection-docblock 2.0.4
    - googleads/googleads-php-lib 25.4.0 requires phpdocumentor/reflection-docblock ^3.0.3 -> satisfiable by phpdocumentor/reflection-docblock[3.0.3, 3.1.0, 3.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.0.3, 2.0.4].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.0, 2.0.4].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.1, 2.0.4].
    - Installation request for phpdocumentor/reflection-docblock (locked at 2.0.4) -> satisfiable by phpdocumentor/reflection-docblock[2.0.4].
Installation failed, reverting ./composer.json to its original content.

My composer.json requirements:

> "minimum-stability": "stable",
  "require": {
    "symfony/http-foundation":"3.2.1",
    "symfony/validator": "3.2.1",
    "egulias/email-validator": "2.1.1",
    "klarna/php-xmlrpc": "5.0.*",
    "klarna/checkout": "v4.0.0",
    "paypal/rest-api-sdk-php": "1.10.*",
    "monolog/monolog": "1.22.0",
    "psr/log": "1.0.2",
    "ruflin/elastica": "3.2.3",
    "google/cloud": "0.20.0"
  },
  "require-dev": {
    "phpunit/phpunit": "4.8.23",
    "pdepend/pdepend": "2.3.2",
    "phpmd/phpmd": "2.5.0",
    "sebastian/phpcpd": "2.0.4",
    "squizlabs/php_codesniffer": "2.7.0",
    "behat/behat": "v3.2.2",
    "behat/mink": "v1.7.1",
    "behat/mink-sahi-driver": "v1.2.1",
    "behat/mink-goutte-driver": "v1.2.1",
    "fzaninotto/Faker": "v1.6.0",
    "behat/mink-extension": "v2.2",
	"phpspec/prophecy": "v1.6.0"
  }
Could it be the packages version conflict as it was in [#210](https://github.com/googleads/googleads-php-lib/issues/210)? 
Thanks.

**Comment by fiboknacky** [comment]
Hello @ivanoff4egs 

It has conflict because your last dependency in the `require-dev` (phpspec/prophecy v1.6.0) also requires `phpdocumentor/reflection-docblock` but with different major versions than ours (^2.0 vs ^3.0.3)

If you can upgrade that dependency to [v1.7.0](https://packagist.org/packages/phpspec/prophecy#v1.7.0), which requires the same major version as ours, this would resolve this issue.
Is it possible for you to do so?

Best,
Knack

**Comment by ivanoff4egs** [comment]
Hello @Knack.
Upgrading phpspec/prophecy v1.6.0 to v1.6.1 solved this issue. 
Thank you very much for your help.

Best regards,
Serge.
