### ISSUE TITLE
catch google session expiry 

### ISSUE THREAD

**Issue by JokerMM** [googleads/googleads-php-lib#259]
Hi 
How can I catch the error OAUTH_TOKEN_INVALID after the access token expire to let the user redirect to the connect page with a message and not see the error ???

**Comment by fiboknacky** [comment]
Hi @JokerMM 

This library refresh tokens automatically when the access token is expired so you probably don't need to worry about that.
Please see [this method](https://github.com/googleads/googleads-php-lib/blob/5eea2f7fb65fd07f0413eb2e33bc2e7563c43078/src/Google/AdsApi/Common/Util/OAuth2TokenRefresher.php#L57) for more details.

Best,
Knack

**Comment by JokerMM** [comment]
Hi @fiboknacky 
My program is that there is page for connection and i put the access code in the session .
after that i use the data in the session to call different reports in different pages from google adwords.
that why i need to catch the error when i try calling from one of the pages to redirect the user to the connection page.

**Comment by fiboknacky** [comment]
Hi @JokerMM 

Sorry but I still don't follow how you use this library to connect to your application.
Could you please clarify more?
It looks like you don't fully rely on our library for OAuth2 authentication.

Do you implement this on their own by asking users to put their access codes directly?
In the OAuth2 flow, you probably just ask your users for consent to act on behalf of them, as described in [this doc](https://developers.google.com/identity/protocols/OAuth2WebServer).

Best,
Knack

**Comment by JokerMM** [comment]
Hi @fiboknacky 

in my connect page I use this code from the library 
```php
$client = new OAuth2([
    'authorizationUri' => 'https://accounts.google.com/o/oauth2/v2/auth',
    'tokenCredentialUri' => 'https://www.googleapis.com/oauth2/v4/token',
]);


        $client->setClientId( $clientId );
        $client->setClientSecret( $clientSecret );
        $client->setRedirectUri( $redirectUri );
        $client->setScope( $scopes );
		  
        try{
  			$client->setCode($code);
 			 $authToken = $client->fetchAuthToken();

        } catch(\Exception $e){

            Log::error( 'Client authentication failed : ' . $e->getMessage() );

            $message = sprintf("<h3>Oups !</h3>
                                <p>Authentication failed.
                                Google error message was :</p>
                                <p><q>%s</q></p>", htmlspecialchars( $e->getMessage() ));


            // render error view
            return View::make('errors.default', array('errorMessage' => $message));

        }

 $config = [
    // Set to 'offline' if you require offline access.
    'access_type' => 'offline'
 	 ];
        $auth_infos = $client->getAccessToken($config);


```

and after getting the data of the access token I put it in the session 

```php

        Session::put( self::G_FULL_AUTH_INFO_SESSION_KEY, $auth_infos);

```

now in every other page i call the $client from the session and it give me all the data needed to call reports from adwords

but after the expired date is finish it give me the error OAUTH_TOKEN_INVALID that why i need to catch this error in any way to redirected it to connection page

**Comment by JokerMM** [comment]
if there another way to do it im open to change the code 
the program in test now not online

**Comment by JokerMM** [comment]
Any Update ??? @fiboknacky 

thanks for helping

**Comment by fiboknacky** [comment]
Hi @JokerMM 

Sorry for late reply. I'm still figuring out.
By the way, could you please clarify how you use this line:
```php
        $auth_infos = $client->getAccessToken($config);
```

It looks like that in the current version of `OAuth2`, it doesn't have the method `getAccessToken` that receives the `$config` as a parameter?

In addition, I wonder if you could use [`getExpiresIn`](https://github.com/google/google-auth-library-php/blob/master/src/OAuth2.php#L1083) to determine if your access token will be expired soon?

Best,
Knack

**Comment by fiboknacky** [comment]
Hi @JokerMM 

Do you have a chance to try what I mentioned in the previous comment?
Thanks!

Knack

**Comment by fiboknacky** [comment]
Close due to inactivity. Feel free to reach out again if you need help.
