### ISSUE TITLE
Function ("mutate") is not a valid method for this service

### ISSUE THREAD

**Issue by faridghar** [googleads/googleads-php-lib#263]
When trying to create a campaign, I kept receiving the following error:

`Function ("mutate") is not a valid method for this service`

The AdWords API documentation clearly states that mutate() is indeed a valid method for the CampaignService class. Researching online brought me to [this](http://stackoverflow.com/questions/8354785/uncaught-soapfault-exception-client-function-is-not-a-valid-method-for-this-s). So I added the following to my php.ini file:

`soap.wsdl_cache_enabled = 0`

And the error disappeared. It's possible to set this config programmatically like so:

`ini_set("soap.wsdl_cache_enabled", "0");`

Should this be added to the source code?

**Comment by fiboknacky** [comment]
Hi @faridghar,

SOAP WSDL caching is supported in [this file](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/adsapi_php.ini#L43).
Is this what you want to set?

Best,
Knack

**Comment by faridghar** [comment]
Hi @fiboknacky,

Is that setting the same as php.ini's soap.wsdl_cache_enabled? Either way,
would it make sense to default it to 0 to avoid other users from running
into the same problem? Spent the last few hours troubleshooting.

Thanks,
Farid

**Comment by fiboknacky** [comment]
Hello Farid,

From [this section](http://php.net/manual/en/soap.configuration.php#ini.soap.wsdl-cache), it's the same.
I've never got report like this before. In general, with PHP default settings, this lib should work without any tweaks on the SOAP caching settings.
May I ask your PHP version number too? From your link, it looks like those using PHP 7 might be affected by this.

And do you need to set this value all the time?
I wonder if this is a one-time issue or not.

Thanks!

Best,
Knack

**Comment by faridghar** [comment]
Yup, I'm on PHP 7.1.1.

I've inserted soap.wsdl_cache_enabled = 0 into my php.ini file, so yes, the
value is always set. The error was being consistently thrown, wasn't
transient. I'll try switching to an earlier PHP version tomorrow and get
back to you.

Thanks

**Comment by fiboknacky** [comment]
Hi @faridghar 

But from [this blog](https://lornajane.net/posts/2015/soapfault-when-switching-php-versions), it looks like the cache directory wouldn't work well with many PHP versions.
I'm not sure how your systems are composed.

Knack

**Comment by faridghar** [comment]
Yeah, that's exactly the blog I used to figure out what was going on. I'm
surprised other users aren't experiencing the same thing. Is version 7.1.1
that unpopular?

**Comment by fiboknacky** [comment]
Hi @faridghar,

I did see people use version 7.0.x but not sure about 7.1.1.
It looks like this happens when calling other SOAP services as well, not only ours.

Best,
Knack
