### ISSUE TITLE
Doctrine usage

### ISSUE THREAD

**Issue by mytryk** [googleads/googleads-php-lib#264]
Hi.
Excuse me, that's not issue for you, just question.

Are there any cases of using a library with Doctrine? All I need are just annotations for DB mapping and, possibly, for validation in some classes generated from WSDL . Therefore, if I make them, they will be lost  on library update. Please, can you advise the best way to make such annotations, not depended of the library updates?

Thanks,
Dmytro

**Comment by fiboknacky** [comment]
Hello Dmytro,

It looks like tweaking in class generation from WSDLs is needed.
Our library generates classes using the modified version of [wsdl2phpgenerator](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator), so if you'd like to modify the classes to use with Doctrine, generating the classes by yourself might be an option.

Depending on how deeply you would like to modify, this might not be a trivial task, though.

Best,
Knack
