### ISSUE TITLE
AW_REPORT_DOWNLOADER.WARNING: GuzzleHttp/6.1.0 curl/7.29.0 PHP/7.0.15

### ISSUE THREAD

**Issue by pure4499** [googleads/googleads-php-lib#265]
I have following error and have no clue at all.
CExeption doesn't catch any error. 

Looks like this part is throwing error.
$reportDownloadResult =
          $reportDownloader->downloadReport($reportDefinition);

I also found out same issue with mine [here](https://github.com/googleads/googleads-php-lib/issues/246).

Could you please help me to resolve this issue?

#########
Error
#########
[2017-03-30 01:13:42] AW_REPORT_DOWNLOADER.WARNING: c2f48fb300e7 GuzzleHttp/6.1.0 curl/7.29.0 PHP/7.0.15 - [30/Mar/2017:01:13:42 -0700] "POST /api/adwords/reportdownload/v201702 HTTP/1.1" 400
[2017-03-30 01:13:42] AW_REPORT_DOWNLOADER.NOTICE: >>>>>>>>
POST /api/adwords/reportdownload/v201702 HTTP/1.1
Authorization: REDACTED
User-Agent: GuzzleHttp/6.1.0 curl/7.29.0 PHP/7.0.15
Content-Type: application/x-www-form-urlencoded
Host: adwords.google.com
developerToken: lPTFIdDDbS9z88OwpU4KTg
clientCustomerId: 1344682299
skipReportHeader: false
skipColumnHeader: false
skipReportSummary: false
useRawEnumValues: false
includeZeroImpressions: false

__rdxml=<?xml version="1.0"?>
<reportDefinition><selector><fields>CampaignId</fields><predicates><field>Status</field><operator>NOT_IN</operator><values>PAUSED</values></predicates></selector><reportName>Criteria performance report #58dcbe35784fc</reportName><reportType>CRITERIA_PERFORMANCE_REPORT</reportType><dateRangeType>TODAY</dateRangeType><downloadFormat>CSV</downloadFormat></reportDefinition>

<<<<<<<<
HTTP/1.1 400 Bad Request
Content-Type: text/xml
Date: Thu, 30 Mar 2017 08:13:42 GMT
Expires: Thu, 30 Mar 2017 08:13:42 GMT
Cache-Control: private, max-age=0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Alt-Svc: quic=":443"; ma=2592000; v="37,36,35"
Accept-Ranges: none
Vary: Accept-Encoding
Connection: close

#########
Code
#########

$auth2Credential = (new OAuth2TokenBuilder())
	->fromFile()
	->build();

$reportSettings = (new ReportSettingsBuilder())
	->fromFile()
	->includeZeroImpressions(false)
	->build();

$session = (new AdWordsSessionBuilder())
	->fromFile()
	->withOAuth2Credential($auth2Credential)
	->withClientCustomerId($strCustomerId)
	->withReportSettings($reportSettings)
	->build();

$selectorReport->setFields(['CampaignId']);

$selectorReport->setPredicates([
          new Predicate('Status', PredicateOperator::NOT_IN, ['PAUSED'])]);

$reportDefinition = new ReportDefinition();
$reportDefinition->setSelector($selectorReport);
$reportDefinition->setReportName(
  'Criteria performance report #' . uniqid());
$reportDefinition->setDateRangeType(
  ReportDefinitionDateRangeType::TODAY);
$reportDefinition->setReportType(
  ReportDefinitionReportType::CRITERIA_PERFORMANCE_REPORT);
$reportDefinition->setDownloadFormat(DownloadFormat::CSV);
// Download report.
$reportDownloader = new ReportDownloader($session);
$reportDownloadResult =
  $reportDownloader->downloadReport($reportDefinition);

$reportDownloadResult->saveToFile($filePath);

**Comment by fiboknacky** [comment]
Hello,

First, could you please remove the line that contains your developer token? It's your private data. :-)
And having a look at this line:

```
__rdxml=
CampaignIdStatusNOT_INPAUSEDCriteria performance report #58dcbe35784fcCRITERIA_PERFORMANCE_REPORTTODAYCSV
```

This doesn't look correct. How did you create the report definition?
The correct one in the log file should look like, e.g., this:

```xml
__rdxml=<?xml version="1.0"?>
<reportDefinition><selector><fields>CampaignId</fields><fields>AdGroupId</fields><fields>Id</fields><fields>Criteria</fields><fields>CriteriaType</fields><fields>Impressions</fields><fields>Clicks</fields><fields>Cost</fields><predicates><field>Status</field><operator>NOT_IN</operator><values>PAUSED</values></predicates></selector><reportName>Criteria performance report #58dcba1d89e12</reportName><reportType>CRITERIA_PERFORMANCE_REPORT</reportType><dateRangeType>LAST_7_DAYS</dateRangeType><downloadFormat>CSV</downloadFormat></reportDefinition>
```

Best,
Knack

**Comment by fiboknacky** [comment]
It seems there was a transient issue for reporting service at that time and should get resolved already.
Please let me know if you needs any assistance.
