### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by pure4499** [googleads/googleads-php-lib#266]
I'm suffering with this error.

CRITERIA_PERFORMANCE_REPORT type report is working correctly for me.
(had a issue but realized there were limitation per day.)
But CAMPAIGN_PERFORMANCE_REPORT type report is not working for me.

Could you please advise me what I'm doing wrong?

########
CODE
########

   $strCustomerId = '-------';    
   $campaignId ="-------";
    $selectorReport = new Selector();
    $selectorReport->setFields(['CampaignId']);

    $selectorReport->setPredicates([new Predicate('CampaignId', PredicateOperator::EQUALS, [$campaignId])]);
    $reportDefinition = new ReportDefinition();
    $reportDefinition->setSelector($selectorReport);
    $reportDefinition->setReportName('Campaign performance report #' . uniqid());
    $reportDefinition->setDateRangeType(ReportDefinitionDateRangeType::LAST_7_DAYS);
    $reportDefinition->setReportType(ReportDefinitionReportType::CAMPAIGN_PERFORMANCE_REPORT);
    $reportDefinition->setDownloadFormat(DownloadFormat::CSV);
    $reportDownloader = new ReportDownloader($session);
    $reportDownloadResult = $reportDownloader->downloadReport($reportDefinition);

    $fileName = 'summary_'.$strCustomerId.'_'.$campaignId.'_'.date('YmdHis').'.csv';
    $filePath = '/data/GoogleAdwords/' . $fileName;

    $reportDownloadResult->saveToFile($filePath);

########
ERROR
########
Client error: 400
[2017-03-30 17:11:21] AW_SOAP.INFO: clientCustomerId=------- operations=1 service=ManagedCustomerService method=get responseTime=537 requestId=00054bfba63457e10abf9e938800bf81 server=adwords.google.com isFault=0 faultMessage=
766159408[2017-03-30 17:11:22] AW_REPORT_DOWNLOADER.WARNING: c2f48fb300e7 GuzzleHttp/6.1.0 curl/7.29.0 PHP/7.0.15 - [30/Mar/2017:17:11:22 -0700] "POST /api/adwords/reportdownload/v201702 HTTP/1.1" 400
[2017-03-30 17:11:22] AW_REPORT_DOWNLOADER.NOTICE: >>>>>>>>
POST /api/adwords/reportdownload/v201702 HTTP/1.1
Authorization: REDACTED
User-Agent: GuzzleHttp/6.1.0 curl/7.29.0 PHP/7.0.15
Content-Type: application/x-www-form-urlencoded
Host: adwords.google.com
developerToken: -------
clientCustomerId: -------
skipReportHeader: false
skipColumnHeader: false
skipReportSummary: false
useRawEnumValues: false
includeZeroImpressions: false

* This editor just replaced tags like this. Actual my code has right format of xml.
__rdxml=<?xml version="1.0"?>
<reportDefinition><selector><fields>CampaignId</fields><predicates><field>CampaignId</field><operator>EQUALS</operator><values>766159408</values></predicates></selector><reportName>Campaign performance report #58dd9ea97d018</reportName><reportType>CAMPAIGN_PERFORMANCE_REPORT</reportType><dateRangeType>LAST_7_DAYS</dateRangeType><downloadFormat>CSV</downloadFormat></reportDefinition>

<<<<<<<<
HTTP/1.1 400 Bad Request
Content-Type: text/xml
Date: Fri, 31 Mar 2017 00:11:22 GMT
Expires: Fri, 31 Mar 2017 00:11:22 GMT
Cache-Control: private, max-age=0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Alt-Svc: quic=":443"; ma=2592000; v="37,36,35"
Accept-Ranges: none
Vary: Accept-Encoding
Connection: close

**Comment by fiboknacky** [comment]
Hello @pure4499,

Could you please send the full SOAP logs (including your client customer ID and developer token) to adwordsapiadvisor@google.com please?
Please mention this issue number in the email as well.

Thanks in advance!

Knack

**Comment by fiboknacky** [comment]
Close due to inactivity.
Please let me know if you're still faced with the issue.
