### ISSUE TITLE
Cannot handle token prior to 2017-03-30T10:21:05+0000

### ISSUE THREAD

**Issue by david-navarro** [googleads/googleads-php-lib#267]
I have an offline connected application with googleads. It worked fine but last saturday our servers changed time (cos has CEST Europe/Madrid config) automatically with ntp service. 
Now my application doesn't work and I get this error: 

BeforeValidException in JWT.php line 124:
Cannot handle token prior to 2017-03-30T10:21:05+0000
in JWT.php line 124
at JWT::decode('eyJh...bla bla bla..

In test envirnoment I have advanced the time a few seconds and it works fine! But in production not yet! :(
I have revoked and reconnected the account.

Any idea, please?

Thx.

**Comment by fiboknacky** [comment]
Hi @david-navarro,

I have no idea about your `JWT.php`, so could you please clarify what it does mainly?
Have you tried creating a new refresh token too?

Best,
Knack

**Comment by david-navarro** [comment]
Hi, my JWT.php come from firebase/apiclient, requeriment for google/apiclient

**Comment by fiboknacky** [comment]
Have you tried creating a new refresh token too?

**Comment by david-navarro** [comment]
Quite so! @fiboknacky you were right. I'd created a new refresh token with other library. 
Thanks!
