### ISSUE TITLE
Get my Refresh Token

### ISSUE THREAD

**Issue by geryslov** [googleads/googleads-php-lib#268]
im running localy the: "GetRefreshToken.php" file, im inserting all the parameters and when i hit the line: 

> "[OPTIONAL] enter any additional OAuth2 scopes as a space delimited string here ..." 

im going to the 

> "https://accounts.google.com/o/oauth2/v2/auth?response_type=code&access_type=offline&client_id=..."

 with my clientID, but then i hit enter to get the token it calls an error:
Error: invalid_request
Missing required parameter: scope.

what i am doing wrong?

**Comment by fiboknacky** [comment]
Hello @geryslov 

May I ask when you're prompted to enter additional scopes, what did you enter?
As a reminder, if you would like to use AdWords or DFP, you don't need to type them in this step.
They're added already by this library.

Best,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity. 
Please let me know if you're still faced with the issue.
