### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by SeriousJ55** [googleads/googleads-php-lib#271]
When running the example GetCampaigns.php, I get the following error:

> Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate

How to fix the issue?

**Comment by fiboknacky** [comment]
Hello @SeriousJ55 

Could you please see if the workaround in #260 help your case?

Best,
Knack

**Comment by hakimio** [comment]
@fiboknacky 
Just something to check: I don't think the comment in AdsSoapClientFactory.php ( https://github.com/googleads/googleads-php-lib/blob/5eea2f7fb65fd07f0413eb2e33bc2e7563c43078/src/Google/AdsApi/Common/AdsSoapClientFactory.php#L148 ) is correct. System cert is not automatically set on PHP 5.6+. I had to manually set "curl.cainfo" on PHP 5.6, 7.0 and 7.1.

**Comment by fiboknacky** [comment]
Hi @hakimio 

I think the comment talks about [cafile](http://php.net/manual/en/context.ssl.php#context.ssl.cafile), not `curl.cainfo`, which is written based on what's described in http://php.net/manual/en/migration56.openssl.php.
I'm not sure much about `curl.cainfo` too, but it shouldn't be related to `AdsSoapClientFactory` as the SOAP client uses SOAP toolkit?

Knack

**Comment by hakimio** [comment]
Yes, you are right. I am confusing things.
Anyway, at least on windows "curl.cainfo" has to be set to get the report data and, if I remember correctly, "GetRefreshToken.php" fails without it, too.

**Comment by fiboknacky** [comment]
Based on http://docs.guzzlephp.org/en/latest/request-options.html#verify, it looks like that PHP 5.6 and later will try to "locate" the CA file automatically, but it doesn't mean that PHP will be bundled with CA files.

You may still need to provide the CA file for your system via [withSslCaFile()](https://github.com/googleads/googleads-php-lib/blob/5eea2f7fb65fd07f0413eb2e33bc2e7563c43078/src/Google/AdsApi/Common/SoapSettingsBuilder.php#L182).

Best,
Knack

**Comment by hakimio** [comment]
Maybe you should mention it somewhere in Readme or Wiki? I think a lot of people will have the same problem.

**Comment by fiboknacky** [comment]
Sure. Thanks for suggestion.

**Comment by fiboknacky** [comment]
I just added a content about SSL CA settings to README.md, so will close this issue.
