### ISSUE TITLE
Really weird PHP errors

### ISSUE THREAD

**Issue by vovan47** [googleads/googleads-php-lib#272]
Hi guys!
I use (Old) Google Ads APIs Client Library for PHP v17.0.0
And I'm getting this error in the middle of something:
```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to AdsUser::GetAuthVarValue() must be of the type array, boolean given, called in /.../library/vendor/googleads/googleads-php-lib/src/Google/Api/Ads/AdWords/Lib/AdWordsUser.php on line 117 and defined in /.../library/vendor/googleads/googleads-php-lib/src/Google/Api/Ads/Common/Lib/AdsUser.php:80
```

I already created topic on Adwords API forum, there's more detailed description of conditions: https://groups.google.com/forum/#!topic/adwords-api/B_v-byF8zeM

I sent them private email already with my SOAP logs, and they suggested me to create an issue here so here I am.
BUT, today I got new error, which happened prior to one described above: 
```
PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201702/AdGroupService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/cm/v201702/AdGroupService?wsdl"
 in /home/ubuntu/cleoo/library/vendor/googleads/googleads-php-lib/src/Google/Api/Ads/Common/Lib/AdsSoapClient.php on line 154
Fetching adgroups for campaign 278695493 failed: Exception 'SoapFault' with message 'SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201702/AdGroupService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/cm/v201702/AdGroupService?wsdl"
```
Maybe it was the root of a problem, please take a look.
Thanks.

**Comment by fiboknacky** [comment]
Hello @vovan47,

This looks like a connection issue between your computers and the API servers.
I've seen you use PHP 7.0. Do you use other frameworks too?

And does it occur with a certain account ID or intermittently after you execute your code for some time?

Cheers,
Knack

**Comment by vovan47** [comment]
Hi @fiboknacky, thanks for the reply.

Yes, the strangest thing about that error is that it's occured on certain
account ID/campaign ID pair during the simple "get" operation of
AdGroupService. But the same operation executed separately (with same ID's)
returned normal result.
I'm not sure what you mean about other frameworks, but we use Zend and
Symfony in that application.
And well, finally it was solved by running the script on a different server
where it went fine. So that was more a local problem of our environment I
guess. You can probably close the issue.

Thanks.
