### ISSUE TITLE
Install instructions without using Composer?

### ISSUE THREAD

**Issue by danielmajor** [googleads/googleads-php-lib#273]
I'd like to set things up here without using Composer, any input on what steps should be taken to achieve this?  I don't see a /vendor/autoload.php folder anywhere, which most of the examples seem to use - are these files available without installing via Composer?

**Comment by fiboknacky** [comment]
Hi @danielmajor,

Unfortunately, this library supports Composer installation only.
And yes, `autoload.php` means the one created automatically by Composer.

Best,
Knack

**Comment by danielmajor** [comment]
Ah - sorry to hear that.  Will look into setting up Composer for this then, thanks.
