### ISSUE TITLE
Usage question. Question about $gmbAccessToken in example

### ISSUE THREAD

**Issue by komirad** [googleads/googleads-php-lib#274]
I am looking at the [GMB example where there is a GMB token](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201702/Extensions/AddGoogleMyBusinessLocationExtensions.php#L204) and I am trying to understand how I can adapt this for my use case. My app allows any user to sign up so the email/customer ids are all dynamic. I want to allow users to use their own GMB locations.

All users in my app connect to their AdWords account via OAuth2. They get back their customer id and refresh token and this is saved in the database. These information is then use to work with their AdWords account every time.

Assuming the user uses a different email for GMB, am I able to use the credentials that was used to connect to AdWords? If not, I am guessing, **I would need to have them input their GMB email and use the same (OAuth2) process as above to get back the access token. Is this right?** Also I don't need separate credentials from the developer console, right?

**I also don't have access to GMB API, so after I get the access token, I would have to have the user manually enter their business account identifier?**

If the user is a manager, does this have any implication on the process described above? 

Thanks for any help provided.

**Comment by fiboknacky** [comment]
Hi JC,

> Assuming the user uses a different email for GMB, am I able to use the credentials that was used to connect to AdWords? If not, I am guessing, I would need to have them input their GMB email and use the same (OAuth2) process as above to get back the access token. 

Yes, this is the same as described in [this line](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201702/Extensions/AddGoogleMyBusinessLocationExtensions.php#L197).

> Also I don't need separate credentials from the developer console, right?

No, you don't need to.

> I also don't have access to GMB API, so after I get the access token, I would have to have the user manually enter their business account identifier?

Yep. You can obtain business account ID by copying the `BUSINESS_ACCOUNT_ID` portion from the business URL of the form: `https://business.google.com/b/BUSINESS_ACCOUNT_ID/...`

Please see more details in [this guide](https://developers.google.com/adwords/api/docs/guides/feed-services-locations#procedure).

> If the user is a manager, does this have any implication on the process described above?

Nope. Rather, if the GMB account you're referring to is _NOT_ a manager, then you can leave the `BUSINESS_ACCOUNT_ID` as null, as shown in [this line](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201702/Extensions/AddGoogleMyBusinessLocationExtensions.php#L65).

Cheers,
Knack

**Comment by komirad** [comment]
Hi Knack,

Thanks for clearing that up for me.

> Nope. Rather, if the GMB account you're referring to is NOT a manager, then you can leave the BUSINESS_ACCOUNT_ID as null, as shown in this line.

If the account id is left empty does this mean that all locations in separate accounts are added to the feed?

Also, is the feed dynamic? I am trying to understand how this would work in AdWords manager and client accounts if either one of them added the feed. For example, if a client added the feed and the AdWords manager doesn't have access rights to the GMB account and vice versa. From what I've gathered so far, the feed is dynamic - but does this mean the party with access to the AdWords account but no rights in GMB cannot re-add the feed if he accidentally deleted it?

JC

**Comment by fiboknacky** [comment]
Hi JC,

> If the account id is left empty does this mean that all locations in separate accounts are added to the feed?

Yes

> I am trying to understand how this would work in AdWords manager and client accounts if either one of them added the feed. For example, if a client added the feed and the AdWords manager doesn't have access rights to the GMB account and vice versa. Does the party with access to the AdWords account but no rights in GMB cannot re-add the feed if he accidentally deleted it?

I'm not sure I understand your question 100% correctly.
For the feed creation part (step 3 and later [in this guide](https://developers.google.com/adwords/api/docs/guides/feed-services-locations#procedure)), if you use AdWords manager account credentials to add the feed to AdWords client account, it should be fine, **provided that** you've provided correct [PlacesLocationFeedData](https://developers.google.com/adwords/api/docs/reference/v201702/FeedService.PlacesLocationFeedData) (including [OAuthInfo](https://developers.google.com/adwords/api/docs/reference/v201702/FeedService.OAuthInfo)) as a [systemFeedGenerationData](https://developers.google.com/adwords/api/docs/reference/v201702/FeedService.Feed#systemFeedGenerationData).
In particular, the access token you've provided in `OAuthInfo` must be the one that can access the GMB account.

Best,
Knack

**Comment by komirad** [comment]
Hi Knack,

Let me clarify my second question.

Let's say more than one user can manage one AdWords account (I used manager and client as example). And only one of them has access rights to the GMB account that we want to link to AdWords (e.g. the client). The client then adds the location feed to AdWords. Now if the manager deletes the feed, I assume he won't be able to re-create it -- Since he does not have access to this GMB account. (i.e. Since he does not have the OAuth credentials, he cannot create the feed but his client can) Is this right?

**Comment by fiboknacky** [comment]
Hello,

You're right. If the OAuth credentials are not valid to access GMB account, then, no, that credentials can't be used to create the feed that links to GMB account.

Best,
Knack

**Comment by komirad** [comment]
Hi Knack,

Thanks for the help so far.

I have been granted access of GMB API and I was able to pull my account id from it. 

I am trying to find the corresponding id from the URL, but I cannot find this from the GMB URL you mentioned:

> Yep. You can obtain business account ID by copying the BUSINESS_ACCOUNT_ID portion from the business URL of the form: https://business.google.com/b/BUSINESS_ACCOUNT_ID/...

My URL looks like this: `https://business.google.com/manage/u/5/?hl=en#/list`. I am using a personal account as a test so maybe that's the cause -- if that's it, then how would a user go about finding the id without GMB API?

- JC

**Comment by fiboknacky** [comment]
Hi JC,

I think you may need to first [create a business account](https://support.google.com/business/answer/6085339?hl=en).
Then, you can create a location and then you should see the URL as `https://business.google.com/manage/u/0/?hl=en#/acc/<BUSINESS_ACCOUNT_ID>/list`.

Unfortunately, I'm not quite sure too when the URL will look like the above or as ` https://business.google.com/b/BUSINESS_ACCOUNT_ID/...`.
I do see both types of URLs in different GMB accounts.

Best,
Knack

**Comment by komirad** [comment]
Hi Knack,

I was able to create locations from personal account. The documentation says I should create a business account if I intend to share management of locations with other users. Is there a forum that I can ask this question? (Because I only know of AdWords API Forum and GMB API Forum)

Also the question about the email above.

Thanks!

**Comment by fiboknacky** [comment]
Hi JC,

Google My Business API forum is actually a subsection of Google My Business forum.
You can access it from here: https://www.en.advertisercommunity.com/t5/Google-My-Business/ct-p/GMB#

Cheers,
Knack
