### ISSUE TITLE
Adwords API - Examples/AdWords/v201702 "Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL"

### ISSUE THREAD

**Issue by ykeita** [googleads/googleads-php-lib#276]
Hello Adwords Api Team,

I was trying to run 'GetCampaigns.php' and i keep receiving 'Fatal error: Uncaught SoapFault exception'. Here is what i see on my terminal:

Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201702/CampaignService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/cm/v201702/CampaignService?wsdl"
 in /Applications/MAMP/htdocs/paypercall-adwords-api/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php:65

Stack trace:

#0 /Applications/MAMP/htdocs/paypercall-adwords-api/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(65): SoapClient->S
oapClient('https://adwords...', Array)

#1 /Applications/MAMP/htdocs/paypercall-adwords-api/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201702/cm/CampaignService.php(144)
: Google\AdsApi\Common\AdsSoapClient->__construct('https://adwords...', Array)

#2 [internal function]: Google\AdsApi\AdWords\v201702\cm\CampaignService->__construct(Array)

#3 /Applications/MAMP/htdocs/paypercall-adwords-api/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Comm in /Applications/MAMP/htdocs/paypercal
l-adwords-api/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php on line 65

Can anyone help me fix this problem? Thank You.

Yacouba Keita

**Comment by fiboknacky** [comment]
Hi Yacouba,

Looks like the connection problem with API servers.
Can you access https://adwords.google.com/api/adwords/cm/v201702/CampaignService?wsdl using `curl` or `wget` on your computer?

Best,
Knack

**Comment by ykeita** [comment]
Helle Knack, thank you for the quick response. When i click on the link, it shows me an xml file with errors in it like:

This XML file does not appear to have any style information associated with it. The document tree is shown below.


<wsdl:definitions xmlns:tns="https://adwords.google.com/api/adwords/cm/v201702" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="https://adwords.google.com/api/adwords/cm/v201702">
<wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:tns="https://adwords.google.com/api/adwords/cm/v201702" elementFormDefault="qualified" jaxb:version="1.0" targetNamespace="https://adwords.google.com/api/adwords/cm/v201702">
<annotation>
<appinfo>
<jaxb:globalBindings typesafeEnumMaxMembers="999999"/>
</appinfo>
</annotation>
<complexType name="AdxError">
<annotation>
<documentation>
Errors that are thrown when a non-AdX feature is accessed by an AdX customer.
</documentation>
</annotation>
<complexContent>
<extension base="tns:ApiError">
<sequence>
<element maxOccurs="1" minOccurs="0" name="reason" type="tns:AdxError.Reason">
<annotation>
<documentation>The error reason represented by an enum.</documentation>
</annotation>
</element>
</sequence>
</extension>
</complexContent>
</complexType>

**Comment by ykeita** [comment]
![screen shot 2017-04-14 at 1 18 25 pm](https://cloud.githubusercontent.com/assets/8906718/25050544/083ec9e8-2116-11e7-930f-019863b9222a.png)

**Comment by ykeita** [comment]
Hello
![screen shot 2017-04-14 at 1 18 25 pm](https://cloud.githubusercontent.com/assets/8906718/25050580/3ff2922a-2116-11e7-851d-7d5dff5a3b46.png)
 Knack, thank you for the quick response. When i click on the link, it shows me an xml file with errors in it like:

This XML file does not appear to have any style information associated with it. The document tree is shown below.

**Comment by fiboknacky** [comment]
Hi,

That's usual. It looks like it works in your browser.
Some couple things you might be able to try:
*   Can your `curl` in Terminal access this WSDL URL?
*   [Checking your `default_socket_timeout`](http://stackoverflow.com/a/17296591/6169712)
*   Do you use any proxy settings? Could you please share what you set in `adsapi_php.ini`?
*   Can you try installing this library without MAMP or using other environments to see if you can run the example?

Best,
Knack

**Comment by ykeita** [comment]
I just put the library on a actual live server instead of mamp, and you were right, it went through. And now it is giving me only one error :

PHP Fatal error:  Class 'SoapClient' not found in /var/www/yacoubaenv/vendor/googleads-php-lib/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php on line 30

____________________________________________________________________
adsapi_php.ini :

[ADWORDS]
; Required AdWords API properties. Details can be found at:
; https://developers.google.com/adwords/api/docs/guides/basic-concepts#soap_and_xml
developerToken = "le................"
clientCustomerId = "499-.............."

; Optional. Set a friendly application name identifier.
userAgent = "Development"

; Optional additional AdWords API settings.
; endpoint = "https://adwords.google.com/"
; isPartialFailure = false

; Optional setting for utility usage tracking in the user agent in requests.
; Defaults to true.
; includeUtilitiesInUserAgent = true

[ADWORDS_REPORTING]
; Optional reporting settings.
; isSkipReportHeader = false
; isSkipColumnHeader = false
; isSkipReportSummary = false
; isUseRawEnumValues = false

[OAUTH2]
; Required OAuth2 credentials. Uncomment and fill in the values for the
; appropriate flow based on your use case. See the README for guidance:
; https://github.com/googleads/googleads-php-lib/blob/master/README.md#getting-started

; For installed application or web application flow.
clientId = "830627224098-915mmvms36dnt50r68slogepvcgr4412.apps.googleusercontent.com"
clientSecret = "ahsKKAcu2SsOogHZG1iaVAEK"
refreshToken = "1/aImk21-WC4R1gSamzk8wi0jdPmnVKwOl9Ixz7XMqmpw"

; For service account flow.
; jsonKeyFilePath = "INSERT_ABSOLUTE_PATH_TO_OAUTH2_JSON_KEY_FILE_HERE"
; scopes = "https://www.googleapis.com/auth/adwords"
; impersonatedEmail = "INSERT_EMAIL_OF_ACCOUNT_TO_IMPERSONATE_HERE"

[SOAP]
; Optional SOAP settings. See SoapSettingsBuilder.php for more information.
; compressionLevel = <COMPRESSION_LEVEL>
; wsdlCache = <WSDL_CACHE>

[PROXY]
; Optional proxy settings to be used by SOAP requests.
; host = "<HOST>"
; port = <PORT>
; user = "<USER>"
; password = "<PASSWORD>"

[LOGGING]
; Optional logging settings.
; soapLogFilePath = "path/to/your/soap.log"
; soapLogLevel = "INFO"
; reportDownloaderLogFilePath = "path/to/your/report-downloader.log"
; reportDownloaderLogLevel = "INFO"
; batchJobsUtilLogFilePath = "path/to/your/bjutil.log"
; batchJobsUtilLogLevel = "INFO"

Thank you Knack!

Y.Keita

**Comment by fiboknacky** [comment]
Hello Keita,

First, please hide your above refresh tokens as well. 

`SoapClient` is a PHP SOAP toolkit, which should be installed in your system before using our library and API.
Now the issue is that this toolkit seems not installed properly.
Could you please consult http://php.net/manual/en/class.soapclient.php to see if your PHP SOAP toolkit is installed properly?

Best,
Knack

**Comment by ykeita** [comment]
Hello Knack,

After i installed SOAP toolkit, the program was able to see my info, but didn't retrieve the campaigns

Here is my console result :

2017-04-14 21:44:56] AW_SOAP.WARNING: clientCustomerId=499-831-1492 operations=1 service=CampaignService method=get responseTime=131 requestId=00054d275a35a2680a37464aef037a4c server=adwords.google.com isFault=1 faultMe
ssage=[QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED @ ; trigger:'<null>']
[2017-04-14 21:44:56] AW_SOAP.NOTICE: POST /api/adwords/cm/v201702/CampaignService?wsdl HTTP/1.1
Host: adwords.google.com
Connection: Keep-Alive
User-Agent: PHP-SOAP/7.1.4-1+deb.sury.org~xenial+1
Content-Type: text/xml; charset=utf-8
SOAPAction: ""
Content-Length: 951
Authorization: REDACTED

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://adwords.google.com/api/adwords/cm/v201702"><SOAP-ENV:Header><ns1:RequestHeader><ns1:clientCustomerId>499-831-1492</ns1:clie
ntCustomerId><ns1:developerToken>REDACTED</ns1:developerToken><ns1:userAgent>Ewebify_Development (AwApi-PHP, googleads-php-lib/25.4.0, PHP/7.1.4-1+deb.sury.org~xenial+1)</ns1:userAgent><ns1:validateOnly>false</ns1:valida
teOnly><ns1:partialFailure>false</ns1:partialFailure></ns1:RequestHeader></SOAP-ENV:Header><SOAP-ENV:Body><ns1:get><ns1:serviceSelector><ns1:fields>Id</ns1:fields><ns1:fields>Name</ns1:fields><ns1:ordering><ns1:field>Nam
e</ns1:field><ns1:sortOrder>ASCENDING</ns1:sortOrder></ns1:ordering><ns1:paging><ns1:startIndex>0</ns1:startIndex><ns1:numberResults>500</ns1:numberResults></ns1:paging></ns1:serviceSelector></ns1:get></SOAP-ENV:Body></S
OAP-ENV:Envelope>

HTTP/1.1 500 Internal Server Error
Content-Type: text/xml; charset=UTF-8
Date: Fri, 14 Apr 2017 21:44:56 GMT
Expires: Fri, 14 Apr 2017 21:44:56 GMT
Cache-Control: private, max-age=0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Alt-Svc: quic=":443"; ma=2592000; v="37,36,35"
Accept-Ranges: none
Vary: Accept-Encoding
Transfer-Encoding: chunked

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header><ResponseHeader xmlns="https://adwords.google.com/api/adwords/cm/v201702"><requestId>00054d275a35a2680a37464aef037a4c</requestId><service
Name>CampaignService</serviceName><methodName>get</methodName><operations>1</operations><responseTime>131</responseTime></ResponseHeader></soap:Header><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring
>[QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED @ ; trigger:'&lt;null&gt;']</faultstring><detail><ApiExceptionFault xmlns="https://adwords.google.com/api/adwords/cm/v201702"><message>[QuotaCheckError.DEVELOPER_TOKEN_NOT_A
PPROVED @ ; trigger:'&lt;null&gt;']</message><ApplicationException.Type>ApiException</ApplicationException.Type><errors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="QuotaCheckError"><fieldPath></fieldP
ath><trigger>&lt;null&gt;</trigger><errorString>QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED</errorString><ApiError.Type>QuotaCheckError</ApiError.Type><reason>DEVELOPER_TOKEN_NOT_APPROVED</reason></errors></ApiException
Fault></detail></soap:Fault></soap:Body></soap:Envelope>

PHP Fatal error:  Uncaught Google\AdsApi\AdWords\v201702\cm\ApiException: [QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED @ ; trigger:'<null>'] in /var/www/yacoubaenv/vendor/googleads-php-lib/vendor/googleads/googleads-php
-lib/src/Google/AdsApi/Common/Util/Reflection.php:39
Stack trace:
#0 /var/www/yacoubaenv/vendor/googleads-php-lib/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(39): ReflectionClass->newInstanceArgs(Array)
#1 /var/www/yacoubaenv/vendor/googleads-php-lib/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(162): Google\AdsApi\Common\Util\Reflection->createInstance('Google\\AdsApi\\A...', Array)
#2 /var/www/yacoubaenv/vendor/googleads-php-lib/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(126): Google\AdsApi\Common\AdsSoapClient->parseApiExceptionFromSoapFault(Object(SoapFault))
#3 /var/www/yacoubaenv/vendor/googleads-php-lib/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201702/cm/CampaignService.php(156): Goo in /var/www/yacoubaenv/vendor/googleads-php-lib/vendor/googleads/googl
eads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php on line 39

**Comment by fiboknacky** [comment]
Hi Keita,

As the error message suggested, your developer token hasn't been approved yet.
This is the part of the process needed for start using the AdWords API as [described here](https://developers.google.com/adwords/api/docs/guides/signup#step_3_continue_your_application).

I recommend to go through the [Sign Up](https://developers.google.com/adwords/api/docs/guides/signup) guide and [Make Your First API Call](https://developers.google.com/adwords/api/docs/guides/first-api-call) again.

If you have questions about developer tokens or the API in general, feel free to reach out at https://groups.google.com/forum/#!forum/adwords-api.

Best,
Knack

**Comment by ykeita** [comment]
Thank you so much for the help Knack

**Comment by adhippatil** [comment]
Hello AdWords API team,
I am running 'GetCampaigns.php' from terminal ,it is showing the list of campaigns. But when I ran it on web browser, it is giving me an error : 
Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl" in /opt/lampp/htdocs/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php:65 Stack trace: #0 /opt/lampp/htdocs/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(65): SoapClient->SoapClient('https://adwords...', Array) #1 /opt/lampp/htdocs/googleads-php-lib/src/Google/AdsApi/AdWords/v201705/cm/CampaignService.php(145): Google\AdsApi\Common\AdsSoapClient->__construct('https://adwords...', Array) #2 [internal function]: Google\AdsApi\AdWords\v201705\cm\CampaignService->__construct(Array) #3 /opt/lampp/htdocs/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(39): ReflectionClass->newInstanceArgs(Array) #4 /opt/lampp/htdocs/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClientFactory.php(86): Google\AdsApi\Common\Util\Refl in /opt/lampp/htdocs/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php on line 65

What should I do to see it running in the web browser also? Please help me!

**Comment by fiboknacky** [comment]
Hello @adhippatil 

First, our code examples are meant to run in command prompt only as stated [here](https://github.com/googleads/googleads-php-lib#basic-usage).
So, if you run it on the webpage, you may not see the result as usual.

Despite that, the error message above looks like a separate problem.
It seems the WSDLs can't be accessed from your server.
Could you please check if you have any firewall or settings that prevent the access?

One thing that you can check if to use `curl` or `wget` to fetch the content from https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl in your server.
You can also try opening the link in the browser to check as well.

Best,
Thanet, AdWords API Team

**Comment by kennblvnp** [comment]
Could someone please answer @adhippatil  thank you!

**Comment by fiboknacky** [comment]
Hello @adhippatil 

The code example is meant to run on terminal only so you might get correct results when running on the browser.
Having said that, your problem might occur from the different version of PHP, and hence different version of settings including SSL CA files.

In your case, if it fails always, it may hint that your CA file isn't valid or isn't found.
Could you please check [this wiki](https://github.com/googleads/googleads-php-lib/wiki/Steps-for-troubleshooting-CA-file-issues) for troubleshooting?

Best,
Knack

**Comment by kennblvnp** [comment]
Windows 10 with 32 and 64 bit of course. Xamp 3.2. PHP 7.1.

Which of these is causing the problem? Its really annoying I can't solve it.

**Comment by fiboknacky** [comment]
Could you please check [this wiki](https://github.com/googleads/googleads-php-lib/wiki/Steps-for-troubleshooting-CA-file-issues)?
Based on what I've seen in other cases, it's likely because of SSL CA file issues.

**Comment by kennblvnp** [comment]
@fiboknacky checking on it.

I have no problem with Mac, I am using Mamp pro 4 which is already built in with SSL CA. Now I am on windows development. 

Ill let you know how it was solved, hopefully.

**Comment by fiboknacky** [comment]
I've got many reports about issues with CA files on Windows PHP. :( 
So I guess that your case would be one of them. 
Please let me know if you can solve the problem. :)

**Comment by kennblvnp** [comment]
I have checked this 

I can't find my crt.

`For Windows, the path to the CA file is usually either C:\windows\system32\curl-ca-bundle.crt or C:\windows\curl-ca-bundle.crt.`

**Comment by kennblvnp** [comment]
@fiboknacky  where can I download a curl-ca-bundle.crt file?

**Comment by kennblvnp** [comment]
@fiboknacky I got it

If you don't have any CA files in your system, download one from curl's website and put it in either the default path above (recommended) or your usual place for them.

[https://curl.haxx.se/docs/caextract.html](Can be downloaded here) but its in pem file...

**Comment by fiboknacky** [comment]
@kennblvnp 

As described in the wiki,
> If you don't have any CA files in your system, download one from [curl's website](https://curl.haxx.se/docs/caextract.html) and put it in either the default path above (recommended) or your usual place for them.

Could you follow the link please?

**Comment by kennblvnp** [comment]
Its in pem file... im looking for crt.

**Comment by fiboknacky** [comment]
It should be very similar. Could you try it first?
See [this post](https://superuser.com/a/442797).

**Comment by kennblvnp** [comment]
I do not know where to download curl.exe.

i tried to download this zip https://curl.haxx.se/latest.cgi?curl=tar.bz2

then extrace it, I cant find .exe file.

**Comment by fiboknacky** [comment]
Sorry I wasn't clear. What I would like you to see is the step 4 in the post:

> Rename the cacert.pem file to curl-ca-bundle.crt

So, you probably could rename the file and use it as .crt file.
You don't need to follow other steps.

Then try moving the file to either of the following:
* C:\windows\system32\
* C:\windows\
* C:\Windows\SysWOW64 (If you use 32-bit Windows 7)

**Comment by kennblvnp** [comment]
Okay i did what you ask me. The error still showing. I even restart my xamp.

**Comment by kennblvnp** [comment]
Check out my php.ini

[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
curl.cainfo="C:\xampp\apache\bin\curl-ca-bundle.crt"

**Comment by fiboknacky** [comment]
What is the result after specifying path to your CA file? Still same errors?
Have you tried `openssl.cafile` too?

**Comment by kennblvnp** [comment]
I tried to change path curl.cainfo.

curl.cainfo="C:\xampp\apache\bin\curl-ca-bundle.crt"
curl.cainfo="C:\windows\system32\curl-ca-bundle.crt"
curl.cainfo="C:\windows\curl-ca-bundle.crt"
curl.cainfo="C:\Windows\SysWOW64\curl-ca-bundle.crt"

Doesn't work.


But this one works perfectly!!! : 
`openssl.cafile="C:\xampp\apache\bin\curl-ca-bundle.crt"`

**Comment by kennblvnp** [comment]
This is for PHP 7.1, Xampp 3.2.2, Windows 10 64x/32x.

Steps:
1. download pem file here https://curl.haxx.se//ca/cacert-2017-09-20.pem
2. rename Rename the cacert-2017-09-20.pem file to curl-ca-bundle.crt
3. copy - paste - replace at C:\xampp\apache\bin\
4. restart xamp

This is solve! Mine is working now. Thanks!

**Comment by fiboknacky** [comment]
Thanks for replying back and for helping summarizing the steps for other users. :)
