### ISSUE TITLE
Unable to handle exception

### ISSUE THREAD

**Issue by rajuvishwas** [googleads/googleads-php-lib#277]
Hello,

We are using Google API to get Keywords Ideas but we keep getting RATE_LIMIT error even after making our script very slow. We decided to handle the exception but due to the fatal error when creating object for Reflection Class, we are unable to do that.

Below is the stack trace:

`PHP Fatal error:  Uncaught Google\AdsApi\AdWords\v201609\cm\ApiException: [RateExceededError <r                                                                                                                                                                      ateName=RATE_LIMIT, rateKey=null, rateScope=ACCOUNT, retryAfterSeconds=30>] in /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php:39
Stack trace:
#0 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(39): ReflectionClass->newInstanceArgs(Array)
#1 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(164): Google\AdsApi\Common\Util\Reflection->createInstance('Google\\AdsApi\\A...',Array)
#2 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(126): Google\AdsApi\Common\AdsSoapClient->parseApiExceptionFromSoapFault(Object(SoapFault))
#3 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201609/o/TargetingIdeaService.php(151): Google\AdsApi\Common\AdsSoapClient->__soapCall('get', Array                                                                                                                                                                      )
#4 / in /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php on line 39

Here is the code of Exception handling:
```
try {

    $page = $targetingIdeaService->get($selector);

} catch(ApiException $apiException) {
    
    foreach ($apiException->getErrors() as $error) {
        if ($error instanceof RateExceededError) {

            $retryAfterSeconds = $error->getRetryAfterSeconds();
            $pausedScript = $retryAfterSeconds * 500;
            sleep($pausedScript);
        }
    }
} 
```

**Comment by fiboknacky** [comment]
Hello @rajuvishwas,

Just want to check one thing first:
How did you declare `use` statement of  `ApiException`?

Best,
Knack

**Comment by rajuvishwas** [comment]
Hi @fiboknacky,

Yes, I forgot to add `use` statement which created the issue. I am able to catch the Exception now. Thank you so much.

Regards,
Raju Vishwas

**Comment by fiboknacky** [comment]
Glad to hear that you can resolve this!

**Comment by mjhallll** [comment]
i have the same problem but i use exception like this 
use Google\AdsApi\AdWords\v201802\cm\ApiException;
