### ISSUE TITLE
GetAccountHierarchy (PHP) error - Warning: array_key_exists()

### ISSUE THREAD

**Issue by sinapsmarketing** [googleads/googleads-php-lib#279]
Hello

I have a problem with the AdWords Api (PHP). When I run GetAccountHierarchy.php I get the errors bellow. The file is unchanged ( https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201702/AccountManagement/GetAccountHierarchy.php )
I tried it on php 5.5.12 & 7.0.15

I was sent here with the question by someone from the AdWords API Team on the Adwords Api Group.

Any pointers?

[2017-04-27 09:33:34] AW_SOAP.INFO: clientCustomerId=9797142165 operations=1 service=ManagedCustomerService method=get responseTime=232 requestId=00054e20f96c5df10a1b42116103be01 server=
adwords.google.com isFault=0 faultMessage=

Warning: array_key_exists(): The first argument should be either a string or an integer in C:\wamp\www\api\app\GetAccountHierarchy.php on line 82

Call Stack:
    0.0010     263248   1. {main}() C:\wamp\www\api\app\GetAccountHierarchy.php:0
    0.0130     702600   2. Google\AdsApi\Examples\AdWords\v201702\AccountManagement\GetAccountHierarchy::main() C:\wamp\www\api\app\GetAccountHierarchy.php:146
    0.0510    2045160   3. Google\AdsApi\Examples\AdWords\v201702\AccountManagement\GetAccountHierarchy::runExample() C:\wamp\www\api\app\GetAccountHierarchy.php:142
    2.1701    3664928   4. array_key_exists() C:\wamp\www\api\app\GetAccountHierarchy.php:82

(Customer ID, Account Name)
2975983167, Test 1

Warning: array_key_exists(): The first argument should be either a string or an integer in C:\wamp\www\api\app\GetAccountHierarchy.php on line 120

Call Stack:
    0.0010     263248   1. {main}() C:\wamp\www\api\app\GetAccountHierarchy.php:0
    0.0130     702600   2. Google\AdsApi\Examples\AdWords\v201702\AccountManagement\GetAccountHierarchy::main() C:\wamp\www\api\app\GetAccountHierarchy.php:146
    0.0510    2045160   3. Google\AdsApi\Examples\AdWords\v201702\AccountManagement\GetAccountHierarchy::runExample() C:\wamp\www\api\app\GetAccountHierarchy.php:142
    2.1721    3666392   4. Google\AdsApi\Examples\AdWords\v201702\AccountManagement\GetAccountHierarchy::printAccountHierarchy() C:\wamp\www\api\app\GetAccountHierarchy.php:91
    2.1731    3666488   5. Google\AdsApi\Examples\AdWords\v201702\AccountManagement\GetAccountHierarchy::printAccountHierarchy() C:\wamp\www\api\app\GetAccountHierarchy.php:112
    2.1731    3666568   6. array_key_exists() C:\wamp\www\api\app\GetAccountHierarchy.php:120

**Comment by fiboknacky** [comment]
Hello @sinapsmarketing 

First, PHP 5.1 is not supported for this library anymore, please use newer versions for more reliable results.

To confirm, you'd like to run this example for the manager account of client customer ID 2975983167.
Is this correct?

Best,
Knack

**Comment by sinapsmarketing** [comment]
@fiboknacky 

The PHP version is 5.5.12 (my bad, i updated the original post).

I'm trying to run this for 9797142165 , which is the manager account for 2975983167 and other test client accounts.

Thanks !

**Comment by fiboknacky** [comment]
Hello @sinapsmarketing 

I can't reproduce the issue. The three accounts under that manager account can be printed successfully.
Could you please investigate the value of the array `$customerIdsToParentLinks` by yourself to see what's in there?

Thanks!
Knack

**Comment by sinapsmarketing** [comment]
array (size=3)
  -65383957 => 
    object(Google\AdsApi\AdWords\v201702\mcm\ManagedCustomerLink)[51]
      protected 'managerCustomerId' => float 9797142165
      protected 'clientCustomerId' => float 8524550635
      protected 'linkStatus' => null
      protected 'pendingDescriptiveName' => null
      protected 'isHidden' => boolean false
  -1318984129 => 
    object(Google\AdsApi\AdWords\v201702\mcm\ManagedCustomerLink)[42]
      protected 'managerCustomerId' => float 9797142165
      protected 'clientCustomerId' => float 2975983167
      protected 'linkStatus' => null
      protected 'pendingDescriptiveName' => null
      protected 'isHidden' => boolean false
  -1203957631 => 
    object(Google\AdsApi\AdWords\v201702\mcm\ManagedCustomerLink)[41]
      protected 'managerCustomerId' => float 9797142165
      protected 'clientCustomerId' => float 3091009665
      protected 'linkStatus' => null
      protected 'pendingDescriptiveName' => null
      protected 'isHidden' => boolean false

@fiboknacky I see that the arrays are values are float and string/integer is expected. Could this be it ?

**Comment by fiboknacky** [comment]
It's a Windows 32-bit issue.
As a workaround, can you try using `float()` around the key in all assignments in the example, such as in [line 69](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201702/AccountManagement/GetAccountHierarchy.php#L69)?

```php
          $customerIdsToAccounts[floatval($account->getCustomerId())] = $account;
```

**Comment by sinapsmarketing** [comment]
I tried with` intval() ` and it worked. Thanks !
