### ISSUE TITLE
GetDeliveryForecastForLineItems: Unable to run example file from repository. 

### ISSUE THREAD

**Issue by gellel** [googleads/googleads-php-lib#282]
Attempted to run the [GetDeliveryForecastForLineItems](https://github.com/googleads/googleads-php-lib/blob/master/examples/Dfp/v201702/ForecastService/GetDeliveryForecastForLineItems.php) example function.

File is failing when attempting to use the reflection class from [utilities](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/Util/Reflection.php).

`Uncaught Google\AdsApi\Dfp\v201702\ApiException: [CommonError.NOT_APPLICABLE @ ; trigger:'0']`

`googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php on line 39`

**Comment by fiboknacky** [comment]
Hi @gellel 

Could you clarify more how you use `Reflection` and what's your other information (e.g., line item ID)?
Also, what version of the library did you use?

Cheers,
Knack

**Comment by gellel** [comment]
Hi @fiboknacky - thanks for replying so quickly!

I am following the example verbatim. The line item ID is: **87719433**

Version ID (composer) 
`{
    "require": {
        "googleads/googleads-php-lib": "^25.3"
    }
}`

**Comment by fiboknacky** [comment]
Hello @gellel 

I still have no idea how you end up with using `Reflection` class.
Could you provide more detail?
Do you face with this error just by running the example? If so, in what line do you get?
(If you can produce SOAP logs as well, it'd be very helpful. :))
If not, could you tell how you use `Reflection`?

Thanks!
Knack

**Comment by gellel** [comment]
I am using the example as provided in your examples folder. 

The code below is the implementation I am using. The only difference is that I am using the one line item versus two. The error is being generated by the dependencies `googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php` on line 39 (as printed by PHP). 

As you can see in the code I am not using reflection directly, it is being used in sample code. 

Hopefully this gives more insight.

`
<?php

/** PHP set method error handlers. **/
ini_set('display_errors', true);
/** PHP set initialisation errors handlers. **/
ini_set('display_startup_errors', true);
/** PHP set error handlers. **/
error_reporting(E_ALL);

/** PHP define constant path for file storage. **/
$FILE_PATH = dirname(__FILE__) . DIRECTORY_SEPARATOR;


/** PHP composer directory. **/
require __DIR__ . '/vendor/autoload.php';

use Google\AdsApi\Common\OAuth2TokenBuilder;
use Google\AdsApi\Dfp\DfpServices;
use Google\AdsApi\Dfp\DfpSession;
use Google\AdsApi\Dfp\DfpSessionBuilder;
use Google\AdsApi\Dfp\v201702\DeliveryForecastOptions;
use Google\AdsApi\Dfp\v201702\ForecastService;
/**
 * Gets a delivery forecast for existing line items.
 */
class GetDeliveryForecastForLineItems {
  // Set the IDs of the line items to get a forecast for.
  const LINE_ITEM_ID_1 = '87719433';
  public static function runExample(DfpServices $dfpServices,
      DfpSession $session, $lineItemId1) {
    $forecastService = $dfpServices->get($session, ForecastService::class);
    // Get forecast for the line items with no options set.
    $forecast = $forecastService->getDeliveryForecastByIds(
        [$lineItemId1], new DeliveryForecastOptions());
    // Print out forecast results.
    foreach ($forecast->getLineItemDeliveryForecasts() as $lineItemForecast) {
      $unitType = strtolower($lineItemForecast->getUnitType());
      printf("Forecast for line item ID %d:\n",
          $lineItemForecast->getLineItemId());
      printf("    %d %s matched\n",
          $lineItemForecast->getMatchedUnits(), $unitType);
      printf("    %d %s delivered\n",
          $lineItemForecast->getDeliveredUnits(), $unitType);
      printf("    %d %s predicted\n",
          $lineItemForecast->getPredictedDeliveryUnits(), $unitType);
    }
  }
  public static function main() {
    $oAuth2Credential = (new OAuth2TokenBuilder())
        ->fromFile()
        ->build();
    $session = (new DfpSessionBuilder())
        ->fromFile()
        ->withOAuth2Credential($oAuth2Credential)
        ->build();
    self::runExample(
        new DfpServices(),
        $session,
        intval(self::LINE_ITEM_ID_1)
    );
  }
}
GetDeliveryForecastForLineItems::main();

?>
`

**Comment by fiboknacky** [comment]
Thanks for info. Will have a look.

Knack

**Comment by fiboknacky** [comment]
Hello @gellel,

I'm sorry for late reply.
Upon consulting with my colleague, the error is quite generic so the DFP API team needs more investigation.
Could you please ask in [DFP API Forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api) instead?

Thanks in advance.

Best,
Knack

**Comment by gellel** [comment]
@fiboknacky thanks for taking the time to check it out. :)

I'll see what I can dig up in the forum.
