### ISSUE TITLE
Google adwords "new AdWordsUser()" Object

### ISSUE THREAD

**Issue by amankr567** [googleads/googleads-php-lib#283]
### Hello everyone,

I am integrating Google adwords Api  in our project using v201609 (PHP client lib) version . I have to get all campaign and other details of third party Google adwords user client . Please help me to setup  API to do my work .

Also give me the way , how can i **create new AdWordsUser object** for further use .

**Thanks in Advance** .

**Comment by fiboknacky** [comment]
Hi @amankr567 

First, we recommend to use the latest version of API ([v201702](https://developers.google.com/adwords/api/docs/reference/)) and client library ([v26.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/26.0.0)) to ensure you can benefit from the latest features and bug fixes.

You can take a look at the [README.md](https://github.com/googleads/googleads-php-lib/blob/master/README.md) file and guides ([Get Started](https://developers.google.com/adwords/api/docs/guides/start) and [Make Your First API Call](https://developers.google.com/adwords/api/docs/guides/first-api-call)).

Please let me know if you have more specific questions so I can address properly.

Best,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity. Please re-open if you need further help.

**Comment by Bl4ckf4ll** [comment]
I'm having a problem with the new Lib, and it's that with the new lib you need to specify the customerId to create a session, but I don't need that, I need to get the User accounts, all the accounts the user has access, there's a way to accomplish that with the new lib?

**Comment by fiboknacky** [comment]
You can create an AdWordsSession by not specifying clientCustomerId.
Then, you can call [CustomerService.getCustomers()](https://developers.google.com/adwords/api/docs/reference/v201802/CustomerService#getcustomers) to get all accounts that the user has access to.

**Comment by dnypinkesh** [comment]
hello,

I am integrating Google adwords Api in our project using v201806 (PHP client lib) version . I have to get all campaign and other details of third party Google adwords user client . Please help me to setup API to do my work .

Also give me the way , how can i create new AdWordsUser object for further use .

Thanks in Advance .

**Comment by fiboknacky** [comment]
Hi @dnypinkesh 

First, there is no AdWordsUser object now.
And have you tried following [README](https://github.com/googleads/googleads-php-lib/blob/master/README.md)?
Do you find any problems during that?

Best,
Knack

**Comment by dnypinkesh** [comment]
thanks Knack,

please tell me one thing also... how can be update api version future???

**Comment by fiboknacky** [comment]
This library uses Composer, as stated in [this section](https://github.com/googleads/googleads-php-lib#requirements-and-preparation).
When you'd like to upgrade the version, you can run `$ composer require googleads/googleads-php-lib:35.0.0` where 35.0.0 is the new version you want to upgrade to.
