### ISSUE TITLE
Google Adwrods-Api oAuth2 scope issue

### ISSUE THREAD

**Issue by amankr567** [googleads/googleads-php-lib#284]
Hello Everyone ,

I am using Google Adwords API v201702 for php client lib and try to [accessing an API on behalf of clients](https://github.com/googleads/googleads-php-lib/wiki/API-access-on-behalf-of-your-clients-(web-flow))

I have successfully created $oauth2 data , by using below code

```
use Google\Auth\OAuth2;

session_start();

$oauth2 = new OAuth2([
    'authorizationUri' => 'https://accounts.google.com/o/oauth2/v2/auth',
    'tokenCredentialUri' => 'https://www.googleapis.com/oauth2/v4/token',
    'redirectUri' => '****',
    'clientId' => '****',
    'clientSecret' => '****',
    'scope' => 'https://www.googleapis.com/auth/adwords'
]);
```
My issue is when i pass an array into **scope** result page become blank , Please help me how can i pass an array to scope for google adwords php client lib for getting all **CustomerServices** data .
Please also describe the way to get **clientCustomerId** using **AccessToken** in Google Adwords API v201702.

**Thanks all.**

**Comment by fiboknacky** [comment]
Hello,

Do you mean it works when using the string, e.g.,  `'https://www.googleapis.com/auth/adwords'`, but failed when using an array?
If so, could you please clarify how you specified the array as `$scope`?
Note that you can specify it as [space-delimited strings](https://github.com/google/google-auth-library-php/blob/master/src/OAuth2.php#L120) as well.

And for:

> Please also describe the way to get clientCustomerId using AccessToken in Google Adwords API v201702.

You can get the customer info directly accessible by the user authenticating the call by using [`getCustomers()`](https://developers.google.com/adwords/api/docs/reference/v201702/CustomerService#getcustomers)

Best,
Knack
