### ISSUE TITLE
I can't pause or enable video campaigns.

### ISSUE THREAD

**Issue by mahirsumer** [googleads/googleads-php-lib#288]
I can't pause or enable video campaigns. How can i do it?

**Comment by fiboknacky** [comment]
Hi @mahirsumer 

Do you wish to use CampaignService with video campaigns?
Unfortunately, CampaignService doesn't support them, as described [here](https://developers.google.com/adwords/api/docs/reference/v201702/CampaignService).

Best,
Knack
