### ISSUE TITLE
How get developer token?

### ISSUE THREAD

**Issue by Radzhab** [googleads/googleads-php-lib#289]
I found client id, client secret, refresh token, but i cannot find this token.

**Comment by fiboknacky** [comment]
Hello @Radzhab 

Developer tokens can be obtained by signing up to use AdWords API, as described [here](https://developers.google.com/adwords/api/docs/guides/signup).
If you need further help on this, please contact the AdWords API team at [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api).

Best,
Knack
