### ISSUE TITLE
BiddableAdGroupCriterion.qualityInfo is NULL instead of QualityInfo.qualityScore

### ISSUE THREAD

**Issue by BenMorel** [googleads/googleads-php-lib#290]
According to the v201702 reference for [BiddableAdGroupCriterion](https://developers.google.com/adwords/api/docs/reference/v201702/AdGroupCriterionService.BiddableAdGroupCriterion) and [QualityInfo](https://developers.google.com/adwords/api/docs/reference/v201702/AdGroupCriterionService.QualityInfo):

- `BiddableAdGroupCriterion`.`qualityInfo` is never null (when selected)
- `QualityInfo`.`qualityScore` can be null: *"Beginning with v201607, this field will return null (...) when there aren't enough impressions or clicks to determine an appropriate quality score value."*

However, when using the API, it's actually `BiddableAdGroupCriterion`.`qualityInfo` that's null for some keywords. And when it's populated, `QualityInfo`.`qualityScore` is *never null*.

Example:

    $selector = new Selector();
    // ...
    $selector->setFields(['QualityScore' /* , ... */]);
    $page = $adGroupCriterionService->get($selector);
    $criteria = $page->getEntries();

    foreach ($criteria as $criterion) {
        $qualityInfo = $criterion->getQualityInfo();
    
        if ($qualityInfo === null) {
            // this happens for some keywords
        } else {
            $qualityScore = $qualityInfo->getQualityScore();
    
            if ($qualityScore === null) {
                // this never happens!
            }
        }
    }

It would be nice to change the SDK implementation, or the API documentation (not sure which one is wrong) to be consistent on this matter.

**Comment by fiboknacky** [comment]
Hi @BenMorel 

Is it possible to give some examples of ad group IDs and ad group criteria IDs that have `qualityInfo` and `qualityScore` as you described?

Thanks in advance.

Best,
Knack

**Comment by BenMorel** [comment]
@fiboknacky sure:

- AdGroup ID : 34534651117
- Criterion ID : 138712450

I can't see an ID field for AdGroupCriterion.

**Comment by fiboknacky** [comment]
Hello Benjamin,

Thanks once again for reporting this.
Engineering has been informed of this and it'll be fixed from the API side, not in this library.
So, I'll close this issue soon.

Best,
Knack
