### ISSUE TITLE
Error message in script

### ISSUE THREAD

**Issue by SeriousJ55** [googleads/googleads-php-lib#291]
My simple API scripts work fine when I launch them from a browser.

But when I launch them from a command line, I get plenty of "error" messages like this one:
`[2017-05-12 15:09:42] AW_SOAP.INFO: clientCustomerId=XXX-XXX-XXXX operations=1 service=CampaignService method=get responseTime=186 requestId=00054f55184ac4e80a3767c6b90XXXXX server=adwords.google.com isFault=0 faultMessage=`

It can't be error messages because my scripts work well and end fine. But I understand they somehow get to STDERR.

How do I get rid of them?

**Comment by fiboknacky** [comment]
Hi @SeriousJ55 

That's not an error message. It's a log message printed for all SOAP calls by default.
You can customize the log levels and the path to print logs [here](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/adsapi_php.ini#L52).

Cheers,
Knack

**Comment by SeriousJ55** [comment]
I found the answer in README.md. I'm sharing the solution for those poor souls like me trying to make this obscure API work: at the end of your adsapi_php.ini file, you need to set your logging settings to "NOTICE".

So the last lines of your adsapi_php.ini file should look like this:

```
[LOGGING]
; Optional logging settings.
; soapLogFilePath = "path/to/your/soap.log"
soapLogLevel = "NOTICE"
; reportDownloaderLogFilePath = "path/to/your/report-downloader.log"
reportDownloaderLogLevel = "NOTICE"
; batchJobsUtilLogFilePath = "path/to/your/bjutil.log"
batchJobsUtilLogLevel = "NOTICE"
```
