### ISSUE TITLE
Wrong types in ReportQuery

### ISSUE THREAD

**Issue by montolio** [googleads/googleads-php-lib#292]
In the ReportQuery the types for dimensions, columns and dimensionAttributes are invalid.
They are array, not string. To to be precise: string[]

That does not work:
$reportQuery->setDimensions(\implode(' ', [Dimension::LINE_ITEM_ID, Dimension::LINE_ITEM_NAME]));

This does:
$reportQuery->setDimensions([Dimension::LINE_ITEM_ID, Dimension::LINE_ITEM_NAME]);

**Comment by fiboknacky** [comment]
Hi @montolio 

Thanks for reporting. Will have a look.

Knack

**Comment by fiboknacky** [comment]
This is fixed in [v28.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/28.0.0).
