### ISSUE TITLE
 i first call the API, issue

### ISSUE THREAD

**Issue by shindesgaar077** [googleads/googleads-php-lib#294]
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Al
l of 'clientId', 'clientSecret', and 'refreshToken' must be set when using insta
lled/web application flow.' in C:\xampp\htdocs\test_laravel\vendor\googleads\goo
gleads-php-lib\src\Google\AdsApi\Common\OAuth2TokenBuilder.php:179
Stack trace:
#0 C:\xampp\htdocs\test_laravel\vendor\googleads\googleads-php-lib\src\Google\Ad
sApi\Common\OAuth2TokenBuilder.php(134): Google\AdsApi\Common\OAuth2TokenBuilder
->validate()
#1 C:\xampp\htdocs\test_laravel\vendor\googleads\googleads-php-lib\examples\AdWo
rds\v201609\BasicOperations\GetCampaigns.php(77): Google\AdsApi\Common\OAuth2Tok
enBuilder->build()
#2 C:\xampp\htdocs\test_laravel\vendor\googleads\googleads-php-lib\examples\AdWo
rds\v201609\BasicOperations\GetCampaigns.php(89): Google\AdsApi\Examples\AdWords
\v201609\BasicOperations\GetCampaigns::main()
#3 {main}
  thrown in C:\xampp\htdocs\test_laravel\vendor\googleads\googleads-php-lib\src\
Google\AdsApi\Common\OAuth2TokenBuilder.php on line 179

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'All of
'clientId', 'clientSecret', and 'refreshToken' must be set when using installed/
web application flow.' in C:\xampp\htdocs\test_laravel\vendor\googleads\googlead
s-php-lib\src\Google\AdsApi\Common\OAuth2TokenBuilder.php:179
Stack trace:
#0 C:\xampp\htdocs\test_laravel\vendor\googleads\googleads-php-lib\src\Google\Ad
sApi\Common\OAuth2TokenBuilder.php(134): Google\AdsApi\Common\OAuth2TokenBuilder
->validate()
#1 C:\xampp\htdocs\test_laravel\vendor\googleads\googleads-php-lib\examples\AdWo
rds\v201609\BasicOperations\GetCampaigns.php(77): Google\AdsApi\Common\OAuth2Tok
enBuilder->build()
#2 C:\xampp\htdocs\test_laravel\vendor\googleads\googleads-php-lib\examples\AdWo
rds\v201609\BasicOperations\GetCampaigns.php(89): Google\AdsApi\Examples\AdWords
\v201609\BasicOperations\GetCampaigns::main()
#3 {main}
  thrown in C:\xampp\htdocs\test_laravel\vendor\googleads\googleads-php-lib\src\
Google\AdsApi\Common\OAuth2TokenBuilder.php on line 179

**Comment by fiboknacky** [comment]
Hi @shindesgaar077 

How did you set the [adsapi_php.ini](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/adsapi_php.ini#L31)?
Have you provided all information needed (clientId, clientSecret, refreshToken)?

Cheers,
Knack

**Comment by shindesgaar077** [comment]
PHP Fatal error:  Uncaught exception 'Google\AdsApi\AdWords\v201609\cm\ApiExcept
ion' with message '[QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED @ ; trigger:'<n
ull>']' in C:\xampp\htdocs\test_laravel\vendor\googleads\googleads-php-lib\src\G
oogle\AdsApi\Common\Util\Reflection.php:39

**Comment by fiboknacky** [comment]
Hi @shindesgaar077 

Your developer token hasn't been approved yet.
For more information, please see [this guide](https://developers.google.com/adwords/api/docs/guides/signup).

If you have further questions about this or anything related to AdWords API in general, please ask in [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api).

Cheers,
Knack

**Comment by divyesh-zignuts** [comment]
Hello developer,

I got the same error at first call, requesting you to please look at the error and give me the solutions.

```An uncaught Exception was encountered
Type: InvalidArgumentException

Message: All of 'clientId', 'clientSecret', and 'refreshToken' must be set when using installed/web application flow.

Filename: /var/projects/filud/filud_dev/application/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/OAuth2TokenBuilder.php

Line Number: 225

Backtrace:

File: /var/projects/filud/filud_dev/application/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/OAuth2TokenBuilder.php
Line: 173
Function: validate```

**Comment by fiboknacky** [comment]
The error message is explicit: You need to supply all the information (client ID, secret and refresh tokens).
Please follow [this guide](https://developers.google.com/adwords/api/docs/guides/first-api-call) to get started.
For more help on this, please post in [AdWords API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).
