### ISSUE TITLE
Are keywords unique?

### ISSUE THREAD

**Issue by yooouuri** [googleads/googleads-php-lib#297]
At this moment, in AdWords the following keyword exists:

Group Id: 42999949136
Keyword Id: **324002149674**
Type: broad
Text: +Heftruck +Basis +cursus

Adding a new keyword to a different campaign & different group

Group Id: 42180344626 (is different from the previous Group Id)
Keyword Id: needs to be generated
Type: broad
Text: +Heftruck +Basis +cursus

```
$adGroupCriterion = new BiddableAdGroupCriterion();
$adGroupCriterion->setAdGroupId(42180344626);
```

The BatchJob returns the following keyword:

![image](https://cloud.githubusercontent.com/assets/12934957/26301527/c75bb4a6-3ee1-11e7-9545-ec394d0b342a.png)

I changed the `groupId` so why does AdWords returns an already existing (keyword) ID?

**Comment by fiboknacky** [comment]
Hello @yooouuri 

The question is more related to AdWords API in general, so would you mind posting your questions in the [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api) instead?

Thanks in advance.

Cheers,
Knack

**Comment by yooouuri** [comment]
Hey Knach,

I did post my question on the forum but they did not approve my question jet.

Sorry for the inconvenience.

Youri

**Comment by fiboknacky** [comment]
Hello,

It should be approved now. 
There'll be our team replying to your post soon so I'll close this issue soon.

Cheers,
Knack
