### ISSUE TITLE
SOAP calls increase open file descriptor count

### ISSUE THREAD

**Issue by bitsbauer** [googleads/googleads-php-lib#298]
As we recently upgraded our System (Cent-OS 7) from PHP5.6 to PHP7.1 we encounter an error after a while if we make service calls: "Process open FD table is full".
I checked and it seems to be related to the SOAP calls made in the lib.

For example if we loop over an amount of customers and on each customer we call:
$service = (new AdWordsServices())->get($session, CampaignService::class);

The open FD counter increases which I checked by calling "lsof -p x | wc -l" on the process-id (x).
After some time the open FD table is full. I tried to disable WSDL cache but no effect on this.
There seems to be problem with not closing file-descriptors within the soap calls.

**Comment by fiboknacky** [comment]
Hi @bitsbauer,

I'll check more about this.
Could you please send your manager account's `clientCustomerId` to adwordsapiadvisor+thanet@google.com?

Thanks in advance.

Knack

**Comment by fiboknacky** [comment]
This should have been fixed by the recent PR.
The fix is also included in the latest release ([v27.1.0](https://github.com/googleads/googleads-php-lib/releases/tag/27.1.0)).

Best,
Knack
