### ISSUE TITLE
Wiki wrong AdWordsService call

### ISSUE THREAD

**Issue by swordbeta** [googleads/googleads-php-lib#300]
https://github.com/googleads/googleads-php-lib/wiki/API-access-on-behalf-of-your-clients-(web-flow)

```
    $adWordsServices->get($session, 'CampaignService', 'v201603', 'cm');
```

should be

```
    $adWordsServices->get($session, 'CampaignService');
```

**Comment by fiboknacky** [comment]
Thanks for reporting.
Will fix it.

Best,
Knack

**Comment by fiboknacky** [comment]
Hi @swordbeta 

Just updated the wiki. Thanks again for reporting.

Cheers,
Knack
