### ISSUE TITLE
PHP API Setup

### ISSUE THREAD

**Issue by sudhyer** [googleads/googleads-php-lib#302]
Hi,

URL: http://localhost/googleads/vendor/googleads/googleads-php-lib/examples/Auth/GetRefreshToken.php

when I am running above URL then getting these types of error on screen.
"Enter your OAuth2 client ID here: Enter your OAuth2 client secret here: Select the ads API you're using: [0] AdWords [1] DFP [2] Both Please enter a valid number for the ads API you're using: [0] AdWords [1] DFP [2] Both Please enter a valid number for the ads API you're using: [0] "

**Comment by fiboknacky** [comment]
Hi @sudhyer 

It's a normal flow when you run this file. It requires you to enter OAuth2 client ID, secret and the product you'd like to use.
It looks like you've entered information up to the product number (0 for AdWords and DFP), right?

If so, what's your issue after entering that info? Have you been faced with an error message?

Best,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity.
