### ISSUE TITLE
Modify soapLogLevel when using ads session builders

### ISSUE THREAD

**Issue by schulzefelix** [googleads/googleads-php-lib#303]
Hello,

I create my Authentication with the OAuth2TokenBuilder and AdWordsSessionBuilder instead of the `adsapi_php.ini`.

Is the a way to modify the Logging options too? 
If I use the `adsapi_php.ini` there is the `[LOGGING]`block where I can set for example the soapLogLevel, but is there a way to do it programmatically?

Thanks in advance.

**Comment by fiboknacky** [comment]
Hello Felix,

Yes, you can do it via [AdsLoggerFactory](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/AdsLoggerFactory.php).
As an example, this is done in AdWordsSessionBuilder from [line 121](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L121) to [line 136](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L136).

You can pass the log level as the third parameter to [`createLogger`](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/AdsLoggerFactory.php#L39).

Hope this help. :)

Knack

**Comment by schulzefelix** [comment]
Thanks, works perfect! I'll close the "issue".
