### ISSUE TITLE
RateExceededError when downloading reports

### ISSUE THREAD

**Issue by Code-Working** [googleads/googleads-php-lib#304]
Hi,

I have basic access (1.000 report downloads per day) and unfortunately exceeded the download limit.

When analyzing the errors, I could not get the underlying `RateExceededError` to determine its scope or number of seconds to wait and so on, because there is no `RateExceededError` class referenced in the `ApiException`.  
The only thing I get is the errorString `RateExceededError.RATE_EXCEEDED` from the `ReportDownloadError`.

The following code is a shortened `print_r()` of the exception thrown during the report download:

    Google\AdsApi\AdWords\v201609\cm\ApiException Object
    (
        [errors:protected] => Array
            (
                [0] => Google\AdsApi\AdWords\Reporting\v201609\ReportDownloadError Object
                    (
                        [fieldPath:protected] =>
                        [trigger:protected] => Basic Access Daily Reporting Quota
                        [errorString:protected] => RateExceededError.RATE_EXCEEDED
                        [ApiErrorType:protected] =>
                    )
            )
        [message1:protected] =>
        [ApplicationExceptionType:protected] =>
        [message:protected] => Details: [fieldPath: ; trigger: Basic Access Daily Reporting Quota; errorString: RateExceededError.RATE_EXCEEDED]
        [string:Exception:private] =>
        [code:protected] => 0
        [file:protected] => [...]/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/Reporting/v201609/ReportDownloader.php
        [line:protected] => 143
        [trace:Exception:private] => Array
            (
                [0] => Array
                    (
                        [file] => [...]/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/Reporting/v201609/ReportDownloader.php
                        [line] => 94
                        [function] => makeReportRequest
                        [class] => Google\AdsApi\AdWords\Reporting\v201609\ReportDownloader
                        [type] => ->
                        [args] => Array ([...])
                    )
                [1] => Array ([...])
            )
        [previous:Exception:private] =>
    )

Is there any trick or any way to get the number of seconds to wait before we can try to download a report again?

Thank you
Code-Working

**Comment by fiboknacky** [comment]
Hello Code-Working,

From the trigger message "Basic Access Daily Reporting Quota", this means you've already reached the daily limit of using reporting, so please try again on the next day.

For other rate exceeded cases, could you please follow this best practices [guide](https://developers.google.com/adwords/api/docs/guides/bestpractices#distinguish_request_sources), by using an _expontential backoff policy_?
For example, if you first pause 5 seconds before the first retry, you could pause 10 seconds after the second and 20 seconds after the third retry. Exponential backoff helps ensure you are not calling the API too aggressively.

Best,
Knack

**Comment by Code-Working** [comment]
Hi @fiboknacky,

thank you for the quick response.

I have already implemented an exponential backoff policy (1 minute, 2 minutes and so on), but this does not help if I have to wait for the next day.

I was just wondering if I would get back any amount of seconds to the time when the rate limit resets.  
The rate exceeded error occured yesterday the first time, today I'm still getting this error.  
Is is correct to assume the daily limit is by 24 hours and not per day-unit?

This is important to me because my app downloads some reports in the morning and some in the afternoon.  
How long do I have to wait if the rate exceeded error occures on the afternoon?

Best
Code-Working

**Comment by fiboknacky** [comment]
Hi Code-Working,

Sorry for your inconvenience but would you mind post your question in [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api) instead?
It looks to me that this is more involved with AdWords API in general, not PHP client library, and people monitoring the forum could help you more effectively.

Thanks in advance. :)

Best,
Knack

**Comment by Code-Working** [comment]
Allright I will post it there. Thank you anyway.
