### ISSUE TITLE
google api php client and googleadwords php api?

### ISSUE THREAD

**Issue by johnraypaulin14** [googleads/googleads-php-lib#305]
Is this particular api can be used along with googleadwords php api?
`$client = new Google_Client();
...
$client->setScopes($SCOPES);

$oauth2 = (new OAuth2TokenBuilder())
					->withClientId($OAuthCredentials['clientId'])
					->withClientSecret($OAuthCredentials['clientSecret'])
					->withRefreshToken($client->getRefreshToken())
					->build();

$session = (new AdWordsSessionBuilder())
                        ->fromFile()    
                        ->withOAuth2Credential($oauth2)                
                        ->build();

$adWordsServices 		= new AdWordsServices();
$managedCustomerService = $adWordsServices->get($session, ManagedCustomerService::class);
			

			$selector = new Selector();
			$selector->setFields(['CustomerId', 'Name']);
			$selector->setOrdering([new OrderBy('CustomerId')]);

$mccAccounts = $managedCustomerService->get($selector);`

This code returns 

Client error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `401 Unauthorized` response: { "error": "invalid_client", "error_description": "Unauthorized" }

**Comment by fiboknacky** [comment]
Hi @johnraypaulin14 

Could you please make sure that while you tried to generate the refresh token, you were logged onto the account that has access to AdWords accounts? If not, could you please try again?

Cheers,
Knack

**Comment by johnraypaulin14** [comment]
Hi @fiboknacky 

Thanks for your reply and yes, I am using an account that has access to AdWords accounts. I actually have used this code (pure OAuth2 class) and works:

**$oauth2 = new OAuth2($OAuthCredentials);**

But I'm trying and want to use Google_Client to access adwords but it is giving me unauthorized access. What am I missing here?

**Comment by fiboknacky** [comment]
Hello @johnraypaulin14 

From what I see now, I would suspect that the refresh tokens you passed in the original post and in your previous comment are not the same.

In the original post, you set refresh token using `$client->getRefreshToken()`:
```php
$oauth2 = (new OAuth2TokenBuilder())
->withClientId($OAuthCredentials['clientId'])
->withClientSecret($OAuthCredentials['clientSecret'])
->withRefreshToken($client->getRefreshToken())
->build();
```

But in the previous comment, you pass the `$OAuthCredentials` array to the `OAuth2` constructor.
Can't you pass the same refresh token to `withRefreshToken()` too?

Best,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity. Please re-open if you still face with this issue.
