### ISSUE TITLE
v27.1.0 breaks compatibility w/ Psr\Log\LoggerInterface

### ISSUE THREAD

**Issue by metadke** [googleads/googleads-php-lib#306]
If you set a custom logger w/ the `with...Logger()` function of the `AdWordsSessionBuilder` you will get a runtime exception later, because some inner implementation calls `isHandling()` on the implementation of `Psr\Log\LoggerInterface` which does not exist.

For example:

<pre>
$myLogger = new  (class that implements Psr\Log\LoggerInterface) { ,,, };

$builder = (new AdWordsSessionBuilder())
  // ...
  ->withReportDownloaderLogger($myLogger)
  ->build();
</pre>

`PHP Fatal error:  Call to undefined method MyLogger::isHandling() in vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/GuzzleLogMessageHandler.php on line 53`

**Comment by fiboknacky** [comment]
Thanks for reporting. Will have a look.

**Comment by fiboknacky** [comment]
This is fixed in [v28.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/28.0.0).
