### ISSUE TITLE
ApiException RateExceeded broken

### ISSUE THREAD

**Issue by Fundaris** [googleads/googleads-php-lib#307]
Hey my code is producing RateExceeded errors and I cant filter them because getApiErrorType() returns Null

Function
`} catch (ApiException $e) {
            foreach ($e->getErrors() as $error) {
                var_dump($error);
                var_dump($error->getApiErrorType());
                if ($error->getApiErrorType() != "RateExceededError") {
                       //some error handling
                }
          }
}`

getErrors() $errors Object
`object(Google\AdsApi\AdWords\v201705\cm\RateExceededError)#62 (10) {
  ["reason":protected]=>
  string(13) "RATE_EXCEEDED"
  ["rateName":protected]=>
  string(10) "RATE_LIMIT"
  ["rateScope":protected]=>
  string(7) "ACCOUNT"
  ["retryAfterSeconds":protected]=>
  int(30)
  ["fieldPath":protected]=>
  string(0) ""
  ["fieldPathElements":protected]=>
  NULL
  ["trigger":protected]=>
  string(0) ""
  ["errorString":protected]=>
  string(31) "RateExceededError.RATE_EXCEEDED"
  ["ApiErrorType":protected]=>
  NULL
  ["ApiError.Type"]=>
  string(17) "RateExceededError"
}`

**Comment by fiboknacky** [comment]
Hi @Fundaris 

Sorry for your inconvenience.
We're fixing this and will inform you once it's pushed to the repo.
Please follow up with #226 

Best,
Knack
