### ISSUE TITLE
how to get stats for location in google ads php api?

### ISSUE THREAD

**Issue by scamexdotexe** [googleads/googleads-php-lib#309]
I want to get stats for a targeted location of a campaign such as:

`var geostats = targetedLocation.getStatsFor(String(duration[0]),String(duration[1]));`

This is in JS version, I am looking to recreate it php version. I can already traverse through accounts and campaigns of each account but I'm lost in getting stats for location.

**Comment by fiboknacky** [comment]
Hello @scamexdotexe 

Where do you get that JS script? It looks like not one of our [client libraries](https://developers.google.com/adwords/api/docs/clientlibraries).
In general, if you'd like to get stats, [AdWords reporting](https://developers.google.com/adwords/api/docs/guides/reporting) is what you can use.

We have examples for downloading reports in [here](https://github.com/googleads/googleads-php-lib/tree/master/examples/AdWords/v201705/Reporting).

The report type that would be closest to your request is [GEO_PERFORMANCE_REPORT](https://developers.google.com/adwords/api/docs/appendix/reports/geo-performance-report).

Best,
Knack

**Comment by scamexdotexe** [comment]
That is a Google Ads Script. Basically, I want to get statistics (based on campaign id) for example for 

_New York = clicks, cost, conversions, etc
Canada = clicks, cost, conversions, etc
Alabama = clicks, cost, conversions, etc
Alaska = clicks, cost, conversions, etc_

Flow of my php code:

1. Get all campaigns from an account (Taking note of the campaign id)
2. Get all location name from campaign criterion service with these predicates:
                              **new Predicate('CampaignId', PredicateOperator::IN, [$campaignId]), 
                              new Predicate('CriteriaType', PredicateOperator::IN, ['LOCATION'])]);**
3. Then, get statistics using CAMPAIGN_LOCATION_TARGET_REPORT based on campaign ID like:
                               **$query = 'SELECT CampaignId,Clicks, Cost, Conversions, CostPerConversion, 
                               Ctr,CampaignName,ConversionRate
                               FROM CAMPAIGN_LOCATION_TARGET_REPORT
                               WHERE CampaignId = ' . $campaignId              
                                                . ' DURING ' . $during;**
My problem is that the result I think is erroneous as it has duplicate values as the #2 step returns with multiple results. 

Is there a class (php) that's similar to or has the same functionality to this (GAS) script:

https://developers.google.com/adwords/scripts/docs/reference/adwordsapp/adwordsapp_targetedlocation

**Comment by fiboknacky** [comment]
Hello,

Sorry, I missed that it was AdWords Scripts.
We don't have a class that is the same as targeted location in the Scripts.

You don't need to get all campaigns first in order to use CAMPAIGN_LOCATION_TARGET_REPORT.
You can use the report directly and specify the query like this:

```
SELECT CampaignId, CampaignName, Id, Clicks, Cost, Conversions, CostPerConversion,
Ctr, ConversionRate
FROM CAMPAIGN_LOCATION_TARGET_REPORT
WHERE CampaignId IN [<YOUR_CAMPAIGN_IDS_DELIMITED_BY_COMMAS>] DURING <YOUR_DATE_RANGE>;
```

The results can contain many rows that look duplicate if you don't specify **Id** in the query too.
This is because **Id** is the main object of this report type.
Even if you don't specify it explicitly, the returned rows are still generated for each criterion ID.

Cheers,
Knack
