### ISSUE TITLE
PHP DFP API CodeIgniter / composer

### ISSUE THREAD

**Issue by canado** [googleads/googleads-php-lib#310]
Hello googleads team

I am  trying to acces google DFP api using 
- codeigniter 3
- composer
- client v201705
- PHP 5.6 ( with soap )

So far I have this error

PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'All of 'clientId', 'clientSecret', and 'refreshToken' must be set when using installed/web application flow.' in /var/www/mysite.com/public_html/qmi/g/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/OAuth2TokenBuilder.php:195

I am not quite sure where to place the .ini file so I have added here
- /root
- /var/www/mysite.com/public_html/qmi/g

I also restarted the server

Do you have a walkthrough ? the reason  I am using a framework, is that I also want to connect to  other api using the same "website"

Regards

**Comment by fiboknacky** [comment]
Hello @canado 

The walkthrough is in [README.md](https://github.com/googleads/googleads-php-lib#getting-started).
The `adsapi_php.ini` is supposed to be placed in your machine "home" directory.

Please let me know if you need further help.

Cheers,
Knack

**Comment by canado** [comment]
Hello @fiboknacky 
I am back to  work, thank you for your reply.
As I read the readme.md file
On section 2
Copy the sample adsapi_php.ini for your product to your home directory and fill out the required properties.

Does it mean I need to upload the adsapi_php.ini file in the project home directory 
something like /var/html/mynamesite/public_html/ ( at the home of my website )
Or do you mean directly in /home on my linux server or  /home/username ?

Other than that I have this error

 PHP Fatal error:  Interface 'Google\\Auth\\FetchAuthTokenInterface' not found in /var/www/mywebsite.com/public_html/vendor/google/auth/src/OAuth2.php on line 36

I think the auth is ok but the callback error is not.
In  the example, it's written 		
$redirect_uri = 'http://' . $_SERVER['HTTP_HOST'] . '/oauth2callback.php';
but I don't have any oauth2callback.php file after composer installation, the only look alike file is OAuth2.php so I redirected to  it

Regards

**Comment by fiboknacky** [comment]
Hello @canado 

For the home directory, it depends on your system but on unix, it equals to `getenv('HOME')`.
The algorithm for getting the home directory can be found in [EnvironmentalVariables.php](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/Util/EnvironmentalVariables.php).

As for
> Other than that I have this error
PHP Fatal error: Interface 'Google\Auth\FetchAuthTokenInterface' not found in /var/www/mywebsite.com/public_html/vendor/google/auth/src/OAuth2.php on line 36
I think the auth is ok but the callback error is not.
In the example, it's written
$redirect_uri = 'http://' . $_SERVER['HTTP_HOST'] . '/oauth2callback.php';
but I don't have any oauth2callback.php file after composer installation, the only look alike file is OAuth2.php so I redirected to it

First, could you please elaborate how you installed our library using composer?
It looks like some dependencies might not be installed properly.

Cheers,
Knack

**Comment by canado** [comment]
Ok so I found the home using 
var_dump($user = posix_getpwuid(posix_getuid()));
and I have this   /var/www

**Comment by canado** [comment]
Ok so I found the home using
var_dump($user = posix_getpwuid(posix_getuid()));
and I have this /var/www

**Comment by canado** [comment]
Ok so I found the home using
var_dump($user = posix_getpwuid(posix_getuid()));
and I have this /var/www

I installed the library using that line
php composer.phar require googleads/googleads-php-lib

then I have the client_secret_1077XXXXXXX.json file in the root of the  CI project
I have unchecked the comments of adsapi_php.ini

I have this in my adsapi_php.ini

; For service account flow.
 jsonKeyFilePath = "client_secret_1077XXXXXXXXX.json"
 scopes = "https://www.googleapis.com/auth/dfp"
 impersonatedEmail = "my@email.com"

; For installed application or web application flow.
client_id = "XXXXX-aaaaaaa.apps.googleusercontent.com"
client_secret = "XXXXXXXXXXXXXXXXXXX"
; If you already have a refresh token, enter it below. Otherwise, run
; GetRefreshToken.php.
refresh_token = "4/6_XXXXXXXXXXXXx-XXXXXXXXXXXXXx#"


Question, in "impersonatedEmail " should I use my personal email  or the service account email ? the one provided by google service console ?  XXXX@XXXX.gserviceaccount.com

Regards

**Comment by fiboknacky** [comment]
Hi @canado 

First, please select whether you'd like to use service account or installed application flow.
Comment the other methods you'd not use for now.

And for the impersonated email, I need to find out and will get back to you later but I remember vaguely that it's used more often for AdWords API.
If you use service account and obtain JSON key correctly, probably you should be able to make a call.

Cheers,
Knack

**Comment by canado** [comment]
Ok then I might be wrong but I think in  my case it will be "web application  flow" since I will use codeigniter over http.

So no need to look  for the email

**Comment by canado** [comment]
ok I made some progress : )

$oauth2 = new OAuth2 is not giving me any error

Now I am trying to make a test with GetAllNetworks
so I copied the 2 methods runExample and main

And in my custom class in Codeigniter I am doing $this->main()
In the log I have 
 PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'json key is missing the client_email field' 

When I look for this error on google,  it says I need to add the right .json file, the one with "type":"service_account"
Which I did, and in the top  of my custom class I use
putenv('GOOGLE_APPLICATION_CREDENTIALS='.FCPATH.'DFP-cjc-XXXXXXX.json'); 

So I think  there is a little step missing but I don't know exactly where : (

Regards

**Comment by canado** [comment]
Ok I have this error now
 Uncaught exception 'DomainException' with message 'Missing authorization code' in /var/www/mysite.com/public_html/qmi/cxense/vendor/google/auth/src/OAuth2.php:457

but I believe it's a codeigniter error

**Comment by fiboknacky** [comment]
Hi @canado 

So, now you only have `DomainException` error? Or do you still get other errors stated above?

Thanks.
Knack

**Comment by canado** [comment]
Only DomainException

**Comment by canado** [comment]
Hello @fiboknacky 
Maybe you can explain me a bit what is under the hood.

1- first I do the $oauth2 = new OAuth2, this  will trigger the google client auth, with the associated adsapi_php.ini and .json file
2 - once the authentification  is done, the system callback the oauth2.php file ? with the token code ? in  the urls ?

By the way as redirect urion my $oauth2 = new OAuth2([ 
 I have 
'redirectUri' => 'http://localhost/dfp',

And it doesn't matter if I write this or my actual website url

**Comment by canado** [comment]
@fiboknacky 

I switched back to $client = new Google_Client(); instead of $oauth2 = new OAuth2([
With the modification I made, I have no error.

My url is like this
https://mysite.com/folder/project

my redirect url is the same
And of course it ends in a infinite redirect loop after the authentication.

So what would be the correct modification for the correct behavior ?

Regards

**Comment by canado** [comment]
@fiboknacky 

I have more concrete clues now.

In  my main class, I have a method in which 
I construct the $client
then I check isset($_SESSION['access_token'])
if not ,I automatically redirect to the same page but in a new method

In this new method I am checking if I have the code in  the url
isset($_GET['code'])
if not I create a href link button to the google authorization page.

Which redirect to the same page same method but with the code : )

Now I have the code ( from the url ), and I have ( $client which was previously  stored via Session and when I var_dump $client everything seems fine )
Now I do
 $client->authenticate($_GET['code']);
$client->getAccessToken()
And this is where I am stuck

$client->getAccessToken() returns nothing.
and if I check $client->isAccessTokenExpired() I have TRUE.

**Comment by fiboknacky** [comment]
It looks like you've not obtained the access token properly as it's empty and the token seems to be expired.
Have you tried following [this guide](https://github.com/googleads/googleads-php-lib/wiki/API-access-on-behalf-of-your-clients-(web-flow)) too?

**Comment by canado** [comment]
@fiboknacky Can you confirm that this library is compatible with a php view. And not only with a Command Line interface ?

Regards

**Comment by fiboknacky** [comment]
Examples are [meant](https://github.com/googleads/googleads-php-lib#basic-usage) to be run in the command line. 
But there is nothing that prevents us to use this library in other environments.

**Comment by canado** [comment]
@fiboknacky 
Thank you so much, I followed your other guide 
https://github.com/googleads/googleads-php-lib/wiki/API-access-on-behalf-of-your-clients-(web-flow)
And this worked like a charm, do you know why ? is it because I am using a webview ?

**Comment by fiboknacky** [comment]
Hello,

Great to hear that. :)

I'm not quite sure about that as I don't see all of your settings and files.
But my assumption is that you've followed some parts of instructions of the Google Auth library, which may not be compatible with this library.

Best,
Knack
