### ISSUE TITLE
Identify keywords which are changed

### ISSUE THREAD

**Issue by rajuvishwas** [googleads/googleads-php-lib#311]
Hello,

We are using **TargetingIdeaSelector** to get search volumes for keywords.

We are receiving wrong search volume for "Ogle flights" as the API is changing our keywords to "google flights" and returning search volume for the same.

Is there anyway to identify if the keywords were changed?

Regards,
Raju Vishwas

**Comment by fiboknacky** [comment]
Hello @rajuvishwas,

Your question seems to related to AdWords API in general.
Could you please post this question in the [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api) instead?

Thanks in advance.

Best,
Knack
