### ISSUE TITLE
Get Service Operation Count using v201705 Latest Library

### ISSUE THREAD

**Issue by Vijaysinh** [googleads/googleads-php-lib#312]
I was using $managedCustomerService->GetLastOperations(); this method to get count of operation used while request api call.

But I am not able to find in latest adwords api v20175 how to get lastOperations count?

I am using following code in my old library, But I want using new Library (Release 27.1.0)

$managedCustomerService = $user->GetService('ManagedCustomerService');
$selector = new Selector();
$selector->fields = array('DateTimeZone','Name','CustomerId','CanManageClients','CurrencyCode');
$graph = $managedCustomerService->get($selector);
$operations_count = $managedCustomerService->GetLastOperations();
       
echo "OPERATIONS Used => " . $operations_count;

 I know method is not in managedcustomer service, but its in AdwordsSoapClient.php (Common/Lib/AdwordsSoapClient.php) in old Library..

so I was using this method with any service to get Operations Count in old Library.. but In new library I am not getting.

Could you please help me to get count in new library?

Thanks,
VJ.

**Comment by fiboknacky** [comment]
Hello VJ.,

There is no GetLastOperations in the new library, but you can refer it from [this guide](https://developers.google.com/adwords/api/docs/ratesheet#api-operations).

If your request is `get`, it's counted as 1 operation.
If your request is `mutate`, the number of operations will equal to the number of mutated items. 

For example, if you send a `mutate` request to create 2 campaigns, the number of operations is 2.

Cheers,
Thanet, AdWords API Team

**Comment by fiboknacky** [comment]
As FYI, we plan to support this functionality in the future to give more convenience.
What I've replied previously is a temporary workaround for now.

Cheers,
Knack

**Comment by Vijaysinh** [comment]
Thank you for updating Knack.. I will manage with this temporary settings for now..

**Comment by Vijaysinh** [comment]
also in earlier version we used  $user->LogAll() to log request.
how to do with new this current Library?

**Comment by fiboknacky** [comment]
Logging is now handled in a different way and it is compatible with PSR-3.
Please have a look at [this section](https://github.com/googleads/googleads-php-lib#logging) and [this guide ](https://github.com/googleads/googleads-php-lib/blob/master/UPGRADING.md)for more general guidelines for upgrading.

In short, if you set the [log location](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/adsapi_php.ini#L54) and [level](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/adsapi_php.ini#L55) properly, then the library will log all operations for you.

**Comment by fiboknacky** [comment]
The operation count is now available in the latest version [v29.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/29.0.0).
