### ISSUE TITLE
CustomerSyncSelector - dateTimeRange issue

### ISSUE THREAD

**Issue by chiragvels** [googleads/googleads-php-lib#314]
Hello,

According to documentation [here](https://developers.google.com/adwords/api/docs/reference/v201705/CustomerSyncService.CustomerSyncSelector) I need to select dateTimeRange as String Format: yyyyMMdd HHmmss <Timezone ID> (for example, 20100609 150223 America/New_York).

When I use this 
  $dateTimeRange = new DateTimeRange();
  $dateTimeRange->min = date('20170619 000000 America/New_York');
  $dateTimeRange->max = date('20170619 235959 America/New_York');

API not accepting the dateTimeRange, So there might be issue with API.
Or if this is not correct, how I can pass perticuar timezone so that I can make sure the changes are in-between those time ranges.

API giving me error "An error has occurred: DateError.INVALID_STRING_DATE_TIME @ "; 

Thanks,

**Comment by fiboknacky** [comment]
Hello Chirag,

Could you please take a look at [this example](https://github.com/googleads/googleads-php-lib/blob/5315452fc5b4560a52f8a677f9babc339d751d55/examples/AdWords/v201702/AccountManagement/GetAccountChanges.php#L72)?

From [this reference](http://php.net/manual/en/function.date.php), it looks like the first param of `date()` is not an exact date, but the format of the date.

Best,
Knack

**Comment by chiragvels** [comment]
Hello Knack,

Thanks for pointing out date() reference, it was silly mistake.

Thanks,

**Comment by chiragvels** [comment]
Hello Knack,

I have also noticed that API results are different with added <timezone> in dateRangeTime format and without <timezone>.

With dateRangeTime as a this format  **'20170619 000000'**  gives result 

CustomerChangeData Object
(
    [changedCampaigns] => Array
        (
            [0] => CampaignChangeData Object
                (
                    [campaignId] => ID
                    [campaignChangeStatus] => FIELDS_UNCHANGED
                    [changedAdGroups] => 
                    [addedCampaignCriteria] => 
                    [removedCampaignCriteria] => 
                    [changedFeeds] => 
                    [removedFeeds] => 
                )

            [1] => CampaignChangeData Object
                (
                    [campaignId] => ID
                    [campaignChangeStatus] => FIELDS_UNCHANGED
                    [changedAdGroups] => Array
                        (
                            [0] => AdGroupChangeData Object
                                (
                                    [adGroupId] => ID
                                    [adGroupChangeStatus] => FIELDS_UNCHANGED
                                    [changedAds] => Array
                                        (
                                            [0] => CHANGES
                                        )

                                    [changedCriteria] => 
                                    [removedCriteria] => 
                                    [changedFeeds] => 
                                    [removedFeeds] => 
                                    [changedAdGroupBidModifierCriteria] => 
                                    [removedAdGroupBidModifierCriteria] => 
                                )

                            [1] => AdGroupChangeData Object
                                (
                                    [adGroupId] => ID
                                    [adGroupChangeStatus] => FIELDS_UNCHANGED
                                    [changedAds] => Array
                                        (
                                            [0] => CHANGES
                                            [1] => CHANGES
                                        )

                                    [changedCriteria] => 
                                    [removedCriteria] => 
                                    [changedFeeds] => 
                                    [removedFeeds] => 
                                    [changedAdGroupBidModifierCriteria] => 
                                    [removedAdGroupBidModifierCriteria] => 
                                )

                            [2] => AdGroupChangeData Object
                                (
                                    [adGroupId] => ID
                                    [adGroupChangeStatus] => FIELDS_UNCHANGED
                                    [changedAds] => Array
                                        (
                                            [0] => CHANGES
                                        )

                                    [changedCriteria] => 
                                    [removedCriteria] => 
                                    [changedFeeds] => 
                                    [removedFeeds] => 
                                    [changedAdGroupBidModifierCriteria] => 
                                    [removedAdGroupBidModifierCriteria] => 
                                )

                        )

                    [addedCampaignCriteria] => 
                    [removedCampaignCriteria] => 
                    [changedFeeds] => 
                    [removedFeeds] => 
                )

        )

    [changedFeeds] => 
    [lastChangeTimestamp] => 20170625 235959 PST8PDT
)

with format  '20170619 000000 America/New_York' gives result


CustomerChangeData Object
(
    [changedCampaigns] => Array
        (
            [0] => CampaignChangeData Object
                (
                    [campaignId] => ID
                    [campaignChangeStatus] => FIELDS_UNCHANGED
                    [changedAdGroups] => 
                    [addedCampaignCriteria] => 
                    [removedCampaignCriteria] => 
                    [changedFeeds] => 
                    [removedFeeds] => 
                )

            [1] => CampaignChangeData Object
                (
                    [campaignId] => ID
                    [campaignChangeStatus] => NEW
                    [changedAdGroups] => 
                    [addedCampaignCriteria] => 
                    [removedCampaignCriteria] => 
                    [changedFeeds] => 
                    [removedFeeds] => 
                )

        )

    [changedFeeds] => 
    [lastChangeTimestamp] => 20170625 235959 America/Chicago
)


Please note that I am selecting dateRange between 20170619 to 20170625 in both case also checked with one day prior incase I use timezone with request to make sure all data come.

Thanks,

**Comment by fiboknacky** [comment]
Hello Chirag,

That would be because the default time zone of the account isn't the same as America/New_York, which should work as expected.
Or do you expect different results? Could you please clarify?

Thank you.

Knack

**Comment by chiragvels** [comment]
Hello Knack,

Sorry for the confusion,
I am using account timezone only to get the results.

Or do you expect different results?Could you please clarify?
Yes, I am getting different results 
with dateTimeRange
  $dateTimeRange->min = '20170619 000000';
  $dateTimeRange->max = '20170625 235959';

and with this 
  $dateTimeRange->min = '20170619 000000 America/Chicago';
  $dateTimeRange->max = '20170625 235959 America/Chicago';

I had given results what I was getting in earlier comment.

and the Adwords UI has all together different results.

Thanks,
Chirag

**Comment by fiboknacky** [comment]
Hello Chirag,

My assumption is that your PHP timezone is not America/Chicago.
That's why when you create the date object with no timezone specified, it's defaulted to `PST8PDT`.

Cheers,
Knack

**Comment by chiragvels** [comment]
Hi @fiboknacky ,

Yes, It is not.
But I was asking for Final Result.
Why final result is different for the same date with same customer id.

With timezone added It is giving me 0 changes Done, but without timezone it is giving me 4 changes.
You can check both output array.

Thanks

**Comment by fiboknacky** [comment]
Hi Chirag,

If you pass the _same_ date time with different timezone, it's equivalent to passing the _different_ time with the same timezone.

For example, `PST8PDT` seems to be 3 hours behind `America/Chicago`.
If you pass `20170619 000000` without the timezone specified (equivalent to `PST8PDT`), it equals to passing `20170618 210000` in `America/Chicago` timezone.

In other words, it's the same as you're trying to compare:
```
$dateTimeRange->min = '20170618 210000 America/Chicago';
$dateTimeRange->max = '20170625 205959 America/Chicago';
```
with:
```
$dateTimeRange->min = '20170619 000000 America/Chicago';
$dateTimeRange->max = '20170625 235959 America/Chicago';
```

Provided the date times passed to the API are different, it's natural that you can get different results, isn't it?

Knack

**Comment by chiragvels** [comment]
Hello Knack,

Thanks for the clarification.

Yes, I got your point. 

Under Adwords UI timing shows for the changes are Jun 19, 2017 12:49:49 AM, Jun 19, 2017 12:51:29 AM.

So results with this dateTimeRange 
                   $dateTimeRange->min = '20170619 000000 America/Chicago';
                   $dateTimeRange->max = '20170619 235959 America/Chicago';
and with this dateTimeRange
                   $dateTimeRange->min = '20170618 210000';
                   $dateTimeRange->max = '20170619 205959';
will be same.

Please correct me If I am wrong.

Thanks,

**Comment by fiboknacky** [comment]
Hi Chirag,

> So results with this dateTimeRange
$dateTimeRange->min = '20170619 000000 America/Chicago';
$dateTimeRange->max = '20170619 235959 America/Chicago';
and with this dateTimeRange
$dateTimeRange->min = '20170618 210000';
$dateTimeRange->max = '20170619 205959';
will be same.

Looks correct. But please note that the default timezone is not recommend based on many sources.
And it can change in other PHP versions.

What I showed in the previous reply is just for demonstration purpose and was done manually.
So, I recommend to specify the timezone you'd like to get its data.
Let's not compare the results from different timezone if not necessary, as it can be error-prone.

Best,
Knack

**Comment by chiragvels** [comment]
Hello Knack,

Thanks for great help, all clear now.

Thanks,
