### ISSUE TITLE
 'cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by MichaLadewig** [googleads/googleads-php-lib#315]
Hello,

I am trying to rebuild our PHP scripts with the new Client. For that, i want to use my local deveolpement environment with XAMPP on Windows 7. 

Installing Composer and the AdWords API Package was no Problem. 

But when i try to start a changed Script, based on one of the Reporting Examples, i get the following Error:

Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\Users\ladewig\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 C:\Users\ladewig\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\Users\ladewig\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\Users\ladewig\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\Users\ladewig\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): Gu in C:\Users\ladewig\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

What i have done so far to fix the problem:

- changed php.ini to curl.cainfo = "C:\Internet\xampp\php\extras\ssl\cacert.pem" (That's exact the location of the file)
- changed php.ini to openssl.cafile = "C:\Internet\xampp\php\extras\ssl\cacert.pem"
- Checked if C:\windows\system32\curl-ca-bundle.crt exists (Windows) - Yes
- Checked if C:\windows\curl-ca-bundle.crt exists (Windows) - Yes
- put 2 dll files to windows\system32 (can't find the post anymore to give you the dll-names)

I am using XAMPP 3.2.1 with PHP 5.6.3

What else could be the problem or which Information do you need to do a deeper analysis of the Isue.

**Comment by fiboknacky** [comment]
Hello @MichaLadewig 

It looks like you've tried and verified many things already.
Another thing I can think of is to try injecting your CA file using [SoapSettingsBuilder::withSslCaFile()](https://github.com/googleads/googleads-php-lib/blob/9494f90d27ac041c4d5bdb93599f8add60c12929/src/Google/AdsApi/Common/SoapSettingsBuilder.php#L182). 
After setting that, you can create a custom SOAP settings object using [`build()`](https://github.com/googleads/googleads-php-lib/blob/9494f90d27ac041c4d5bdb93599f8add60c12929/src/Google/AdsApi/Common/SoapSettingsBuilder.php#L190).

Then, you can create an AdWordsSession using the created SOAP settings object in the previous step by using [`withSoapSettings()`](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L195)

Cheers,
Knack

**Comment by MichaLadewig** [comment]
Hello Knack,

thank you for your suggestion. Unfortunatly it doesn't work. But I don't know, if i implemented it correctly.

I added:

use Google\AdsApi\Common\SoapSettingsBuilder;

and my main function is:

 // Generate a refreshable OAuth2 credential for authentication.
    $oAuth2Credential = (new OAuth2TokenBuilder())
        ->fromFile('../adsapi_php.ini')
        ->build();

    
    $soapSettings = (new SoapSettingsBuilder())
        ->withSslCaFile('C:\Internet\xampp\php\extras\ssl\cacert.pem')
        ->build();
    // See: ReportSettingsBuilder for more options (e.g., suppress headers)
    // or set them in your adsapi_php.ini file.
    $reportSettings = (new ReportSettingsBuilder())
        ->fromFile('../adsapi_php.ini')
        ->includeZeroImpressions(false)
        ->build();

    // See: AdWordsSessionBuilder for setting a client customer ID that is
    // different from that specified in your adsapi_php.ini file.
    // Construct an API session configured from a properties file and the OAuth2
    // credentials above.
    $session = (new AdWordsSessionBuilder())
        ->fromFile('../adsapi_php.ini')
        ->withOAuth2Credential($oAuth2Credential)
        ->withReportSettings($reportSettings)
        ->withSoapSettings($soapSettings)
        ->build();

How can I check the Settings, the Script uses? Is there a Possibility to print all relevant settings? Maybe, i used a wrong php.ini or the settings are overwritten by another file or something like that.

**Comment by MichaLadewig** [comment]
I have also tried to add 

->disableSslVerify()

to the SoapSettingsBuilder, with no results.

**Comment by fiboknacky** [comment]
Hi @MichaLadewig 

`AdWordsSession` has a getter for all attributes, such as [getSoapSettings](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSession.php#L103).
Could you use this to inspect the values (e.g., using `var_dump`)?

Also, could you please try [this CA](https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt) from Mozilla (mentioned in the Guzzle [reference doc](http://docs.guzzlephp.org/en/stable/request-options.html#verify))

And what happen when you set `->disableSslVerify()`?
Nothing is shown?

Best,
Knack

**Comment by MichaLadewig** [comment]
->disableSslVerify() gives me the same cURL error 60

**Comment by MichaLadewig** [comment]
here are the Soap Settings, returned by getSoapSettings():

object(Google\AdsApi\Common\SoapSettings)#8 (8) { ["compressionLevel":"Google\AdsApi\Common\SoapSettings":private]=> NULL ["wsdlCacheType":"Google\AdsApi\Common\SoapSettings":private]=> NULL ["proxyHost":"Google\AdsApi\Common\SoapSettings":private]=> NULL ["proxyPort":"Google\AdsApi\Common\SoapSettings":private]=> NULL ["proxyUser":"Google\AdsApi\Common\SoapSettings":private]=> NULL ["proxyPassword":"Google\AdsApi\Common\SoapSettings":private]=> NULL ["sslVerify":"Google\AdsApi\Common\SoapSettings":private]=> bool(false) ["sslCaFile":"Google\AdsApi\Common\SoapSettings":private]=> string(43) "C:\Internet\xampp\php\extras\ssl\cacert.pem" }

**Comment by fiboknacky** [comment]
Is there any way to confirm that the SSL lib in your Windows environment work properly?
`->disableSslVerify()` is not recommended but once it's done, usually it should work.
This leads me to think about whether the SSL is installed properly.

**Comment by MichaLadewig** [comment]
the PHP info says:

OpenSSL/1.0.1i is installed and cURL is enabled.

**Comment by fiboknacky** [comment]
I can't think of other factors now. :(
If not too difficult, could you try our [deprecated branch](https://github.com/googleads/googleads-php-lib/tree/deprecated) too please?

Though the logic of using SSL is not exactly the same, the deprecated branch also relies on SSL.
So, at least we can verify that your SSL settings work.

Thanks in advance.

**Comment by fiboknacky** [comment]
And did you try obtaining certificates from Mozilla as suggested in [this comment](https://github.com/googleads/googleads-php-lib/issues/315#issuecomment-311596226)?

**Comment by MichaLadewig** [comment]
Hello Knack,

i am trying to migrate our old Projects to the new client. With the old client, there were never any Problems like this. 

Mozilla certificates is a new posibility. I will report the results. Thank you.

**Comment by fiboknacky** [comment]
Hello @MichaLadewig 

Yes, please let me know the result.
I once had an issue reported by Windows users too, but after they set the location of CA explicitly or disable SSL peer verification, they could make it work.

Knack

**Comment by MichaLadewig** [comment]
Looking in this Guzzle Reference doc, it is said, that the path to ca-bundle.crt File has to be /etc/pki/tls/certs/ca-bundle.crt. Because i am on Windows, the path doesn't exist. Does this File replace the cacert.pem? How do i use ca-bundle.crt?

**Comment by fiboknacky** [comment]
Based on [this section](http://docs.guzzlephp.org/en/stable/request-options.html#verify), it seems you have checked the following paths already:
* Check if C:\windows\system32\curl-ca-bundle.crt exists (Windows)
* Check if C:\windows\curl-ca-bundle.crt exists (Windows)

So, I don't think you need to care about /etc/pki/tls/certs/ca-bundle.crt as it's for unix.

Anyway, what's interesting to me now is, in the doc, there is a mentioning:
> you should consider setting the openssl.cafile environment variable to the path on disk to the file so that this entire process is skipped.

Looking back to your original post, it looks like you set `openssl.cafile` to `C:\Internet\xampp\php\extras\ssl\cacert.pem`.
Can you try setting this to `C:\windows\system32\curl-ca-bundle.crt` instead please?

And FYI, [this post](https://superuser.com/a/442797) looks similar to your case.

**Comment by MichaLadewig** [comment]
that caused a cURL error 77:

Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 77: error setting certificate verify locations: CAfile: C:\windows\system32\curl-ca-bundle.crt CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\Users\ladewig\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 C:\Users\ladewig\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\Users\ladewig\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\Users\ladewig\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\Users\ladewig\vendor\guz in C:\Users\ladewig\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

**Comment by fiboknacky** [comment]
Could you please check if the file is accessible by your script?

**Comment by MichaLadewig** [comment]
Maybe the CApath is required? Should it be C:\windows\system32?

**Comment by MichaLadewig** [comment]
Oh, it really could not be read

**Comment by fiboknacky** [comment]
Hello, 

Can you make your file readable yet?

Knack

**Comment by MichaLadewig** [comment]
for me, it is readable and even writeable.

But my colleague gave me an hint. Is it possible, that this problem occurs because i call that PHP-script via browser? He told me, he also hab problems to call a local file while starting a script via browser because the script could not see anything out of its webserver. Is it only possible to run a script via command line?

**Comment by fiboknacky** [comment]
Hi @MichaLadewig 

I don't think so, although our examples are needed to run via command line.
It looks like you would want to first verify if you can use your certificate with Guzzle.
Is it possible for you to [try Guzzle alone](http://docs.guzzlephp.org/en/stable/quickstart.html#making-a-request), so we can narrow down the issue?

Best,
Knack

**Comment by MichaLadewig** [comment]
Hi Knack,

i think, i figured out the problem. I am using Windows 7. In Win7 all requests to the windows\system32\ Folder seem to be redirected to Windows\SysWOW64\. So i put the curl-ca-bundle.crt there and got access to it.

Now, there is no cURL error anymore.

**Comment by fiboknacky** [comment]
Hello,

Great that you can find the solution now. :)

Knack

**Comment by uday1283** [comment]
Hi,

I have followed this thread very closely but with no success. I am running windows-8 with 32 bit OS.

Below is the error 

Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/
libcurl-errors.html)' in 
guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
Stack trace:
#0 \guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 \guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\
Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 \guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handle
r\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory) in \guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

**Comment by fiboknacky** [comment]
Have you followed [this guide](https://github.com/googleads/googleads-php-lib/wiki/Steps-for-troubleshooting-CA-file-issues)?
What step did you get stuck?

**Comment by uday1283** [comment]
I am getting this error while putting authentication code in command prompt. Can you help me in disabling SSL .. I have follow your above link but not getting where to put very bottom lines which are as below.
/*THIS I HAVE ALREADY DONE BUT STILL CURL ERROR*/
public function disableSslVerify()
    {
      //  $this->sslVerify = false;
	  $this->sslVerify = true;

        return $this;
    }
/************************************* WHERE TO PUT THESE BELOW LINES?
$oAuth2Credential = (new OAuth2TokenBuilder())
    ->fromFile()
    ->build();
$soapSettings = (new SoapSettingsBuilder())
    ->disableSslVerify()
    ->build();
$session = (new AdWordsSessionBuilder())
    ->fromFile()
    ->withSoapSettings($soapSettings)
    ->withOAuth2Credential($oAuth2Credential)
    ->build();


Thanks

**Comment by fiboknacky** [comment]
Your code is already correct, but you shouldn't change that line to true:
`$this->sslVerify = true;`.

In short, just do:

```php
$oAuth2Credential = (new OAuth2TokenBuilder())
    ->fromFile()
    ->build();
$soapSettings = (new SoapSettingsBuilder())
    ->disableSslVerify()
    ->build();
$session = (new AdWordsSessionBuilder())
    ->fromFile()
    ->withSoapSettings($soapSettings)
    ->withOAuth2Credential($oAuth2Credential)
    ->build();
```

**Comment by uday1283** [comment]
Hi 

Can you comment on above. We have placed this on our live server but still having same issue even after getting the token generated.

Thanks

**Comment by uday1283** [comment]
Hey Issue is now resolved.

I guess you need to mark this URL in your list specially for WAMP users.

#https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate

Thanks

**Comment by fiboknacky** [comment]
Thanks.
So, which reply in the link did you follow and can resolve this issue?
Is it [this one](https://stackoverflow.com/a/34883260)?
