### ISSUE TITLE
Get monthly search of one keyword

### ISSUE THREAD

**Issue by lucamagni** [googleads/googleads-php-lib#317]
Hi,
I have install php library and all work perfectly (there are errors only in path of autoload.php but it's easy to correct), I have only one question:
Is possible to get monthly search of only keyword that I pass to API? Because the example of GetKeywordsIdea works only for related keywords of my keyword, but I would take monthly search exactly of my keyword.
Many thanks,
Best regards

**Comment by fiboknacky** [comment]
Hello @lucamagni 

> Because the example of GetKeywordsIdea works only for related keywords of my keyword, but I would take monthly search exactly of my keyword.

Could you please paraphrase the above sentence? I don't get the part "take monthly search exactly of my keyword".

Alternatively, as this is related to product side, you can post the question on the [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api) as well. There're more people monitoring that forum and happy to answer your questions. :-)

Thanks.
Knack

**Comment by lucamagni** [comment]
Hi fiboknacky,
thanks for response and sorry for my bad english.
I try to explain with an example:
If I use API to get average number of searches about keyword "hello", I have this results:
hello song  -> 9.900
hello app -> 720
ecc..

But I would only this:
hello -> average number of searches.

So is there a possibility to performe an API call that display this result?

Many thanks.
Luca

**Comment by fiboknacky** [comment]
Hello Luca,

I'm glad to see that you get helped in the forum already. :)
So I'll close this issue.

Knack
