### ISSUE TITLE
Long AD_GROUP_ID (46481580951) is converted into integer(2147483647)

### ISSUE THREAD

**Issue by prashantmore321** [googleads/googleads-php-lib#319]
I used following code for adding Ad to a AdGroup using adword API.

////////////////////////////////////////////////////////////////////////////////////////////////

const AD_GROUP_ID = '46481580951';

    public static function runExample(AdWordsServices $adWordsServices, AdWordsSession $session, $adGroupId) {
        $adGroupAdService = $adWordsServices->get($session, AdGroupAdService::class);

        // Create the expanded Dynamic Search Ad. This ad will have its headline
        // and final URL auto-generated at serving time according to domain name
        // specific information provided by DynamicSearchAdsSetting at the
        // campaign level.
        $expandedDSA = new ExpandedDynamicSearchAd();
        // Set the ad description.
        $expandedDSA->setDisplayUrl('www.abc.com');
        $expandedDSA->setFinalUrls(['www.abc.com']);
$expandedDSA->setDescription('Dummy description');

        // Create the ad group ad.
        $adGroupAd = new AdGroupAd();
        $adGroupAd->setAdGroupId($adGroupId);
        $adGroupAd->setAd($expandedDSA);

        // Create the operation.
        $operation = new AdGroupAdOperation();
        $operation->setOperator(Operator::ADD);
        $operation->setOperand($adGroupAd);

        // Create the ad on the server and print some information.
        $result = $adGroupAdService->mutate([$operation]);
        $newAdGroupAd = $result->getValue()[0];
        $expandedDSA = $newAdGroupAd->getAd();
        printf(
                "Expanded Dynamic Search Ad with ID %d and description '%s' was"
                . " added.\n", $expandedDSA->getId(), $expandedDSA->getDescription()
        );
    }

//////////////////////////////////////////////////////////////////////////////

I got following error,

1- EntityNotFound.INVALID_ID @ operations[0].operand.adGroupId; trigger:'AdGroupId: 2147483647',    As my 
const AD_GROUP_ID = '46481580951'; is converted to integer.

**Comment by fiboknacky** [comment]
Hello,

I assume that your PHP is 32 bit and you ran our code example.
As it's 32 bit, your ID, which is larger than 32-bit max int, is converted to the max int, 2147483647. 

As stated in [README](https://github.com/googleads/googleads-php-lib#basic-usage), if you're using 32-bit PHP, please change `intval()` to `floatval()` when running them.

Cheers,
Knack

**Comment by prashantmore321** [comment]
Hello,

Thanks. It worked

Cheers,
Prashant
