### ISSUE TITLE
Update alpha dependency.

### ISSUE THREAD

**Issue by SamMousa** [googleads/googleads-php-lib#320]
Package google/auth has been released as `v1.0`; currently this library requires `^0.11`.

This should be checked for compatibility and after that updated.

**Comment by fiboknacky** [comment]
Thanks for reporting. Will check it out.

Knack

**Comment by jsonUK** [comment]
Hoping this gets fixed soon. Thanks!

**Comment by padalec** [comment]
Hi, there,  
I make some tests with GoogleAuth 1.0 and looks it's working correct, I used the examples:
1. GetRefreshToken.php - refresh token generated 
2. GetCampaigns.php - campaigns was returned

**Comment by fiboknacky** [comment]
This is fixed in [v29.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/29.0.0)
