### ISSUE TITLE
Customizable include path for the config file

### ISSUE THREAD

**Issue by lindelius** [googleads/googleads-php-lib#321]
Hey,

Being forced to place the config file in the home directory is far from ideal. It would be much better if the file path could be customizable somehow (via a public static property for example) so that you can keep the config files with the rest of the project.

**Comment by fiboknacky** [comment]
Hello @lindelius 

As stated in [README.md](https://github.com/googleads/googleads-php-lib#basic-usage), you can set your own path by using

```php
fromFile('/config/myprops.ini')
```

You can also set it programmatically using the following builders:
* OAuth2TokenBuilder
* AdWordsSessionBuilder
* DfpSessionBuilder

Best,
Knack

**Comment by lindelius** [comment]
@fiboknacky oh, there it is. My apologies. Not sure how we missed that.

**Comment by fiboknacky** [comment]
No worries. :)
