### ISSUE TITLE
SSL Certificate Issue

### ISSUE THREAD

**Issue by fammejias1** [googleads/googleads-php-lib#322]
I've followed the similar issues other users have had but can't seem to understand what the issue is:

Below is a print out of the SoapSettings, and the error I am gettings from Guzzle.  Don't understand why is not finding cert if its setting the sslCaFile correctly.
-----------------------------------------------
PS D:\Dev\WSPHP\budgetads> php .\UpdateCampaigns.php
CERT INFO: Google\AdsApi\Common\SoapSettings Object
(
    [compressionLevel:Google\AdsApi\Common\SoapSettings:private] =>
    [wsdlCacheType:Google\AdsApi\Common\SoapSettings:private] =>
    [proxyHost:Google\AdsApi\Common\SoapSettings:private] =>
    [proxyPort:Google\AdsApi\Common\SoapSettings:private] =>
    [proxyUser:Google\AdsApi\Common\SoapSettings:private] =>
    [proxyPassword:Google\AdsApi\Common\SoapSettings:private] =>
    [sslVerify:Google\AdsApi\Common\SoapSettings:private] => 1
    [sslCaFile:Google\AdsApi\Common\SoapSettings:private] => d:\dev\wsphp\budgetads\certs\curl-ca-bundle.crt
)
GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in file D:\Dev\WSPHP\budgetads\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187
Stack trace:
  1. GuzzleHttp\Exception\RequestException->() D:\Dev\WSPHP\budgetads\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
  2. GuzzleHttp\Handler\CurlFactory->createRejection() D:\Dev\WSPHP\budgetads\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:150
  3. GuzzleHttp\Handler\CurlFactory->finishError() D:\Dev\WSPHP\budgetads\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:103
  4. GuzzleHttp\Handler\CurlFactory->finish() D:\Dev\WSPHP\budgetads\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php:43
  5. GuzzleHttp\Handler\CurlHandler->__invoke() D:\Dev\WSPHP\budgetads\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php:28
  6. GuzzleHttp\Handler\Proxy->GuzzleHttp\Handler\{closure}() D:\Dev\WSPHP\budgetads\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php:51
  7. GuzzleHttp\Handler\Proxy->GuzzleHttp\Handler\{closure}() D:\Dev\WSPHP\budgetads\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php:66
  8. GuzzleHttp\PrepareBodyMiddleware->__invoke() D:\Dev\WSPHP\budgetads\vendor\guzzlehttp\guzzle\src\Middleware.php:30
  9. GuzzleHttp\Middleware->GuzzleHttp\{closure}() D:\Dev\WSPHP\budgetads\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php:70
 10. GuzzleHttp\RedirectMiddleware->__invoke() D:\Dev\WSPHP\budgetads\vendor\guzzlehttp\guzzle\src\Middleware.php:59
 11. GuzzleHttp\Middleware->GuzzleHttp\{closure}() D:\Dev\WSPHP\budgetads\vendor\guzzlehttp\guzzle\src\HandlerStack.php:67
 12. GuzzleHttp\HandlerStack->__invoke() D:\Dev\WSPHP\budgetads\vendor\guzzlehttp\guzzle\src\Client.php:277
 13. GuzzleHttp\Client->transfer() D:\Dev\WSPHP\budgetads\vendor\guzzlehttp\guzzle\src\Client.php:98
 14. GuzzleHttp\Client->sendAsync() D:\Dev\WSPHP\budgetads\vendor\guzzlehttp\guzzle\src\Client.php:106
 15. GuzzleHttp\Client->send() D:\Dev\WSPHP\budgetads\vendor\google\auth\src\HttpHandler\Guzzle6HttpHandler.php:34
 16. Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke() D:\Dev\WSPHP\budgetads\vendor\google\auth\src\OAuth2.php:492
 17. Google\Auth\OAuth2->fetchAuthToken() D:\Dev\WSPHP\budgetads\vendor\google\auth\src\Credentials\UserRefreshCredentials.php:92
 18. Google\Auth\Credentials\UserRefreshCredentials->fetchAuthToken() D:\Dev\WSPHP\budgetads\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\Util\OAuth2TokenRefresher.php:60
 19. Google\AdsApi\Common\Util\OAuth2TokenRefresher->getOrFetchAccessToken() D:\Dev\WSPHP\budgetads\vendor\googleads\googleads-php-lib\src\Google\AdsApi\AdWords\AdWordsHeaderHandler.php:63
 20. Google\AdsApi\AdWords\AdWordsHeaderHandler->generateHttpHeaders() D:\Dev\WSPHP\budgetads\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php:86
 21. Google\AdsApi\Common\AdsSoapClient->__soapCall() D:\Dev\WSPHP\budgetads\vendor\googleads\googleads-php-lib\src\Google\AdsApi\AdWords\v201705\cm\CampaignService.php:157
 22. Google\AdsApi\AdWords\v201705\cm\CampaignService->get() D:\Dev\WSPHP\budgetads\src\Downloader\AdWordsMetadataDownloader.php:63
 23. OFL\Downloader\AdWordsMetadataDownloader->GetReport() D:\Dev\WSPHP\budgetads\src\Downloader\AdWordsAbstractDownloader.php:156

HERE is how I set it up in code:
------------------------------------
	public function GetAdWordsSession() {
		// in order to add the cacert certificate
		$soapSettings = (new SoapSettingsBuilder())
			->withSslCaFile('d:\dev\wsphp\budgetads\certs\curl-ca-bundle.crt')
			->build();

		// Generate a refreshable OAuth2 credential for authentication.
		$oAuth2Credential = (new OAuth2TokenBuilder())
			->fromFile('adsapi_php.ini')
			->build();

		// Construct an API session configured from a properties file and the OAuth2
		// credentials above.
		$session = (new AdWordsSessionBuilder())
			->fromFile('adsapi_php.ini')
			->withOAuth2Credential($oAuth2Credential)
			->withClientCustomerId($this->clientCustomerId)
			->withSoapSettings($soapSettings)
			->build();		

		$soapSettingsRes = $session->getSoapSettings();
		
		print_r($soapSettingsRes);

		return $session;
	}

NOTE: the new library is working correctly locally (in my windows computers), with the exception of this certificate issue. 

NOTE: I want to resolve this issue locally before I deploy to PROD which is a hosted site. (non Windows)

NOTE:  I can add the curl.cainfo to my local PHP.INI file and everything works correctly.  But I am afraid of doing it this way as I won't have access to the PHP.INI on the hosted server.  So I am trying to get this to work thru code.   Is this the right approach or will the CERT issue be different on the hosted server.   In other words, is this a WINDOWS only issue?

Thank you, I appreciate your help.

**Comment by fiboknacky** [comment]
Hello @fammejias1 

>		->withSslCaFile('d:\dev\wsphp\budgetads\certs\curl-ca-bundle.crt')

Could you confirm again if this is the right part for your certificate?
In addition, could you please try a fresh new cert, e.g., from https://curl.haxx.se/docs/caextract.html?

And what is your PHP version?

Best,
Knack

**Comment by fammejias1** [comment]
That is the right location of the cert
Php Version is 7.1.1

I will try cert you provided.

**Comment by fiboknacky** [comment]
Also, does the same cert work if you put it in the `C:\windows\system32\` or `C:\windows\` _without_ setting the path in `SoapSettings` nor in the `php.ini`?
I know that you may worry about the permission on your host but let's verify this first. :)

**Comment by fammejias1** [comment]
NOTE:  I've only been able to get this to work if I put the cert using the php.ini file.

Any other method doesn't work for me: i.e.: putting the cert in c:\windows\system32\ or c:\windows or using the withSslCaFile() code above.

curl.cainfo = "D:\Dev\WSPHP\budgetads\certs\curl-ca-bundle.crt"

Not sure with the withSslCaFile() method is not working.

**Comment by fiboknacky** [comment]
Glad to hear that it works now.
In fact, your setting is also in the [listed locations](http://docs.guzzlephp.org/en/stable/request-options.html) of Guzzle too.
