### ISSUE TITLE
PHP Fatal error: SoapFault exception when pushing LineItems

### ISSUE THREAD

**Issue by ps613** [googleads/googleads-php-lib#323]
I have a tool that pushes changes to DFP Line items that was working fine until recently.  I haven't used it (or changed it) in a week or two, and this morning it stopped working and output SoapFault exceptions.  I've upgraded "googleads/googleads-php-lib" to the latest version 28.0.0 (from 27.1.0) as well as all the other dependencies but it doesn't help.  The error is generated by this block which pushes about 400 new LineItems to an empty Order: 

`$lineItemService = $dfpServices->get(Dfp::session(), LineItemService::class);
$newLines = [ /* Array of 400 LineItems */ ];

// Create the line items on the server.
try {
		$Lines = $lineItemService->createLineItems($newLines);
} catch (ApiException $Exception) {
		$ApiErrors = $Exception->getErrors();
		foreach ($ApiErrors as $Error) {
				printf("There was an error on the field '%s', caused by an invalid value '%s', with the error message '%s'\n",
						$Error->getFieldPath(),
						$Error->getTrigger(),
						$Error->getErrorString());
		}
}`

I added a catch{} for the SoapFault, the "code" was "0", the rest of the details are: 

`
PHP Fatal error:  Uncaught SoapFault exception: [soap:Server] null while invoking public abstract java.util.List com.google.ads.publisher.api.service.lineitem.LineItemService.createLineItems(java.util.List) throws com.google.ads.api.services.common.error.ApiException with params [[com.google.ads.publisher.api.service.lineitem.v201705.jaxbgen.LineItem@1dff0f5d, com.google.ads.publisher.api.service.lineitem.v201705.jaxbgen.LineItem@5a14db7d, com.google.ads.publisher.api.service.lineitem.v201705.jaxbgen.LineItem@4f064748, com.google.ads.publisher.api.service.lineitem.v201705.jaxbgen.LineItem@3f54eed1, com.google.ads.publisher.api.service.lineitem.v201705.jaxbgen.LineItem@5ab49b81, com.google.ads.publisher.api.service.lineitem.v201705.jaxbgen.LineItem@26077c99, com.google.ads.publisher.api.service.lineitem.v201705.jaxbgen.LineItem@5bc65316, com.google.ads.publisher.api.service.lineitem.v201705.jaxbgen.LineItem@43fc1cd9, com.google.ads.publisher.api.service.lineitem.v201705.jaxbgen.LineItem@3deaefb4, 
...
in  vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php on line 116
`
The error doesn't seem to be related to a timeout, it happens after about 4-5 minutes and the default timeout seems to be 10 minutes (600 seconds).  

Any clue why this error is suddenly happening with the above block? 

This happens consistently (I've tried many times this morning), and only this one function seems to be affected.  I've pushed Key/Values, Advertisers and Orders without issue.  We are using PHP 5.5.9 on Ubuntu.

**Comment by fiboknacky** [comment]
Hello @ps613 

This looks more like a server exception not from the lib itself.
Could you please post your question in the [DFP API Forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api), so experts in DFP API can help you more directly?

Thank you.

Cheers,
Knack

**Comment by ps613** [comment]
Yeah that's what I thought.  There is no mention of 'java' anywhere in my repo, I figured this was an error being returned by the API. 

I'll post in the API Forum. Thanks
