### ISSUE TITLE
Client is unauthorized to retrieve access tokens using this method

### ISSUE THREAD

**Issue by valetanddama** [googleads/googleads-php-lib#324]
I received an invitation to **adwords** and registered in the system under the mail some@gmail.com. Then I found the **developerToken** in the system and **clientCustomerId**. And on the developerToken's page, there was another email, but we're all in the same domain name. Then, under my mail, I created a project in the google console and created a service account key for it, for the project I allowed the **DCM / DFA Reporting And Trafficking API**. Then I registered all the data in **adsapi_php.ini**

```json
DeveloperToken = "bla-bla-bla"
ClientCustomerId = "bla-bla-bla"

JsonKeyFilePath = "jsonKeyFilePath.json"
Scopes = "https://www.googleapis.com/auth/adwords"
ImpersonatedEmail = "some@gmail.com"
```

And when I use the library
```php
$ OAuth2Credential = (new OAuth2TokenBuilder ())
            -> fromFile (jsonKeyFilePath.json)
            -> build ();

        $ Session = (new AdWordsSessionBuilder ())
            -> fromFile (jsonKeyFilePath.json)
            -> withOAuth2Credential ($ oAuth2Credential)
            -> build ();

        $ AdWordsServices = new AdWordsServices ();

        $ CampaignService = $ adWordsServices-> get ($ session, CampaignService :: class);

        $ Selector = new Selector ();
        $ Selector-> setFields (array ('Id', 'Name'));
        $ Selector-> setOrdering (array (new OrderBy ('Name', 'ASCENDING'))));
        $ Selector-> setPaging (new Paging (0, 100));

        $ Page = $ campaignService-> get ($ selector);
```

, I get an error

> Client error: `POST https: // www.googleapis.com / oauth2 / v4 / token` result in a` 401 Unauthorized` response:
>   {
>    "Error": "unauthorized_client",
>    "Error_description": "Client is unauthorized to retrieve access tokens using this me (truncated ...)

Could there be a reason that developerToken refers to one email, and the project to another email, although I received an invite from this email. What other reasons might there be?

**Comment by fiboknacky** [comment]
Hello,

Have you tried the steps in [this wiki](https://github.com/googleads/googleads-php-lib/wiki/API-access-using-own-credentials-(server-to-server-flow))? It includes links to detailed steps to setup the library and a project for service accounts. Note that to go this way, you need a [G Suite account](https://gsuite.google.com/).

> Then, under my mail, I created a project in the google console and created a service account key for it, for the project I allowed the DCM / DFA Reporting And Trafficking API

I'm afraid that DCM / DFA is not needed to using this library to access AdWords API.
So, I'd recommend to try following the steps I mentioned above.

Cheers,
Knack

**Comment by iamraphson** [comment]
@fiboknacky I have this error too.😩😫

**Comment by fiboknacky** [comment]
Hello @iamraphson 

Are you faced with the same error when following the steps in [this wiki](https://github.com/googleads/googleads-php-lib/wiki/API-access-using-own-credentials-(server-to-server-flow))?
Do you use exactly the same product and settings as valetanddama?

Thanks.
Knack

**Comment by iamraphson** [comment]
Hi @fiboknacky 

I have fixed the issue..Thanks a lot
