### ISSUE TITLE
adsapi_php.ini identification

### ISSUE THREAD

**Issue by bravafabrics** [googleads/googleads-php-lib#325]
Hi everyone,
It's been two days that i'm working to configure it.
Here the step I have followed : 
- Installer the google ads by using composer
- Get a customer ID and developper token (I had to create an other account and link it with my adwords account).
- Get the OAuth2 identification : so for that I went to my account (the one which i have the customer ID and developper token), I have created other credentials, finally get the client id and client secret. With these datas, I was able to get the refresh token.

Finally I have fulfill the customer id, developper token, client id, client secret and refresh token.
I have put the adsapi_php.ini in the folder : examples/AdsWords/v201705/BasicOperations/ with that new datas.
When I wanted to try if everything is ok, i execute for example GetCampaign.php and i got these error, trouble about the OAuth2 authentification : 

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'All of 'clientId', 'clientSecret', and 'refreshToken' must be set when using installed/web application flow.' in C:\wamp\www\google\googleads-php-lib\src\Google\AdsApi\Common\OAuth2TokenBuilder.php:204
Stack trace:
#0 C:\wamp\www\google\googleads-php-lib\src\Google\AdsApi\Common\OAuth2TokenBuilder.php(158): Google\AdsApi\Common\OAuth2TokenBuilder->validate()
#1 C:\wamp\www\google\googleads-php-lib\examples\AdWords\v201705\BasicOperations\GetCampaigns.php(77): Google\AdsApi\Common\OAuth2TokenBuilder->build()
#2 C:\wamp\www\google\googleads-php-lib\examples\AdWords\v201705\BasicOperations\GetCampaigns.php(89): Google\AdsApi\Examples\AdWords\v201705\BasicOperations\GetCampaigns::main()
#3 {main}
  thrown in C:\wamp\www\google\googleads-php-lib\src\Google\AdsApi\Common\OAuth2TokenBuilder.php on line 204
I'm just becoming crazy about that.
If you guys can help me, it will be so nice !
Enjoy your day !

**Comment by fiboknacky** [comment]
Hi @bravafabrics 

Have you put the `adsapi_php.ini` in _your home directory_ as mentioned in the [getting started guide](https://github.com/googleads/googleads-php-lib#getting-started)?
Step 2 is "Copy the sample adsapi_php.ini for your product to your home directory and fill out the required properties."

Best,
Knack

**Comment by bravafabrics** [comment]
Hi, 
Yes I have done it because if it's not the case, I will get the following message ; 
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Config file not found as specified: 'adsapi_php.ini' or in the home directory.

But I have a theory, do you think that it could be possible ? 
My theory is the developper token that I Have from my manager account is in Access Level : "Test Account". 
Is there any thing to do ? If it is in Test Account, error should be there ? 
Thank you for your time !

**Comment by fiboknacky** [comment]
Hi @bravafabrics 

> My theory is the developper  token that I Have from my manager account is in Access Level : "Test Account".
> Is there any thing to do ? If it is in Test Account, error should be there ?
> 

Even if your developer token is not approved yet, you should be able to issue a SOAP call against the test account.

The error message hints that some information (either client ID, secret, or refresh token) is missing.
So may I ask for the content of your `adsapi_php.ini` first?
Could you list up what you've put in the file (but please make sure to blind some parts of each entry as it's sensitive information)?

Thanks!

Knack

**Comment by funianrun** [comment]
@fiboknacky 
the getting started guide mentions the home directory but for noobs we have no clue what this means.  Is it my php folder, is it the project folder, is it the home computer folder ?

Very tricky to figure out without any examples

**Comment by thangduo** [comment]
Which OS are you using? Linux, Windows or Mac?

If you are using Linux or Mac, you can get to the Home folder by this
command:

cd ~

Please read more about this special folder here:
https://en.wikipedia.org/wiki/Home_directory


Thanks,
Thang Duong



Thang Duong | Developer Advocate | dcthang@google.com | 650-793-5832

**Comment by fiboknacky** [comment]
Close due to inactivity.

**Comment by mishraprabhat** [comment]
Hi there, 
I have been working on Google  Adwords APIs, and I am stuck on the similar issue here:
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Config file not found as specified: 'adsapi_php.ini'. Home directory could not be located so it was not searched.'

I have added the adsapi_php.ini on my root directory (i.e, /home/username for linux in my case) with required credentials, i.e., developerToken, client customer ID, client ID, client Secret and refreshToken.  

Please help 

Thank you 
Prabhat

**Comment by fiboknacky** [comment]
Hi Prabhat,

Could you check what's the result of [`getHome()`](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/Util/EnvironmentalVariables.php#L36) in your environment?

Best,
Knack

**Comment by mishraprabhat** [comment]
HI @fiboknacky ,

Thank you for getting back to me so quick :)

Here is the error I am getting when I run the [getHome()](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/Util/EnvironmentalVariables.php#L36) function:
 PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'Could not locate home directory.

Best
Prabhat

**Comment by fiboknacky** [comment]
What linux and its version are you using? It's a bit strange that it doesn't have environment variables that we can use to find its home.
As a workaround, you can pass the path to your config file directly, as we show in [README](https://github.com/googleads/googleads-php-lib#basic-usage).

In short, use `fromFile()`  of both [AdWordsSessionBuilder](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L104) and [OAuth2TokenBuilder](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/OAuth2TokenBuilder.php#L59) to specify the location of config file.

Best,
Knack

**Comment by matteoFeduzi** [comment]
Hi, I also have the same problem. Can anyone help me?

I would like to use the Google AdWords APIs on my site and of course I am installing them on my web server.

The problem I get is the following:

"Fatal error: Uncaught InvalidArgumentException: Config file not found as specified: 'adsapi_php.ini'. Home directory could not be located so it was not searched. in....."

I installed the library using the composer command and inserted it directly under the folder of my WordPress theme.

Maybe I have to put everything under the public_html directory, I've already tried it but it doesn't work.

Best regards.

**Comment by dsaha1656** [comment]
try this 
```
$oAuth2Credential = (new OAuth2TokenBuilder())
        ->fromFile(__DIR__."/adsapi_php.ini")
        ->build();
```

**fromFile** takes a parameter with the file location

**Comment by thangduo** [comment]
Would it be better if we would allow you to specify a custom location of the `adsapi_php.ini` file via a new system variable?

**Comment by thangduo** [comment]
The solution is to use the fromFile function and pass an explicit path to load the adsapi_php.ini file as @dsaha1656 commented above.

Adding an environment variable is an optional but useful technique for the same code to run on different environment (such as inside a container). You can apply this technique in your application without waiting for us to support it. I am closing this issue now because it already has a working solution.
