### ISSUE TITLE
Problem with the google/auth package when running several google libraries at the same time

### ISSUE THREAD

**Issue by pdolinaj** [googleads/googleads-php-lib#326]
I am trying to run these 3 packages at the same time but due to the google/auth compatibility issue I can't:

composer require google/apiclient
OK

composer require googleads/googleads-php-lib
OK

composer require google/cloud

Problem 1
    - Can only install one of: google/auth[v1.0, v0.11.1].
    - Can only install one of: google/auth[v1.0, v0.11.1].
    - Can only install one of: google/auth[v1.0, v0.11.1].
    - google/apiclient v2.2.0 requires google/auth ^1.0 -> satisfiable by google/auth[v1.0].
    - Installation request for google/apiclient ^2.2 -> satisfiable by google/apiclient[v2.2.0].
    - Installation request for google/auth (locked at v0.11.1) -> satisfiable by google/auth[v0.11.1].

**Comment by fiboknacky** [comment]
Hello @pdolinaj 

We're testing the compatibility of google/auth v1.0 with our library.
If no problems, we'll update the `composer.json` to use v1.0, which will be the same as google/cloud.

This is already tracked at #320, so I'll close this issue soon.

 Best,
Knack
