### ISSUE TITLE
I should navigate to examples/GetRefreshToken.php, but you ignore it

### ISSUE THREAD

**Issue by OskarStark** [googleads/googleads-php-lib#327]
Installing this library via composer, does not have `GetRefreshToken.php`

see here: https://github.com/googleads/googleads-php-lib/blob/master/.gitattributes#L3

If it is an Example, fine, but if its needed to setup the lib it shouldn't be under `examples/` folder

**Comment by fiboknacky** [comment]
Hello @OskarStark 

Thanks for your feedback.
We're considering about this for a long term.

For now, sorry for your inconvenience, but please use `git checkout` to fetch that file or download the example as instructed [here](https://github.com/googleads/googleads-php-lib#downloading-a-compressed-tarball).
I'll update our wiki so this is clearer.

Please note that the `GetRefreshToken` file is probably needed only when you'd like to get refresh tokens  for the first time. 
In production environments, it's not required to run the library.

Cheers,
Knack

**Comment by OskarStark** [comment]
Hi @fiboknacky, first of all, thank you for your feedback.

I am currently refactoring a legacy project, which used the `6.1.0` version
and it changes a lot, as I am now using version `28.0`. Great work so far,
I like the direction of the way you are doing things in this project.

Thank you for making it clearer 👍

IMO it should not be a problem to rename `examples/` to `tools/` and ship
it with the releases, or consider adding a `tools.phar` file which provides
some help for developers. If you like I can support you

Have a good day 🌞  Cheers, Oskar

PS: One small problem with the `GetRefreshToken.php`, I temporary installed
`dev-master` via composer in a symfony project and the include for the
`autoload.php`was wrong. Same for the other examples. Maybe you can check
this on your own. If you need more detailed feedback, don't hesitate to
contact me 👍

**Comment by fiboknacky** [comment]
Hello Oskar,

Thanks a lot for useful feedback. :)

> I am currently refactoring a legacy project, which used the `6.1.0` version

Thanks for being an old fan of our library.

> IMO it should not be a problem to rename `examples/` to `tools/` and ship
> it with the releases, or consider adding a `tools.phar` file which provides
> some help for developers. If you like I can support you

That's one good direction that we can consider too.
We may not rename the `examples/` directory to `tools/` directly as there are many other files that are really examples.
But separating `GetRefreshToken` (and other tools-like files) into another directory and ship them with `src/` is one of our consideration.

 
> PS: One small problem with the `GetRefreshToken.php`, I temporary installed
> `dev-master` via composer in a symfony project and the include for the
> `autoload.php`was wrong.

First, thanks for your offering. :) We're really welcome any contributions from developers, not limited to only this topic. So if you wish to submit pull requests, please feel free to do so.

As for the path to `autoload` itself, could you please clarify more?
We've recently updated the distribution method of examples and added [this section](https://github.com/googleads/googleads-php-lib#running-examples) to README.
I've tested that if we follow the section (either by using the `git clone` or `tarball`), the path to `autoload` is correct.

Cheers,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity. If you have more suggestion, feel free to add more.
