### ISSUE TITLE
Finer control over dependencies

### ISSUE THREAD

**Issue by brstgt** [googleads/googleads-php-lib#329]
As long as I use composer, I have to include ALL services and versions if I only want to access a single service / endpoint from a single version.
This is a MASSIVE overkill.
Why don't you create composer deps/packages for each version and or service (AdWords, DFP) and maybe a target to include all services for backward compat?

It really sucks to add thousands (6372 !!) of files for a single API request.

**Comment by fiboknacky** [comment]
Hello @brstgt 

Thanks for your feedback.
As far as I see, it's not trivial to separate them as a separate composer project, while maintaining the library's versions in sequence.

> Why don't you create composer deps/packages for each version and or service (AdWords, DFP) and maybe a target to include all services for backward compat?

Could you please specify more in detail what's your suggested approach that you've mentioned above?

Best,
Knack

**Comment by fiboknacky** [comment]
I'll close this as we now discuss in #342 instead.
