### ISSUE TITLE
[ManagedCustomerServiceError.NOT_AUTHORIZED @ operations[0]]

### ISSUE THREAD

**Issue by aswinda** [googleads/googleads-php-lib#330]
![capture](https://user-images.githubusercontent.com/5094198/28367413-0dc1b7e0-6cbb-11e7-9233-502e81bc1fc1.PNG)

`$oAuth2Credential = (new OAuth2TokenBuilder)
            ->withClientId('xxxxx')
            ->withClientSecret('xxxx')
            ->withRefreshToken($users[0]->refresh_token)
            ->build();

        $adwSession = (new AdWordsSessionBuilder)
            ->withDeveloperToken('xxxx')
            ->withUserAgent('xxxxx')
            ->withClientCustomerId('xxx')
            ->withOAuth2Credential($oAuth2Credential)
            ->build();

        $this->createAccount(new AdWordsServices(), $adwSession, $request->input('customer_name'), $request->input('phone'));

    }

    public function createAccount(AdWordsServices $adWordsServices,
      AdWordsSession $session, $customerName, $phone) {
        $managedCustomerService =
        $adWordsServices->get($session, ManagedCustomerService::class);
        
        // Create a managed customer.
        $customer = new ManagedCustomer();
        $customer->setName('Aswinda Prima Putra#08985276363');
        $customer->setCurrencyCode('IDR');
        $customer->setDateTimeZone('WIB');
    
        // Create a managed customer operation and add it to the list.
        $operations = [];
        $operation = new ManagedCustomerOperation();
        $operation->setOperator(Operator::ADD);
        $operation->setOperand($customer);
        $operations[] = $operation;

        // Create a managed customer on the server and print out some information
        // about it.
        $customer = $managedCustomerService->mutate($operations)->getValue()[0];
        printf("Account with customer ID %d was created.\n",
            $customer->getCustomerId());
    }`

why iam getting this error ? Thank you

**Comment by fiboknacky** [comment]
Hello,

Have you used the refresh token that is authorized to manage the account you specified?
Please review [this section](https://developers.google.com/adwords/api/docs/guides/first-api-call#get_an_oauth2_refresh_token_and_configure_your_client) for more information.

Best,
Knack

**Comment by aswinda** [comment]
Hi @fiboknacky  thanks for the reply

yes i already following the guide at that page
is there any way that i could debug my code like try catch or something so i know the detail about what error that i'm facing

Thanks

**Comment by fiboknacky** [comment]
Hi @aswinda 

That's probably the detail of the error this time already.
One quick way to resolve this is to generate a new refresh token.
Please make sure you've logged in as a user ([step 4 in this guide](https://github.com/googleads/googleads-php-lib/wiki/%5BDeprecated,-old-library%5D-API-access-using-own-credentials-(installed-application-flow)#step-2---setting-up-the-client-library)) that has access to the account you're issuing requests against.

Best,
Knack
