### ISSUE TITLE
get account hierarchy is not returning all accounts

### ISSUE THREAD

**Issue by scamexdotexe** [googleads/googleads-php-lib#332]
It should return more or less 31 accounts (parent and child) but unexpectedly it return only 12.

I'm using this particular code from the example (returns 12): 
```
private static function printAccountHierarchy($account,
      $customerIdsToAccounts, $customerIdsToChildLinks, $depth = null) {
    if ($depth === null) {
      print "(Customer ID, Account Name)<br>";
      self::printAccountHierarchy(
          $account, $customerIdsToAccounts, $customerIdsToChildLinks, 0);
      return;
    }

    print str_repeat('-', $depth * 2);
    $customerId = $account->getCustomerId();
    printf("%s, %s<br>", $customerId, $account->getName());

    if (array_key_exists($customerId, $customerIdsToChildLinks)) {
      foreach ($customerIdsToChildLinks[$customerId] as $childLink) {
        $childAccount =
            $customerIdsToAccounts[$childLink->getClientCustomerId()];
        self::printAccountHierarchy($childAccount, $customerIdsToAccounts,
            $customerIdsToChildLinks, $depth + 1);
      }
    }
  }
```
But if I try to use this plain code to display accounts, it will return 31 accounts.

foreach ($customerIdsToAccounts as $account) {
echo $account->getName() . '<br>';
}

What did I missed here?  Thanks

**Comment by fiboknacky** [comment]
Could you give your highest manager account ID?

Knack

**Comment by scamexdotexe** [comment]
1155835314

**Comment by scamexdotexe** [comment]
Thank you for your reply :+1:

**Comment by scamexdotexe** [comment]
is it okay to post account id?

**Comment by fiboknacky** [comment]
I got that for investigation already so you can delete it. (It seems you did already though).
Will have a look soon.

Cheers,
Knack

**Comment by scamexdotexe** [comment]
Oh okay. Thanks.

**Comment by fiboknacky** [comment]
Hi @scamexdotexe 

Unfortunately, I can't reproduce the issue. On my side, the [GetAccountHierarchy](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201705/AccountManagement/GetAccountHierarchy.php) example produces 31 accounts as expected.

Did it output only 12 accounts on your side when you run the example as is?

Best,
Knack

**Comment by scamexdotexe** [comment]
Yes. We're wondering why because we tried the example first but it is only returning 12 accounts. We enabled logging and turned logging as information, I think we got 31 accounts but the output was the same 12, accounts.

**Comment by scamexdotexe** [comment]
I mean in the logs we can see that there are 31 accounts in total but page output is different.

**Comment by fiboknacky** [comment]
If you set `withClientCustomerId()` correctly, it should return 31 accounts.

One more thing that you might want to try is to regenerate a refresh token and ensure again that the token has access to the highest manager account ID.

Best,
Knack

**Comment by scamexdotexe** [comment]
I've tried that. One strange thing is the array $customerIdsToChildLinks has negative index. (e.g. --6031450078). This is I think causing the problem.

**Comment by scamexdotexe** [comment]
or key (negative key)

**Comment by scamexdotexe** [comment]
Casting the customer id to string seems working for now:

`$customerIdsToChildLinks[(String)$link->getManagerCustomerId()][] = $link;`

```
 if (array_key_exists((String)$customerId, $customerIdsToChildLinks)) {
      foreach ($customerIdsToChildLinks[(String)$customerId] as $childLink) {
        $childAccount =
            $customerIdsToAccounts[$childLink->getClientCustomerId()];
        printAccountHierarchy($childAccount, $customerIdsToAccounts,
            $customerIdsToChildLinks, $depth + 1);
      }
    
  
}
```

This is what my code looks and it works for the time being.

**Comment by fiboknacky** [comment]
It looks like you're using PHP 32-bit (or on Windows)?
Perhaps, this gets casted wrongly during it's assigned as an array key.

Knack

**Comment by scamexdotexe** [comment]
I'm on Windows. Yes, I suspect too that is the case. Thanks for your help. 

John.
