### ISSUE TITLE
GetCampaigns.php running on terminal but giving an error while running on web browser

### ISSUE THREAD

**Issue by adhippatil** [googleads/googleads-php-lib#333]
Hello AdWords API team,
I am running 'GetCampaigns.php' from terminal ,it is showing the list of campaigns. But when I ran it on web browser, it is giving me an error :
Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl" in /opt/lampp/htdocs/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php:65 Stack trace: #0 /opt/lampp/htdocs/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(65): SoapClient->SoapClient('https://adwords...', Array) #1 /opt/lampp/htdocs/googleads-php-lib/src/Google/AdsApi/AdWords/v201705/cm/CampaignService.php(145): Google\AdsApi\Common\AdsSoapClient->__construct('https://adwords...', Array) #2 [internal function]: Google\AdsApi\AdWords\v201705\cm\CampaignService->__construct(Array) #3 /opt/lampp/htdocs/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(39): ReflectionClass->newInstanceArgs(Array) #4 /opt/lampp/htdocs/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClientFactory.php(86): Google\AdsApi\Common\Util\Refl in /opt/lampp/htdocs/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php on line 65

What should I do to see it running in the web browser also? Please help me!

**Comment by fiboknacky** [comment]
Hello @adhippatil 

First, our code examples are meant to run in command prompt only as stated [here](https://github.com/googleads/googleads-php-lib#basic-usage).
So, if you run it on the webpage, you may not see the result as usual.

Despite that, the error message above looks like a separate problem.
It seems the WSDLs can't be accessed from your server.
Could you please check if you have any firewall or settings that prevent the access?

One thing that you can check if to use `curl` or `wget` to fetch the content from https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl in your server.
You can also try opening the link in the browser to check as well.

Best,
Thanet, AdWords API Team

**Comment by adhippatil** [comment]
Hello Thanet,
Thanks for the reply. I hit the url https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl in my browser, I am seeing this XML file
![xml_file](https://user-images.githubusercontent.com/8168026/28774740-7bb4cf76-760c-11e7-8d9a-a5a4659d5c54.png)
I am using ubuntu 14.04 o/s on my pc

**Comment by fiboknacky** [comment]
Hello @adhippatil

Sorry for late reply.
We don't have examples that run on the browser directly but it should be straightforward to adapt from the existing ones. You can extract a part of [runExample()](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201708/BasicOperations/GetCampaigns.php#L38) and put it in your function to show results on the web page.

Based on the result you've shown to us, it looks like your computer can access the AdWords API servers and WSDL files, so this wouldn't be a problem of connectivity.

Best,
Knack

**Comment by theainz** [comment]
Hi Knack,

Can you expand a little on the comment about runExample and getting the code to work in a browser please?

Thanks, Neil

**Comment by fiboknacky** [comment]
Hi Neil,

Sure I'm considering that too.

Knack

**Comment by theainz** [comment]
Thanks, to be honest, I'm not sure how else I would run it in my programs to work out what's working / not working & develop something useful. :-/
