### ISSUE TITLE
Failed to connect to www.googleapis.com port 443: Timed out

### ISSUE THREAD

**Issue by yhdengctrip** [googleads/googleads-php-lib#335]
Hi Adwords API team,
     I unable to connect to google api server by using proxy.

     I setting the proxy host and port in the adsapi_php.ini, like below:

   [PROXY]
; Optional proxy settings to be used by SOAP requests.
host = "http://proxyurl.com"
port = 8080
; user = "<USER>"
; password = "<PASSWORD>"

and I run the script , it response:
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed to connect to www.googleapis.com port 443: Timed out
(see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in D:\work\project\job_test\tasks-job\Google\Adwords\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:18
6
Stack trace:
#0 D:\work\project\job_test\tasks-job\Google\Adwords\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Objec
t(GuzzleHttp\Handler\EasyHandle), Array)
#1 D:\work\project\job_test\tasks-job\Google\Adwords\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(Gu
zzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))

#2 D:\work\project\job_test\tasks-job\Google\Adwords\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHt
tp\Handler\CurlHandler), Object(GuzzleHttp\Handler\ in D:\work\project\job_test\tasks-job\Google\Adwords\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line
 186

Fatal error: Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed to connect to www.googleapis.com port 443: Timed out (see
http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in D:\work\project\job_test\tasks-job\Google\Adwords\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:186
Stack trace:
#0 D:\work\project\job_test\tasks-job\Google\Adwords\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Objec
t(GuzzleHttp\Handler\EasyHandle), Array)
#1 D:\work\project\job_test\tasks-job\Google\Adwords\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(Gu
zzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 D:\work\project\job_test\tasks-job\Google\Adwords\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHt
tp\Handler\CurlHandler), Object(GuzzleHttp\Handler\ in D:\work\project\job_test\tasks-job\Google\Adwords\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line
 186

  but when I using  CURLOPT_PROXY to test request www.googleapis.com with this proxy, it can response right.

Did I miss the setting?

Thank you.

**Comment by fiboknacky** [comment]
Hello,

Could you please give more details how you used CURLOPT_PROXY for testing?

Best,
Knack

**Comment by yhdengctrip** [comment]
Hello:

Below is the curl I use:

  $curl = curl_init('www.googleapis.com');
    curl_setopt($curl, CURLOPT_HEADER, 1);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($curl, CURLOPT_TIMEOUT, 30);
    curl_setopt($curl, CURLOPT_PROXY, 'http://hkproxy.cn1.global.ctrip.com:8080');

    $R = curl_exec($curl);
    $info = curl_getinfo($curl);
    curl_close($curl);

    print_r($info);
    print_r($R);


The proxy http://hkproxy.cn1.global.ctrip.com:8080  is only can used in our Company Intranet.

And it responsed:
Array
(
    [url] => http://www.googleapis.com/
    [content_type] => text/html; charset=UTF-8
    [http_code] => 404
    [header_size] => 567
    [request_size] => 112
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.078
    [namelookup_time] => 0
    [connect_time] => 0.015
    [pretransfer_time] => 0.015
    [size_upload] => 0
    [size_download] => 9
    [speed_download] => 115
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 0.078
    [redirect_time] => 0
    [redirect_url] =>
    [primary_ip] => 10.9.128.29
    [certinfo] => Array
        (
        )

    [primary_port] => 8080
    [local_ip] => 10.32.85.121
    [local_port] => 15499
)
HTTP/1.1 404 Not Found
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 02 Aug 2017 07:34:45 GMT
Vary: X-Origin
Content-Type: text/html; charset=UTF-8
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Accept-Ranges: none
Vary: Origin,Accept-Encoding
X-Cache: MISS from fqsquidproxy
X-Cache-Lookup: MISS from fqsquidproxy:8080
Transfer-Encoding: chunked
Via: 1.1 fqsquidproxy (squid/3.5.20)
Connection: keep-alive

Not Found

发件人: Thanet Knack Praneenararat [mailto:notifications@github.com]
发送时间: 2017年8月2日 15:27
收件人: googleads/googleads-php-lib <googleads-php-lib@noreply.github.com>
抄送: dyh邓怡辉(Will Deng) <yhdeng@Ctrip.com>; Author <author@noreply.github.com>
主题: Re: [googleads/googleads-php-lib] Failed to connect to www.googleapis.com port 443: Timed out (#335)


Hello,

Could you please give more details how you used CURLOPT_PROXY for testing?

Best,
Knack

**Comment by yhdengctrip** [comment]
发件人: dyh邓怡辉(Will Deng)
发送时间: 2017年8月2日 15:38
收件人: 'googleads/googleads-php-lib' <reply@reply.github.com>; googleads/googleads-php-lib <googleads-php-lib@noreply.github.com>
抄送: Author <author@noreply.github.com>
主题: 答复: [googleads/googleads-php-lib] Failed to connect to www.googleapis.com port 443: Timed out (#335)

Hello:

Below is the curl I use:

  $curl = curl_init('www.googleapis.com');
    curl_setopt($curl, CURLOPT_HEADER, 1);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($curl, CURLOPT_TIMEOUT, 30);
    curl_setopt($curl, CURLOPT_PROXY, 'http://proxyurl:8080');

    $R = curl_exec($curl);
    $info = curl_getinfo($curl);
    curl_close($curl);

    print_r($info);
    print_r($R);


The proxy http://proxyurl:8080  is only can used in our Company Intranet.

And it responsed:
Array
(
    [url] => http://www.googleapis.com/
    [content_type] => text/html; charset=UTF-8
    [http_code] => 404
    [header_size] => 567
    [request_size] => 112
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.078
    [namelookup_time] => 0
    [connect_time] => 0.015
    [pretransfer_time] => 0.015
    [size_upload] => 0
    [size_download] => 9
    [speed_download] => 115
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 0.078
    [redirect_time] => 0
    [redirect_url] =>
    [primary_ip] => 10.9.128.29
    [certinfo] => Array
        (
        )

    [primary_port] => 8080
    [local_ip] => 10.30.15.121
    [local_port] => 15499
)
HTTP/1.1 404 Not Found
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 02 Aug 2017 07:34:45 GMT
Vary: X-Origin
Content-Type: text/html; charset=UTF-8
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Accept-Ranges: none
Vary: Origin,Accept-Encoding
X-Cache: MISS from fqsquidproxy
X-Cache-Lookup: MISS from fqsquidproxy:8080
Transfer-Encoding: chunked
Via: 1.1 fqsquidproxy (squid/3.5.20)
Connection: keep-alive

Not Found

发件人: Thanet Knack Praneenararat [mailto:notifications@github.com]
发送时间: 2017年8月2日 15:27
收件人: googleads/googleads-php-lib <googleads-php-lib@noreply.github.com<mailto:googleads-php-lib@noreply.github.com>>
抄送: dyh邓怡辉(Will Deng) <yhdeng@Ctrip.com<mailto:yhdeng@Ctrip.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
主题: Re: [googleads/googleads-php-lib] Failed to connect to www.googleapis.com<http://www.googleapis.com> port 443: Timed out (#335)


Hello,

Could you please give more details how you used CURLOPT_PROXY for testing?

Best,
Knack

**Comment by yhdengctrip** [comment]
Hello:

Below is the curl I use:

  $curl = curl_init('www.googleapis.com');
    curl_setopt($curl, CURLOPT_HEADER, 1);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($curl, CURLOPT_TIMEOUT, 30);
    curl_setopt($curl, CURLOPT_PROXY, 'http://proxyurl:8080');

    $R = curl_exec($curl);
    $info = curl_getinfo($curl);
    curl_close($curl);

    print_r($info);
    print_r($R);


The proxy http://proxyurl:8080  is only can used in our Company Intranet.

And it responsed:
Array
(
    [url] => http://www.googleapis.com/
    [content_type] => text/html; charset=UTF-8
    [http_code] => 404
    [header_size] => 567
    [request_size] => 112
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.078
    [namelookup_time] => 0
    [connect_time] => 0.015
    [pretransfer_time] => 0.015
    [size_upload] => 0
    [size_download] => 9
    [speed_download] => 115
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 0.078
    [redirect_time] => 0
    [redirect_url] =>
    [primary_ip] => 10.9.128.29
    [certinfo] => Array
        (
        )

    [primary_port] => 8080
    [local_ip] => 10.30.15.121
    [local_port] => 15499
)
HTTP/1.1 404 Not Found
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 02 Aug 2017 07:34:45 GMT
Vary: X-Origin
Content-Type: text/html; charset=UTF-8
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Accept-Ranges: none
Vary: Origin,Accept-Encoding
X-Cache: MISS from fqsquidproxy
X-Cache-Lookup: MISS from fqsquidproxy:8080
Transfer-Encoding: chunked
Via: 1.1 fqsquidproxy (squid/3.5.20)
Connection: keep-alive

Not Found

发件人: Thanet Knack Praneenararat [mailto:notifications@github.com]
发送时间: 2017年8月2日 15:27
收件人: googleads/googleads-php-lib <googleads-php-lib@noreply.github.com<mailto:googleads-php-lib@noreply.github.com>>
抄送: dyh邓怡辉(Will Deng) <yhdeng@Ctrip.com<mailto:yhdeng@Ctrip.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
主题: Re: [googleads/googleads-php-lib] Failed to connect to www.googleapis.com<http://www.googleapis.com> port 443: Timed out (#335)


Hello,

Could you please give more details how you used CURLOPT_PROXY for testing?

Best,
Knack

**Comment by yhdengctrip** [comment]
Hello:

Below is the curl I use:

  $curl = curl_init('www.googleapis.com');
    curl_setopt($curl, CURLOPT_HEADER, 1);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($curl, CURLOPT_TIMEOUT, 30);
    curl_setopt($curl, CURLOPT_PROXY, 'http://proxyurl:8080');
    
    $R = curl_exec($curl);
    $info = curl_getinfo($curl);
    curl_close($curl);
    
    print_r($info);
    print_r($R);


The proxy http://proxyurl:8080  is only can used in our Company Intranet.

And it responsed:
Array
(
    [url] => http://www.googleapis.com/
    [content_type] => text/html; charset=UTF-8
    [http_code] => 404
    [header_size] => 567
    [request_size] => 112
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.078
    [namelookup_time] => 0
    [connect_time] => 0.015
    [pretransfer_time] => 0.015
    [size_upload] => 0
    [size_download] => 9
    [speed_download] => 115
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 0.078
    [redirect_time] => 0
    [redirect_url] =>
    [primary_ip] => 10.9.128.29
    [certinfo] => Array
        (
        )

    [primary_port] => 8080
    [local_ip] => 10.30.15.121
    [local_port] => 15499
)
HTTP/1.1 404 Not Found
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 02 Aug 2017 07:34:45 GMT
Vary: X-Origin
Content-Type: text/html; charset=UTF-8
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Accept-Ranges: none
Vary: Origin,Accept-Encoding
X-Cache: MISS from fqsquidproxy
X-Cache-Lookup: MISS from fqsquidproxy:8080
Transfer-Encoding: chunked
Via: 1.1 fqsquidproxy (squid/3.5.20)
Connection: keep-alive

Not Found

**Comment by fiboknacky** [comment]
Hi,

Based on the latest reply, unlike your original message, it seems that CURLOPT_PROXY doesn't work well too.
Could you please confirm?

Best,
Knack

**Comment by fiboknacky** [comment]
Sorry, I misunderstood that you meant the error code was 200. Please ignore my last reply.

In `adsapi_php.ini`, could you please change the `endpoint` to use `http://` (not `https://`)?
```
 endpoint = "http://adwords.google.com:443"
```

I've found that some proxies handle the SSL for us already, so specifying the `https://` makes it not work properly.

**Comment by yhdengctrip** [comment]
Hi fiboknacky,
  sorry for rely late.
   I have setting the endpoint = "http://adwords.google.com:443".
   The response results is different, but still is can not connecting server by using proxy.

 
`Error:
Error creating resource: [message] fopen(http://adwords.google.com:443/api/adwords/reportdownload/v201705): failed to open stream: 由于连接方在一段时间后没有正确答复
或连接的主机没有反应，连接尝试失败。

[file] D:\work\project\job_test\tasks-job\Google\Adwords\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 324

PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Error creating resource: [message] fopen(http://adwords.google.com:443/api/adwords/reportdownlo
ad/v201705): failed to open stream: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。`

**Comment by fiboknacky** [comment]
Hello @yhdengctrip,

It looks like you're using reporting, right?
If so, unfortunately, setting of proxy via `adsapi_php.ini` file is not supported yet.
I'm working on this so it can be used in reporting as well.

For now, could you try setting the proxy of Guzzle directly by adding the following after [this line](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/Reporting/v201705/ReportDownloader.php#L139)?
```php
     $requestOptions[RequestOptions::PROXY] = 'localhost:999' ;
```

If it still doesn't work, could you please try:
```php
     $requestOptions[RequestOptions::PROXY] = [
         'https' => 'localhost:999'
     ];
```
and specify endpoint in `adsapi_php.ini` as `http://adwords.google.com` (not `https://` and no `:443`)

Best,
Knack

**Comment by yhdengctrip** [comment]
Hello @Knack,
   Yes, I using it for reporting. 

   I reset the endpoint as you said:

`   endpoint = "http://adwords.google.com"`

 and add follow code after line 139 in file ReportDownloader.php:

```$requestOptions[RequestOptions::PROXY] = 'http://proxyurl:8080';```


or 

```
  $requestOptions[RequestOptions::PROXY] = [
      'http' => 'proxyurl:8080'
  ];
```

Sometimes responses:

```
Error:
Client error: `POST http://adwords.google.com/api/adwords/reportdownload/v201705` resulted in a `400 Bad Request` response

PHP Fatal error:  Uncaught exception 'Symfony\Component\Serializer\Exception\UnexpectedValueException' with message 'Premature end of data in tag html line 2
' in D:\work\project\job_test\tasks-job\Google\Adwords\vendor\symfony\serializer\Encoder\XmlEncoder.php:97
```


and sometime responses:
`PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed to connect to www.googleapis.com port 443: Timed out`

**Comment by fiboknacky** [comment]
Hello,

When do you say "sometimes", does this mean the two results happened randomly?

And which one do you set between

```php
$requestOptions[RequestOptions::PROXY] = 'http://proxyurl:8080';
```

and

```php
  $requestOptions[RequestOptions::PROXY] = [
      'http' => 'proxyurl:8080'
  ];
```
?

They can behave totally differently so we need to scope down first.
And please note that I've suggested to use `'https' => 'proxyurl:8080'`, not `'http'`
It may still worth to try the usual endpoint as `https://adwords.google.com` too.

Best,
Knack

**Comment by yhdengctrip** [comment]
Hi knacky,
    
    I request API these days, and found that sometimes there still time out error.

```Fatal error: Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed to connect to www.googleapis.com port 443: Timed out```

   At first I thought it was the problem of our proxy, so I test to using our proxy to continuous request "www.google.com" every 10s, and it aways returns the right http_code (200).

  Do you know how to solve this problem, or it just the proxy problem?

**Comment by yhdengctrip** [comment]
Hi Knacky,
    would you please look forword this quesiton。
Thanks

**Comment by fiboknacky** [comment]
Sorry for late reply.
I was in vacation.
It looks like you've closed this issue already. Please let me know if you need any help further.

Knack

**Comment by yhdengctrip** [comment]
Hi Knacky,
  I setting the file (vendor/guzzlehttp/guzzle/src/Client.php)  add below code after line 180.

` $defaults['proxy']['https'] = 'proxyurl.com';`

and the result is right. but I can not guarantee it will always right, so I need to test a few days.
