### ISSUE TITLE
Can't install via composer

### ISSUE THREAD

**Issue by padalec** [googleads/googleads-php-lib#338]
Hi there,
when I try to install this library via composer I got error below:

Problem 1
    - Installation request for googleads/googleads-php-lib ^28.0 -> satisfiable by googleads/googleads-php-lib[28.0.0].
    - Conclusion: remove google/auth v1.0
    - Conclusion: don't install google/auth v1.0
    - googleads/googleads-php-lib 28.0.0 requires google/auth ^0.11.0 -> satisfiable by google/auth[v0.11.0, v0.11.1].
    - Can only install one of: google/auth[v0.11.0, v1.0].
    - Can only install one of: google/auth[v0.11.1, v1.0].
    - Installation request for google/auth (locked at v1.0) -> satisfiable by google/auth[v1.0].

**Comment by thangduo** [comment]
Hi Michal,

What OS are you using? Are you doing a fresh install, i.e. create a new and
empty folder, then run `composer require googleads/googleads-php-lib`?

Thanks,
Thang Duong


Thang Duong | Developer Advocate | dcthang@google.com | 650-793-5832

**Comment by thangduo** [comment]
It appears that you got the same problem that has already been addressed: https://github.com/googleads/googleads-php-lib/issues/320

I am closing this issue as duplicate.

Thanks,
Thang Duong
