### ISSUE TITLE
CampaignService doesnt get Youtube and Display campaigns

### ISSUE THREAD

**Issue by EduardoJaco** [googleads/googleads-php-lib#339]
In this version, v201708, CampaignService.Get() just get Search campaigns. 

I just can get Youtube and Display Network campaigns using ReportService with Campaign Performance Report.

**Comment by fiboknacky** [comment]
Hello @EduardoJaco 

CampaignService doesn't support video campaigns as noted [in this page](https://developers.google.com/adwords/api/docs/reference/v201705/CampaignService).
But it should return Display Network campaigns.

Could you please give your campaign IDs that should have appeared?

Thanks,
Knack

**Comment by fiboknacky** [comment]
Close as the answer is provided.
