### ISSUE TITLE
Follow-up for #329

### ISSUE THREAD

**Issue by brstgt** [googleads/googleads-php-lib#342]
Sorry, i was not able to comment on #329 (don't know why). So I had to create a new issue:

I don't see why this should be a problem. You could split the packages into commons, one package for each adwords API version and one package for each DFP API version.
E.g.
googleads/adwords_201705 - v1.0.1 depends on googleads/common - v1.0.1
googleads/dfp_201705 - v1.0.1 depends on googleads/common - v1.0.1
googleads/dfp_201611 - v1.1.2 depends on googleads/common - v1.1.2

So I can choose which API's I really need to not bloat my repository. This is a common pattern and used in many other libraries and dependency management systems. E.g. the Google Android libs work like that.

**Comment by fiboknacky** [comment]
Hello @brstgt 

Thanks for your comment.
Let me clarify why we've not provided the library tags / branches in that way.

* The cloned zip file itself is only 5.7 MB and thus we don't think this is not an enormous size that can cause storage concerns for any computers (It's actually just a big bigger than a photo taken by high-end smartphones these day). Installation via composer is very fast based on our testing too.

* You've mentioned the Google Android libs. To the best of my knowledge, it has a linear versioning, which is unlike our lib that has two products and each product has its own versions that don't correspond to the lib version directly. So I'm afraid that the two can't be compared directly.

* Provided that the composer.json requires versions to be like `vX.Y.Z`, I can't see a way to separate DFP and AdWords using tags, while still keeping the versioning of the whole lib linear. Separating more tags for this lib (which is unique in the way I mentioned in the previous bullet) would confuse new users too.

Best,
Knack

**Comment by brstgt** [comment]
The problem is the 5.7MB, its the number of files and the total number of
dependencies in my project. If every dependency would look like that I'd
have a million files in my repo. It totally bloats my IDE which has to
index many thousands of files for nothing and this keeps stressing my
desktop PC.

In the googleads package you have two dimensions of versioning. The one is
code and the other is the API. It seems the API is updated every few
months. So you can create a new package for a new version of the API. Which
is totally ok because as a developer I have to decide explicitly which API
version to use by importing the proper namespace. This has nothing to do
with code versioning.

By having a seperate package for each API version you can still have a
semver versioning scheme for your code.

Use cases:
- A new API is out: Create a new package. E.g. googleads/dfp_$apiVersion
- A bug is fixed for an existing API Version: Increase version on e.g.
googleads/dfp_201705 from e.g. v1.0.0 to v1.0.1
- A new feature is introruced in code: Increase version on e.g.
googleads/dfp_201705 from e.g. v1.0.1 to v1.1.0
- Code structure is being refactored and not backwards compatible Increase
version on e.g. googleads/dfp_201705 from e.g. v1.1.0 to v2.0.0

Where is the problem and why do you need a linear versioning? Simply think
in components instead of a monolithic package.

There are other examples that work that way.

https://github.com/zendframework/zendframework


2017-08-23 8:27 GMT+02:00 Thanet Knack Praneenararat <
notifications@github.com>:

**Comment by brstgt** [comment]
Very strange. I can only comment via mail.

Fix: The problem is NOT the size of 5.7MB ...

2017-08-23 8:39 GMT+02:00 benjamin roth <brstgt@gmail.com>:

**Comment by dklimkin** [comment]
Hello brstgt,

Thank you for explaining the approach. We've considered this but decided not to change the way we version the libraries at this time.

The current layout supports an important use case: using different API versions for different services simultaneously. E.g. one may use CampaignService of v201702 but FeedItemService of v201705 in the same codebase. This proved to be useful for large migrations, or for specific edge cases.

As for your concern, consider setting up a small shell script that would prune unwanted versions, provided you use only one at a time.

**Comment by brstgt** [comment]
Maybe you did not fully understand my intention.
This edge case would still be possible with a component oriented package
architecture! You can install as many (Server-)API versions as you want by
adding multiple dependencies in composer.

A composer file could look like this:

{

"require": {

"googleads/googleads-adwords-201702": "^28.0",

"googleads/googleads-adwords-201705": "^28.0",

"googleads/googleads-dfp-201705": "^28.0"

},

}

Sure - I can create a shell script but this is not a proper approach. It is
a hack.


2017-08-23 11:44 GMT+02:00 Danial Klimkin <notifications@github.com>:
