### ISSUE TITLE
Setting up Adwords API - PHP

### ISSUE THREAD

**Issue by ejaymomentummedia** [googleads/googleads-php-lib#343]
Hi Adwords Team,

I just test the adwords example codes such as GetCampaigns,php and it worked fine.
However, I'm trying to make my own function using the sample codes as my guide.

Here is my sample code:

namespace adwords\googleads_php_lib\src\Google\AdsApi\Examples\AdWords\v201708\BasicOperations;

use adwords\googleads_php_lib\src\Google\AdsApi\AdWords\AdWordsServices;
use adwords\googleads_php_lib\src\Google\AdsApi\AdWords\AdWordsSession;
use adwords\googleads_php_lib\src\Google\AdsApi\AdWords\AdWordsSessionBuilder;
use adwords\googleads_php_lib\src\Google\AdsApi\AdWords\v201708\cm\CampaignService;
use adwords\googleads_php_lib\src\Google\AdsApi\AdWords\v201708\cm\OrderBy;
use adwords\googleads_php_lib\src\Google\AdsApi\AdWords\v201708\cm\Paging;
use adwords\googleads_php_lib\src\Google\AdsApi\AdWords\v201708\cm\Selector;
use adwords\googleads_php_lib\src\Google\AdsApi\AdWords\v201708\cm\SortOrder;
use adwords\googleads_php_lib\src\Google\AdsApi\Common\OAuth2TokenBuilder;

function test() {
  return main();
}

function main() {
  $oAuth2Credential = (new OAuth2TokenBuilder())
        ->fromFile()
        ->build();
 
  $session = (new AdWordsSessionBuilder())
        ->fromFile()
        ->withOAuth2Credential($oAuth2Credential)
        ->build();

  return $session';

}

----------------------------------------------------

I already included adsapi_php.ini in my home directory, i also added some directory to locate the different classes that are needed.

The function that I'm trying to execute is the "function test()". But its not working.

Upon transferring and running the GetCampaigns.php to the same directory where that code is located. It gave me this error:

Fatal error: Class 'adwords\googleads_php_lib\src\Google\AdsApi\Common\OAuth2TokenBuilder' not found in C:\xampp\htdocs\api\GetCampaigns.php on line 86

I already changed the directory of directory of classes to properly locate it. But its no good

Hope you can help me setting up the codes in my file.

Thank you so much,

Ejay

**Comment by fiboknacky** [comment]
Hello Ejay,

From the first glance, the "use" keyword shouldn't be tweaked like you've done:
```php
use adwords\googleads_php_lib\src\Google\AdsApi\Common\OAuth2TokenBuilder;
```

This is because this library is supposed be installed using composer and we've set autoloading based on those namespaces.
Could you please try reverting your changes back to what's like in [GetCampaigns.php](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201708/BasicOperations/GetCampaigns.php#L29)?

Best,
Knack

**Comment by ejaymomentummedia** [comment]
Hi Knack,

It now worked. I tried re-installing using composer. and i just locate the vendor.autoload.php properly
I can now use Adwords API :)

Thanks,

Ejay

**Comment by fiboknacky** [comment]
Hello Ejay,

Glad to hear that. 👍 

Best,
Knack
