### ISSUE TITLE
PHP API issue

### ISSUE THREAD

**Issue by ejaymomentummedia** [googleads/googleads-php-lib#345]
Hi Adwords Team,

I already construct my own functions using your code structure in your code samples.
It is now working properly in my localhost. But then upon uploading it my web application, Its not giving me any response.

I print_r $session and $oAuth2Credential and it generated me my expected result,
It seems that im having the problem or issue here in this part:

$campaignService = $adWordsServices->get($session, CampaignService::class);

Thanks,

Ejay

**Comment by fiboknacky** [comment]
Hello,

Could you please provide more specific details like what happened when you tried to get $campaignService?
And if possible could you give your code snippet too?

Best,
Knack

**Comment by ejaymomentummedia** [comment]
Hi Knack,

Sorry for the late response, Just got back from a holiday,

Here Is my code for the reporting:

$oAuth2Credential = (new OAuth2TokenBuilder())
        ->fromFile()
        ->build();
    // credentials above.
    $session = (new AdWordsSessionBuilder())
        ->fromFile()
        ->withOAuth2Credential($oAuth2Credential)
        ->build();
        $reportQuery = 'SELECT CampaignName, CampaignId, '
        . 'Impressions, Clicks FROM CRITERIA_PERFORMANCE_REPORT '
        . 'WHERE CampaignId = '.$adwordsId.' AND Status IN [ENABLED, PAUSED] DURING LAST_7_DAYS';


	// Download report as a string.
	$reportDownloader = new ReportDownloader($session);
	$reportSettingsOverride = (new ReportSettingsBuilder())
	    ->includeZeroImpressions(true)
	    ->build();
	$reportDownloadResult = $reportDownloader->downloadReportWithAwql(
	    $reportQuery, DownloadFormat::CSV, $reportSettingsOverride);

	$csv = $reportDownloadResult->getAsString();

--------------------

That code is working fine in my localhost, but as i upload it in my live website its not working. I already checked print_r($oAuth2Credential) and print_r($session) and its perfectly working in my live website.

I think the problem is when executing the API transaction. I also tested the CampaignService API.
I'm having a problem in this line $campaignService = $adWordsServices->get($session, CampaignService::class);

Thanks,

Ejay

**Comment by fiboknacky** [comment]
Hello @ejaymomentummedia 

> That code is working fine in my localhost, but as i upload it in my live website its not working. I already checked print_r($oAuth2Credential) and print_r($session) and its perfectly working in my live website.

When you say "it's not working", what does it look like? Any errors printed out? Or just silence and nothing returned? Or just `$csv` doesn't have any values?

Knack

**Comment by ejaymomentummedia** [comment]
Hi Knack,

Silence and nothing returned

Ejay,

**Comment by fiboknacky** [comment]
Could you inspect the result e.g., `$reportDownloadResult`, `$csv`?
What's in there?

Thanks.

**Comment by ejaymomentummedia** [comment]
Hi Knack, 

My report API is now working, but i didn't change anything, weird.
But here is an another concern, The GetCampaign.php is running perfectly in my localhost

![getcampaigns](https://user-images.githubusercontent.com/31235701/29802413-8c4e7df8-8ca7-11e7-88ad-8ab2f056d4ea.PNG)

But as i execute it in my live website, its giving me this error

![image](https://user-images.githubusercontent.com/31235701/29802449-c90e075e-8ca7-11e7-8cc7-d44a662896c9.png)

Hope you can provide me some ways to avoid this, my report api is now currently working but just incase i enounter this in the future, it will be a big help

Thanks,

Ejay

**Comment by fiboknacky** [comment]
Hi Ejay,

For the reporting issue, let's see if the issue happens again. For now, I can't see any causes that would prevent you from downloading reports.

For the GetCampaigns.php example, could you please turn on all error reporting (as suggested in [this post](https://stackoverflow.com/a/21429652)) and try again?

Cheers,
Knack

**Comment by ejaymomentummedia** [comment]
Hi Knack,

This is my sample code for retrieving campaigns.

![image](https://user-images.githubusercontent.com/31235701/29808904-928139c0-8ccc-11e7-8a72-201e38216504.png)

This is the result:

![image](https://user-images.githubusercontent.com/31235701/29808919-a3050966-8ccc-11e7-97d8-1b94317d1729.png)

But Whenever i uncomment the $campaignService, it gets like this. null result:

![image](https://user-images.githubusercontent.com/31235701/29808956-c2f252ba-8ccc-11e7-81ae-8a7a5fca7bef.png)

![image](https://user-images.githubusercontent.com/31235701/29808971-d350fd78-8ccc-11e7-942a-87f9a35a8d56.png)

![image](https://user-images.githubusercontent.com/31235701/29808977-dc9a6702-8ccc-11e7-93f9-80f632a800ef.png)

![image](https://user-images.githubusercontent.com/31235701/29808991-ec815bc6-8ccc-11e7-956a-6b46ccfd803c.png)

Thanks,

Ejay

**Comment by ejaymomentummedia** [comment]
Hi Knack,

This is also my settings:

![image](https://user-images.githubusercontent.com/31235701/29809052-2c40104a-8ccd-11e7-9b42-cbe0b80395d6.png)

![image](https://user-images.githubusercontent.com/31235701/29809072-41018004-8ccd-11e7-86ca-17dfeddc43ba.png)

**Comment by fiboknacky** [comment]
Looking from your provided data, it looks like this might be a problem on your server settings.
(I saw error code 500 of nginx)
Do you have any proxies or settings that prevent SOAP calls?

**Comment by ejaymomentummedia** [comment]
Hi Knack, 

Cool! It might be it. I'll contact the one who's handling our server, Maybe it has something to do with the permission of files in the server.

I'll let you know.

Thanks,

Ejay

**Comment by fiboknacky** [comment]
Close for now. Feel free to let us know if the problem still persists.
