### ISSUE TITLE
 Uncaught Error: Class 'OAuth2TokenBuilder' not found 

### ISSUE THREAD

**Issue by Gman932** [googleads/googleads-php-lib#346]
I am attempting to use get campaigns via PHP.  I've downloaded and included the 'Google\AdsApi' folder, and all sub-directories in my parent folder.

When I run the following php script from ym parent directory, I get the error "Uncaught Error: Class 'OAuth2TokenBuilder' not found "

Any ideas why this is occuring? Full code below:

'''<?php
 
require_once './Google/AdsApi/Common/OAuth2TokenBuilder.php';
require_once './Google/AdsApi/AdWords/AdWordsSession.php';
require_once './Google/AdsApi/Common/AdsBuilder.php';

$oAuth2Credential = (new OAuth2TokenBuilder())
	->withClientId("43774...leusercontent.com")
	->withClientSecret("6z...f_")
	->withRefreshToken("1/gNLPu...OVxI")
	->build();

// Construct an API session configured from the OAuth2 credentials above.
$session = (new AdWordsSessionBuilder())
	->withDeveloperToken("22...zA")
	->withOAuth2Credential($oAuth2Credential)
	->withClientCustomerId("5...9")
	->build();
 
// Create a new user
$user = new AdWordsUser();
$user->SetDeveloperToken($developerToken);
 
// Load the oAuth settings
$user->SetOAuth2Info(loadAuth($tokenFilename));
 
// Get a list of campaigns
$campaignService = $user->GetService('CampaignService', 'v201209');
$selector = new Selector();
$selector->fields = array('Id', 'Name');
$campaigns = $campaignService->get($selector);
 
print_r($campaigns);'''

**Comment by fiboknacky** [comment]
Hello,

This library is supposed to be installed using composer, as written in our [README guide](https://github.com/googleads/googleads-php-lib#getting-started).
Could you please follow the instructions and try again?

In addition, it looks like you're mixing between the already sunset branch (I see the use of `AdWordsUser()`) with the main branch.
I highly recommend to focus on the main branch only.
You can see how to use classes in the main branch in the [`examples/`](https://github.com/googleads/googleads-php-lib/tree/master/examples/AdWords) folder.

Cheers,
Knack

**Comment by Gman932** [comment]
Hi thank you for your quick reply.

I had previously attempted that method, and it did not appear to work properly.  Now, my ".\googleads-php-lib-master\src" file is empty.  I do not think the library is currently sitting in the parent directory where php.exe sits.

**Comment by fiboknacky** [comment]
Hi @Gman932 

Could you please tell me how you've followed the instructions step-by-step please?
This is to check if there is any misunderstanding happening. 

Thanks.
Knack

**Comment by Gman932** [comment]
Hi Knack,

Sure things, please see below:

1. I downloaded and installed composer using the command line:
https://getcomposer.org/download/

2. Then form the command line, I ran:
php composer.phar require googleads/googleads-php-lib

3. It returned the following

> Using version ^29.0 for googleads/googleads-php-lib
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 15 installs, 0 updates, 0 removals
  - Installing symfony/serializer (v3.3.8): Downloading (100%)
  - Installing webmozart/assert (1.2.0): Downloading (100%)
  - Installing phpdocumentor/reflection-common (1.0): Downloading (100%)
  - Installing phpdocumentor/type-resolver (0.3.0): Downloading (100%)
  - Installing phpdocumentor/reflection-docblock (3.2.2): Downloading (100%)
  - Installing psr/log (1.0.2): Downloading (100%)
  - Installing monolog/monolog (1.23.0): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)
  - Installing guzzlehttp/guzzle (6.3.0): Downloading (100%)
  - Installing psr/cache (1.0.1): Downloading (100%)
  - Installing firebase/php-jwt (v5.0.0): Downloading (100%)
  - Installing google/auth (v1.0.1): Downloading (100%)
  - Installing googleads/googleads-php-lib (29.0.0): Downloading (100%)
symfony/serializer suggests installing doctrine/annotations (For using the annotation mapping. You will also need doctrine/cache.)
symfony/serializer suggests installing doctrine/cache (For using the default cached annotation reader and metadata cache.)
symfony/serializer suggests installing psr/cache-implementation (For using the metadata cache.)
symfony/serializer suggests installing symfony/config (For using the XML mapping loader.)
symfony/serializer suggests installing symfony/http-foundation (To use the DataUriNormalizer.)
symfony/serializer suggests installing symfony/property-access (For using the ObjectNormalizer.)
symfony/serializer suggests installing symfony/property-info (To deserialize relations.)
symfony/serializer suggests installing symfony/yaml (For using the default YAML mapping loader.)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
googleads/googleads-php-lib suggests installing php-64bit (>=5.5.9)
Writing lock file
Generating autoload files

**Comment by fiboknacky** [comment]
Hi,

Thanks for the details.
Don't you see anything under `vendor/` directory of your project directory?
There should be `googleads/googleads-php-lib/` under `vendor/`.

Best,
Knack

**Comment by Gman932** [comment]
I do have it there. Thanks very much.  I adjusted the namespace, but again, I think that there is a problem with the require area;  now there is a
 PHP Fatal error:  Uncaught Error: Class 'AdWordsUser' not found.

From searching online, I can't find the .php file that this class belongs to anywhere in the library.

**Comment by fiboknacky** [comment]
Hello @Gman932 

Again, there is no `AdWordsUser` in our library now.
That's why I asked if you have confusion between the old branch and the main branch. :)
This [upgrading guide](https://github.com/googleads/googleads-php-lib/blob/master/UPGRADING.md) might help you too.

Best,
Knack
