### ISSUE TITLE
GetRefreshToken

### ISSUE THREAD

**Issue by Sparkeroo96** [googleads/googleads-php-lib#350]
Hi, I keep trying different solution but i cant seem to get this figured out
I am using Xampp, php 5.6.8 to try and run the api
When i run GetRefreshToken.php and enter the auth code i get:
'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs_rscpp1\rscpp\htdocs\php\includes\external\adwords\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187

I have added cacert.pem to php/extras/ssl
and my php.ini file points to it with : curl.cainfo = "C:\xampp\php\extras\ssl\cacert.pem"
I also added openssl.cafile = "C:\xampp\php\extras\ssl\cacert.pem" for good measure
And still i get the error, ive restarted my local server and dl a fresh cacert.pem
Please help me with this issue

**Comment by fiboknacky** [comment]
Hello @Sparkeroo96 

Could you please follow what we discussed in #322 and #315 and see if it resolves your case?
In short, another way to try is using [withSslCaFile()](https://github.com/googleads/googleads-php-lib/blob/9494f90d27ac041c4d5bdb93599f8add60c12929/src/Google/AdsApi/Common/SoapSettingsBuilder.php#L182).

Best,
Knack

**Comment by Sparkeroo96** [comment]
Hey @fiboknacky  thanks for trying to help
I can't seem to figure out where i put the withSslCaFile()
Also I've attempted to do it without security for the time being and when I run getCampaign.php I am getting the error, which I dont know if it is related or not:
Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201708/CampaignService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/cm/v201708/CampaignService?wsdl"
 in C:\xampp\htdocs_rscpp1\rscpp\htdocs\php\includes\external\adwords\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php:68
Stack trace:
#0 C:\xampp\htdocs_rscpp1\rscpp\htdocs\php\includes\external\adwords\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php(68): SoapClient->SoapClient('https://adwords...', Array)
#1 C:\xampp\htdocs_rscpp1\rscpp\htdocs\php\includes\external\adwords\vendor\googleads\googleads-php-lib\src\Google\AdsApi\AdWords\v201708\cm\CampaignService.php(146): Google\AdsApi\Common\AdsSoapClient->__construct('https://adwords...', Array)
#2 [internal function]: Google\AdsApi\AdWords\v201708\cm\CampaignService->__construct(Array)
#3 C:\xampp\htdocs_rscpp1\rscpp\htdocs\php\includes\extern in C:\xampp\htdocs_rscpp1\rscpp\htdocs\php\includes\external\adwords\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php on line 68

**Comment by fiboknacky** [comment]
To use `withSslCaFile()`, please do something similar to the below snippet:

```php
        $soapSettings = (new SoapSettingsBuilder())
		->withSslCaFile(PATH_TO_YOUR_SSL_CA_FILE)
		->build();

	// Generate a refreshable OAuth2 credential for authentication.
	$oAuth2Credential = (new OAuth2TokenBuilder())
		->fromFile('adsapi_php.ini')
		->build();

	// Construct an API session configured from a properties file and the OAuth2
	// credentials above.
	$session = (new AdWordsSessionBuilder())
		->fromFile('adsapi_php.ini')
		->withOAuth2Credential($oAuth2Credential)
		->withSoapSettings($soapSettings)
		->build();		
```

And the error message that you've shared in the previous reply is a different issue.
First, could you check if you can access https://adwords.google.com/api/adwords/cm/v201708/CampaignService?wsdl in your computer?

Trying to increasing `connection_timeout` might help too. You can do this by creating `AdsSoapClientFactory` and specifying desired value:
```php
$adsSoapClientFactory = new AdsSoapClientFactory(
            (new AdWordsSoapLogMessageFormatterProvider(), null, 3000)); // 5 minutes
$adWordsServices = new AdWordsServices($adsSoapClientFactory);
$biddingStrategyService =
        $adWordsServices->get($session, BiddingStrategyService::class);
// Use the service....
// ....
```

Best,
Knack

**Comment by Sparkeroo96** [comment]
I'm just trying to do the example GetCampaigns.php and it wont do that so I havent got anywhere to put that snippet, I increased the timeout in php.ini and using curl i can print out https://adwords.google.com/api/adwords/cm/v201708/CampaignService?wsdl in my command prompt

**Comment by Sparkeroo96** [comment]
Actually I added that stuff to GetCampaigns and I'm still getting the same  error
[WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201708/CampaignService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/cm/v201708/CampaignService?wsdl"

**Comment by fiboknacky** [comment]
> Actually I added that stuff to GetCampaigns and I'm still getting the same error
[WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201708/CampaignService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/cm/v201708/CampaignService?wsdl"

* What is the stuff that you added to GetCampaigns?
* Does this error always occur or sometimes occur?
* Does this happen in your local computer or live server? Is it possible for you to try other environments?

If possible, could you please try calling other SOAP services too, just to make sure that this issue happens to our library only or to other APIs too.

Best,
Knack

**Comment by Sparkeroo96** [comment]
I edited the main function in GetCampaign.php, this error always occurs and it happens on my localmachine, that can use ngrok to tunnel to the internet if needed, as of now I cannot test it on a live server

```
public static function main() {  include('C:\xampp\htdocs_rscpp1\rscpp\htdocs\php\includes\external\adwords\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\SoapSettingsBuilder.php');
	  $soapSettings = (new \Google\AdsApi\Common\SoapSettingsBuilder)
		->withSslCaFile('C:\xampp\php\extras\ssl\cacert.pem')
		->build();
	  //########################
    // Generate a refreshable OAuth2 credential for authentication.
    $oAuth2Credential = (new OAuth2TokenBuilder())
        ->fromFile('C:\xampp\htdocs_rscpp1\rscpp\htdocs\php\includes\external\adwords\adsapi_php.ini')
        ->build();

    // Construct an API session configured from a properties file and the OAuth2
    // credentials above.
    $session = (new AdWordsSessionBuilder())
        ->fromFile('C:\xampp\htdocs_rscpp1\rscpp\htdocs\php\includes\external\adwords\adsapi_php.ini')
        ->withOAuth2Credential($oAuth2Credential)
		->withSoapSettings($soapSettings)
        ->build();
    self::runExample(new AdWordsServices(), $session);
  }
```

I also tried to do this  
```
var_dump(class_exists("SOAPClient"));
if (extension_loaded('soap')) {
  echo 'soap loaded';
}

$soapClient = new SoapClient('https://adwords.google.com/api/adwords/cm/v201708/CampaignService?wsdl');
$arr_soap_functions = $soapClient->__getFunctions();
print_r($arr_soap_functions);
```
And the Print out is 
bool(true)
soap loaded
Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201708/CampaignService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/cm/v201708/CampaignService?wsdl"
 in C:\xampp\htdocs_rscpp1\rscpp\htdocs\php\includes\external\adwords\examples\examples\AdWords\v201708\BasicOperations\test.php:13
Stack trace:
#0 C:\xampp\htdocs_rscpp1\rscpp\htdocs\php\includes\external\adwords\examples\examples\AdWords\v201708\BasicOperations\test.php(13): SoapClient->SoapClient('https://adwords...')
#1 {main}
  thrown in C:\xampp\htdocs_rscpp1\rscpp\htdocs\php\includes\external\adwords\examples\examples\AdWords\v201708\BasicOperations\test.php on line 13

**Comment by Sparkeroo96** [comment]
Moved the files about into /windows and windows/32 as well without setting their destination, still getting same error

**Comment by fiboknacky** [comment]
Hello @Sparkeroo96 

Just in case, in what country is your computer/server located?

Knack

**Comment by Sparkeroo96** [comment]
England

**Comment by fiboknacky** [comment]
Could you please try / check some settings described below?
- Try settings `libxml_disable_entity_loader(false)` ([reference](http://php.net/manual/en/function.libxml-disable-entity-loader.php))
- Check if your `php.ini` contains `extension=php_openssl.dll` and have it _uncommented_.
- Try setting WSDL caching. You can set it using [`adsapi_php.ini`](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/adsapi_php.ini#L43)
- Try hosting a WSDL file locally by settings `/etc/hosts/` (e.g., as described [in this page](https://blog.kowalczyk.info/article/10c/local-dns-modifications-on-windows-etchosts-equivalent.html)). You can do so for just one service (like CampaignService now). If this works, a long-term solution would be to host all WSDL files locally, which we'll work on that soon.
- Is it possible for you to try making a request to other SOAP services? I'd like to scope down if this issue happens because of your environment settings or connections between yours and our servers.

Knack

**Comment by Sparkeroo96** [comment]
libxml_disable_entity_loader(false) started as true and tried as false, same error
extension=php_openssl.dll This is in there and uncommented
WSDL caching same error
127.0.0.1	 https://adwords.google.com/api/adwords/cm/v201708/CampaignService?wsdl   Put that in hosts and still same bug
I believe soap is working correctly

It seems to work if I have ->disableSslVerify()

**Comment by fiboknacky** [comment]
Sorry for quick trials.
It looks like the only workaround now is to disable SSL verify, which is not recommended for a long run.
I will seek out any other ways to resolve this issue.

Regards,
Knack

**Comment by Sparkeroo96** [comment]
No worries, thank you for your help so far
