### ISSUE TITLE
Fatal error: Uncaught exception 'ReflectionException' with message 'Class Google/AdsApi/AdWords/v201708/cm/CampaignService does not exist'

### ISSUE THREAD

**Issue by kmschremser** [googleads/googleads-php-lib#351]
HI, I installed the lib (thanks for providing it !! :). But after running it with basic operations GetCampaigns.php to test it, I ran into this error ... can you help me? 

Fatal error: Uncaught exception 'ReflectionException' with message 'Class Google/AdsApi/AdWords/v201708/cm/CampaignService does not exist' in /Library/WebServer/Documents/adwords/googleads/googleads-php-lib/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/AdWordsServiceDescriptor.php:xx

Thanks.

Best, Klaus-M.

**Comment by kmschremser** [comment]
Already solved. :) The vendor files were not updated and an old version was there.

**Comment by fiboknacky** [comment]
Thanks for using the library. :)
I'm glad that you can resolve the issue already but if you have any questions, feel free to ask in the issues page.

Best,
Knack
