### ISSUE TITLE
v29.0.0 installation problem

### ISSUE THREAD

**Issue by alikopasa** [googleads/googleads-php-lib#352]
When I try to install v29.0.0 like before versions, I got below errors. Can you help me please?
I installed with steps as mentioned https://github.com/googleads/googleads-php-lib

root@nod4 [/home/www]# php composer.phar require googleads/googleads-php-lib
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^29.0 for googleads/googleads-php-lib
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for googleads/googleads-php-lib ^29.0 -> satisfiable by googleads/googleads-php-lib[29.0.0].
    - Conclusion: remove google/auth v0.11.1
    - Conclusion: don't install google/auth v0.11.1
    - googleads/googleads-php-lib 29.0.0 requires google/auth ^1.0.0 -> satisfiable by google/auth[v1.0, v1.0.1].
    - Can only install one of: google/auth[v1.0, v0.11.1].
    - Can only install one of: google/auth[v1.0.1, v0.11.1].
    - Installation request for google/auth (locked at v0.11.1) -> satisfiable by google/auth[v0.11.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by fiboknacky** [comment]
Hello,

Could you please share what the `composer.json` of your project looks like?

Cheers,
Knack

**Comment by fiboknacky** [comment]
And does this flag (--update-with-dependencies) for composer help?

**Comment by alikopasa** [comment]
I used this command 

> php composer.phar require googleads/googleads-php-lib


Error updated ;

php composer.phar require googleads/googleads-php-lib
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^29.0 for googleads/googleads-php-lib
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package googleads/googleads-php-lib No version set (parsed as 1.0.0) is satisfiable by googleads/googleads-php-lib[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
  Problem 2
    - The requested package google/auth (installed at v0.11.1, required as ^1.0.0) is satisfiable by google/auth[v0.11.1] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.

composer.json like below
{
  "name": "googleads/googleads-php-lib",
  "description": "Google Ads APIs Client Library for PHP (AdWords and DFP)",
  "require": {
    "php": ">=5.5.9",
    "ext-openssl": "*",
    "ext-soap": "*",
    "google/auth": "^1.0.0",
    "guzzlehttp/guzzle": "^6.0",
    "guzzlehttp/psr7": "^1.2",
    "monolog/monolog": "^1.17.1",
    "phpdocumentor/reflection-docblock": "^3.0.3",
    "symfony/serializer": "^2.8.0 || ^3.0.3"
  },
  "require-dev": {
    "php": ">=5.5.17",
    "phpunit/phpunit": "^4.8"
  },
  "suggest": {
    "php-64bit": ">=5.5.9"
  },
  "homepage": "https://github.com/googleads/googleads-php-lib",
  "license": "Apache-2.0",
  "autoload": {
    "psr-4": { "Google\\AdsApi\\": "src/Google/AdsApi/" }
  },
  "authors": [
    {
      "name": "Google",
      "homepage": "https://github.com/googleads/googleads-php-lib/contributors"
    }
  ]
}

**Comment by fiboknacky** [comment]
Could you remove your `composer.json` and try again?
Probably the error was caused b your `composer.json`.
It specifies v28.0.0 but your command demands v29.0.0.

In v29.0.0, we have updated the requirement of google/auth to v1.0.0, which conflicts with that of older versions.

Knack

**Comment by alikopasa** [comment]
Thank you very much for your help after deleting composer.json with this code it worked successfully.

`php composer.phar require googleads/googleads-php-lib --update-with-dependencies`
