### ISSUE TITLE
PHP Fatal error:  SOAP-ERROR: Parsing WSDL

### ISSUE THREAD

**Issue by yhdengctrip** [googleads/googleads-php-lib#353]
Hi Adwords API Team,
   I am using adwords api with proxy to get campaigns, but when I set 
`$campaignService = $adWordsServices->get($session, CampaignService::class);`
 and it returns
`PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201708/CampaignService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/cm/v201708/CampaignService?wsdl"`

below is proxy setting in adsapi_php.ini and I'm sure the proxy is able to access "https://adwords.google.com/api/adwords/cm/v201708/CampaignService?wsdl":

```
[PROXY]
; Optional proxy settings to be used by SOAP requests.
host = "myproxy"
port = 8080
; user = "<USER>"
; password = "<PASSWORD>"
```

I debug in the file of "AdsSoapClient.php" at line 64, 

```
$this->reflection = new Reflection();
print_r($options);
parent::__construct($wsdl, $options);
```

it output :

```
[features] => 1                                       
[trace] => 1                                          
[encoding] => utf-8                                   
[connection_timeout] => 600                           
[proxy_host] => myproxy
[proxy_port] => 8080                                  
[stream_context] => Resource id #73                   
[keep_alive] =>                                       
[classmap] => Array   ..... 
```                               

Am I missing something?
 
Thanks.

**Comment by fiboknacky** [comment]
Hi @yhdengctrip 

It should work right away without settings any other things.
Could you try using other environments without proxy?

And does this happen always or sometimes?
Do you use Windows or unix-based?

Cheers,
Knack

**Comment by yhdengctrip** [comment]
Hi Knacky,
   I need to setting proxy, because google.com is block in the China mainland, and current we have not server outside of China mainland.
   This problem is always happen and My OS is Windows.

   From your point of view, maybe is problem of proxy,

   but I using the proxy with curl like below:

 
```
$curl = curl_init('https://adwords.google.com/api/adwords/cm/v201702/CampaignService?wsdl');
curl_setopt($curl, CURLOPT_HEADER, 1);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($curl, CURLOPT_TIMEOUT, 30);
curl_setopt($curl, CURLOPT_PROXY, 'myproxy');	
$R = curl_exec($curl);
print_r($R);
```


and it return to normal (part of returns):

```
......
 <complexType name="InternalApiError">                                                                         
   <annotation>                                                                                                
     <documentation>                                                                                           
       Indicates that a server-side error has occured. {@code InternalApiError}s                               
       are generally not the result of an invalid request or message sent by the                               
       client.                                                                                                 
     </documentation>                                                                                          
   </annotation>                                                                                               
   <complexContent>                                                                                            
     <extension base="tns:ApiError">                                                                           
       <sequence>                                                                                              
         <element maxOccurs="1" minOccurs="0" name="reason" type="tns:InternalApiError.Reason">                
           <annotation>                                                                                        
             <documentation>                                                                                   
               The error reason represented by an enum.                                                        
             </documentation>                                                                                  
           </annotation>                                                                                       
         </element>                                                                                            
       </sequence>                                                                                             
     </extension>                                                                                              
   </complexContent>     
.....
```

**Comment by fiboknacky** [comment]
Hello,

> I need to setting proxy, because google.com is blocked in the China mainland, and current we have not server outside of China mainland.
Thanks for this information.

I'm not sure if the problem is caused by the proxy yet. It can be caused by some settings of Windows as well.

Could you please tell me more about:
- Windows version (do you install it by XAMPP?)
- PHP version

Thank you,
Knack

**Comment by yhdengctrip** [comment]
Hi,
   Windows version is WIN7 pro, and PHP version is 5.6.29, the development ENV is Nginx+PHP+Mysql

Thanks.

**Comment by fiboknacky** [comment]
Hello @yhdengctrip 

Could you please try / check some settings described below?
- Try settings `libxml_disable_entity_loader(false)` ([reference](http://php.net/manual/en/function.libxml-disable-entity-loader.php))
- Check if your `php.ini` contains `extension=php_openssl.dll` and have it _uncommented_.
- Try setting WSDL caching. You can set it using [`adsapi_php.ini`](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/adsapi_php.ini#L43)
- Try hosting a WSDL file locally by settings `/etc/hosts/` (e.g., as described [in this page](https://blog.kowalczyk.info/article/10c/local-dns-modifications-on-windows-etchosts-equivalent.html)). You can do so for just one service (like CampaignService now). If this works, a long-term solution would be to host all WSDL files locally, which we'll work on that soon.
- Is it possible for you to try making a request to other SOAP services? I'd like to scope down if this issue happens because of your environment settings or connections between yours and our servers.

Thanks,
Knack
