### ISSUE TITLE
Problem with Guzzle and ReportDownloader

### ISSUE THREAD

**Issue by wedgemaster** [googleads/googleads-php-lib#355]
Hello,

I have installed the Google Ads API Client Library for PHP on my project.
I created a new class "DownloadAdwordsReport" (see the code bellow) using quite the same code of the example : DownloadCriteriaReportWithAwql.php

But when I try to test it, I got this error and i don't know why, all dependencies are ok with the composer.

**Fatal error: Call to undefined method GuzzleHttp\Client::request() in /var/www/vhosts/xxxxxxxx/src/Google/AdsApi/AdWords/Reporting/v201708/ReportDownloader.php on line 141**

Thanks for your help

```
namespace Google\AdsApi\DownloadAdwordsReport;

require dirname(__FILE__) . '/vendor/autoload.php';

use Google\AdsApi\AdWords\AdWordsSession;
use Google\AdsApi\AdWords\AdWordsSessionBuilder;
use Google\AdsApi\AdWords\Reporting\v201708\ReportDownloader;
use Google\AdsApi\AdWords\Reporting\v201708\DownloadFormat;
use Google\AdsApi\AdWords\ReportSettingsBuilder;
use Google\AdsApi\Common\OAuth2TokenBuilder;

/**
 * Downloads CRITERIA_PERFORMANCE_REPORT for the specified client customer ID.
 */
class DownloadAdwordsReport {

    public static function getReport(AdWordsSession $session, $reportQuery, $filename) {
        $reportDownloader = new ReportDownloader($session);
        $reportSettingsOverride = (new ReportSettingsBuilder())
            ->includeZeroImpressions(false)
            ->build();
        $reportDownloadResult = $reportDownloader->downloadReportWithAwql($reportQuery, DownloadFormat::CSV, $reportSettingsOverride);
        $reportDownloadResult->saveToFile($filename);
    }

    public static function main($adwords_client_account, $reportQuery, $filename) {
        // Generate a refreshable OAuth2 credential for authentication.
        $oAuth2Credential = (new OAuth2TokenBuilder())
            ->fromFile()
            ->build();

        // See: AdWordsSessionBuilder for setting a client customer ID that is
        // different from that specified in your adsapi_php.ini file.
        // Construct an API session configured from a properties file and the OAuth2
        // credentials above.
        $session = (new AdWordsSessionBuilder())
            ->fromFile()
            ->withOAuth2Credential($oAuth2Credential)
            ->withClientCustomerId($adwords_client_account)
            ->build();

        self::getReport($session, $reportQuery, $filename);
    }
}
```

**Comment by fiboknacky** [comment]
Hello

Can you run our example or cannot at all?
And could you make sure that your installed Guzzle is at least v6.0?
That method exists since [v6.0](https://github.com/guzzle/guzzle/blob/master/src/Client.php), but not in [v5.3](https://github.com/guzzle/guzzle/blob/5.3/src/Client.php).

Best,
Knack

**Comment by wedgemaster** [comment]
Here is the version installed by the composer : 

- guzzlehttp/guzzle                 6.3.0
- guzzlehttp/promises               v1.3.1
- guzzlehttp/psr7                   1.4.2

If I run the DownloadCriteriaReportWithAwql.php example, it works by adding
->withClientCustomerId('xxx-xxx-xxxx')

**Comment by fiboknacky** [comment]
Hi @wedgemaster 

If you don't add `->withClientCustomerId`, will it fail with the same error message?
Just in case, could you check the installed Guzzle's Client.php inside your `vendor/` directory?
Is there a `request()` method with the same signature there?

Best,
Knack

**Comment by wedgemaster** [comment]
No the error is different : 

```
Fatal error: Uncaught exception 'Google\AdsApi\AdWords\v201708\cm\ApiException' with message 'Details: [fieldPath: selector.reportDefinition; trigger: ; errorString: ReportDefinitionError.CUSTOMER_SERVING_TYPE_REPORT_MISMATCH]' in /var/www/vhosts/xxxx/httpdocs/dev/gapi_inc_new/src/Google/AdsApi/AdWords/Reporting/v201708/ReportDownloader.php on line 160

Google\AdsApi\AdWords\v201708\cm\ApiException: Details: [fieldPath: selector.reportDefinition; trigger: ; errorString: ReportDefinitionError.CUSTOMER_SERVING_TYPE_REPORT_MISMATCH] in /var/www/vhosts/xxxx/httpdocs/dev/gapi_inc_new/src/Google/AdsApi/AdWords/Reporting/v201708/ReportDownloader.php on line 160
```

And the lethod is there. 
And when i go to ReportDownloader.php on line 141 like the error said with phpstorm, i do the right click go to declaration and he found it...

**Comment by fiboknacky** [comment]
> Fatal error: Uncaught exception 'Google\AdsApi\AdWords\v201708\cm\ApiException' with message 'Details: [fieldPath: selector.reportDefinition; trigger: ; errorString: ReportDefinitionError.CUSTOMER_SERVING_TYPE_REPORT_MISMATCH]' in /var/www/vhosts/xxxx/httpdocs/dev/gapi_inc_new/src/Google/AdsApi/AdWords/Reporting/v201708/ReportDownloader.php on line 160

That would be because your default client customer ID (set in `adsapi_php.ini`) is a manager account, which seems to work as intended.

Another questions:
- Where do you place this file? 
- What if you move your file to the same directory as our DownloadCriteriaReportWithAwql.php example and change the namespace accordingly? Does it work?

**Comment by wedgemaster** [comment]
Well, the truth is the file and the example file are placed in the same directory who is "/gapi_inc_new/"
If i place the example file to "\gapi_inc_new\examples\AdWords\v201708\Reporting\" folder
I got an error : 

`Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Config file not found as specified: 'adsapi_php.ini'. Home directory could not be located so it was not searched.' in `

Don't no why because the .ini is in my home and work when they are in "/gapi_inc_new/"

**Comment by fiboknacky** [comment]
Hello @wedgemaster 

I can't reproduce your issue, so first let's step back to the beginning.
**How did you install this library?**

Did you create a new project directory and follow [this instructions](https://github.com/googleads/googleads-php-lib#getting-started) (do `composer require`)?
Or did you use [`git clone`](https://github.com/googleads/googleads-php-lib#using-git-clone) and download everything as is? 
Or did you download the [compressed tarball file](https://github.com/googleads/googleads-php-lib#downloading-a-compressed-tarball) from [this page](https://github.com/googleads/googleads-php-lib/releases)?

This is necessary information for our investigation as it would affect how your files are organized.
Thank you.

Best,
Knack

**Comment by wedgemaster** [comment]
Hello @fiboknacky 

I downloaded the compressed files from the github project.
Put all the files in a new folder "/gapi_inc_new" at the root of my localhost project who is a clone of my remote project.
I used the command "composer install" in that directory.
I copy and paste the adsapi_php.ini in the root "/", and setup the configuration data inside.
Then I push it on the remote host and test it on the remote side.

Thanks for your help.

**Comment by fiboknacky** [comment]
Do you face this issue even in your local computer?

**Comment by wedgemaster** [comment]
On localhost I have other problems.
If I run the test we did yesterday who works on remote, on localhost it got errors : 
```
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\wamp\www\dev\gapi_inc_new\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187
( ! ) GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\wamp\www\dev\gapi_inc_new\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187
```
That why i do all test on remote.

**Comment by fiboknacky** [comment]
Windows have some certificate settings that are sometimes different and cause a problem to Guzzle.
There are many workarounds for that but let's focus on your original issue first.

Is it possible for you to download the files directly on the remote host and do `composer install` on the remote host instead?

**Comment by wedgemaster** [comment]
I can try to install composer on the server.
I'm going to do it and let you know if something change

**Comment by fiboknacky** [comment]
Thank you.
Theoretically everything about composer-installed libraries should reside in `/vendor` but we do get feedback from a user that when he tried installing the lib directly, it worked.

**Comment by wedgemaster** [comment]
Well, I installed with the composer on remote host and same problem...
When I try my custom class,  same error.

My PHP version is 5.5.9, maybe is there a problem with the Guzzle version ?

**Comment by wedgemaster** [comment]
For information, i forgot to mention that the project is over codeigniter 2.1.4
On a specific controller, there was a require() to the old library

I'm trying to update with the new library, so I do a require() of my class pasted in my first post
And I call it with : 
\Google\AdsApi\DownloadAdwordsReport\DownloadAdwordsReport::main($client['adwords_client_bl'], $reportQuery, $local_path.$filename);

And there the fatal error of guzzle

**Comment by wedgemaster** [comment]
I found the problem.
I have another directory on my root that contain a library for analytics.
And it use also guzzle with an old version. (without request)

So the adwords library go to the wrong guzzle namespace.

What should i do to stay on /gapi_inc_new and not check the others folder ?

**Comment by fiboknacky** [comment]
I can't see all your project settings so it's hard to give one-shot solution but I'll try. :)
In general, I think you may have to find the place where autoloading does its job.
Try to avoid doing ad-hoc require() of many files, as it would be conflict with the settings of PSR-4 autoloading.

I think if two projects are separated, normally it shouldn't look into a wrong directory unless you have a code that explicitly does so.

**Comment by wedgemaster** [comment]
Yes I know, thanks by the way of trying to help me.
I didn't code this project, so i'm discovering too.

The analytics api lib and your adwords api lib is called at the same time and they are in the same directory level...
And obviously do the conflict with the namespace.

I think the solution is to rename all the namespace... more like a temporary fix.

**Comment by fiboknacky** [comment]
Do you mean the [google-api-php-client](https://github.com/google/google-api-php-client/blob/master/composer.json) repository?
If so, it seems that repo also allows for Guzzle [v6.0](https://github.com/google/google-api-php-client/blob/master/composer.json#L15) too.

Knack
