### ISSUE TITLE
 Uncaught SoapFault exception: [WSDL] SOAP-ERROR: 

### ISSUE THREAD

**Issue by hichamuim** [googleads/googleads-php-lib#357]
i use version V201402 
page AdsSoapClient.php ligne 169

> <b>Fatal error</b>:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201402/CampaignService?wsdl' : failed to load external entity &quot;https://adwords.google.com/api/adwords/cm/v201402/CampaignService?wsdl&quot;

**Comment by fiboknacky** [comment]
Hello @hichamuim 

v201402 was already sunset. Please migrate to use the latest version ([v201708](https://developers.google.com/adwords/api/docs/reference/release-notes/v201708)).
Usually, each version exists for around a year.
You can have a look at the deprecation schedule [here](https://developers.google.com/adwords/api/docs/sunset-dates).

Best,
Knack
