### ISSUE TITLE
Get Ads Instead of AdGroups

### ISSUE THREAD

**Issue by ejaymomentummedia** [googleads/googleads-php-lib#360]
Hi Adwords Team,

Do you have script for me to get Ads only, instead of Adgroups?
In the examples in BasicOperations. I found GetAdGroups.php only.

Thanks,

Ejay

**Comment by dklimkin** [comment]
Please see:

https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201708/BasicOperations/AddExpandedTextAds.php

as an example.
