### ISSUE TITLE
CombinedApprovalStatus not returning raw enum values

### ISSUE THREAD

**Issue by Code-Working** [googleads/googleads-php-lib#361]
Hello,

I've switched from API v201609 to v201708 a few days ago since v201609 is nearing its end.

However, it seems as if the CombinedApprovalStatus introduced in v201705 does not return raw enum values in the AD_PERFORMANCE_REPORT although I am telling the API to do so. For example, it returns `Approved (limited)` instead of `APPROVED_LIMITED`. Most of the columns are returned as expected.

I don't know if this is a php-lib specific issue since I'm only using this one.

Regards  
Code-Working

**Comment by dklimkin** [comment]
Hello Code-Working,

This issue is not specific to the library but an issue with the underlying API. Could you please report it on support forum instead?

  https://groups.google.com/forum/#!forum/adwords-api

Thank you.
