### ISSUE TITLE
AdGroupType returns empty string instead of UNKNOWN when enabling raw enum values in reports

### ISSUE THREAD

**Issue by Code-Working** [googleads/googleads-php-lib#362]
Hello,

similar to #361, I am downloading an AD_PERFORMANCE_REPORT with v201708 and enabling raw enum values.

However, the column AdGroupType returns an empty string instead of the expected `UNKNOWN`.

As for #361, I don't know if this is a php-lib specific issue but I'm reporting it here because I am using this API.

Regards  
Code-Working

**Comment by dklimkin** [comment]
Similarly, please follow up with AdWords API support team. Thank you.
