### ISSUE TITLE
Get Customer By ID

### ISSUE THREAD

**Issue by hichamuim** [googleads/googleads-php-lib#363]
Hello,

How Can I Get Customer Account By ID (Searching By Customer Id)?

**Comment by dklimkin** [comment]
Hello hichamuim,

Please check out the code examples under:

  https://github.com/googleads/googleads-php-lib/tree/master/examples/AdWords/v201708/AccountManagement

You'd need to use either CustomerService, or ManagedCustomerService depending on the hierarchy.

I am closing this issue as this is not a library bug. Please use the forum for general questions:

  https://groups.google.com/forum/#!forum/adwords-api

-Danial.
