### ISSUE TITLE
REPORTS API ERROR

### ISSUE THREAD

**Issue by ejaymomentummedia** [googleads/googleads-php-lib#364]
Hi Adwords Team,

I'm using reporting API for the past 6 hrs and its working properly. Then all of a sudden I received this error.

Fatal error: Uncaught exception 'Google\AdsApi\AdWords\v201708\cm\ApiException' with message 'Details: [fieldPath: ; trigger: Basic Access Daily Reporting Quota; errorString: RateExceededError.RATE_EXCEEDED]' in C:\xampp\htdocs\api\adwords\vendor\googleads\googleads-php-lib\src\Google\AdsApi\AdWords\Reporting\v201708\ReportDownloader.php:160 Stack trace: #0 C:\xampp\htdocs\api\adwords\vendor\googleads\googleads-php-lib\src\Google\AdsApi\AdWords\Reporting\v201708\ReportDownloader.php(127): Google\AdsApi\AdWords\Reporting\v201708\ReportDownloader->makeReportRequest(Array) #1 C:\xampp\htdocs\api\cron.php(340): Google\AdsApi\AdWords\Reporting\v201708\ReportDownloader->downloadReportWithAwql('SELECT Campaign...', 'CSV', Object(Google\AdsApi\AdWords\ReportSettings)) #2 C:\xampp\htdocs\api\cron.php(36): get_ads() #3 {main} thrown in C:\xampp\htdocs\api\adwords\vendor\googleads\googleads-php-lib\src\Google\AdsApi\AdWords\Reporting\v201708\ReportDownloader.php on line 160

I also tried running your example code in reporting. and it gave me the same error.

Thanks,

Ejay

**Comment by fiboknacky** [comment]
Hi Ejay,

The error shows that you have exceeded the [daily limit](https://developers.google.com/adwords/api/docs/ratesheet#adwords-api-access-levels) of reporting requests of basic access, which is 1000 per day.
Please consider apply for standard access if you'd like to download more than 1000 reports per day.

As this is related to AdWords API in general, please contact our [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api) for further help if needed.

Thanks.
Knack
