### ISSUE TITLE
Fatal error inside Guzzle when requesting account information 

### ISSUE THREAD

**Issue by acmwallace** [googleads/googleads-php-lib#365]
I am trying to upgrade to the latest version of the Google Ads system, and am running into an issue with Guzzle.
a) I grabbed all the files with composer, but moved them into our file tree, because otherwise, the changes would be rather horrific in terms if the time required. All the files are inside a "lib" directory inside our code tree (which is where the older Google Ads PHP API files were).
b) I am trying to get a list of the accounts from a managed customer service.

My code:

$oAuth2Credential = ( new OAuth2TokenBuilder() )
        ->fromFile( $this->CONFIG_FILE_PATH )
        ->build();

$adwords_session = ( new AdWordsSessionBuilder() )
        ->fromFile( $this->CONFIG_FILE_PATH )
        ->withOAuth2Credential($oAuth2Credential)
        ->build();

$adWordsServices = new AdWordsServices();

$managedCustomerService = $adwords_services->get( $adwords_session, ManagedCustomerService::class );

$selector = new Selector();
$selector->setFields( [ 'CustomerId',  'Name' ] );
$selector->setOrdering( [new OrderBy('CustomerId', SortOrder::ASCENDING)] );
$selector->setPaging(new Paging(0, 50));

// Make the get request.
$page = $managedCustomerService->get($selector);

Unfortunately, the "get($selector)" line throws an exception:

exception 'Exception' with message 'exception 'InvalidArgumentException' with message 'URI must be a string or UriInterface' in /home/httpd/idxv3/lib/GuzzleHttp/Psr7/functions.php:62

Not sure what's going on. THat's pretty deep inside the codebase. Any thoughts?

thanks,
Andy

**Comment by fiboknacky** [comment]
Hi Andy,

I'd recommend to install using composer on the server.
Or else you may need to ensure all dependencies are fetched correctly.
My initial guess is that your Guzzle might not be of a correct version.
I've seen some cases where users just have other libs installed on their systems and installed Guzzle is not a right one that is needed by this library.

Is it possible for you to run [GetAccountHierarchy](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201708/AccountManagement/GetAccountHierarchy.php) example?

Best,
Knack

**Comment by acmwallace** [comment]
Arg. We have almost 20 webservers. In order to make this work by using
Composer to install it, I'm not even sure what hoops I'm going to have to
go through to get it on all those machines (which come and go at the whim
of Google Cloud Services).

I'll see if I can set up my machine as a webserver to test the example.

--
IHOUSEWEB Inc.
8950 Cal Center Dr
bldg. 1 suite 202
Sacramento, CA 95826

Andy Wallace | Senior Software Engineer | 916-246-7777 |
awallace@ihouseweb.com

**Comment by fiboknacky** [comment]
Hello @acmwallace 

Is there anything we can help on our side?
If not, I'll close this issue soon.

Best,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity.
