### ISSUE TITLE
PHP Fatal error:  Cannot redeclare class Google\AdsApi\Common\OAuth2TokenBuilder in

### ISSUE THREAD

**Issue by spatadeidg** [googleads/googleads-php-lib#366]
I am using the latest version of Ads and followed along the mentioned steps and getting the following error PHP Fatal error:  Cannot redeclare class Google\AdsApi\Common\OAuth2TokenBuilder **in
app/Vendor/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/OAuth2TokenBuilder.php on line 29

I am using the example mentioned here https://github.com/googleads/googleads-php-lib/blob/master/examples/Dfp/v201708/CreativeService/GetAllCreatives.php

Also, not able to see examples and test folder from repo

![image](https://user-images.githubusercontent.com/32145079/30666628-f844562c-9e22-11e7-9f74-38fd17ce58cb.png)

**Comment by fiboknacky** [comment]
Hello @spatadeidg 

How did you get our lib? Through `composer require`?
If you wish to run examples, could you please follow [this instruction](https://github.com/googleads/googleads-php-lib#running-examples)?

Best,
Knack

**Comment by spatadeidg** [comment]
Hey Knack, 

Nevermind, I was able to resolve the issue.  Yes,  I am using composer require.

Thanks,
Sagar

**Comment by fiboknacky** [comment]
Thanks for letting me know. :)
