### ISSUE TITLE
Policy Violation Issues

### ISSUE THREAD

**Issue by ztobs** [googleads/googleads-php-lib#369]
Hi Knack,

I dont understand why policy violation should become a pain in the ass to handle.
I used https://developers.google.com/adwords/api/docs/samples/php/error-handling to take care of some violations when creating both ads and adgroups and they were fine.
Only for another policy violation (related to drug this time) popping up.

Must fatal errors be thrown during violation, at most a notice it should be. Then the ad should be skipped.
I need to run a script that creates and manages campaigns, adgroups, ads and keywords. So i cant afford to allow a policy violation halt the whole process.

Here is the error:
`Fatal error: Uncaught Google\AdsApi\AdWords\v201708\cm\ApiException: [PolicyViolationError{super=PolicyViolationError.POLICY_ERROR @ operations[1].operand.ad.description, key=PolicyViolationKey{policyName=ru_biologically_active_additive,violatingText=Lutein}, externalPolicyName=Google AdWords, externalPolicyUrl=, externalPolicyDescription=This ad or keyword requires review before it can run., isExemtable=true, violatingParts=[Part{index=31, length=6}]}, PolicyViolationError{super=PolicyViolationError.POLICY_ERROR @ operations[0].operand.ad.description, key=PolicyViolationKey{policyName=ru_biologically_active_additive,violatingText=Lutein}, externalPolicyName=Google AdWords, externalPolicyUrl=, externalPolicyDescription=This ad or keyword requires review before it can run., isExemtable=true, violatingParts=[Part{index=31, length=6}]}]`

**Comment by fiboknacky** [comment]
Hello Lukan,

Would [this HandlePolicyViolationError example](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201708/ErrorHandling/HandlePolicyViolationError.php) help your case?
Based on the log, it's exemtable error so you should be able to ask for policy exemption.

Please see [this guide](https://developers.google.com/adwords/api/docs/guides/exemption-requests) for detail.
In case you have further questions about AdWords API in general, I recommend to post your questions in [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api).

Best,
Knack

**Comment by fiboknacky** [comment]
Close due to in activity. If you still run into a problem, feel free to let me know.
