### ISSUE TITLE
ERROR IN DURING CLAUSE

### ISSUE THREAD

**Issue by ejaymomentummedia** [googleads/googleads-php-lib#371]
Hi Adwords Team,

I get an error in using ALL_TIME in during clause in CRITERIA_PERFORMANCE_REPORT:

 $reportQuery = 'SELECT CampaignName, CampaignId, '
		. 'Impressions, Clicks, Ctr FROM CRITERIA_PERFORMANCE_REPORT '
   		 . 'WHERE CampaignId = '.$adwords_id.' AND Status IN [ENABLED, PAUSED] DURING ALL_TIME';

But upon using YESTERDAY, it works:

 $reportQuery = 'SELECT CampaignName, CampaignId, '
		. 'Impressions, Clicks, Ctr FROM CRITERIA_PERFORMANCE_REPORT '
   		 . 'WHERE CampaignId = '.$adwords_id.' AND Status IN [ENABLED, PAUSED] DURING YESTERDAY';

Thanks,

Ejay

**Comment by fiboknacky** [comment]
Hello Ejay,

This issue is more related to the AdWords API product.
Could you please post your question in the [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api) instead?

Thank you in advance.
Knack

**Comment by ejaymomentummedia** [comment]
Hi Knack,

ok thanks :)
