### ISSUE TITLE
 Error: Data expected to be an array, NULL given. 

### ISSUE THREAD

**Issue by nk-nareshkumar** [googleads/googleads-php-lib#374]
Hi,

i am getting this error : 

> Notice (8): Undefined index: ApiError [ROOT/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/Reporting/v201708/ReportDownloader.php, line 160]
> 
> Warning (4096): Argument 1 passed to Google\AdsApi\AdWords\AdWordsNormalizer::isOneOrMany() must be of the type array, null given, called in /var/www/PATH/adwords-api/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/Reporting/v201708/ReportDownloader.php on line 160 and defined [ROOT/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/AdWordsNormalizer.php, line 280]
> 
> Notice (8): Undefined index: ApiError [ROOT/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/Reporting/v201708/ReportDownloader.php, line 162]

and 

**Error: Data expected to be an array, NULL given.**  in this line : 

```
 $reportDownloadResult = $reportDownloader->downloadReport(
                $reportDefinition, $reportSettingsOverride);
```

Here is my file link : https://gist.github.com/nk-nareshkumar/b01139bcb17ada932fa2bdd24c38b1d2

**What we are doing:**
We have successfully got refresh token by google Auth. And after login we are trying to get all report first by client id, client secret, developer token, refresh token. Ads session built successfully, got customer id also.

**What we are getting :**
We are getting blank file with any extension like csv. Getting some error Data expected to be an array, NULL given. 

Please guide us where we are wrong.

Thanks
Naresh Kumar

**Comment by fiboknacky** [comment]
Hello Naresh,

Could you please tell what version of the client library you're using?
And can you run our example, [DownloadCriteriaReportWithAwql](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201708/Reporting/DownloadCriteriaReportWithAwql.php)?

Best,
Knack

**Comment by nk-nareshkumar** [comment]
Hi there,

We are using v201708 here.
and we don't want to set adsapi_php.ini for each client as we have 100 adwords users . it should be automatic like 

We also tried same [DownloadCriteriaReportWithAwql](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201708/Reporting/DownloadCriteriaReportWithAwql.php) 

But we dont want to set adsapi_php.ini for each client. as we are running a cron job and fetching reports for clients.

Is there any issue with ->withClientCustomerId ?

How to get client customer id for each client ?


```

$oAuth2Credential = (new OAuth2TokenBuilder())
                ->withClientId(Configure::read('GOOGLE_OAUTH_CLIENT_ID'))
                ->withClientSecret(Configure::read('GOOGLE_OAUTH_CLIENT_SECRET'))
                ->withRefreshToken($refresh_token)
                ->build();
       

$session = (new AdWordsSessionBuilder())
                ->withUserAgent('YOUR USER AGENT')
                ->withDeveloperToken('YOUR DEVELOPER TOKEN')
                ->withOAuth2Credential($oAuth2Credential)
                ->build();
```

**Comment by fiboknacky** [comment]
Hello,

Sorry if I wasn't clear. I meant the version of client library (e.g., [v29.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/29.0.0), [v30.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/30.0.0)), not the API version.

So you still get the same error when running our example as is?

Regarding your other questions,

> and we don't want to set adsapi_php.ini for each client as we have 100 adwords users . it should be automatic like here in code as we are running a cron job and fetching reports for clients.

You can partially use the `adsaapi_php.ini` as well. Just change the attribute you wish, e.g., `clientCustomerId`.
So you can do something like this:

```php
  $session = (new AdWordsSessionBuilder())
        ->fromFile()
        ->withOAuth2Credential($oAuth2Credential)
        ->withClientCustomerId('INSERT_YOUR_CLIENT_CUSTOMER_ID')
        ->build();
```

Finally, to get client customer ID for each client account in case you know and have access to the manager account ID, use [CustomerService.getCustomers()](https://developers.google.com/adwords/api/docs/reference/v201708/CustomerService#getCustomers)
You can retrieve the ID via [customerId](https://developers.google.com/adwords/api/docs/reference/v201708/CustomerService.Customer#customerid).

Best,
Knack
