### ISSUE TITLE
 Not getting Auth refresh token with every request 

### ISSUE THREAD

**Issue by nk-nareshkumar** [googleads/googleads-php-lib#375]
Hi,

I am not able to get Auth refresh_token on every request.  If any accidental activity occur by client like no INTERNET while fetching refresh token or missed to save it then new OAuth2  will not return refresh token again. so, i want refresh token in every request. We are using this refresh token for cron job to fetch adwords report. Please guide me. 

**More about us:**
We have a platform written in PHP which have more than 500 clients who has Adwords account.
First user will authorize us to fetch his report when he is not online.. So for this we implemented a Web Application Flow. with this we can get the Access Token and refresh token. These token we can use to fetch report from server to server when client is not online.. 
We are sending a request on Google server to fetch reports from all of our client in batch. thats called our cron job which run after every 10-15 min at every day.

Please find pasted code 

```
use Google\Auth\OAuth2;

public function login() {
      $oauth2 = new OAuth2([
            'authorizationUri' => 'https://accounts.google.com/o/oauth2/v2/auth',
            'tokenCredentialUri' => 'https://www.googleapis.com/oauth2/v4/token',
            'redirectUri' => 'GOOGLE_OAUTH_REDIRECT_URI',
            'clientId' => 'GOOGLE_OAUTH_CLIENT_ID',
            'clientSecret' => 'GOOGLE_OAUTH_CLIENT_SECRET',
            'scope' => 'https://www.googleapis.com/auth/adwords'            
        ]);

        if (!isset($_GET['code'])) {
            
            $config = [
                'access_type' => 'offline'
            ];
            header('Location: ' . $oauth2->buildFullAuthorizationUri($config));
            exit; 

        } else {
           
            $oauth2->setCode($_GET['code']);
            $authToken = $oauth2->fetchAuthToken();
            
           echo $authToken['refresh_token'];
           exit; 
        }
}
```

Thank You
Naresh

**Comment by nk-nareshkumar** [comment]
I am pasting here my old version Api (released 2016) script. which i was going to get refresh token on every hit if old hit failed because of any technical issue.

It was working perfect , but with new 2017 Adwords api i want to do same so that i can run my offline cron job with these token.


```
function getAccessRefreshToken($code) {

        $Rec_Data = array();

        if (!empty($code)) {

            $postFields = 'client_id=' . Configure::read('AW_CLIENT_ID') . '&client_secret=' . Configure::read('AW_CLIENT_SECRET') . '&code=' . $code . '&grant_type=authorization_code&redirect_uri=' . Configure::read('REDIRECT_URI');

            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, 'https://accounts.google.com/o/oauth2/token');
            curl_setopt($ch, CURLOPT_POSTFIELDS, $postFields);

            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
            curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);

            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

            $Rec_Data = curl_exec($ch);


            if (curl_exec($ch) === false) {
                return $Rec_Data;
                //echo 'Curl error: ' . curl_error($ch);
            }

            $Rec_Data = json_decode($Rec_Data, true);
        }

        return $Rec_Data;
    }
```

**Comment by fiboknacky** [comment]
Hello @nk-nareshkumar,

> I am not able to get Auth refresh_token on every request. If any accidental activity occur by client like no INTERNET while fetching refresh token or missed to save it then new OAuth2 will not return refresh token again. so, i want refresh token in every request. We are using this refresh token for cron job to fetch adwords report. Please guide me.

Based on your statement, would it be possible for you to retry OAuth2 process in such a case?
Once you obtain a refresh token, you could store in your databases as [Google OAuth2 refresh tokens don't expire](https://developers.google.com/adwords/api/docs/guides/authentication#an_alternative_to_service_accounts).

You probably would need to run this process once for each new client.

Best,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity.
