### ISSUE TITLE
multiple HandlePolicyViolationError per object

### ISSUE THREAD

**Issue by pfranck** [googleads/googleads-php-lib#378]
Hi ! 
Is it possible to change in the example the line 105 :
https://github.com/googleads/googleads-php-lib/blob/f6f58cddbf95a5cada38469441a6ee1155ecc476/examples/AdWords/v201710/ErrorHandling/HandlePolicyViolationError.php#L105

by :` $operation->setExemptionRequests(array_merge($operation->getExemptionRequests()?:[],[ new ExemptionRequest($error->getKey())]));` to handle the multi policyViolationError 

thanks a lot

**Comment by fiboknacky** [comment]
Hello @pfranck,

Thanks for suggestion.
This is in our radar already. I'll leave this opened until I push the change.

Best,
Knack

**Comment by fiboknacky** [comment]
This is fixed with [v32.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/32.0.0).
