### ISSUE TITLE
ReportDownloder downloadReport method returns stream instead of contents

### ISSUE THREAD

**Issue by Jafo232** [googleads/googleads-php-lib#381]
When calling downloadReport with a null filepath, it is returning a stream, not the contents.

Shouldn't:

`return $response->getBody();`

Be this instead?:

`return $response->getContents()`

Then it would retain the way it used to be.

**Comment by fiboknacky** [comment]
Hello @Jafo232 

Could you specify which line of what file in our library?
The current [ReportDownloader::downloadReport](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/Reporting/v201710/ReportDownloader.php#L102) returns [ReportDownloadResult](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/Reporting/ReportDownloadResult.php), so I'm not sure which file do you mean.

Best,
Knack

**Comment by Jafo232** [comment]
Here is the code:

```
 /**
   * Downloads the report with the specified export format.
   *
   * @param string $exportFormat the export format of the report
   * @param string $filePath an optional file path to download the report to
   * @return void|StreamInterface nothing if a file path is specified, otherwise
   *     report contents as a stream
   * @throws UnexpectedValueException if the report is still in progress or has
   *     failed
   */
  public function downloadReport($exportFormat, $filePath = null) {
    $downloadUrl = $this->getDownloadUrl($exportFormat);

    $requestOptions = [];
    $requestOptions[RequestOptions::HEADERS] = [
        'User-Agent' => $this->getFormattedUserAgent()
    ];
    $proxy = $this->reportService->getAdsSession()->getConnectionSettings()
        ->getProxyUrl();
    if (!empty($proxy)) {
      $requestOptions[RequestOptions::PROXY] = ['https' => $proxy];
    }
    if ($filePath !== null) {
      $requestOptions[RequestOptions::SINK] = $filePath;
      $this->httpClient->request('GET', $downloadUrl, $requestOptions);
    } else {
      $requestOptions[RequestOptions::STREAM] = true;
      $response = $this->httpClient->request(
          'GET', $downloadUrl, $requestOptions);
      return $response->getBody();
    }
  }
```

**Comment by Jafo232** [comment]
Located here:

https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Dfp/Util/v201708/ReportDownloader.php

**Comment by fiboknacky** [comment]
Thanks for pointing out. 
If you compare this to the old library, then we meant it this way as [StreamInterface](https://github.com/php-fig/http-message/blob/master/src/StreamInterface.php) is more versatile.
You could use it as a stream or just convert to a string yourself by calling `$response->getBody()->getContents()`.

Knack

**Comment by fiboknacky** [comment]
As there is no further question, and the answer is already given, I'll close this issue.
Let me know if you have additional questions.
