### ISSUE TITLE
TargetingIdeaService doesn't return stats or ideas for some keywords

### ISSUE THREAD

**Issue by DouglasGLewis** [googleads/googleads-php-lib#383]
here is an example of two keywords that don't return STATS information on the actual keyword (there are many more)
natural recovery supplement
grief (or any multi word keyword that includes grief). Actually, grief doesen't even return IDEAS.

Also quite often, the IDEAS results return numbers that very significantly from the Google keyword planner. Below are the results that I look for.
	    	AttributeType::SEARCH_VOLUME,
	    	AttributeType::AVERAGE_CPC,
	    	AttributeType::COMPETITION

**Comment by fiboknacky** [comment]
Hello @DouglasGLewis 

As this is related to AdWords API in general, could you please your question in [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api) instead?

Thanks.
Knack
