### ISSUE TITLE
phpdocumentor/reflection-docblock 4.1.1

### ISSUE THREAD

**Issue by braankoo** [googleads/googleads-php-lib#385]
hi. Im having same issue here. Laravel 5.5
when i try to install package i get:
` Problem 1
    - Installation request for googleads/googleads-php-lib ^31.0 -> satisfiable by googleads/googleads-php-lib[31.0.0].
    - Conclusion: remove phpdocumentor/reflection-docblock 4.1.1
    - Conclusion: don't install phpdocumentor/reflection-docblock 4.1.1
    - googleads/googleads-php-lib 31.0.0 requires phpdocumentor/reflection-docblock ^3.0.3 -> satisfiable by phpdocumentor/reflection-docblock[3.0.3, 3.1.0, 3.1.1, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.3.0].
    - Can only install one of: phpdocumentor/reflection-docblock[3.0.3, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.0, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.1, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.0, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.1, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.2, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.3, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.3.0, 4.1.1].
    - Installation request for phpdocumentor/reflection-docblock (locked at 4.1.1) -> satisfiable by phpdocumentor/reflection-docblock[4.1.1].`

Phpunit is using reflection-docblock.
here is part of composer tree:
`phpunit/phpunit 6.4.3 The PHP Unit Testing framework.
|  `--php ^5.6 || ^7.0
|  |  `--php ^5.6 || ^7.0
|  `--php ^5.6 || ^7.0
|  `--php ^5.6 || ^7.0
|--php ^7.0
|--phpspec/prophecy ^1.7
|  |  `--php ^7.1
|  |--php ^5.3|^7.0
|  |--phpdocumentor/reflection-docblock ^2.0|^3.0.2|^4.0
|  |  |--php ^7.0
|  |  |--phpdocumentor/reflection-common ^1.0@dev
|  |  |  `--php >=5.5
|  |  |--phpdocumentor/type-resolver ^0.4.0
|  |  |  |--php ^5.5 || ^7.0
|  |  |  `--phpdocumentor/reflection-common ^1.0
|  |  |     `--php >=5.5
|  |     `--php ^5.3.3 || ^7.0
|  |  |--php ^7.0
|  |  |  `--php ^7.0
|  |     |--php ^7.0
|  |        `--php ^7.0
|     `--php ^7.0
|--phpunit/php-code-coverage ^5.2.2
|  |--php ^7.0
|  |--phpunit/php-file-iterator ^1.4.2
|  |  `--php >=5.3.3
|  |--phpunit/php-text-template ^1.2.1
|  |  `--php >=5.3.3
|  |--phpunit/php-token-stream ^1.4.11 || ^2.0
|  |  `--php ^7.0
|  |  `--php ^5.6 || ^7.0
|  |  `--php ^7.0
|  |  `--php >=5.6
|     `--php ^7.0
|--phpunit/php-file-iterator ^1.4.2
|  `--php >=5.3.3
|--phpunit/php-text-template ^1.2.1
|  `--php >=5.3.3
|--phpunit/php-timer ^1.0.9
|  `--php ^5.3.3 || ^7.0
|--phpunit/phpunit-mock-objects ^4.0.3
|  |  `--php ^7.1
|  |--php ^7.0
|  |--phpunit/php-text-template ^1.2.1
|  |  `--php >=5.3.3
|     |--php ^7.0
|        `--php ^7.0
|  |--php ^7.0
|  |  `--php ^7.0
|     |--php ^7.0
|        `--php ^7.0
|  `--php ^7.0
|  `--php ^7.0
|  |--php ^7.0
|     `--php ^7.0
|  `--php ^7.0
|  |--php ^7.0
|  |  `--php ^7.0
|     `--php ^7.0
|  `--php >=5.6.0
   `--php >=5.6
`

Any idea ?

**Comment by fiboknacky** [comment]
Hello Branko,

Before we release the next version, could you please use 
`composer require googleads/googleads-php-lib:dev-master` as a workaround?
This will fetch the latest `composer.json`, which has been updated to allow `phpdocumentor/reflection-docblock` version 4.1.1.

Best,
Knack

**Comment by braankoo** [comment]
Thank you Knack.
All working fine now :)

**Comment by fiboknacky** [comment]
Glad that's working!
I'm closing this issue.
