### ISSUE TITLE
Google Adwords fatal error 

### ISSUE THREAD

**Issue by ravitechximum** [googleads/googleads-php-lib#386]
Catchable fatal error: Argument 1 passed to Google\AdsApi\Common\Configuration::__construct() must be of the type array, null given, called in /home/techximu/public_html/adwords/adpulse/wp-content/plugins/adwordsapi/admin/views/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/ConfigurationLoader.php on line 80 and defined in /home/techximu/public_html/adwords/adpulse/wp-content/plugins/adwordsapi/admin/views/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Configuration.php on line 32

**Comment by fiboknacky** [comment]
Hi @ravitechximum 

Could you please include more details?
What are you trying to do and what's in your `adsapi_php.ini`?

Cheers,
Knack

**Comment by ravitechximum** [comment]
Hi,

I have created the  Adwords API plugin for displaying reports from AdWords campaigns. But when we activate the plugin it sends me the fatal errors.

**Here is my adsapi_php.ini**


[ADWORDS]
; Required AdWords API properties. Details can be found at:
; https://developers.google.com/adwords/api/docs/guides/basic-concepts#soap_and_xml
developerToken = "s8r_6DRH7pXHjAaL6PlNXQ"
clientCustomerId = "477-***-****"


; Optional. Set a friendly application name identifier.
; userAgent = "INSERT_USER_AGENT_HERE"

; Optional additional AdWords API settings.
; endpoint = "https://adwords.google.com/"
; isPartialFailure = false

; Optional setting for utility usage tracking in the user agent in requests.
; Defaults to true.
; includeUtilitiesInUserAgent = true

[ADWORDS_REPORTING]
; Optional reporting settings.
; isSkipReportHeader = false
; isSkipColumnHeader = false
; isSkipReportSummary = false
; isUseRawEnumValues = false

[OAUTH2]
; Required OAuth2 credentials. Uncomment and fill in the values for the
; appropriate flow based on your use case. See the README for guidance:
; https://github.com/googleads/googleads-php-lib/blob/master/README.md#getting-started

; For installed application or web application flow.
clientId = "13940536277-83kfq6ijhcf6ovolf4ju6qq9h2rie63m.apps.googleusercontent.com"
clientSecret = "GV0mXh0P0ZsAQxFswCnkhGfo"
refreshToken = "1/Czaof9rRKOl_uz3UMoY5bVdKGeTfEi9SfDbyewt-xLg"

; For service account flow.
; jsonKeyFilePath = "INSERT_ABSOLUTE_PATH_TO_OAUTH2_JSON_KEY_FILE_HERE"
; scopes = "https://www.googleapis.com/auth/adwords"
; impersonatedEmail = "INSERT_EMAIL_OF_ACCOUNT_TO_IMPERSONATE_HERE"

[SOAP]
; Optional SOAP settings. See SoapSettingsBuilder.php for more information.
; compressionLevel = <COMPRESSION_LEVEL>
; wsdlCache = <WSDL_CACHE>

[PROXY]
; Optional proxy settings to be used by SOAP requests.
; host = "<HOST>"
; port = <PORT>
; user = "<USER>"
; password = "<PASSWORD>"

[LOGGING]
; Optional logging settings.
; soapLogFilePath = "path/to/your/soap.log"
; soapLogLevel = "INFO"
; reportDownloaderLogFilePath = "path/to/your/report-downloader.log"
; reportDownloaderLogLevel = "INFO"
; batchJobsUtilLogFilePath = "path/to/your/bjutil.log"
; batchJobsUtilLogLevel = "INFO"

**Comment by fiboknacky** [comment]
Do you still face with this issue? It looks like you close this one.

**Comment by ravitechximum** [comment]
Yes, we have  still face with this issue




*Thanks & Regards*

*Ravi Kumar *
*Sr. Web Developer*

Office:* 011-49066772*
Email:* ravi.techXimum@gmail.com <ravi.techXimum@gmail.com> *| Web:*
www.techXimum.com.au
<http://www.techximum.com.au/>*
Address:* D466, Shiksha Bharti Road, Ramphal Chowk, Sec-7, Dwarka, New
Delhi-110077*
TechXimum Solutions treats personal information seriously. Please view our
Privacy Policy on our website.

**Comment by dklimkin** [comment]
@ravitechximum you've just posted some of the sensitive fields to the public resource. Please make sure to:
1. Reset your developer token:
  https://developers.google.com/adwords/api/docs/guides/reset-devtoken
2. Revoke the OAuth client credentials for this ClientID and Client Secret. You can re-create the new credentials immediatelly.

**Comment by ravitechximum** [comment]
yes, we reset your developer token:

**Comment by fiboknacky** [comment]
Hello @ravitechximum 

It looks like you've not used the latest version of the library. Could you tell me what version of the library you're using please?

And 
> But when we activate the plugin it sends me the fatal errors.

Could you specify how you "activated the plugin"?
I guess you've not run our examples. Could you attach your code snippet here?

Thanks in advance.

Best,
Knack

**Comment by fiboknacky** [comment]
I close this to inactivity. Please let us know if you have further issues.
