### ISSUE TITLE
AdGroupAdReturnValue Protected Objects json_encode issue.

### ISSUE THREAD

**Issue by aonurbilgin** [googleads/googleads-php-lib#388]
Hi,

json_encode() only serializes the publicly visible properties of an object. 
Is there any method for protected result objects ?

I have tried get_object_vars() btw.

Thanks

**Comment by fiboknacky** [comment]
Hello @aonurbilgin 

Are you trying to serialize results from calling SOAP services into JSON?
What I can think of now is [Symfony Serializer](https://symfony.com/doc/current/components/serializer.html).
We use it in batch processing's normalization and serialization to XML as well.
That library supports serialization to JSON too.

Best,
Knack

**Comment by aonurbilgin** [comment]
Hi @fiboknacky 

Yes I'm trying to  serialize results from calling SOAP services into JSON. Project writen with Symfony and working as a REST API. So in that case project use JsonResponse Class for showing results. Now i have tried Symfony Serializer and its serialize object but for the JsonResponse class i have to use json_decode($jsonContent). This method looks like have some unnecessary process

Serialized Object;
`{\"operand\":{\"adGroupId\":1111111111,\"ad\":{\"headlinePart1\":\"headline 1\",\"headlinePart2\":\"headline 2\",\"description\":\"description\",\"path1\":\"path1\",\"path2\":\"path2\",\"id\":null,\"url\":null,\"displayUrl\":null,\"finalUrls\":[\"http:\\/\\/www.website.com\"],\"finalMobileUrls\":null,\"finalAppUrls\":null,\"trackingUrlTemplate\":null,\"urlCustomParameters\":null,\"urlData\":null,\"automated\":null,\"type\":null,\"devicePreference\":null,\"AdType\":null},\"status\":\"PAUSED\",\"policySummary\":null,\"labels\":null,\"baseCampaignId\":null,\"baseAdGroupId\":null,\"forwardCompatibilityMap\":null},\"exemptionRequests\":null,\"operator\":\"ADD\",\"OperationType\":null}`

Result I want;
```
{
    "result": {
        "operand": {
            "adGroupId": 1111111111,
            "ad": {
                "headlinePart1": "headline 1",
                "headlinePart2": "headline 2",
                "description": "description",
                "path1": "path1",
                "path2": "path2",
                "id": null,
                "url": null,
                "displayUrl": null,
                "finalUrls": [
                    "http://www.website.com"
                ],
                "finalMobileUrls": null,
                "finalAppUrls": null,
                "trackingUrlTemplate": null,
                "urlCustomParameters": null,
                "urlData": null,
                "automated": null,
                "type": null,
                "devicePreference": null,
                "AdType": null
            },
            "status": "PAUSED",
            "policySummary": null,
            "labels": null,
            "baseCampaignId": null,
            "baseAdGroupId": null,
            "forwardCompatibilityMap": null
        },
        "exemptionRequests": null,
        "operator": "ADD",
        "OperationType": null
    }
}

```

**Comment by fiboknacky** [comment]
Hello,

I'm not quite sure I understand you correctly, but the result you've shown looks like the normal result from Symfony serialization. Can't you achieve that using Symfony Serializer?

json_decode looks irrelevant to me as what you're trying to achieve is to encode or serialize, not decode, right?
Please correct me if I misunderstand.

Best,
Knack

**Comment by fiboknacky** [comment]
I close this to inactivity. Please let us know if you have further issues.
