### ISSUE TITLE
Getting no SV in TargetingIdea on specific keywords

### ISSUE THREAD

**Issue by Fundaris** [googleads/googleads-php-lib#389]
Hey somehow I get no searchvolume for some keywords via API

My selector:
https://pastebin.com/bP3MmDgA

$targetingIdeaService->get($selector)
object(Google\AdsApi\AdWords\v201705\o\TargetingIdeaPage)#60 (2) {
  ["totalNumEntries":protected]=>
  int(0)
  ["entries":protected]=>
  NULL
}

When I **remove** _Kurt cobain_ I get Search volume for all remaining keywords. I get also SV for _assassins creed klamotten_ so its not the space and queuing  _Kurt cobain_ alone also results in no SV.

Soap-log:
[2017-10-27 12:06:46] AW_SOAP.INFO: clientCustomerId=XXXX operations=1 service=TargetingIdeaService method=get responseTime=400 requestId=XXXX server=adwords.google.com isFault=0 faultMessage= 

We noticed it today with Rel 28.1 and even updating to 31.0 didnt helped.

**Comment by fiboknacky** [comment]
Hello @Fundaris 

This issue is related to [this topic](https://groups.google.com/forum/#!topic/adwords-api/HGLEHuA9xUw) in AdWords API forum.
As this issue is not related directly to this library, could you please add your case there instead?

Thank you.

Best,
Knack
