### ISSUE TITLE
Campaign Performance Data - Mismatch with Adwords Dashboards

### ISSUE THREAD

**Issue by ashishodia** [googleads/googleads-php-lib#390]
Hi Team,

We have some data mis-macted with Google Adwords data when we are using this API.

We have fetched the data for date 2017-10-03 for a account and validating it with Google Adwords Account data. We found that some campiagn clicks are not matching.

For Example below campaign data from API library (Doors 2017 has 2 clicks). however, adwords shows it 27(this is for 3rd Oct data- will share the account ID with you in a sperate request).

Brand 2017	17
Doors 2017	2
Edgebands 2017	17
Furniture 2017	26
Windows & Door 2017	4
Windows 2017	25

Please provide us RCA, as we reporting this data in Reporting and Analysis part.

**Comment by ashishodia** [comment]
Hi Team,

Any update on the same. connect me at ankur.shishodia@adglobal360.com

**Comment by dklimkin** [comment]
Hello @ashishodia,

This issue tracker is for library specific bugs and issues only. For general AdWords API questions please refer to the support forum instead:

  https://groups.google.com/forum/#!forum/adwords-api

**Comment by ashishodia** [comment]
Thansks for sharing the feedback.

Yes, we are seing this API level issue, Please look into this so that we can investigate more.

**Comment by dklimkin** [comment]
Hello @ashishodia, please ask this question on the forum instead. Thank you.

  https://groups.google.com/forum/#!forum/adwords-api

**Comment by ashishodia** [comment]
Thanks Posted on Forum as well
