### ISSUE TITLE
Error trapping with the library

### ISSUE THREAD

**Issue by DouglasGLewis** [googleads/googleads-php-lib#391]
I'm using the latest version of this library and am having trouble trapping RATE_EXCEEDED errors. I wrap my calls in a try catch block but the error happens in the library code so it just stops execution. Any Ideas?

here is the error:
Fatal error</b>:  Uncaught Google\AdsApi\AdWords\v201710\cm\ApiException: [RateExceededError &lt;rateName=RATE_LIMIT, rateKey=null, rateScope=ACCOUNT, retryAfterSeconds=30&gt;] in /var/www/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php:39
Stack trace:
#0 /var/www/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(39): ReflectionClass-&gt;newInstanceArgs(Array)
#1 /var/www/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(165): Google\AdsApi\Common\Util\Reflection-&gt;createInstance('Google\\AdsApi\\A...', Array)
#2 /var/www/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(130): Google\AdsApi\Common\AdsSoapClient-&gt;parseApiExceptionFromSoapFault(Object(SoapFault))
#3 /var/www/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201710/o/TargetingIdeaService.php(152): Google\AdsApi\Common\AdsSoapClient-&gt;__soapCall('get', Array)
#4 /var/www/html/main/code_v2.php(489): Google\AdsApi\AdWords\v201710\o\TargetingIdeaServ in <b>/var/www/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php</b> on line <b>39</b><br />

**Comment by DouglasGLewis** [comment]
One further comment would be this is a sporadic event (maybe one out of every 20 requests) and the line in my code that produces this error is $targetingIdeaService->get($selector);

**Comment by fiboknacky** [comment]
Hello @DouglasGLewis 

> I wrap my calls in a try catch block but the error happens in the library code so it just stops execution. Any Ideas?

Could you please show your code snippet? Doesn't catch block for the ApiException work?

Best,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity. Please let us know if you still need help.
