### ISSUE TITLE
Getting an error while installing

### ISSUE THREAD

**Issue by deepaksaini6413** [googleads/googleads-php-lib#392]
Problem 1
    - Installation request for googleads/googleads-php-lib ^31.0 -> satisfiable by googleads/googleads-php-lib[31.0.0].
    - Conclusion: don't install guzzlehttp/guzzle 6.3.0
    - Conclusion: don't install guzzlehttp/guzzle 6.2.3
    - Conclusion: don't install guzzlehttp/guzzle 6.2.2
    - Conclusion: don't install guzzlehttp/guzzle 6.2.1
    - Conclusion: don't install guzzlehttp/guzzle 6.2.0
    - Conclusion: don't install guzzlehttp/guzzle 6.1.1
    - Conclusion: don't install guzzlehttp/guzzle 6.1.0
    - Conclusion: don't install guzzlehttp/guzzle 6.0.2
    - Can only install one of: guzzlehttp/guzzle[6.0.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.0, 5.3.1].
    - googleads/googleads-php-lib 31.0.0 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0].
    - Conclusion: don't install guzzlehttp/guzzle 6.0.1
    - Installation request for guzzlehttp/guzzle (locked at 5.3.1, required as ~5.3|~6.0) -> satisfiable by guzzlehttp/guzzle[5.3.1].

My composer.json is 
"require": {
        "php": ">=5.6.4",
        "cartalyst/stripe-laravel": "~2",
        "genealabs/laravel-caffeine": "^0.3.12",
        "guzzlehttp/guzzle": "~5.3|~6.0",
        "intervention/image": "^2.3",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "^5.4.0",
        "stripe/stripe-php": "^5.2",
        "tymon/jwt-auth": "^0.5.12",
        "weblee/mandrill": "dev-master"
    },

**Comment by fiboknacky** [comment]
Hello,

A quick way would be first remove your `composer.lock` first (as now your project is bound and locked to guzzlehttp/guzzle v5.3) and reinstall your project using `composer install` again.
If you have no other dependencies that need guzzlehttp/guzzle v5.3, I recommend to use only 6.0.

Best,
Knack

**Comment by deepaksaini6413** [comment]
thanks fiboknacky, My problem has solved.

**Comment by fiboknacky** [comment]
Glad that you could resolve this. :)
