### ISSUE TITLE
how to handle RateExceededError ?

### ISSUE THREAD

**Issue by asmagillani** [googleads/googleads-php-lib#393]
I am getting this exception 

ApiException in Reflection.php line 39:
[RateExceededError <rateName=RATE_LIMIT, rateKey=null, rateScope=ACCOUNT, retryAfterSeconds=30>]

please provide a sample solution to handle this exception 

Thanks

**Comment by fiboknacky** [comment]
Hello @asmagillani 

We don't have a code example for that in the PHP client library, but you can find more information about this rate exceeded error in [this guide](https://developers.google.com/adwords/api/docs/guides/rate-limits#elements_of_rateexceedederror).
The only existing code example I can find now is in the .NET library: [HandleRateExceededError.cs](https://github.com/googleads/googleads-dotnet-lib/blob/master/examples/AdWords/CSharp/v201710/ErrorHandling/HandleRateExceededError.cs).

As an idea, what you need to do in this case is to retry after you caught this error:

```php
while ($retryCount < self::NUM_RETRIES) {
  try {
    // Do your work, e.g., calling a service.
    break;
  } catch (ApiException $apiException) {
    foreach ($apiException->getErrors() as $apiError) {
      if (!($apiError instanceof RateExceededError)) {
         // Rethrow any errors other than RateExceededError or handle them accordingly.
      }
      // Handle rate exceeded errors by sleeping for an amount of time at least equal to 
      // 'retryAfterSeconds'.
      sleep($apiError->getRetryAfterSeconds());
      $retryCount++;
    }
  } finally {
    if ($retryCount === self::NUM_RETRIES) {
      throw new Exception(sprintf("Could not recover after making %d attempts.",
          $retryCount));
    }
  }
}
```

Best,
Knack

**Comment by fiboknacky** [comment]
The answer is given and it seems no further questions regarding this, so I'll close this issue.
