### ISSUE TITLE
Above 1000 files per directory - Google App Engine Limit Exceeded

### ISSUE THREAD

**Issue by AssyriaGameStudio** [googleads/googleads-php-lib#397]
Hi,
So we're trying to use your DFP php client library to pull revenue information into our back-end dashboard.

Unfortunately we're running into an issue whereby we're using Google App Engine to host our admin dashboard...

Google App Engine has a limit of 1000 files per directory and 10,000 files total; both rules which your own Ads Library breaks the quotas of...

If there any way around this quote limit?

**Comment by dklimkin** [comment]
How do you include the library into your project? Do you use composer?

Make sure you don't include sample code. You can also safely remove the stub files for the API versions you don't use:

  https://github.com/googleads/googleads-php-lib/tree/master/src/Google/AdsApi/Dfp

E.g. keep only the latest one.

**Comment by thangduo** [comment]
Hi Adam,

Thanks for reporting the issue. Unfortunately, this is not reproducible on our end.

Are you referring to this quota?
![quota](https://user-images.githubusercontent.com/4349155/33286505-82217308-d383-11e7-99c9-eb374b947c61.png)


The 10,000 file quota applies to uploaded files, not including the files under `vendor` directory. Indeed, you could specify the DFP PHP client library as a dependency in your `composer.json` file to let Google AppEngine download and install our client library as a dependency, without counting the files toward your uploaded file quota.

The PHP runtime looks for a `composer.json` file in your application's source directory and uses `composer` to install any dependencies before starting your application, as documented [here](https://cloud.google.com/appengine/docs/flexible/php/runtime).
