### ISSUE TITLE
phpdocumentor/reflection-docblock 4.*

### ISSUE THREAD

**Issue by DaleAdtrak** [googleads/googleads-php-lib#399]
Having an issue installing this with Laravel due to a dependency issue with phpdocumentor/reflection-docblock.
Appears to have been fixed in commit ff3232c and then rolled back in 86d8883.
Any fixes for this?

Heres the error:
  Problem 1
    - Installation request for googleads/googleads-php-lib ^32.0 -> satisfiable by googleads/googleads-php-lib[32.0.0].
    - Conclusion: remove phpdocumentor/reflection-docblock 4.1.1
    - Conclusion: don't install phpdocumentor/reflection-docblock 4.1.1
    - googleads/googleads-php-lib 32.0.0 requires phpdocumentor/reflection-docblock ^3.0.3 -> satisfiable by phpdocumentor/reflection-docblock[3.0.3, 3.1.0, 3.1.1, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.3.0].
    - Can only install one of: phpdocumentor/reflection-docblock[3.0.3, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.0, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.1.1, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.0, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.1, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.2, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.2.3, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[3.3.0, 4.1.1].
    - Installation request for phpdocumentor/reflection-docblock (locked at 4.1.1) -> satisfiable by phpdocumentor/reflection-docblock[4.1.1].

**Comment by nmfarshad** [comment]
I'm guessing you are using Laravel 5.5 
If your application doesnt depend on phpdocumentor/reflection-docblock v4.1.1 
you can install google leads with downgrading phpdocumentor/reflection-docblock version from 
4.1.1 to 3.3.0 

composer require phpdocumentor/reflection-docblock:~3.3.0

This is a workaround untill google leads devs get back !

**Comment by fiboknacky** [comment]
Hello Dale,

Sorry for this inconvenience. It was my mistake so the composer.json was reverted to the state before.
I've commited the change so the composer.json of dev-master now has `"phpdocumentor/reflection-docblock": "^4.0.0 || ^3.0.3"` as expected.

Please try `composer require googleads/googleads-php-lib:dev-master` again.
We'll include this change in the next release.

Knack

**Comment by fiboknacky** [comment]
This is fixed in [v32.1.0](https://github.com/googleads/googleads-php-lib/releases/tag/32.1.0).
