### ISSUE TITLE
Get beta version of this client library to stable.

### ISSUE THREAD

**Issue by vtsao** [googleads/googleads-php-lib#4]
Re-purposing this as a tracking bug for getting the [beta version](https://github.com/googleads/googleads-php-lib/tree/experimental) of this client library to stable.

Blocked by:
- [x] #68
- [x] #77
- [x] #86
- [x] #115
- [x] #120
- [x] #124
- [x] #125
- [x] #138
- [x] #145

**Comment by iknox** [comment]
Any word on this (at the least an update of the experimental branch to work with the current API)?  I believe Jan 1 was the official we-don't-support PHP 5.2 date was it not?

**Comment by vtsao** [comment]
We are still planning to work on it, but no updates as of this moment.

**Comment by YOzaz** [comment]
Actualy, even autoload would be sufficient in composer.json for current branch:
```json5
    "autoload": {
        "classmap": [
            "src/Google/Api/Ads/Dfp/Lib",
            "src/Google/Api/Ads/Dfp/Util",
            "src/Google/Api/Ads/Common"
        ]
    }
```

**Comment by hakimio** [comment]
Why haven't there been any commits to experimental branch since august 2014? PSR-0 compliance these days is a must not something you can just ignore. 
Just drop PHP 5.2 support already. It's been more than 4 years since 5.2.17 was released. 
Of course, PSR-4 would be nice too...

**Comment by joshhornby** [comment]
PSR0 is deprecated is it not?

**Comment by hakimio** [comment]
Yeah, I can see now that it is. PSR-4 now replaces it.

**Comment by vtsao** [comment]
We've only recently announced that we're dropping PHP 5.2 support this Jan (many developers are still on 5.2 so it's hard to just stop supporting 5.2).

So, we are looking forward to revamping this client library this year. Stay tuned!

**Comment by onema** [comment]
:+1:

**Comment by florisgoumans** [comment]
@vtsao any plans on rewriting this class completely PSR-4 compliant? Such a shame such a useful tool is currently only available with this quality.

**Comment by vtsao** [comment]
Yes, it's still on our radar.

**Comment by florisgoumans** [comment]
Any ETA? This seems quite inefficient to start building an app with.

**Comment by vtsao** [comment]
I would recommend just using the non-experimental version for now. I hope to get around to making some updates to this this quarter.

**Comment by florisgoumans** [comment]
@vtsao To bad, it's quite un-usable in modern day frameworks with this code. Hope it will get fixed soon.

**Comment by onema** [comment]
@florisgoumans it is not true that this library is "un-usable" in modern day frameworks. 

We use it quite extensively making thousands of api calls for hundreds of clients every day in a symfony 2 application. We install it via  composer without any issues and have access to all classes using the global namespace. 

It is true that being a none PSR compliant library causes several pains (chief among them is the order in which you declare your object), but you should be able to use it without the use of requires or includes. 

If you wrap the client functionality in a class or set of classes, updating the code in the future (with a PSR version of the library) will be quite easy!

Good luck

**Comment by onema** [comment]
@vtsao FYI I have created a small command/library that can be used to break files containing multiple classes into "single file per class", it can also add missing namespaces. Check it out: [ClassyFile](https://github.com/onema/classyfile).

Generating the new files is as simple as : 
```php
include 'vendor/autoload.php';
$classifile = new \Onema\ClassyFile\ClassyFile();

// a namespace will be generated from the file path: `Google\Api\Ads\AdWords` and saved to the cwd under /Google/Api/Ads/AdWords/Lib/
$filePath = 'googleads/googleads-php-lib/src/Google/Api/Ads/AdWords/v201502/';
$classifile->generateClassFiles($filePath, true, 3, 4);

// a namespace will be generated from the file path: `Google\Api\Ads\AdWords\Lib` and saved to the cwd under /Google/Api/Ads/AdWords/Lib/
$filePath = 'googleads/googleads-php-lib/src/Google/Api/Ads/AdWords/Lib/';
$classifile->generateClassFiles($filePath, true, 3, 5);
// ...
```
or from the CLI:
```
$ php classyfile convert googleads/googleads-php-lib/src/Google/Api/Ads/Common/Lib/ --create-namespace --offset=3 --length=5
```

It currently doesn't account for adding use statements if none have been specified in the original file, but I believe is a good step in the right direction. 

I have added two events to allow the extension of the library. Adding missing use statements could be added in the form of an event listener or an event subscriber. 

Let me know if this is helpful or if you have any questions.

**Comment by hakimio** [comment]
@onema
Why does your library require "bing-ads-sdk-php" ?

**Comment by onema** [comment]
@hakimio It should require it. I was testing it with different libraries... I forgot to update the `composer.json` :$. Will update.

**Comment by onema** [comment]
*it should not require it

**Comment by maxbrokman** [comment]
Any update on this?

**Comment by vtsao** [comment]
I've had some more time to work on this recently, but no ETA yet.

**Comment by mbardelmeijer** [comment]
:+1: for PSR-4

**Comment by litan1106** [comment]
I would like namespace too...

**Comment by hakimio** [comment]
Do you finally have an ETA for this feature request?
Also when will you fix your phpdoc?

**Comment by vtsao** [comment]
@hakimio No ETA yet. We are actually rewriting the client library, so it's not just namespacing the existing one.

**Comment by jamesaspence** [comment]
+1. We're integrating this library currently and would love PSR-4 support.

**Comment by vtsao** [comment]
FYI we have just released a new beta version of this library, please see our blog post for details:
http://googleadsdeveloper.blogspot.com/2016/02/announcing-beta-release-of-new-ads-php.html

**Comment by onema** [comment]
This is really awesome good job @vtsao!

**Comment by BenMorel** [comment]
:+1: Good stuff, can't wait to have the new version officially released!

**Comment by vtsao** [comment]
FYI we've made another release of the beta version of this client library to the experimental branch. Please check it out and see the [changelog](https://github.com/googleads/googleads-php-lib/blob/experimental/CHANGELOG.md) for more information.

**Comment by thierrymarianne** [comment]
@vtsao Excellent work! Thank you!

**Comment by vtsao** [comment]
We've made another beta update (1.3.0-beta):
https://github.com/googleads/googleads-php-lib/tree/experimental

Check out the changelog here:
https://github.com/googleads/googleads-php-lib/blob/experimental/CHANGELOG.md

**Comment by vtsao** [comment]
We've made another release of the beta client library (1.3.1-beta). Fixes some bugs and we've released DFP retrieval examples:
https://github.com/googleads/googleads-php-lib/tree/experimental

Check out the changelog here:
https://github.com/googleads/googleads-php-lib/blob/experimental/CHANGELOG.md

**Comment by vtsao** [comment]
FYI we've made another release of the beta client library to the experimental branch (1.4.0-beta). Please see:
https://github.com/googleads/googleads-php-lib/blob/experimental/CHANGELOG.md#140-beta

for changes.

**Comment by mzstic** [comment]
Hi, are there any updates when experimental branch will stop being experimantal?
Thx, looks good so far 👍

**Comment by vtsao** [comment]
Thanks @mzstic. No updates at the moment, but keep following this issue!

**Comment by jbboehr** [comment]
Are you planning to rename the package? 1.4 is less than 14.0...

**Comment by vtsao** [comment]
@jbboehr Thanks for bringing this up, we're currently still thinking about how to proceed with this, will definitely let the community know when we've decided.

**Comment by dan-rally** [comment]
It appears the experimental branch now only supports a deprecated version of API, any updates on this please? Thanks.

**Comment by vtsao** [comment]
@dan-rally we'll be updating experimental soon.

**Comment by dan-rally** [comment]
@vtsao OK thanks for the update.

**Comment by vtsao** [comment]
The experimental library has now been pushed to stable and the old library has been deprecated. Please see our blog post announcement for details:
https://googleadsdeveloper.blogspot.com/2016/12/announcing-new-ads-php-client-library.html

Thanks for everyone's contributions to both the old and new libraries!
