### ISSUE TITLE
Uncaught SoapFault exception: [WSDL] SOAP-ERROR

### ISSUE THREAD

**Issue by angular013** [googleads/googleads-php-lib#402]
I have just installed using Composer , was able to get the refresh token successfully , then i tried to run GetCampaigns.php , and it gave this error.  This error came both on command prompt as well as on browser. I am using Xampp on windows. 

Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl" in E:\xampp\htdocs\new_job\google_adwords\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php:76 Stack trace: #0 E:\xampp\htdocs\new_job\google_adwords\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php(76): SoapClient->SoapClient('https://adwords...', Array) #1 E:\xampp\htdocs\new_job\google_adwords\vendor\googleads\googleads-php-lib\src\Google\AdsApi\AdWords\v201705\cm\CampaignService.php(145): Google\AdsApi\Common\AdsSoapClient->__construct('https://adwords...', Array) #2 [internal function]: Google\AdsApi\AdWords\v201705\cm\CampaignService->__construct(Array) #3 E:\xampp\htdocs\new_job\google_adwords\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\Util\Reflection.php(39): ReflectionCl in E:\xampp\htdocs\new_job\google_adwords\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php on line 76

**Comment by fiboknacky** [comment]
Hello @angular013 

Do you face with this issue for all services and reporting? Or does it happen intermittently?
The new version (v32.0.0) now ships local WSDL files, so it doesn't rely on the live WSDLs anymore.
Could you please try this version too?

Best,
Knack

**Comment by angular013** [comment]
@fiboknacky,  i posted the above issue using the latest version installed using composer command. I only tried to run GetCampaigns.php for now and always getting the above error

**Comment by angular013** [comment]
@fiboknacky , i installed using the command on composer page.
![image](https://user-images.githubusercontent.com/28813039/33009302-42de075a-cdf8-11e7-8c00-2b6bfdce5533.png)

instead of the steps written below , which said to clone the repo:

![image](https://user-images.githubusercontent.com/28813039/33009351-681e8738-cdf8-11e7-8d2c-9515fa56b26c.png)

will this be causing the issue ? maybe installing using "composer require googleads/googleads-php-lib" command did not install the latest version ?

**Comment by fiboknacky** [comment]
Hello @angular013,

To install and run examples, an alternative way is to [download a compressed tarball](https://github.com/googleads/googleads-php-lib#downloading-a-compressed-tarball) and follow the README.md file in the tarball.
But using `git clone` should definitely work as well. 

In the latest commit, if there are local WSDLs, they will be used instead of the live ones.
Could you confirm if the WSDLs in https://github.com/googleads/googleads-php-lib/tree/master/resources/wsdls are used in [AdsSoapClient.php](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/AdsSoapClient.php?utf8=%E2%9C%93#L76) and there is the `resources` directory in your project directory?
From the error message, it looks like that the live ones are still used.

By the way, if you can't even open https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl in your browser, this may be because of some network connection issues. Changing some environments (e.g., using other computers, OSes, XAMPP versions) may help us confirm this.

Best,
Knack

**Comment by angular013** [comment]
@fiboknacky , the resources directory seems to be present 
![image](https://user-images.githubusercontent.com/28813039/33010482-78ed106c-cdfc-11e7-88ef-726b95c15cd9.png)

and the link ( https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl ) is giving this page in the browser  ,

![image](https://user-images.githubusercontent.com/28813039/33010512-95cb609e-cdfc-11e7-9148-4012c9e4d1bd.png)

and you said "Could you confirm if the WSDLs in https://github.com/googleads/googleads-php-lib/tree/master/resources/wsdls are used in AdsSoapClient.php"....in which line of 'AdsSoapClient.php' should i look to check if the local WSDLs are being used or not ?

**Comment by fiboknacky** [comment]
I've added a line number in my previous reply already. Let me put it again here: https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/AdsSoapClient.php?utf8=%E2%9C%93#L73

In particular, could you please if `file_exists($localWsdlPath)` is true? Does the `$localWsdlPath` path exist?

**Comment by angular013** [comment]
@fiboknacky , so i ran a test , and the local Wsdl path does not exist , i added a little code for testing in 'AdSoapClient.php'

![image](https://user-images.githubusercontent.com/28813039/33011334-82cb4736-cdff-11e7-9c03-dcded20c42ab.png)

and this is the output it gave:

![image](https://user-images.githubusercontent.com/28813039/33011365-9bb36274-cdff-11e7-9d5c-c6b8debf0943.png)

**Comment by angular013** [comment]
i now echoed the local path also ,

![image](https://user-images.githubusercontent.com/28813039/33011575-32ced288-ce00-11e7-8008-862704a76f8e.png)

**Comment by fiboknacky** [comment]
I see. So it looks like the implementation isn't customized to Windows yet (there are some slashes mixed with backslashes). I'll work on this.

Meanwhile, we can instead focus on why your environment cannot access the live WSDLs.
Could you try using `file_get_contents()` on https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl?
Can your PHP access this resource?

**Comment by angular013** [comment]
@fiboknacky , so i tried to run;
`echo file_get_contents("https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl?");`
and it gave this error ;

![image](https://user-images.githubusercontent.com/28813039/33013225-17f82cd4-ce05-11e7-97ba-e782679c87ca.png)

there are some SSL issue which i encpountered on XAMPP before when i used CURL , so to fix it , i used to switch off the CURL SSL check. how should i switch off the SSL check in your library for this live WSDL ?

**Comment by angular013** [comment]
So i fixed the SSL issue on XAMPP , but now the code;
`echo file_get_contents("https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl?");`
gives this below error;

![image](https://user-images.githubusercontent.com/28813039/33013796-0d95846a-ce07-11e7-8a45-f7590ebcabb1.png)

and the  'GetCampaigns.php' gived the below error now ;

![image](https://user-images.githubusercontent.com/28813039/33013825-21dc5552-ce07-11e7-910c-6850f2a7a941.png)

**Comment by fiboknacky** [comment]
We don't recommend to switch off SSL check but if you really need it, please have a look at [`disableSslVerifyPeer`](https://github.com/googleads/googleads-php-lib/blob/27.1.0/src/Google/AdsApi/Common/SoapSettingsBuilder.php#L164).

There are some troubleshooting methods that you may be interested in trying first, e.g., what we describe in [README](https://github.com/googleads/googleads-php-lib#ssl-ca-files).
Guzzle also lists up the place where valid SSL CAs are looked for in Windows. Please see [this section](http://docs.guzzlephp.org/en/stable/request-options.html#verify) of its website.

More info about certificates when using XAMPP and Windows can be found [here](https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate).

Best,
Knack

**Comment by fiboknacky** [comment]
> So i fixed the SSL issue on XAMPP , but now the code;
echo file_get_contents("https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl?");
gives this below error;

Looks like you have extra "?" at the end?

> and the 'GetCampaigns.php' gived the below error now ;

It seems your request has hit the servers! At least, the issue with the library seems to be resolved.
For the `USER_PERMISSION_DENIED` error, it's related to AdWords API in general.
Could you please post your question in [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api)? There is a specialized team handling the questions related to AdWords API.

Best,
Knack

**Comment by angular013** [comment]
@fiboknacky , ok thanks i will look into that forum... just a quick question , there are alot of files when i installed through composer, around 9669 files , it caused my laptop to get stuck when i tried to extract 

![image](https://user-images.githubusercontent.com/28813039/33014466-3818981a-ce09-11e7-90ca-89251500905f.png)

So can you confirm that if that the actual file numbers for this library + dependencies , or i did something wrong when installing ?

**Comment by fiboknacky** [comment]
That is correct. There are many stub files generated from WSDLs in the `src/` folder.

**Comment by angular013** [comment]
the library is working now . The USER_PERMISSION_DENIED error was coming, because i created the OAuth credentials for my production manager Adwords account ,  but provided the test client account's clientCustomerId  in the configuration file ''adsapi_php.ini".  So i created the credentials again for my 'test manager account' , and used those credentials and it worked.
