### ISSUE TITLE
What example pulls the total account spend over a time period?

### ISSUE THREAD

**Issue by brod-ie** [googleads/googleads-php-lib#403]
We're building an internal reporting tool that'll state how much we've spent that day, week, or month advertising on Google

I've tried three examples but none are pulling out the Cost column for campaigns, ideally I can have this value for the whole account

Can you point me to an example that can achieve this?

**Comment by thangduo** [comment]
Hi Ryan Ryan Brodie,

Are you referring to AdWords or DFP?

Thanks,
Thang Duong

**Comment by brod-ie** [comment]
@thangduo Thanks for your prompt response 😊

AdWords, we're approved for basic access too and I can successfully pull data using the examples, just not the data I need!

**Comment by fiboknacky** [comment]
Hello Ryan,

I guess you've tried [DownloadCriteriaReportWithSelector.php](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201710/Reporting/DownloadCriteriaReportWithSelector.php) already?

Based on what you described, you probably just need to add a report field ["Cost"](https://developers.google.com/adwords/api/docs/appendix/reports/campaign-performance-report#cost) to your report definition.

If you need further help on this, I recommend to post on [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api), as it's more related to the AdWords API in general.

Best,
Knack

**Comment by brod-ie** [comment]
@fiboknacky I have and I get an empty report:

```
cat criteria-report-XXXXXX.csv

"Criteria performance report #XXXXXXXXXXX (Nov 22, 2017-Nov 28, 2017)"
Campaign ID,Ad group ID,Keyword ID,Keyword / Placement,Criteria Type,Impressions,Clicks,Cost
Total, --, --, --, --,0,0,0
```

However when I use the other campaign examples I correctly see our two running campaigns.

**Comment by fiboknacky** [comment]
There can be many factors that make your report empty.
Could you please ask in the AdWords API Forum. There will be our specialized team helping on that. :)
