### ISSUE TITLE
Namespace problem

### ISSUE THREAD

**Issue by songxiaoxiao** [googleads/googleads-php-lib#404]
There are two Suggestions and questions about the SDK
first:There is GuGe/auth in the SDK directory.namespace:Google\Auth\Credentials\UserRefreshCredentials;  Should a be capitalized in auth?
second:
![image](https://user-images.githubusercontent.com/11972980/33417214-876ff190-d5db-11e7-8494-ae1a57a055a8.png)
The code in the diagram is a constructor for a service where the path can be changed to a configuration file.

What does the endpoint mean in adsapi_php.ini? No explanation was found in the document

**Comment by fiboknacky** [comment]
Hello @songxiaoxiao 

I don't understand your first question. Could you please clarify?

For the second one, the endpoint refers to the locations of AdWords API servers.
So, for regular users, it should be retained as `https://adwords.google.com/`.
The path you mentioned in the service's constructor belongs to a WSDL file.
And the file is automatically generated, so I don't recommend to modify that and other files in that directory.

Best,
Knack

**Comment by songxiaoxiao** [comment]
First, thank you for your answer；
My English is poor,
The first problem is that the `namespace Google/Auth/***; ` but the Auth letter of the directory file is lowercase, and Linux is strictly case-sensitive, causing the namespace error to fail to find the class file,
The second question is that I think there are a lot of people using the SDK, and it's different for everyone, so I need to do the server agent on this side.I can either change this address or I will pass it to the address when I instantiate the class, which is not good, so I can configure the domain name globally in adsapi_php.ini;

**Comment by fiboknacky** [comment]
Thanks for your clarification.

> The first problem is that the namespace Google/Auth/***; but the Auth letter of the directory file is lowercase, and Linux is strictly case-sensitive, causing the namespace error to fail to find the class file,

I don't see where the directory file is in lower case. Could you please confirm?
`Auth` in [examples/Auth](https://github.com/googleads/googleads-php-lib/tree/master/examples/Auth) is also in an upper case.
In addition, this library is supposed to be downloaded by [composer](http://getcomposer.org), which takes care of PSR-4 autoload via `composer.json` in [this line](https://github.com/googleads/googleads-php-lib/blob/master/composer.json#L25).
From what I reviewed again now, it should be fine.


> The second question is that I think there are a lot of people using the SDK, and it's different for everyone, so I need to do the server agent on this side.I can either change this address or I will pass it to the address when I instantiate the class, which is not good, so I can configure the domain name globally in adsapi_php.ini;

Do you mean you need to use a proxy? If so, we have proxy support in [this line](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/adsapi_php.ini#L47).
Changing the endpoint or parameter in the constructor as you're trying to do wouldn't work properly.

If you need help in Chinese, I'll ask my colleague to help. Please let me know in that case. :)

Best,
Knack

**Comment by songxiaoxiao** [comment]
Thank you. I'll take a research

**Comment by fiboknacky** [comment]
I'll close this issue as due to inactivity. Feel free to speak up if you need more help on this.
