### ISSUE TITLE
Composer install issue..

### ISSUE THREAD

**Issue by varunkumar31** [googleads/googleads-php-lib#405]
This package requires php >=5.5.17 but your PHP version (5.5.9) does not satisfy that requirement.
Its not correct message.

**Comment by fiboknacky** [comment]
Hello @varunkumar31,

To use this library in production, php >= 5.5.9 is required (as described in [this line](https://github.com/googleads/googleads-php-lib/blob/master/composer.json#L5)).
php >= 5.5.17 is required only if you would like to run tests of this library successfully, as described in `require-dev` [here](https://github.com/googleads/googleads-php-lib/blob/master/composer.json#L16).

For the difference between `require` and `require-dev`, please consult [this post](https://stackoverflow.com/a/29304370). :)

Best,
Knack

**Comment by varunkumar31** [comment]
Hi Knack,

Its true but my PHP version is 5.5.9 then why I am getting this error. 
I run simply 

> composer install

Following messages display on termial 

> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - This package requires php >=5.5.17 but your PHP version (5.5.9) does not satisfy that requirement.

My OS: linux 14+

**Comment by fiboknacky** [comment]
Could you elaborate how you get the library?
Do you use `git clone` or download a tarball?

**Comment by songxiaoxiao** [comment]
小白经验：建议你吧php升级到5.6以上否则你还会遇到问题

**Comment by hakimio** [comment]
@varunkumar31 run "composer install --no-dev "

**Comment by varunkumar31** [comment]
Thank You all for quick responses. Composer run successfully.

**Comment by czmarcos** [comment]
I got this error, does anyone have any ideia?

```
sudo composer require googleads/googleads-php-lib:^32.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for googleads/googleads-php-lib ^32.0 -> satisfiable by googleads/googleads-php-lib[32.0.0].
    - googleads/googleads-php-lib 32.0.0 requires ext-soap * -> the requested PHP extension soap is missing from your system.
  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/15-xml.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-curl.ini
    - /etc/php/7.0/cli/conf.d/20-dom.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gd.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-mbstring.ini
    - /etc/php/7.0/cli/conf.d/20-mcrypt.ini
    - /etc/php/7.0/cli/conf.d/20-mysqli.ini
    - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-simplexml.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.0/cli/conf.d/20-wddx.ini
    - /etc/php/7.0/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.0/cli/conf.d/20-xmlrpc.ini
    - /etc/php/7.0/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.0/cli/conf.d/20-xsl.ini
    - /etc/php/7.0/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
Installation failed, reverting ./composer.json to its original content.
```

**Comment by fiboknacky** [comment]
Hello @czmarcos 

As the message hinted, your PHP lacks SOAP extension.
You can see how to install and enable this extension in [this page](http://php.net/manual/en/soap.setup.php).

[This post](https://stackoverflow.com/a/26879589) describes how to enable this extension in CentOS.
And [this](http://www.laravelinterviewquestions.com/2017/05/installing-soap-module-on-php-7-ubuntu.html#sthash.H7bC4BtC.dpbs) is for ubuntu.

Probably, you would just need to find this line in `/etc/php/7.0/cli/php.ini`:
```;extension=soap```
and uncomment it.

Best,
Knack

**Comment by czmarcos** [comment]
@fiboknacky thanks a lot! solved my issue!

**Comment by annirathore** [comment]
> extension=soap

Thanks a lot
