### ISSUE TITLE
Unable to fetch data

### ISSUE THREAD

**Issue by varunkumar31** [googleads/googleads-php-lib#406]
Hi Team,

Nicely done as per mentioned. Now I called first API without any error but it display no record. I've campaign in production mode but there is not record.

> php examples/AdWords/v201705/BasicOperations/GetExpandedTextAds.php 

> [2017-11-30 18:36:24] AW_SOAP.INFO: clientCustomerId=491-978-3346 operations=1 service=AdGroupAdService method=get responseTime=525 requestId=00055f32ed2619f00a6250c5e4012681 server=adwords.google.com isFault=0 faultMessage=  
> Number of results found: 0

I've created developer's token and refresh token from my account(MCC acount) and it connected with adword account. Please help me to rid out of this problem. Many Thanks..

**Comment by fiboknacky** [comment]
Hello @varunkumar31 

Since this is related to AdWords API in general, not the client library, could you please post your question in [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api)?
Thank you.

Best,
Knack
