### ISSUE TITLE
Google API Price extension - corrupted data (CampaignId, microAmount, feedItemId, feedMappingId)

### ISSUE THREAD

**Issue by Alexander-Pop** [googleads/googleads-php-lib#407]
Hi.
We Use PHP and I was following examples: https://developers.google.com/adwords/api/docs/guides/extension-settings#update_ad_extensions and everything works fine if i run code in browser like http://mysite.com/myfile.php so code is inside "myfile.php" file

But if I run using cron, I get:
exception 'Google\AdsApi\AdWords\v201710\cm\ApiException' with message
'[EntityNotFound.INVALID_ID @ operations[0].operand.campaignId;
trigger:'CampaignId: 94408149']' in /PATH/TO/LIBRARY/lib/Google/src/Google/AdsApi/Common/Util/Reflection.php:39

SOAP:
AW_SOAP.WARNING: clientCustomerId=MY-ID operations=3 service=CampaignExtensionSettingService method=mutate responseTime=160 requestId=00055f3907c35e200a3f3b12820373fb server=adwords.google.com isFault=1 faultMessage=[EntityNotFound.INVALID_ID @ operations[0].operand.campaignId; trigger:'CampaignId: 94408149']

part of code we use:
$campaignId = "944081497";
$campaignExtensionSettingService = $adWordsServices->get($session, CampaignExtensionSettingService::class);

$selector = new Selector();
$selector->setFields(['CampaignId', 'ExtensionType', 'Extensions']);
$selector->setPredicates([
    new Predicate('CampaignId', PredicateOperator::EQUALS,
        [$campaignId]),
    new Predicate('ExtensionType', PredicateOperator::EQUALS,
        [FeedType::PRICE])
]);

$page = $campaignExtensionSettingService->get($selector);

$campaignExtensionSetting = $page->getEntries()[0];
$campaignExtensionSetting->setExtensionType(FeedType::PRICE);

If I debug $campaignExtensionSetting->getCampaignId(); - I get corrupted value ”@ I (get 944081497 if run in http://mysite.com/myfile.php)

Again if I run http://mysite.com/myfile.php I get 944081497 which is right. So in error above you see "94408149" which is missing 7 in the end and that's why doesn't work.
I've tried intval() to floatval() as suggested here https://groups.google.com/forum/#!topic/adwords-api/NEjJg_7GXQw but it doesn't help..
What can be a reason that Google returns corrupted ID?

I noticed that other data is corrupted:

Google\AdsApi\AdWords\v201710\cm\CampaignExtensionSetting::__set_state(array(
   'campaignId' => '”@ I',
   'extensionType' => 'PRICE',
   ....

Google\AdsApi\AdWords\v201710\cm\Money::__set_state(array(
                 'microAmount' => ' 4p' . "\0" . '',

'feedId' => '9 …U',
         'feedItemId' => ' V…xf',
         'policyData' =>
        array (
          0 =>
          Google\AdsApi\AdWords\v201710\cm\FeedItemPolicyData::__set_state(array(
             'placeholderType' => 35,
             'feedMappingId' => 'B s',
             ......

so microAmount, feedId, feedItemId, feedMappingId are wrong too

running http://mysite.com/myfile.php - all is good

please assist

**Comment by fiboknacky** [comment]
Hello @Alexander-Pop 

I checked your SOAP log and it seems the campaign ID sent to the servers was wrong at the beginning.
Do you make any modification to the example that you're running? 
And have you faced with this in other examples too?

Best,
Knack

**Comment by Alexander-Pop** [comment]
hi @fiboknacky
Our goal is to update Price extension prices periodically. This case is not included in example so we've created it having existing examples. We didn't touch API core file but used https://developers.google.com/adwords/api/docs/guides/extension-settings#update_ad_extensions as example. the part of example:
$campaignExtensionSettingService = $adWordsServices->get(
    $session, CampaignExtensionSettingService::class);
$selector = new Selector();
$selector->setFields(['CampaignId', 'ExtensionType', 'Extensions']);
$selector->setPredicates([
    new Predicate('CampaignId', PredicateOperator::EQUALS,
        [$campaignId]),
    new Predicate('ExtensionType', PredicateOperator::EQUALS,
        [FeedType::SITELINK])
]);

$page = $campaignExtensionSettingService->get($selector);
$campaignExtensionSetting = $page->getEntries()[0];

and did:
$campaignId = "944081497";
$campaignExtensionSettingService = $adWordsServices->get($session, CampaignExtensionSettingService::class);

$selector = new Selector();
$selector->setFields(['CampaignId', 'ExtensionType', 'Extensions']);
$selector->setPredicates([
new Predicate('CampaignId', PredicateOperator::EQUALS,
[$campaignId]),
new Predicate('ExtensionType', PredicateOperator::EQUALS,
[FeedType::PRICE])
]);

$page = $campaignExtensionSettingService->get($selector);
$campaignExtensionSetting = $page->getEntries()[0];
$campaignExtensionSetting->setExtensionType(FeedType::PRICE);

If I debug $campaignExtensionSetting->getCampaignId(); - I get corrupted value ”@ I (get 944081497 if run in http://mysite.com/myfile.php)
if dump full object:
Google\AdsApi\AdWords\v201710\cm\CampaignExtensionSetting::__set_state(array(
'campaignId' => '”@ I',
'extensionType' => 'PRICE',

(see other parts in my initial Q above)

Running http://mysite.com/myfile.php and debug, I see:
Google\AdsApi\AdWords\v201710\cm\CampaignExtensionSetting::__set_state(array(
'campaignId' => '944081497',
'extensionType' => 'PRICE',

I assume in process $page = $campaignExtensionSettingService->get($selector); something is happened?

Let me know if you need other info. Thanks

**Comment by fiboknacky** [comment]
In the original post, you showed the error occurring from doing mutate(), but in the second reply, it's involved with only get().
Could you please attach the SOAP logs (or at least request ID) for the second case that you said it's corrupted too?

And it would help us investigate more if you could run your file in command prompt not via the browser.

Best,
Knack

**Comment by Alexander-Pop** [comment]
@fiboknacky
es example request ID = 00055f4d155fc2580a3f234f730fcee0
it shows <ns1:campaignId>94408149</ns1:campaignId> which is wrong (has to be extra 7 in the end). And as I mentioned above I assume that problem with that variable starts after $page = $campaignExtensionSettingService->get($selector);

Right before it I check $campaignId value and it is "944081497"
 $page = $campaignExtensionSettingService->get($selector);
 $campaignExtensionSetting = $page->getEntries()[0];
 $campaignExtensionSetting->setExtensionType(FeedType::PRICE);
after that
 $campaignExtensionSetting->getCampaignId() gives '”@ I'

This issue exists only from command line when I run cron manually and all is ok from browser. Pleae let me know if you need further info. Thanks!

**Comment by fiboknacky** [comment]
Hello @Alexander-Pop 

It looks like there are problems in the conversion of the objects to XMLs.
Could you please send your whole file to adwordsapiadvisor@google.com (and mention this issue page too)?

And could you please tell me the following?
*  Your environments (OS and PHP versions)
*  How did you fetch the library?

Best,
Knack

**Comment by Alexander-Pop** [comment]
@fiboknacky
thanks for your efforts to try to help.
We could fix it. The problem was that v201710 worked for us only on php5.6. Running on admin server via cron was failed as we had php5.4 on admin. Updating admin server to 5.6 fixed the issue. thanks 
resolved

**Comment by fiboknacky** [comment]
Thanks for confirming. I close this issue.
