### ISSUE TITLE
Disable `shouldLogResponsePayload`

### ISSUE THREAD

**Issue by brod-ie** [googleads/googleads-php-lib#409]
How can I set `shouldLogResponsePayload` to false? I can't find where the logger is constructed

**Comment by fiboknacky** [comment]
Hi @brod-ie 

Could you please tell more about your use case?
Probably, you wouldn't need to touch that parameter, as it's configured to work properly with each utility. 
For example, we turn this parameter off for AdWords reporting, as the response can get really large and spam your log files.

If you really need to configure that, the place you'd need to look is, for example, ReportDownloader's [constructor](https://github.com/googleads/googleads-php-lib/blob/4308d6b03f7ded643fe78b0f2ae0dfa416a62f3e/src/Google/AdsApi/AdWords/Reporting/v201702/ReportDownloader.php#L67).
You need to create [`AdsGuzzleHttpClientFactory`](https://github.com/googleads/googleads-php-lib/blob/86d8883f8d9b90633d701857ebc0233397567de1/src/Google/AdsApi/Common/AdsGuzzleHttpClientFactory.php) to be used in [this line](https://github.com/googleads/googleads-php-lib/blob/4308d6b03f7ded643fe78b0f2ae0dfa416a62f3e/src/Google/AdsApi/AdWords/Reporting/v201702/ReportDownloader.php#L81).

To create `AdsGuzzleHttpClientFactory`, you can mimic what's done from [line 72](https://github.com/googleads/googleads-php-lib/blob/4308d6b03f7ded643fe78b0f2ae0dfa416a62f3e/src/Google/AdsApi/AdWords/Reporting/v201702/ReportDownloader.php#L72) to [line 79](https://github.com/googleads/googleads-php-lib/blob/4308d6b03f7ded643fe78b0f2ae0dfa416a62f3e/src/Google/AdsApi/AdWords/Reporting/v201702/ReportDownloader.php#L79), but [change `shouldLogResponsePayload` to false](https://github.com/googleads/googleads-php-lib/blob/4308d6b03f7ded643fe78b0f2ae0dfa416a62f3e/src/Google/AdsApi/AdWords/Reporting/v201702/ReportDownloader.php#L74):

```
    $logMessageFormatterProvider =
          new AdWordsGuzzleLogMessageFormatterProvider(
              $session, true, self::$REDACTED_DATA_MESSAGE);
```

If you use other utils like DFP reporting or AdWords batch jobs, please look at those utils' constructors instead.

Hope this help.

Best,
Knack

**Comment by brod-ie** [comment]
Not to worry I've realised if I set the logging level to `ERROR` it no longer outputs this notice. You can close the issue now, thanks.
