### ISSUE TITLE
Server error: `POST http://www.ggapis.cus/oauth2/v4/token` resulted in a `500 Internal Server Error` response: 500 Internal Server E (truncated...) E:\facetool-v2\spring\controller\Def.php:288:boolean false

### ISSUE THREAD

**Issue by songxiaoxiao** [googleads/googleads-php-lib#412]
It has not been found that this is an issue that occurs occasionally at all times of the most recent requests.
What's the reason for that? Is it my code?

**Comment by fiboknacky** [comment]
It looks like you use your own server? If so, probably it's an issue on your server as hinted by the error code.

**Comment by songxiaoxiao** [comment]
@fiboknacky It may be that my proxy server has a small problem and is checking it.Thank you.

**Comment by songxiaoxiao** [comment]
@fiboknacky  Are you Chinese?I think you are very kind

**Comment by fiboknacky** [comment]
@songxiaoxiao I'm not born Chinese. :) Thanks for your words.

**Comment by fiboknacky** [comment]
Close due to inactivity. I assumed that you've figured out the solution.
Feel free to reach out for help if you have other issues. Thanks.
