### ISSUE TITLE
ApiException: [AdGroupCriterionError.CONCRETE_TYPE_REQUIRED @ operations[0].operand.criterion; trigger:'Criterion']

### ISSUE THREAD

**Issue by kennblvnp** [googleads/googleads-php-lib#413]
$placement = new Placement();
    $placement->setUrl('wordpress.com');

    $biddableAdGroupCriterion = new BiddableAdGroupCriterion();
    $biddableAdGroupCriterion->setAdGroupId(47069225942);
    $biddableAdGroupCriterion->setCriterion($placement);
    $biddableAdGroupCriterion->setBidModifier(1.5);

    // Create an ad group criterion operation and add it to the list.
    $biddableAdGroupCriterionOperation = new AdGroupCriterionOperation();
    $biddableAdGroupCriterionOperation->setOperand($biddableAdGroupCriterion);
    $biddableAdGroupCriterionOperation->setOperator(Operator::ADD);

    $operations[] = $biddableAdGroupCriterionOperation;

    $result = $adGroupCriterionService->mutate($operations);

**Comment by kennblvnp** [comment]
This is now solved.

The error was some of my use are from v201708 and others were v201710.

This is my error, watch carefully the dates:
```
use Google\AdsApi\AdWords\v201710\cm\CampaignCriterion;
use Google\AdsApi\AdWords\v201710\cm\CampaignCriterionOperation;
use Google\AdsApi\AdWords\v201710\cm\CampaignCriterionService;
use Google\AdsApi\AdWords\**v201708**\cm\AdGroupCriterionService;
use Google\AdsApi\AdWords\**v201708**\cm\Operator;
use Google\AdsApi\AdWords\**v201708**\cm\Platform;
use Google\AdsApi\AdWords\v201710\cm\Placement;
use Google\AdsApi\Common\OAuth2TokenBuilder;
use Google\AdsApi\AdWords\**v201708**\cm\AdGroupCriterionOperation;
use Google\AdsApi\AdWords\v201710\cm\BiddableAdGroupCriterion;
```

**Comment by fiboknacky** [comment]
Thanks for information and glad that you can resolve it. :)
I'll close this issue as it seems no other problems exist.
