### ISSUE TITLE
Removing Placement with NegativeAdGroupCriterion is not working

### ISSUE THREAD

**Issue by kennblvnp** [googleads/googleads-php-lib#414]
I have this code using the Negative class,

    $placement = new Placement();
    $placement->setUrl($url);

    // $adGroupCriterion = new BiddableAdGroupCriterion();
    $adGroupCriterion = new NegativeAdGroupCriterion();
    $adGroupCriterion->setAdGroupId($adGroupId);
    $adGroupCriterion->setCriterion($placement);
    // $adGroupCriterion->setBidModifier($bid_adjustment);

    $adGroupCriterionOperation = new AdGroupCriterionOperation();
    $adGroupCriterionOperation->setOperand($adGroupCriterion);

But its not affecting anything... whats wrong with my code?

**Comment by fiboknacky** [comment]
Hello @kennblvnp 

For issues related to AdWords API in general, could you please post in [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api)?
Thanks!

Best,
Knack

**Comment by kennblvnp** [comment]
Okay thanks! Great help!
