### ISSUE TITLE
How to enable the compression?

### ISSUE THREAD

**Issue by Croxarens** [googleads/googleads-php-lib#417]
Looking at the official Google AdWords Guide, in the "Best Practices" section is suggested to compress the SOAP API communications.
It's not specified there how to do it, but it's written

> If you're using a client library, see its documentation on enabling compression.

I didn't find any info on that regards, so I was wondering if the communications are already compressed by default and if not, how to do it.
Nevertheless, which one is the googleads-php-lib official documentation?

**Comment by hakimio** [comment]
"compressionLevel" setting.
https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/adsapi_php.ini

**Comment by fiboknacky** [comment]
Hi @Croxarens 

As @hakimio kindly replied, the settings can be configured via `adsapi_php.ini`.
In addition, as mentioned [here](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/SoapSettingsBuilder.php#L62), the settings are optional and defaults to `null`, in which case PHP will use its default value.

Please let us know if you need additional help on this.

**Comment by fiboknacky** [comment]
Close due to inactivity. Let us know if you need further help.
