### ISSUE TITLE
BiddingStrategyType is getting empty.

### ISSUE THREAD

**Issue by varunkumar31** [googleads/googleads-php-lib#418]
`<?php
namespace Google\AdsApi\Examples\AdWords\v201710\BasicOperations;

require __DIR__ . '/../../../../vendor/autoload.php';

use Google\AdsApi\AdWords\AdWordsServices;
use Google\AdsApi\AdWords\AdWordsSession;
use Google\AdsApi\AdWords\AdWordsSessionBuilder;
use Google\AdsApi\AdWords\v201710\cm\CampaignService;
use Google\AdsApi\AdWords\v201710\cm\OrderBy;
use Google\AdsApi\AdWords\v201710\cm\Paging;
use Google\AdsApi\AdWords\v201710\cm\Selector;
use Google\AdsApi\AdWords\v201710\cm\SortOrder;

// Added Two new classes
use Google\AdsApi\AdWords\v201710\cm\BiddingStrategyConfiguration;
use Google\AdsApi\AdWords\v201710\cm\BiddingStrategyType;

use Google\AdsApi\Common\OAuth2TokenBuilder;

class GetCampaigns {

  const PAGE_LIMIT = 500;

  public static function runExample(AdWordsServices $adWordsServices,
      AdWordsSession $session) {
    $campaignService = $adWordsServices->get($session, CampaignService::class);

    // Create selector.
    $selector = new Selector();
    $selector->setFields(['Id', 'Name', 'BiddingStrategyType']);
    $selector->setOrdering([new OrderBy('Name', SortOrder::ASCENDING)]);
    $selector->setPaging(new Paging(0, self::PAGE_LIMIT));
    **$biddingStrategyConfiguration = new BiddingStrategyConfiguration();**
    $totalNumEntries = 0;
    do {
      // Make the get request.
      $page = $campaignService->get($selector);

      // Display results.
      if ($page->getEntries() !== null) {
        $totalNumEntries = $page->getTotalNumEntries();
        foreach ($page->getEntries() as $campaign) {
 
         //Fetch getBiddingStrategyType
          echo $biddingStrategyConfiguration->getBiddingStrategyType().PHP_EOL;

          printf(
              "Campaign with ID %d and name '%s' was '%s' found.\n",
              $campaign->getId(),
              $campaign->getName(),
              $BiddingStrategyConfiguration->getBiddingStrategyType()
          );
        }
      }

      // Advance the paging index.
      $selector->getPaging()->setStartIndex(
          $selector->getPaging()->getStartIndex() + self::PAGE_LIMIT);
    } while ($selector->getPaging()->getStartIndex() < $totalNumEntries);

    printf("Number of results found: %d\n", $totalNumEntries);
  }

  public static function main() {
    // Generate a refreshable OAuth2 credential for authentication.
    $oAuth2Credential = (new OAuth2TokenBuilder())
        ->fromFile()
        ->build();

    // Construct an API session configured from a properties file and the OAuth2
    // credentials above.
    $session = (new AdWordsSessionBuilder())
        ->fromFile()
        ->withOAuth2Credential($oAuth2Credential)
        ->build();
    self::runExample(new AdWordsServices(), $session);
  }
}

GetCampaigns::main();
`

Please help me to fetch biddingStrategyType for campaign.

**Comment by fiboknacky** [comment]
Hello,

Your `$biddingStrategyConfiguration` is instantiated by yourself and is not fetched from the server.
That's why you see empty bidding strategy type.

Best,
Knack

**Comment by varunkumar31** [comment]
How to instantiate this in correct manner. Please share some snippet.

**Comment by fiboknacky** [comment]
May I ask what would you l like to do?
If retrieving bidding strategy configuration of a campaign, then please get it from the campaign:

```
$biddingStrategyConfiguration = $campaign->getBiddingStrategyConfiguration(); 
```

Then, you can get many properties including bidding strategy type from that object.

If you want to set a new bidding strategy configuration to a campaign, please consult [this Bidding guide](https://developers.google.com/adwords/api/docs/guides/bidding).
