### ISSUE TITLE
How do I properly setup this in Laravel 5.5?

### ISSUE THREAD

**Issue by kennblvnp** [googleads/googleads-php-lib#419]

**Comment by fiboknacky** [comment]
Please use composer to install the library as [described in README](https://github.com/googleads/googleads-php-lib#using-composer-require).
The directory to install should be anywhere you plan to use with Laravel.

**Comment by kennblvnp** [comment]
Thanks its compatible with Laravel 5.5. I manage to work it with just this library.

**Comment by fiboknacky** [comment]
Thanks for confirming.
