### ISSUE TITLE
In ProviderRepository.php line 208: Class 'LaravelGoogleAds\LaravelGoogleAdsProvider' not found  in Laravel 5.5

### ISSUE THREAD

**Issue by kennblvnp** [googleads/googleads-php-lib#420]
When running this command:

composer require googleads/googleads-php-lib

**Comment by fiboknacky** [comment]
Could you please post the full log?
By the way, LaravelGoogleAds\LaravelGoogleAdsProvider doesn't seem related to our library.

**Comment by kennblvnp** [comment]
@fiboknacky 

I was using this library `https://github.com/nikolajlovenhardt/laravel-google-ads`

then I got this error `requires googleads/googleads-php-lib` thats why I tried to install your library then I got that error:

`In ProviderRepository.php line 208: Class 'LaravelGoogleAds\LaravelGoogleAdsProvider' not found`

**Comment by fiboknacky** [comment]
Could you please consult with the author of `nikolajlovenhardt/laravel-google-ads` instead?
The error message seems not related to this library. There might be some usages that you need to catch up with the author of that library.

**Comment by kennblvnp** [comment]
Okay thanks! It was worth a try
