### ISSUE TITLE
TargetingIdeaService : RequestType::STATS set MatchType

### ISSUE THREAD

**Issue by Vijaysinh** [googleads/googleads-php-lib#423]
In old api we are use to set MatchType while getting stats using targeting idea
  $keywordMatchTypeSearchParameter = new KeywordMatchTypeSearchParameter();
  $keywordMatchTypeSearchParameter->keywordMatchTypes = array('BROAD');

This is my code for latest api... but I am not able to set MatchType to get stats.. could you please help me that how to do in latest api?

        $selector = new TargetingIdeaSelector();
        $selector->setRequestType(RequestType::STATS);
        $selector->setIdeaType(IdeaType::KEYWORD);
        $selector->setRequestedAttributeTypes([
            AttributeType::KEYWORD_TEXT,AttributeType::SEARCH_VOLUME,AttributeType::AVERAGE_CPC]);
        $paging = new Paging();
        $paging->setStartIndex(0);
        $paging->setNumberResults(10);
        $selector->setPaging($paging);
        
        foreach ($kws as $val) {
            $keyword = new Keyword();
            $keyword->setText($val);
            $keyword->setMatchType(KeywordMatchType::BROAD);
            $keywords[] = $keyword;
        }
        
        $searchParameters = [];
        $relatedToQuerySearchParameter = new RelatedToQuerySearchParameter();
        $relatedToQuerySearchParameter->setQueries($keywords);
        $searchParameters[] = $relatedToQuerySearchParameter;
is it removed ? what is default match type used in google adwords keyword planner tool? What is default matchtype data returns using adwords api if we dont set any matchType?

**Comment by fiboknacky** [comment]
Hello @Vijaysinh 

For questions regarding the usage of AdWords API, could you please ask in [this forum](https://groups.google.com/forum/#!forum/adwords-api)?
Thank you.

Best,
Knack
