### ISSUE TITLE
ProductPartitions::showAdGroupTree() not showing the whole tree 

### ISSUE THREAD

**Issue by razvanbalosin** [googleads/googleads-php-lib#425]
In the ProductPartitions class, the `$children` array indexes in `showAdGroupTree()` are being overridden with a new empty array in the loop, ~line 244. 

`\AdsApi\AdWords\Shopping\v201710\ProductPartitions`

```
foreach ($page->getEntries() as $adGroupCriterion) {
    $children[$adGroupCriterion->getCriterion()->getId()] = [];
    ....
}
```

A simple fix would be to check if the key already exists

```
foreach ($page->getEntries() as $adGroupCriterion) {
    if (!array_key_exists($adGroupCriterion->getCriterion()->getId(), $children)) {
        $children[$adGroupCriterion->getCriterion()->getId()] = [];
    }
    ....
}
```

**Comment by fiboknacky** [comment]
Thanks for informing. I'll confirm this and make a patch if applicable.
Also feel free to make a pull request if you'd like. 

Best,
Knack

**Comment by razvanbalosin** [comment]
Thanks, just created a pull request #429

**Comment by fiboknacky** [comment]
Pull request has been merged so I marked this closed.
Thanks for your contribution!
