### ISSUE TITLE
Unsetting properties?

### ISSUE THREAD

**Issue by YOzaz** [googleads/googleads-php-lib#426]
Despite the fact that I hate your decision to close properties as protected - and leave communication through getters and setters - can you please shed the light for me, how can we unset certain properties?

E.g. I want to set advertiser ID for creative to `null` (as obviously, `unset( $creative->advertiserId )` won't work).

```php
$creative->setAdvertiserId(null);
```
But instead of unsetting or setting to null, it sets to zero - because:
https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Dfp/v201705/Creative.php#L95

And then SOAP call fails.

And yes, `PHP_INT_SIZE` is *4* on my environment.

Help!

**Comment by fiboknacky** [comment]
Would not touching advertiser ID at all have the same effect?
In AdWords API, if you don't set attributes to any values, they will be set as `null` and ignored by the servers.
I expect this to be the same in DFP API.

Knack

**Comment by YOzaz** [comment]
@fiboknacky that is correct if you're creating objects from scratch. But in our case, we are duplicating (copying) various objects. Till this update, creative(s) duplicating was as easy as querying from API, unsetting ID, and calling `createCreatives` with same object; now, we'll either have to create lots of `IF...ELSE` checks and copy properties over, or call `Reflection` class and unmark ID property as protected (which is kind of hacky).

**Comment by YOzaz** [comment]
As a temporary workaround, we'll use this approach:
```php
/** @var \Google\AdsApi\Dfp\v201705\Creative $creative */
$reflectionClass = new \ReflectionClass( get_class($creative) );
$idProperty = $reflectionClass->getProperty('id');
$idProperty->setAccessible( true );
$idProperty->setValue( $creative, null );
$idProperty->setAccessible( false );
```
But ideally, I'd suggest changing API and checking for value integrity:
```php
    /**
     * @param int $id
     * @return \Google\AdsApi\Dfp\v201705\Creative
     */
    public function setId($id)
    {
      $this->id = ($id && PHP_INT_SIZE === 4)
          ? floatval($id) : $id;
      return $this;
    }
```

**Comment by thangduo** [comment]
This is a great feedback.

Unfortunately, this is not a high priority issue for us. And we will have to close it as Not Fixed for now. 

Please reopen this issue if it becomes high priority for you. Otherwise, we will revisit it later this year.

**Comment by thangduo** [comment]
It looks like there are 2 aspects of this issue:

1. You would like to set optional ID properties (`setAdvertiserId`) to null
2. You would like to unset an arbitrary properties.

For (1), we can fix it as a bug in the next release.

For (2), we will continue to investigate the use case and work on it later.

**Comment by YOzaz** [comment]
Thanks @thangduo for the feedback.
In general, setting values to `null` is pretty much the same like unsetting in this case, as your library filters them out from JSON request. So for my project, option (1) is fine 👍 
It can be either value check in the function itself, or `NULL_VALUE` constant - we'll adopt as required.
Thank you!

**Comment by fiboknacky** [comment]
Classes are now generated to support setting null in [v33.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/33.0.0).

**Comment by YOzaz** [comment]
Thank you!
