### ISSUE TITLE
SoapFault: Could not connect to host Adwords API

### ISSUE THREAD

**Issue by edourdi** [googleads/googleads-php-lib#427]
Hello, 

I can't run the GetCampaigns.php with WAMP on my computer. I use to develop with adwords API on mamp with my mac and it's works but I can't figure it out what append with WAMP.

I get this message : 

Fatal error: Uncaught SoapFault exception: [HTTP] Could not connect to host in C:\wamp64\www\athena_facebook_converter\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php:90 Stack trace: #0 C:\wamp64\www\athena_facebook_converter\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php(90): SoapClient->__doRequest('<?xml version="...', 'https://adwords...', '', 1, 0) #1 [internal function]: Google\AdsApi\Common\AdsSoapClient->__doRequest('<?xml version="...', 'https://adwords...', '', 1, 0) #2 C:\wamp64\www\athena_facebook_converter\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php(131): SoapClient->__soapCall('get', Array, NULL, Array, Array) #3 C:\wamp64\www\athena_facebook_converter\vendor\googleads\googleads-php-lib\src\Google\AdsApi\AdWords\v201708\cm\CampaignService.php(158): Google\AdsApi\Common\AdsSoapClient->__soapCall('get', Array) #4 C:\wamp64\www\athena_facebook_converter\examples\AdWords\v201708\BasicOperations\GetCampaigns.php(54): Go in C:\wamp64\www\athena_facebook_converter\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php on line 90
( ! ) SoapFault: Could not connect to host in C:\wamp64\www\athena_facebook_converter\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php on line 90
Call Stack
#	Time	Memory	Function	Location
1	0.0034	260872	{main}( )	...\GetCampaigns.php:0
2	0.3367	807224	Google\AdsApi\Examples\AdWords\v201708\BasicOperations\GetCampaigns::main( )	...\GetCampaigns.php:97
3	0.5059	2196800	Google\AdsApi\Examples\AdWords\v201708\BasicOperations\GetCampaigns::runExample( )	...\GetCampaigns.php:88
4	0.5507	2820360	Google\AdsApi\AdWords\v201708\cm\CampaignService->get( )	...\GetCampaigns.php:54
5	0.5507	2821368	Google\AdsApi\Common\AdsSoapClient->__soapCall( )	...\CampaignService.php:158

OpenSSL seem to be Enable on my php.ini.

I tried to run the script with firewall desactivated.

But still doesn't work.

Does anybody have an idea on what append ?

Thank you

**Comment by fiboknacky** [comment]
Could you please check [this wiki](https://github.com/googleads/googleads-php-lib/wiki/Steps-for-troubleshooting-CA-file-issues) and try the steps there?

**Comment by edourdi** [comment]
Thank you fiboknacky. I figure out what append.

My certificate was in .pem instead of .crt for windows.

**Comment by LeorentKelmendi** [comment]
@edourdi is the cert under `auth/tests/fixtures` right ? there are two certs public and private! How did you manage to make it work did you convert your private.pem to crt ?

**Comment by edourdi** [comment]
Hello LeorentKelmendi, 

Yes a change the format of my certificate.
Juste be sure that your parameter have the good path to access to your certificate.

Hope you will manage,
