### ISSUE TITLE
How to get the total cost of the customer?

### ISSUE THREAD

**Issue by shanglei001** [googleads/googleads-php-lib#432]
Hi, How to get the total cost of the customer?
Now,I get the `ALL_TIME`  cost by `DownloadCriteriaReportWithSelector.php` . 
Download a file and then get it through scanning the last line .
I think there should be many easier ways, but I don't find now.

Thinks

**Comment by fiboknacky** [comment]
Hello,

You can use [ACCOUNT_PERFORMANCE_REPORT](https://developers.google.com/adwords/api/docs/appendix/reports/account-performance-report) and include [Cost](https://developers.google.com/adwords/api/docs/appendix/reports/account-performance-report#cost) in your report definition.
For further help regarding this, please ask in [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api) as it's related to the product in general.

Best,
Knack
