### ISSUE TITLE
Create Ad Unit with Out Of Page size

### ISSUE THREAD

**Issue by rishisharma08** [googleads/googleads-php-lib#433]
there is no way to create a size with "out of page" option.
how do i do it?
for other sizes, the code would be

```
$adUnitSize = new AdUnitSize();
$adUnitSize->setSize( new Size( "300", "250", false ) );
$adUnitSizes[] = $adUnitSize;
$adUnit->setAdUnitSizes( $adUnitSizes );
```

but how to do this for an OOP size?

**Comment by rishisharma08** [comment]
i see there is a note about OOP here:
https://developers.google.com/doubleclick-publishers/docs/reference/v201708/InventoryService.Size
```For interstitial size (out-of-page), native, ignored and fluid size, Size must be 1x1.```
so i did this, but it does not show up as "Out-of-page" i the adUnit settings when i select it.

**Comment by fiboknacky** [comment]
@thangduo Could you please help on this?

**Comment by thangduo** [comment]
Can you try to set the AdUnit to out-of-page size on the UI?

**Comment by rishisharma08** [comment]
Hi, thanks for the response.
i did that on UI for a few units, but that is not really feasible for 350 adUnits.
the 1x1 solution works for now. but rather have something in the API to do this properly.

**Comment by thangduo** [comment]
We are investigating this issue. It could be a bug. We will update this issue next week.

**Comment by thangduo** [comment]
This is a bug and we are going to fix it in a near future (tentatively May 2018) release.

Once the fix is released, I will update this bug for how to set the Out-of-page ad unit size and close this issue.

Thank you for reporting this issue to us.

**Comment by thangduo** [comment]
We added [isInterstitial](https://developers.google.com/ad-manager/api/reference/v201805/InventoryService.AdUnit#isInterstitial) to support interstitial size AdUnits. You can now access this properties via the API.

Thanks,
Thang Duong
