### ISSUE TITLE
Error: looks like we got no XML document

### ISSUE THREAD

**Issue by mahirsumer** [googleads/googleads-php-lib#436]
I tried get values from BudgetOrderService with v201702.

I can get data on some accounts smoothly. But mostly i am getting an error.

Error:
looks like we got no XML document

Detailed Error: 
Fatal error: Uncaught SoapFault exception: [Client] looks like we got no XML document in /home/domainname/public_html/subdomains/reports/common/functions/google-api/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php:116 Stack trace: #0 /home/domainname/public_html/subdomains/reports/common/functions/google-api/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(116): SoapClient->__soapCall('get', Array, NULL, Array, Array) #1 /home/domainname/public_html/subdomains/reports/common/functions/google-api/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201702/billing/BudgetOrderService.php(104): Google\AdsApi\Common\AdsSoapClient->__soapCall('get', Array) #2 /home/domainname/public_html/subdomains/reports/common/functions/api-functions-test.php(1409): Google\AdsApi\AdWords\v201702\billing\BudgetOrderService->get(Object(Google\AdsApi\AdWords\v201702\cm\Selector)) #3 /home/domainname/public_html/subdomains/reports/common/functions/api-functions-test.php(1449):getBudgetInfo() #4 in /home/domainname/public_html/subdomains/reports/common/functions/google-api/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php on line 116

**Comment by fiboknacky** [comment]
Hello @mahirsumer 

> looks like we got no XML document

This doesn't seem like our error message.
I guess it comes from your `api-functions-test.php` file?
Could you please share what's in your file too?

Best,
Knack

**Comment by mahirsumer** [comment]
i tried with this:

`require 'google-api/vendor/autoload.php';

use Google\AdsApi\AdWords\AdWordsServices;
use Google\AdsApi\AdWords\AdWordsSession;
use Google\AdsApi\AdWords\AdWordsSessionBuilder;
use Google\AdsApi\AdWords\ReportSettingsBuilder;
use Google\AdsApi\Common\OAuth2TokenBuilder;
use Google\AdsApi\AdWords\v201702\billing\BudgetOrderService;


function main($client_id){
		
$path = "/home/domainname/public_html/reports/common/functions/google-api/vendor/adsapi_php.ini";
		
    	$oAuth2Credential = (new OAuth2TokenBuilder())
        	->fromFile($path)
			->build();

		$session = (new AdWordsSessionBuilder())
    		->withClientCustomerId($client_id)
			->withDeveloperToken('xxxxxxxxxxx')
			->withOAuth2Credential($oAuth2Credential)
			->build();
			
		return $session;
}

function getBudgetInfo(){
		
	$adWordsServices = new AdWordsServices();
	 $session = main('XXX-XXX-XXXX');
	    
	    $budgetService = $adWordsServices->get($session, BudgetOrderService::class);
		
		$selector = new Selector();
	    $selector->setFields(['Name', 'Id']);
	
		$page = $budgetService->get($selector);

print_pre($page);
	}

try{
       getBudgetInfo();
} catch (Exception $e) {
    	echo 'Error: ',  $e->getMessage();
}
`

**Comment by fiboknacky** [comment]
Hello,

Could you please share your SOAP logs to adwordsapiadvisor+thanetpra@google.com?
Thanks.

**Comment by fiboknacky** [comment]
Close due to inactivity.
