### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Telrik** [googleads/googleads-php-lib#437]
i  get $adGroupAd

and then i use this function to edit text ad headline and description:
```
public function setAdgroupAd(AdWordsServices $adWordsServices, AdWordsSession $session, $adId, $adGroupAdId)
    {
        $adGroupAdService = $adWordsServices->get($session, AdGroupAdService::class);
        $operations = [];

        $expandedTextAd = new ExpandedTextAd();
        $expandedTextAd->setId($adId);
        $expandedTextAd->setHeadlinePart2('Cruise to Mars #' . uniqid());

        $adGroupAd = new AdGroupAd();
        $adGroupAd->setAd($expandedTextAd);
        $adGroupAd->setAdGroupId($adGroupAdId);

        $operation = new AdGroupAdOperation();
        $operation->setOperand($adGroupAd);
        $operation->setOperator(Operator::SET);
        $operations[] = $operation;

        $result = $adGroupAdService->mutate($operations);

        print_r($result);
    }
```

and it's not working ;(
Ad with ID 153662274467 and type 'EXPANDED_TEXT_AD' was disapproved with the following policy topic entries:
%%%29053420276-153662274467[2018-01-12 13:37:48] AW_SOAP.WARNING: clientCustomerId=158-698-9669 operations=1 service=AdGroupAdService method=mutate responseTime=48 requestId=000562910354d3400a3729c74f096d82 server=adwords.google.com isFault=1 faultMessage=[RequiredError.REQUIRED @ operations[0].operand.status, AdError.CANNOT_USE_AD_SUBCLASS_FOR_OPERATOR @ operations[0].operand.ad]
exception 'Google\AdsApi\AdWords\v201708\cm\ApiException' with message '[RequiredError.REQUIRED @ operations[0].operand.status, AdError.CANNOT_USE_AD_SUBCLASS_FOR_OPERATOR @ operations[0].operand.ad]' in /var/www/partsouq.com/protected/extensions/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php:39
Stack trace:
#0 /var/www/partsouq.com/protected/extensions/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(39): ReflectionClass->newInstanceArgs(Array)
#1 /var/www/partsouq.com/protected/extensions/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(165): Google\AdsApi\Common\Util\Reflection->createInstance('Google\\AdsApi\\A...', '[RequiredError....')
#2 /var/www/partsouq.com/protected/extensions/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(130): Google\AdsApi\Common\AdsSoapClient->parseApiExceptionFromSoapFault(Object(SoapFault))
#3 /var/www/partsouq.com/protected/extensions/googleads-php-lib/src/Google/AdsApi/AdWords/v201708/cm/AdGroupAdService.php(191): Google\AdsApi\Common\AdsSoapClient->__soapCall('mutate', Array)
#4 /var/www/partsouq.com/protected/commands/AdWordCommand.php(148): Google\AdsApi\AdWords\v201708\cm\AdGroupAdService->mutate(Array)
#5 /var/www/partsouq.com/protected/commands/AdWordCommand.php(215): AdWordCommand->setAdgroupAd(Object(Google\AdsApi\AdWords\AdWordsServices), Object(Google\AdsApi\AdWords\AdWordsSession), 153662274467, 29053420276)

can anyone suggest?

**Comment by fiboknacky** [comment]
Hello @Telrik 

Once you created an ad, you cannot modify it except for its status.
Please see [this page](https://developers.google.com/adwords/api/docs/common-errors#AdError.CANNOT_USE_AD_SUBCLASS_FOR_OPERATOR) for detail.

For further help on this, please consult [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api) where you can ask questions regarding AdWords API in general.

Cheers,
Knack

**Comment by Telrik** [comment]
Wow ok so there is now way to update fields except status .
that's strange .
so i can only update by adwords editor and web ?

**Comment by fiboknacky** [comment]
I believe when you do that on the AdWords editor or web UI, it creates a new ad with zero statistics.
See [this article](https://support.google.com/adwords/answer/2375287?co=ADWORDS.IsAWNCustomer%3Dfalse&hl=en) for information.

**Comment by Telrik** [comment]
is there any method in api to make clone of ad and delete old one?

**Comment by fiboknacky** [comment]
Could you please reach out to AdWords API forum as your questions are related to the product in general, not this client library?
Thanks for your understanding.
