### ISSUE TITLE
NegativeCampaignCriterion 

### ISSUE THREAD

**Issue by Babis86** [googleads/googleads-php-lib#439]
Hello everybody,
this is not really a issue.
I noticed that the content label "JUVENILE" is still accepted as NegativeCampaignCriterion in version 201710. After https://developers.google.com/adwords/api/docs/guides/migration/v201710 this should return an error message. I tested it with other criteria like AFE, UGC_FORUMS, SIRENS and CONFLICT. They returned the expected error message "CANNOT_EXCLUDE_CRITERION".

Best regards
Babis86
```
4 =>
  Google\AdsApi\AdWords\v201710\cm\CampaignCriterionOperation::__set_state(array(
     'operand' =>
    Google\AdsApi\AdWords\v201710\cm\NegativeCampaignCriterion::__set_state(array(
       'campaignId' => -2302,
       'isNegative' => NULL,
       'criterion' =>
      Google\AdsApi\AdWords\v201710\cm\ContentLabel::__set_state(array(
         'contentLabelType' => 'JUVENILE',
         'id' => -512667,
         'type' => NULL,
         'CriterionType' => 'ContentLabel',
         'parameterMap' =>
        array (
          'Criterion.Type' => 'CriterionType',
        ),
      )),
       'bidModifier' => NULL,
       'campaignCriterionStatus' => NULL,
       'baseCampaignId' => NULL,
       'forwardCompatibilityMap' => NULL,
       'CampaignCriterionType' => NULL,
       'parameterMap' =>
      array (
        'CampaignCriterion.Type' => 'CampaignCriterionType',
      ),
    )),
     'operator' => 'ADD',
     'OperationType' => 'AdwordsCriterion',
     'parameterMap' =>
    array (
      'Operation.Type' => 'OperationType',
    ),
  )),

```

**Comment by fiboknacky** [comment]
Hello @Babis86 

Thanks for reporting this.
Could you please send a SOAP log to adwordsapiadvisor+thanet@google.com?

Best,
Knack

**Comment by fiboknacky** [comment]
Hello @Babis86 

I've confirmed that JUVENILE is still be accepted as ContentLabelType and not deprecated yet.
I'll update the documentation afterwards.

Thanks for your reporting again. :)

Best,
Knack
