### ISSUE TITLE
the requested PHP extension soap is missing from your system

### ISSUE THREAD

**Issue by benson-condos** [googleads/googleads-php-lib#440]
I'm trying to install this library in my laravel project using composer 

> composer require googleads/googleads-php-lib

but I keep getting  the error message:
`  Problem 1
    - Installation request for googleads/googleads-php-lib ^32.1 -> satisfiable by googleads/googleads-php-lib[32.1.0].
    - googleads/googleads-php-lib 32.1.0 requires ext-soap * -> the requested PHP extension soap is missing from your system.
`

I have checked my phpinfo(); and Soap is clearly installed in my docker container. Am I missing something?

**Comment by fiboknacky** [comment]
Hello @benson-condos 

Could you please attach your phpinfo() result that shows SOAP is clearly installed?

Best,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity.

**Comment by abhaymaurya** [comment]
Hello everyone, I had same issue. I am running php via xampp and recently I tried installing a Laravel project (Windows). When running `composer install` I ran into this very same issue.
In my case I just had to go to:
C:\xampp\php\php.ini
as thats the config file which gets loaded for php. You can find out yours by running:
php --ini
(I use GitBash for command line operations)
So in my php.ini file I found following line:  
`;extension=php_soap.dll`
I had to remove the ";" from the start of the line as it means commented,
Then running `composer install` went smooth as butter.
Hope it helps some of the fellow devs.

**Comment by valmorflores** [comment]
Some problem, but different cause and solution.
My problem has running two versions of php (in Apache 7.2 and in S.O. 7.1)
In php.ini allright but in console this error: the requested PHP extension soap is missing from your system. 
php --version
and phpinfo() versions are diff.
To run some version in apache and SO (7.2):
sudo update-alternatives --set php /usr/bin/php7.2
sudo update-alternatives --set phar /usr/bin/phar7.2
sudo update-alternatives --set phar.phar /usr/bin/phar.phar7.2
sudo update-alternatives --set phpize /usr/bin/phpize7.2
sudo update-alternatives --set php-config /usr/bin/php-config7.2

**Comment by JaneMax** [comment]
For my ubuntu 20.04 and php 7.4, as I understood, versions conflict, works:
```
sudo add-apt-repository ppa:ondrej/php
```
and apace restart
