### ISSUE TITLE
latest dfp version (/src/Google/AdsApi/Dfp/v201711/Placement.php) is missing some attributes 

### ISSUE THREAD

**Issue by pmodium** [googleads/googleads-php-lib#441]
Hi,
We are upgrading the DFP libraries(from v201702-->v201711) to the latest version and found some attributes missing.Latest versions of `Placement.java` class is missing below attributes.
These are only available in com.google.api.ads.dfp.axis.v201702.Placement  which will sunset in Feb and not in the latest versions(v201705,v201708, and v201711).
Any reason why?

getAdSenseTargetingLocale()
getTargetingAdLocation()
getTargetingDescription()
getTargetingSiteName()
getIsAdSenseTargetingEnabled()

**Comment by thangduo** [comment]
Let me take a look now.

**Comment by thangduo** [comment]
Thanks for reporting this issue to us.

These fields were removed in v201705. Please see all the removed fields in our [v201705 release notes](https://developers.google.com/doubleclick-publishers/docs/rel_notes#whats-new_3).

We will also need to clean up our documentation about the PlacementService v201708 → latest.
