### ISSUE TITLE
Authorization Issue && Google Adwords Custom Remarketing Problem 

### ISSUE THREAD

**Issue by trinath503** [googleads/googleads-php-lib#443]
1. How do i generate the authorization code?
    here is the link to what i done : http://prntscr.com/i4f455
    after Running the url, the result is : http://prntscr.com/i4f7hy

2. Is there a way to integrate google adwords with a CRM such that the CRM's data (email addresses of the generated/added leads) gets directly pushed to the adwords account without manually uploading the data list (email addresses of the generated/added leads) in the adwords to run the adwords campaign for those specific data list? 

3. Can I do the step-2 using REST Api's instead of SOAP?

Looking for your valuable solution.

**Comment by fiboknacky** [comment]
Hello @trinath503 

As your questions are related to AdWords API in general, could you please post your questions in the [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api)?

Thank you.

Best,
Knack
