### ISSUE TITLE
Need some help with uploading to latest version

### ISSUE THREAD

**Issue by Pieterjanvanveen** [googleads/googleads-php-lib#445]
Hy All,

I'm currently using version v201702 and need to update to the latest version of this lib.
I use composer to update "_composer require googleads/googleads-php-lib_" but i'm getting the following messages:

Problem 1
    - Installation request for googleads/googleads-php-lib ^32.1 -> satisfiable by googleads/googleads-php-lib[32.1.0].
    - Conclusion: don't install google/auth v0.11.1
    - googleads/googleads-php-lib 32.1.0 requires google/auth ^1.0.0 -> satisfiable by google/auth[v1.0, v1.0.1, v1.1.0, v1.2.0, v1.2.1].
    - Can only install one of: google/auth[v1.0, v0.11.1].
    - Can only install one of: google/auth[v1.0.1, v0.11.1].
    - Can only install one of: google/auth[v1.1.0, v0.11.1].
    - Can only install one of: google/auth[v1.2.0, v0.11.1].
    - Can only install one of: google/auth[v1.2.1, v0.11.1].
    - Installation request for google/auth (locked at v0.11.1) -> satisfiable by google/auth[v0.11.1].

Can anyone help me to update to the latest version?

**Comment by fiboknacky** [comment]
Hello @Pieterjanvanveen 

As it is hinted in the log, do you specify dependency of google/auth at v0.11.1 in your composer.lock or composer.json?
This library depends on the v1.0,0, so it conflicts with what you specify.

Best,
Knack

**Comment by Pieterjanvanveen** [comment]
Hello Knack,

Well, there is a dependency for google/auth v0.11.1 in the composer.lock but not in the composer.json. I'm new into composer so I didn't know if I could change the lock my self. I thought it would be updated automatically after updating a package?

I've changed the dependency version in the composer.lock my self and now the package is updated without any trouble.

Thanks for your quick response and your extra hint 👍 !

**Comment by fiboknacky** [comment]
Hello,

Glad that you can resolve the issue. :)
If your composer.lock was created by yourself last time and you know that changing version (like this) doesn't affect other of your dependencies, you can remove it.
It will be created automatically again after you run `composer install`, `composer update` or `composer require` on a new dependency.
Please find [this page](https://getcomposer.org/doc/01-basic-usage.md#installing-without-composer-lock) for more info.

Best,
Knack
