### ISSUE TITLE
Use of undefined constant id - assumed 'id'

### ISSUE THREAD

**Issue by tmdt** [googleads/googleads-php-lib#447]
https://github.com/googleads/googleads-php-lib/blob/5a55870f468860f7a058959f0d48cbaa11b20fd4/src/Google/AdsApi/Dfp/v201802/Technology.php#L46

Hello
Is it possible that there is a `$` missing in `!is_null(id)` ?

**Comment by fiboknacky** [comment]
Thanks for reporting. Will have a look.

**Comment by fiboknacky** [comment]
This is fixed in [v33.0.1](https://github.com/googleads/googleads-php-lib/releases/tag/33.0.1).
