### ISSUE TITLE
Use of undefined constant adGroupId - assumed 'adGroupId'

### ISSUE THREAD

**Issue by davido-brainlabs** [googleads/googleads-php-lib#448]
https://github.com/googleads/googleads-php-lib/blob/5a55870f468860f7a058959f0d48cbaa11b20fd4/src/Google/AdsApi/AdWords/v201710/cm/AdGroupCriterion.php#L93

Similar to issue https://github.com/googleads/googleads-php-lib/issues/447.

Appears to be a missing $ on adgroup.

**Comment by fiboknacky** [comment]
Please track on #447.
