### ISSUE TITLE
I keep getting this message even if I already have ini_set("soap.wsdl_cache_enabled", "0"); 

### ISSUE THREAD

**Issue by Eksilente** [googleads/googleads-php-lib#449]
https://github.com/googleads/googleads-php-lib/blob/74e20d186f37b8985e75811631809c87c937ddde/src/Google/AdsApi/Common/AdsSoapClientFactory.php#L130

**Comment by Eksilente** [comment]
I got this working already by setting the code like this

$soapSettings=(new SoapSettingsBuilder())
			    		->withWsdlCacheType(null)
			    		->build();

**Comment by fiboknacky** [comment]
Hello Hasmer,

As we've provided WSDL files bundled with this library, we've deprecated settings WSDL cache now.
So, if you have `wsdlCache` in the `[SOAP]` section of `adsapi_php.ini`, please remove it when using the new versions.

Best,
Knack

**Comment by fiboknacky** [comment]
Seems you've no further questions on this issue so I close this one. Let me know if you still have any.
