### ISSUE TITLE
Unable to Mutate AdWords Express Campaigns/AdGgroups

### ISSUE THREAD

**Issue by nhtahoe** [googleads/googleads-php-lib#451]
I kept getting following errors when trying to perform mutate operation on AdWords Express Campaigns:
```
"errors":[{"className":"OperationAccessDenied","errorReason":"MUTATE_ACTION_NOT_PERMITTED_FOR_CLIENT","retryAfterSeconds":null,"message":null}]}
```

I ultimately found https://developers.google.com/adwords/api/docs/common-errors#OperationAccessDenied.MUTATE_ACTION_NOT_PERMITTED_FOR_CLIENT which seems to indicate that mutating Express accounts is not possible.

Is this something that can be enabled? Or at least better covered in the documentation?

**Comment by fiboknacky** [comment]
Hi @nhtahoe,

I saw you've also asked on the AdWords API forum.
As this is related to the product more than the specific client library, I'll close this issue.
Please follow up on the forum post.

Cheers,
Knack
