### ISSUE TITLE
ReportQuery TimeZone

### ISSUE THREAD

**Issue by mojeprojekty** [googleads/googleads-php-lib#452]
In prev release v201711, I was using ReportService without setting up any timezone. The default value probably was getting from DFP panel (Pacific: -08:00). Now I am using v201802 and all reports are calculated with my local time. So, in v201802 in ReportQuery is new setter (setTimeZoneType), how to use it? Becouse I tried to set PHP timzezones but its not working.

best regards,
Michael.

**Comment by mojeprojekty** [comment]
Whoops sorry, I search again and probably I found it, maybe someone will have same problem. You have to pass to setTimeZoneType a const from Google\AdsApi\Dfp\v201802\TimeZoneType

`
//example
$reportQuery->setTimeZoneType(TimeZoneType::AD_EXCHANGE);
`

BTW with similiar changes maybe it will be better to throw an exception againt using "defualt" hardcoded value?

best regards,
Micheal.

**Comment by thangduo** [comment]
Thanks for your reporting. I am glad that you could figure it out.

**Comment by thangduo** [comment]
We are not going to throw an exception because there is well defined default behavior in DFP regarding timezones, as documented here:
https://developers.google.com/doubleclick-publishers/docs/adx_reporting_migration#reporting_time_zones

We are also updating our latest release notes to call the timezone change out of other breaking changes.

**Comment by thangduo** [comment]
This is now added to DFP v201802 [release notes](https://developers.google.com/doubleclick-publishers/docs/rel_notes#whats-new): 

> Sales Manager and Ad Exchange Historical reports can now specify a time zone with [timeZoneType](https://developers.google.com/doubleclick-publishers/docs/reference/v201802/ReportService.ReportQuery#timeZoneType).

**Comment by mojeprojekty** [comment]
Thanks
