### ISSUE TITLE
Pausing Adgroup

### ISSUE THREAD

**Issue by ztobs** [googleads/googleads-php-lib#453]
Hi fiboknacky,

I wrote a script that automates adgroup functions and everything works fine. Thanks for such a simplified documentation and good tool.
I got a problem pausing Adgroups. 1st i notices there wasnt an example to pause adgroups, then i used the removeAdgroup example to create the pause adgroup.
It doesnt thow any exceptions so i assumed it was working, only to discover that it didnt pause the adgroup. Can you help me fix the snippet

`<?php

/**
 * Created by PhpStorm.
 * User: Joseph Lukan
 * Date: 9/21/2017
 * Time: 11:03 AM
 */

namespace Ztobs\Classes;

use Google\AdsApi\AdWords\AdWordsServices;
use Google\AdsApi\AdWords\AdWordsSession;
use Google\AdsApi\AdWords\v201708\cm\AdGroup;
use Google\AdsApi\AdWords\v201708\cm\AdGroupOperation;
use Google\AdsApi\AdWords\v201708\cm\AdGroupService;
use Google\AdsApi\AdWords\v201708\cm\AdGroupStatus;
use Google\AdsApi\AdWords\v201708\cm\Operator;

/**
 * This example pauses an ad group. 
 */
class PauseAdGroup {

    public static function run(AdWordsServices $adWordsServices,
                               AdWordsSession $session, $adGroupId) {
        $adGroupService = $adWordsServices->get($session, AdGroupService::class);

        $operations = [];
        // Create ad group with PAUSED status.
        $adGroup = new AdGroup();
        $adGroup->setId($adGroupId);
        $adGroup->setStatus(AdGroupStatus::PAUSED);

        // Create ad group operation and add it to the list.
        $operation = new AdGroupOperation();
        $operation->setOperand($adGroup);
        $operation->setOperator(Operator::SET);
        $operations[] = $operation;

        // Pause the ad group on the server.
        $result = $adGroupService->mutate($operations);

        $adGroup = $result->getValue()[0];
        //printf("Ad group with ID %d was paused.\n", $adGroup->getId());
    }

}

`

**Comment by fiboknacky** [comment]
Could you attach a SOAP log too?
PLEASE MAKE SURE you hide all sensitive information.

Best,
Knack

**Comment by ztobs** [comment]
`[2018-03-01 20:20:41] AW_SOAP.INFO: clientCustomerId=***-***-**** operations=1 service=CampaignService method=get responseTime=245 requestId=0005665ec14a09580a37a54bae0e**** server=adwords.google.com isFault=0 faultMessage=  
[2018-03-01 20:20:44] AW_SOAP.INFO: clientCustomerId=***-***-**** operations=1 service=AdGroupService method=mutate responseTime=631 requestId=0005665ec177d0180a37a7817b0d**** server=adwords.google.com isFault=0 faultMessage=  `

**Comment by fiboknacky** [comment]
Sorry if I was not clear. I meant the SOAP XML logs that show what was uploaded and what was returned by the servers.
Only the full request ID would be fine too.

Thanks.

**Comment by ztobs** [comment]
Ok, i dont know how to get the SOAP XML log you are talking about, but here are my requestIds
0005665ec14a09580a37a54bae0e5330
and 
0005665ec177d0180a37a7817b0df028

**Comment by fiboknacky** [comment]
You can configure logging by referring to [this section](https://github.com/googleads/googleads-php-lib#logging). :)
For your initial question, let me take some time to look.

**Comment by fiboknacky** [comment]
Your first request ID shows that you've made a `get` request for Id and Name of campaigns, so it doesn't show whether the ad group was paused or not.

The second request ID shows that you've made a `mutate` request to pause an ad group ID 51200597663, which seems to be paused successfully based on the result returned from the server.
Checking on the AdWords UI, this ad group is shown to be paused too.
So, this works as intended.

If this is not the ad group you mean, could you please specify what ad group you're looking at?
And please send the request ID too.

Thanks.

**Comment by ztobs** [comment]
Thanks, i was using a different account. It was working fine.
