### ISSUE TITLE
Different source codes for adsapi_php.ini

### ISSUE THREAD

**Issue by deepsingleinterface** [googleads/googleads-php-lib#456]
I am getting different **adsapi_php.ini** files while fetching codes for version (^33.1) from : 
`composer require googleads/googleads-php-lib`
and 
`git clone https://github.com/googleads/googleads-php-lib.git`

Please check and fix the issue.

**Comment by fiboknacky** [comment]
Could you clarify what do you mean by "getting different adsapi_php.ini"?
As far as I know, we've not changed the logic of getting `adsapi_php.ini` in this version.
