### ISSUE TITLE
ReportDownloader problem - HTTP ERROR 500

### ISSUE THREAD

**Issue by syamsoul** [googleads/googleads-php-lib#458]
Hi..

I copy code from sample https://developers.google.com/adwords/api/docs/samples/php/reporting#download-a-criteria-performance-report-with-selector

But it give me HTTP ERROR 500 ..

I found that the problem is in ReportDownloader class...

But I don't know what is the problem.
Because it returns nothing except only error 500.

why??

**Comment by fiboknacky** [comment]
Could you enable [logging](https://github.com/googleads/googleads-php-lib#logging) and share the log result please?

Best,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity. Please let me know if you're still faced with the issue.
