### ISSUE TITLE
v201802 fails in ReportDownloader

### ISSUE THREAD

**Issue by panand363** [googleads/googleads-php-lib#463]
I have upgraded to v201802 for the googleads/googleads-php-lib . I am using the ReportDownloader class to download a few reports. The code is crashing .
I use composer to upgrade the packages

Please Note that I am using v201705 which is working fine with the same setup. Also v201710 is working fine with the same setup.
 A snipped below for the code I am using

```
echo "A";
        $oauth = (new OAuth2TokenBuilder())
                ->withClientSecret($client_secret)
                ->withClientId($client_id)
                ->withRefreshToken($refresh_token)
                ->build();

        $session = (new AdWordsSessionBuilder())
            ->withOAuth2Credential($oauth)
            ->withClientCustomerId($customer_client_id)
            ->withDeveloperToken($developer_token)
            ->build();
        echo "B";

        try {
            $reportDownloader = new ReportDownloader($session);

            echo "C";

            $reportDownloadResult = $reportDownloader->downloadReportWithAwql($report_query, DownloadFormat::CSV);

        print_r($reportDownloadResult);
        } catch (Exception $e) {
            echo json_encode($e);
        }
```

I get the output as AB but C is missing as the statement fails on 
``
$reportDownloader = new ReportDownloader($session);
``
I have tried this code on the following PHP Versions
5.6.32
7.1
7.2

Then I made a new project with just the googleads/googleads-php-lib in it, I use composer to upgrade the packages. In the new project I get the following error

``
Parse error: syntax error, unexpected ':', expecting ';' or '{' in /var/www/html/of/vendor/symfony/serializer/Normalizer/GetSetMethodNormalizer.php on line 59
A PHP Error was encountered

Severity: Parsing Error

Message: syntax error, unexpected ':', expecting ';' or '{'

Filename: Normalizer/GetSetMethodNormalizer.php

Line Number: 59

Backtrace:

``

I would also like to mention that I am using methods to get client lists which works fine with v201802

Can someone please help ?

Thanks 
Puneet

**Comment by fiboknacky** [comment]
Hello,

What symfony serializer's version do you use?

Knack

**Comment by panand363** [comment]
Hi,
I am not using symphony directly. But it is installed via composer when I installed /updated the googleads/googleads-php-lib

The version is as follows

``
symfony/serializer                v4.0.6 Symfony Serializer Component

``

Cheers

Puneet

**Comment by fiboknacky** [comment]
Looks like your PHP doesn't recognize PHP 7.0 return type declaration syntax [here](https://github.com/symfony/serializer/blob/master/Normalizer/GetSetMethodNormalizer.php#L59).

Could you please double-check your PHP version?

Best,
Knack

**Comment by panand363** [comment]
Hi Knack,
I am checking the version as well as trying  fresh install of php on the server. Will keep updated

Thanks

Puneet

**Comment by fiboknacky** [comment]
OK. Please let me know.

**Comment by panand363** [comment]
Hi,
Managed to make it work. 
**Solution 1:**

in composer.json
```
require: {
"googleads/googleads-php-lib":"33.1.0",
  "symfony/serializer": "3.0.3",
 "php": ">=5.5.9",
"google/auth": "^1.0.0",
}
```

This works for PHP version 5.5.9 or greater versions around the 5.6.x PHP versions

**Solution 2**
in composer.json

```
"require": {
		"php": "^7.1.3",
		"google/auth": "^1.0.0",
		"googleads/googleads-php-lib": "^33.1",
		"symfony/serializer": "3.0.3"

	}

```
This solution 2 works for php 7.1.x and above versions.

Thanks to @fiboknacky  for all the help

Thanks and Regards

Puneet
