### ISSUE TITLE
cURL error 7: Failed to connect to www.googleapis.com port 443: Connection refused 

### ISSUE THREAD

**Issue by dvrsdheeraj** [googleads/googleads-php-lib#464]
Hello,
I am using google api ,when I try to get user information curl is throwing the error "Failed to connect to www.googleapis.com port 443: Connection refused" .

code is as follows
gcallback.php:

setAccessToken($_SESSION['access_token']); else if (isset($_GET['code'])) { $token = $gClient->fetchAccessTokenWithAuthCode($_GET['code']); $_SESSION['access_token'] = $token; } else { header('Location: login.php'); exit(); } $oAuth = new Google_Service_Oauth2($gClient); $userData = $oAuth->userinfo_v2_me->get(); $_SESSION['id'] = $userData['id']; $_SESSION['email'] = $userData['email']; $_SESSION['gender'] = $userData['gender']; $_SESSION['picture'] = $userData['picture']; $_SESSION['familyName'] = $userData['familyName']; $_SESSION['givenName'] = $userData['givenName']; header('Location: index.php'); exit(); ?>
config.php:

setClientId("1086598902122-v1qctbnc5oil1mtncs0bo15snrvssbdc.apps.googleusercontent.com"); $gClient->setClientSecret("FXoySmm4_QIspGvSw5TyCA-6"); $gClient->setApplicationName("CPI Login Tutorial"); $gClient->setRedirectUri("http://127.0.0.1/google/g-callback.php"); $gClient->addScope("https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/userinfo.email"); ?>
please give me solution for this

![curl](https://user-images.githubusercontent.com/26809990/37535119-d6644cb2-296c-11e8-90e7-f1fe0e117608.png)

**Comment by fiboknacky** [comment]
Have you opened this issue by accident?
Please follow what I've suggested in #462.

Thank you.
Knack
