### ISSUE TITLE
Soap Proxy Not Work

### ISSUE THREAD

**Issue by jackzing** [googleads/googleads-php-lib#465]
Hello,
 I have set the proxy in adsapi_php.ini and I got the error message "[SoapFault]  Could not connect to host"  while the code works well with proxychain command, So what maybe I forgot? The following is my proxy config screenshot. 
![image](https://user-images.githubusercontent.com/19620482/37588056-10775c1a-2b9c-11e8-8a48-d680f772bfd2.png)
Thank you!

**Comment by fiboknacky** [comment]
Hello,

Do you have more stack trace or other information than just that message?
So, originally you could send API request to the servers, but when you add a proxy, then you're faced with this error. Am I correct?

Knack

**Comment by jackzing** [comment]
Hi,
Yes, you are.  I attached the stack trace screenshot as follow. Also, My code is the example:GetReportFields.php, which I want to test the proxy works well. 
![image](https://user-images.githubusercontent.com/19620482/37641490-deeba69c-2c54-11e8-9278-39b9f0acc46e.png)

**Comment by fiboknacky** [comment]
Does your proxy work with this library when called _outside Laravel_?

**Comment by jackzing** [comment]
Yes, it works well. The follow is my test code.
![image](https://user-images.githubusercontent.com/19620482/37642883-bb2a70b2-2c59-11e8-998d-3ed83a5b05c9.png)

**Comment by fiboknacky** [comment]
Hello, 

Sorry if I'm not clear. I meant if you could use the library purely to do API requests (both with and without proxy settings). 
Please don't use CURL manually as you did in the previous reply.

The reason is that we need to know first where the problem occurs.
If you use curl_init() manually, then we'll never know if the problem occurs in the library or Laravel or any settings between them.

Best,
Knack

**Comment by jackzing** [comment]
Hi, 
Thank you! I will try to use the library purely to do API requests and let you know the result soon.

**Comment by fiboknacky** [comment]
OK. Let me know your result. :)

**Comment by jackzing** [comment]
Hi Knack,

I  have used the library purely to run the example: GetReportFields .php. The result list as follows.
use the proxychains4 command(P.S. I can't access google directly.):

![image](https://user-images.githubusercontent.com/19620482/37644632-649f514e-2c5f-11e8-8a19-9905a82cd6dd.png)

use the proxy in adsapi_php.ini file:
![image](https://user-images.githubusercontent.com/19620482/37644814-e75e252e-2c5f-11e8-812c-143913d2c95f.png)
Also, the proxy setting in adsapi_php.ini:
![image](https://user-images.githubusercontent.com/19620482/37644901-23c98850-2c60-11e8-932f-231163015f2a.png)

Hope the above message can help.

**Comment by fiboknacky** [comment]
Hello @jackzing 

I'm not familiar much with proxychain, but having a look at its config file would shed some light.
Could you please send your proxychain config file and the URL that you've entered in the `adsapi_php.ini` to adwordsapiadvisor+thanet@google.com please?

Thanks!
Knack

**Comment by azarecki** [comment]
Hello, 

I have similar problem running example _GetCampaigns.php_ from v201802 with newest version (33.1.0)
`
PHP Fatal error:  Uncaught SoapFault exception: [HTTP] Could not connect to host in /home/user/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php:97
Stack trace:
#0 /home/user/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(97): SoapClient->__doRequest('<?xml version="...', 'https://adwords...', '', 1, 0)
#1 [internal function]: Google\AdsApi\Common\AdsSoapClient->__doRequest('<?xml version="...', 'https://adwords...', '', 1, 0)
#2 /home/user/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(153): SoapClient->__soapCall('get', Array, NULL, Array, Array)
#3 /home/user/googleads-php-lib/src/Google/AdsApi/AdWords/v201802/cm/CampaignService.php(163): Google\AdsApi\Common\AdsSoapClient->__soapCall('get', Array)
#4 /home/user/googleads-php-lib/examples/AdWords/v201802/BasicOperations/GetCampaigns.php(55): Google\AdsApi\AdWords\v201802\cm\CampaignService->get(Object(Google\AdsApi\AdWords\v201802\c in /home/user/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php on line 97
`

Like @jackzing I do not have direct access to internet, only using proxy (squid). Unfortunately I do not have access to proxy config, so I cannot provide you with it.
Previously I was using version 30.0.0 and it worked fine. Only change I did was changed proxy definition in adsapi_php.ini from [PROXY] to [CONNECTION]. 
Should I ask my proxy provider to change some option in it or there is something I can change in lib to get it working?

Thanks,
Adam

**Comment by fiboknacky** [comment]
Hello @azarecki 

In your case, how did you change from [PROXY] to [CONNECTION]?
Could you elaborate your config details?

Knack

**Comment by azarecki** [comment]
I changed from 
```[PROXY]
host = HOST
port = PORT
user = USER
password = PASS
```to```
[CONNECTION]
proxy = USER:PASS@HOST:PORT
```
Thanks,
Adam

**Comment by azarecki** [comment]
I tried with http and https, but without success.
 ```
[CONNECTION]
proxy = sysuser:3cRP****@proxy.domain.com:3456
```
I discussed this issue with proxy provider, they checked if there where any requests blocked to 
```
https://adwords.google.com/api/adwords/cm/v201802/CampaignService?wsdl
```
and they said that from their point of view everything is ok, no requests were blocked.

Thanks,
Adam

**Comment by jackzing** [comment]
Hi guys,

I have solved the issue in my case, my proxy setting in adsapi_php.ini file lists as follow.
![image](https://user-images.githubusercontent.com/19620482/37895741-ca6b9550-3114-11e8-9b4b-b0ac8199a25d.png)
note:  the proxy don't need the schema (http, https)  and the proxy must be HTTP proxy.

Thanks,
Jack.

**Comment by fiboknacky** [comment]
Hi Jack,

Thanks so much for getting back to us.
The URL for the proxy is passed to Guzzle [RequestOptions::PROXY](http://docs.guzzlephp.org/en/stable/request-options.html#proxy) so it should support any kinds of schema too.

Anyway, I'm glad that you can resolve your issue.

@azarecki 
You tried `proxy = http://sysuser:3cRP****@proxy.domain.com:3456` too?

Best,
Knack

**Comment by jackzing** [comment]
Hi Knack,
I think so. But the proxy is also used in vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(line:324). When you add HTTP schema in the proxy config, the options for stream-context-create will like as follow, which don't work well.
![image](https://user-images.githubusercontent.com/19620482/37943428-140d8c5a-31aa-11e8-9f5e-1ad204b2dcbc.png)
The proxy for stream-context-create can work well without HTTP schema. Hope that will help you.

Thanks,
Jack.

**Comment by fiboknacky** [comment]
Hi Jack,

Thanks for your more detail.

**Comment by azarecki** [comment]
Hi, 

First of all sorry for not responding for such a long time. I tried multiple other setups and it looks like it is not connected with proxy, but with wsdl (and it's cache). 
I've misguided you a little bit with changes in config. In pervious version of library I used _wsdlCache = "Off"_. In 32.0.0 wsdl mechanism changed and now this option is not avaliable (there are wsdl files in lib source). 

Problem in 33.1.0 looks like this: First time in a day when I use example it works ok, campaigns are fetched properly. Every next time ends with _Could not connect to host_ error. It worked the same for older versions of lib when I did not set _wsdlCache = "Off"_.

It is clearly somehow connected with caching, but I do not know what it might be. I know my issues are little complicated, but any help would be highly appreciated. Should I create separate ticket / post for it?

Best,
Adam

**Comment by fiboknacky** [comment]
Hi Adam,

Could you please create a new issue describing your situation again?
I'm gonna close this one so it doesn't confuse others.

Best,
Knack

**Comment by rongqiudeng** [comment]
Hi Fiboknacky ,
Could you please tell me how to setting adwords soap socks5 proxy? Because my project use socks5 proxy ,Like this:
 [CONNECTION]
; Optional proxy settings to be used by requests.
; If you don't have username and password, just specify host and port.
;proxy = "protocol://user:pass@host:port"
proxy = "socks5://127.0.0.1:7070"
I found that when I refresh the token, I use the curl proxy. Socks5 proxy can be used at this time. But using the soap proxy when making other api calls, I tried to modify the proxy_host when the AdsSoapClient class was initialized. Finally, I can't link the host.
That's all ,
Thank you very much!

**Comment by fiboknacky** [comment]
I'm not familiar much with socks5.
Do you need to specify socks5 as a schema? Do http and https work?

**Comment by rongqiudeng** [comment]
Mr.fiboknacky,thank you for your reply，Now that I have solved the problem of http proxy, I use Privoxy to convert socks5 proxy to http proxy to solve this problem. Of course, if you can provide https proxy solution it would be better. By the way, php soap extension proxy seems to be Only supports http protocol.
> For HTTP authentication, the login and password options can be used to supply credentials. For making an HTTP connection through a proxy server, the options proxy_host, proxy_port, proxy_login and proxy_password are also available. For HTTPS client certificate authentication use local_cert and passphrase options. An authentication may be supplied in the authentication option. The authentication method may be either SOAP_AUTHENTICATION_BASIC (default) or SOAP_AUTHENTICATION_DIGEST.
[http://php.net/manual/zh/soapclient.soapclient.php](http://php.net/manual/zh/soapclient.soapclient.php)

**Comment by fiboknacky** [comment]
I'm glad that you can resolve this issue now. Feel free to reach out to us next time.
