### ISSUE TITLE
Get a list of companies using only a OAuth2 token

### ISSUE THREAD

**Issue by RattleSneyk** [googleads/googleads-php-lib#467]
Hello!
Already asked the question, but the wording changed.
How can I get a list of companies using only a OAuth2 token?

**Comment by fiboknacky** [comment]
Hello,

Do you mean only by an OAuth2 access token, but not developer token?
If so, no. You need a [developer token](https://developers.google.com/adwords/api/docs/guides/first-api-call#developer_token) for all API accesses.

Best,
Knack

**Comment by fiboknacky** [comment]
I close this as you filed a new issue in #468
