### ISSUE TITLE
Get a list of companies using only a OAuth2 token #2

### ISSUE THREAD

**Issue by RattleSneyk** [googleads/googleads-php-lib#468]
I can not leave a comment in the previous Issue.

Ok, and if the developer token and a OAuth2 token?
without client's id or how to get it?

Found the information here - https://developers.google.com/adwords/api/docs/guides/clientlogin-to-oauth2-individual-accounts#retrieve_oauth_20_refresh_token_for_individual_adwords_account

But there are no examples of the code for npp.
I do not understand what to do next with the received access_token ...

**Comment by fiboknacky** [comment]
Could you please reach out to [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api), as your question is mostly related to getting started with AdWords API?

I highly recommend you to start reading all the guides in the AdWords API website, e.g., [Make Your First API Call](https://developers.google.com/adwords/api/docs/guides/first-api-call). That should answer all your questions.

Thanks.
Knack
