### ISSUE TITLE
Sample file return error 500

### ISSUE THREAD

**Issue by Safeads** [googleads/googleads-php-lib#470]
Hello, I am trying to update to "v201710" but when i execute sample file: BasicOperations/GetCampaigns.php show error 500 and in my log return: 
[Thu Mar 22 17:08:54 2018] [warn] mod_fcgid: stderr: PHP Fatal error:  Can't use function return value in write context in /teste-nova-api/src/Google/AdsApi/Common/Util/EnvironmentalVariables.php on line 37

Have an reason to this? 

I don't change nothing in sample file, i just set info in adsapi_php.ini

**Comment by fiboknacky** [comment]
Hello,

Could you tell how you upgraded your version? And what client library version and PHP version are you using?

Best,
Knack

**Comment by Safeads** [comment]
To download i followed this steps: https://github.com/googleads/googleads-php-lib#using-composer-require

PHP Version: 5.6.30

**Comment by Safeads** [comment]
I just download files again and problem solved :)
