### ISSUE TITLE
Consolidated billing error (BudgetOrderError.INVALID_BILLING_ACCOUNT) in the new library

### ISSUE THREAD

**Issue by spatariu** [googleads/googleads-php-lib#471]
Hello,

We are migrating the Adwords library from the old library to the new one and we have an issue adding consolidated billing to a managed client. Everything seems the same,
the request objects are identical as data, but differ a bit as structure. I am pasting the request SOAP object made by the new PHP library (the sensitive data is hidden since 
this is a public channel):

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://adwords.google.com/api/adwords/cm/v201802" xmlns:ns2="https://adwords.google.com/api/adwords/billing/v201802">
    <SOAP-ENV:Header>
        <ns2:RequestHeader>
            <ns1:clientCustomerId>xxxx</ns1:clientCustomerId>
            <ns1:developerToken>xxxx</ns1:developerToken>
            <ns1:userAgent>Rankingcoach Adwords (AwApi-PHP, googleads-php-lib/33.1.0, PHP/5.5.9-1ubuntu4.22)</ns1:userAgent>
            <ns1:validateOnly>false</ns1:validateOnly>
            <ns1:partialFailure>false</ns1:partialFailure>
        </ns2:RequestHeader>
    </SOAP-ENV:Header>
    <SOAP-ENV:Body>
        <ns2:mutate>
            <ns2:operations>
                <ns1:operator>ADD</ns1:operator>
                <ns2:operand>
                    <ns2:billingAccountId>xxxx</ns2:billingAccountId>
                    <ns2:billingAccountName>xxxx</ns2:billingAccountName>
                    <ns2:poNumber>xxxx</ns2:poNumber>
                    <ns2:budgetOrderName>xxxx</ns2:budgetOrderName>
                    <ns2:primaryBillingId>xxxx</ns2:primaryBillingId>
                    <ns2:spendingLimit>
                        <ns1:microAmount>500000000</ns1:microAmount>
                    </ns2:spendingLimit>
                    <ns2:startDateTime>20180326 202251 Europe/Berlin</ns2:startDateTime>
                    <ns2:endDateTime>20200110 000000 Europe/Berlin</ns2:endDateTime>
                </ns2:operand>
            </ns2:operations>
        </ns2:mutate>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

The response:

Array
(
    [status] => error
    [msg] => Google\AdsApi\AdWords\v201802\billing\BudgetOrderService Error
    [0] => Array
        (
            [masg] => BudgetOrderError.INVALID_BILLING_ACCOUNT
            [field_path] => operations[0].operand
        )

)

Could you please give us some ideas what is wrong here?

**Comment by fiboknacky** [comment]
Hi @spatariu 

I believe this would be because of some API version updates, not the client library itself.
Could you please ask the experts on [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api) instead?
Please state your previous API version and current API version you're using.

Best,
Knack

**Comment by spatariu** [comment]
We tried the same call with the new library on the version v201705 and it doesn't work, but the calls from the old library with v201705 work so I am not sure it's an api version issue.

**Comment by fiboknacky** [comment]
Could you please attach the SOAP logs for both old and new client library requests to adwordsapiadvisor+thanetpra@google.com?

Thanks.

**Comment by spatariu** [comment]
Since there are sensitive details (login data) and big amounts of money involved I cannot send you the requests in a more specific format than above. If it helps you I can give you the customerId for tracking at the most. We have an master mcc white labeled by google which manages thousands of accounts.

**Comment by spatariu** [comment]
Since there are sensitive details (login data) and big amounts of money involved I cannot send you the requests in a more specific format than above. If it helps you I can give you the customerId for tracking at the most. We have an master mcc white labeled by google which manages thousands of accounts.

**Comment by fiboknacky** [comment]
Hi @spatariu 

If you can't provide more details, I'm afraid it's really hard to debug.
The above email is on the google domain and I belong to the official AdWords API support team, so please rest assured that this will be fine.

At the very least, if you're not comfortable sending everything, could you send the request ID instead for both cases instead?

Best,
Knack

**Comment by spatariu** [comment]
I can provide you the request id that we need to debug '00056853731ba4980a814e0ace0b2aab' from v201802. Thank you!

**Comment by fiboknacky** [comment]
Could you provide request ID of old lib that you say it works too, please?

**Comment by spatariu** [comment]
Yes, sorry for the delay, this is the same call from the old library v201705 which works, id: '00056861cdbfe1300ac11ec2230ac0b9'.

Thanks,
Claudiu

**Comment by fiboknacky** [comment]
Hello Claudiu,

The only apparent difference I can find is the `budgetOrderName`, which shouldn't be a factor to fail your request.
I'll contact billing team to see what happen.

Best,
Knack

**Comment by spatariu** [comment]
Hi Knack,

Great, thank you, we only hope that the old library will still work until the billing team comes with a resolution. We are forced to use it until further hints.

Regards,
Claudiu

**Comment by fiboknacky** [comment]
Hi Claudiu,

Unfortunately, the AdWords API v201705 is already sunset.
From the SOAP logs, there are no differences except for the API version and `budgetOrderName`.
Even if the old library still existed, it would face the same issue if you pass exactly the same `budgetOrderName`.

It's not clear whether this is an issue of v201802 or just a transient issue for the billing part in general.
But what's clear now is that this is not related to whether it's the old or new library, from the information I've got so far. :)

Knack

**Comment by fiboknacky** [comment]
Hello Claudiu,

Looking closely to your request, I can see that the client customer IDs you used in two requests are different.
You've successfully sent a request using v201705 because you requested the change for client customer ID 557733XXXX, which is associated with your billing account ID.
The other one (using v201802) failed because your requested the change for client customer ID  685897XXXX, which is not associated to that billing account ID you used.

That's why this resulted in the INVALID_BILLING_ACCOUNT.

If you wish to review the mechanism of BudgetOrderService, please see [this guide](https://developers.google.com/adwords/api/docs/guides/budget-order).
If you wish further help about billing setup, please reach out to [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api).

Best,
Knack
