### ISSUE TITLE
Structured Snippet Feed Item Setting Locale

### ISSUE THREAD

**Issue by docred5** [googleads/googleads-php-lib#472]
Hello,

I am trying to create a StructuredSnippetFeedItem using the latest version of the api (201802) but it is setting the locale to nl (Dutch) when it needs to be en-gb. I will put a copy of my code below but i can only assume that it is to do with services being the same in dutch and english. 

Is there a way to pass in english in the header or is there something else i'm missing.

I know the code below works because it creates the snippets in adwords, just the wrong locale. 

```
$snippets = ['item 1', 'item 2', 'item 3'];

$snip = new StructuredSnippetFeedItem();
$snip->setHeader('Services');
$snip->setValues($snippets);

$customerExtensionSetting = new CampaignExtensionSetting();
$customerExtensionSetting->setCampaignId("google_campagin_id");
$customerExtensionSetting->setExtensionType(FeedType::STRUCTURED_SNIPPET);
$customerExtensionSetting->setExtensionSetting(new ExtensionSetting());
$customerExtensionSetting->getExtensionSetting()->setExtensions([$snip]);

$operation = new CampaignExtensionSettingOperation();
$operation->setOperator(Operator::ADD);
$operation->setOperand($customerExtensionSetting);
$operations = [$operation];

$result = $campaign_extension_setting_service->mutate($operations);
```

James

**Comment by fiboknacky** [comment]
Hi @docred5 

Regarding this, could you please submit your question on [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api), as it's related to the translation of the values on AdWords API server side?

Best,
Knack
