### ISSUE TITLE
How to get Top of page bid.

### ISSUE THREAD

**Issue by pminhtri1010** [googleads/googleads-php-lib#475]
I am using TargetingIdeaService of api adwords
I am receiving data from adwords api but i want attributes by Top of page bid.
Can you help me get attributes by Top of page bid data?

Thanks you,
Tri

**Comment by fiboknacky** [comment]
Hello Tri,

This question is related to AdWords API usage in general, so could you please post your question [here](https://groups.google.com/forum/#!forum/adwords-api) instead?

Thank you.
Knack
