### ISSUE TITLE
ReportQueryBuilder

### ISSUE THREAD

**Issue by ejaymomentummedia** [googleads/googleads-php-lib#476]
Hi Adwords Team,

I'm having trouble with the new Report Query Builder. What I did was i cloned the new PHP Adwords Client
and then I just copied the src/Google/AdsApi folder to my existing adwords package in my site.

I also included the new settings that needs to be added in my code:
![image](https://user-images.githubusercontent.com/31235701/38603522-75312562-3da0-11e8-96b8-2b527d8a6ab7.png)

Then chaging my query from this,

![image](https://user-images.githubusercontent.com/31235701/38603585-95d8a092-3da0-11e8-87e0-522cbcbf1bc3.png)

to this:

![image](https://user-images.githubusercontent.com/31235701/38603602-a19543a4-3da0-11e8-925d-1407221b0dee.png)

The function is giving me HTTP ERROR 500.

my adsapi_php.ini is quite correct because when i print_r() the session. its working fine.

I'm getting stuck in migration to v201802, hope you can help me with this one.

Thanks,

Ejay

**Comment by fiboknacky** [comment]
Hello Ejay,

Could you please confirm two things?
- If you don't change to use ReportQueryBuilder, your code still works
- Can you run our example, [DownloadCriteriaReportWithAwql](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201802/Reporting/DownloadCriteriaReportWithAwql.php), "as is"?
- Could you get more detailed error message? What does it say? Is it possible to update the library without copy-and-paste, but use `composer update` instead?

Best,
Knack

**Comment by ejaymomentummedia** [comment]
Hi Knack,

If you don't change to use ReportQueryBuilder, your code still works?
 - No, It says 
![image](https://user-images.githubusercontent.com/31235701/38648532-47328d8e-3e24-11e8-8e0b-5d396154d8d4.png)

 but when i print_r() this code: 

 $oAuth2Credential = (new OAuth2TokenBuilder())
              ->fromFile()
              ->build();
          // credentials above.
          $session = (new AdWordsSessionBuilder())
              ->fromFile()
              ->withOAuth2Credential($oAuth2Credential)
              ->build();

it has a fine response

Can you run our example, DownloadCriteriaReportWithAwql, "as is"?
 - i run it in my localhost only. it says

![image](https://user-images.githubusercontent.com/31235701/38648740-73fcc5f4-3e25-11e8-9a5c-e1a7dd9cd865.png)

No i don't have any error messages. I just copied all the v201802 in their perspective folders in my live site. 

Is it really advisable to update the whole adwords package? If so it will take hours for me to upload.

Thanks,

Ejay

**Comment by thangduo** [comment]
Hi Ejay,

Please note that the `ReportQueryBuilder::build()` function doesn't return a string.

Indeed, it returns a `ReportQuery` object. To get the final AWQL string, you must invoke its `__toString()` method. Here are a couple ways to get the final AWQL string:

```
$query = (new ReportQueryBuilder())
    ->select(['Id'])
    ->from(ReportDefinitionReportType::CRITERIA_PERFORMANCE_REPORT);

// One way is to use the sprintf() function for returning a string.
$awqlString = sprintf('%s', $query);

// Alternatively, double-quoted strings will expand variable names.
$awqlString = "$query";

// Effectively, you will get:
// $awqlString = "SELECT Id FROM CRITERIA_PERFORMANCE_REPORT";

// The $awqlString can be passed to the `ReportDownloader::downloadReportWithAwql()` function.
$downloadResult =
    $reportDownloader->downloadReportWithAwql(
        $awqlString,
        'CSV'
    );
```

Please confirm whether creating and passing an AWQL string could resolve your issue.

Thanks,
Thang Duong

**Comment by ejaymomentummedia** [comment]
Hi Knack,

Thanks for all the response, The issue is now fixed. I guess i just imported the new version in a wrong way.
Next time you have new version ill just going to push the whole package.

One last thing, how can I make my account or API key to have unlimited requests? Im running a daily pull with adwords, and since i just noticed the new version few days ago, My data is not accurate since March 30, Im manually pulling data from adwords to make the records accurate from march 30 -  present. But I always got restricted because of reaching the daily limit of requests.

Thank you so much,

Ejay

**Comment by fiboknacky** [comment]
Hi Ejay,

Glad that you could resolve your issue.
Yes, upgrading the whole package would be more consistent and easy to debug when any problems occur. I do recommend doing so. Doing `composer update` shouldn't take so long time. :)

> One last thing, how can I make my account or API key to have unlimited requests? Im running a daily pull with adwords, and since i just noticed the new version few days ago, My data is not accurate since March 30, Im manually pulling data from adwords to make the records accurate from march 30 - present. But I always got restricted because of reaching the daily limit of requests.

If you're already [standard-access](https://developers.google.com/adwords/api/docs/access-levels) user, then that's the best you could get.
We don't have "absolutely unlimited" quota for any users. 
If you send too many requests (which is deemed as a spammer) by the server, your account or developer token can still get rate limited.

I'm going to close this issue as your original is resolved.

Best,
Knack
