### ISSUE TITLE
cURL error 56: Proxy CONNECT aborted

### ISSUE THREAD

**Issue by TriNguyen1992** [googleads/googleads-php-lib#478]
Hi, 
I've been working with Google AdWords Api for a few days recently, and I got this error from running getCampaigns.php via command line but I haven't figured it out yet even I tried a lot. Please help me out. Anyway, I use XAMPP on Window10
many thanks,

PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 56: Proxy CONNECT aborted (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\GoogleAdwords\googleads-php-lib\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:186

**Comment by fiboknacky** [comment]
Hello,

It looks like you have a problem with your proxy settings.
Do you use a proxy to send requests to AdWords API?
Could you please check that the proxy allows such communication?

Best,
Knack

**Comment by TriNguyen1992** [comment]
Hi @fiboknacky , thanks so much for your quick reply.
Could you please tell me how to check " the proxy allows such communication"?
because I'm just a newbie working with these things.
Thanks ^

**Comment by TriNguyen1992** [comment]
I did the settings: I turn _Use setup script_ on, in adsapi_php.ini I configed _proxy = "http://localhost:443"_ as I work localhost on window10 but it still didn't work for me, I just wonder what  was I ?

**Comment by fiboknacky** [comment]
So your proxy is installed in localhost?
Can you use your proxy to send requests to other services / APIs?

**Comment by TriNguyen1992** [comment]
So your proxy is installed in localhost? 
-> I just followed exactly what's in the Adwords Api Doc says, and when I execute GetCampaigns.php (On browser or in Command Line), I got the error above, or if I tried to config _proxy = "http://127.0.0.1:80"_  I'd get the error: _cURL error 56: Received HTTP code 405 from proxy after CONNECT_ . Do I have other choice instead of using proxy?
I've been stucking with this problem for a few days. thanks bro ^,

**Comment by fiboknacky** [comment]
Hi,

> -> I just followed exactly what's in the Adwords Api Doc says, and when I execute GetCampaigns.php (On browser or in Command Line), I got the error above, or if I tried to config proxy = "http://127.0.0.1:80" I'd get the error: cURL error 56: Received HTTP code 405 from proxy after CONNECT . Do I have other choice instead of using proxy?

What doc are you talking about? Could you point me to that doc please?

In general, you have to figure out first how your proxy is configured.
I can't help on that part as I'm not able to see how your computing environment is set up.
I may help if you can try on other computers too, to see if the problem still exists.

Best,
Knack

**Comment by TriNguyen1992** [comment]
Hi @fiboknacky , thank you so much for your patience in this case to help me bro.
Actually, at the beginning the proxy config (in _adsapi_php.ini_) was commented and the original error was  _Uncaught SoapFault exception: [HTTP] Could not connect to host in C:\xampp\htdocs\GoogleAdwords\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php:98_ , then I turned the proxy config on (as I read some solutions from internet) and got the error that we were talking about so far. 
As the original error in this comment, do you have any idea how to fix it?

**Comment by fiboknacky** [comment]
Hello,

First, if you don't have a proxy that you can use, you shouldn't turn it on.

For your problem, there are many factors that can lead to that error, such as your XAMPP isn't configured properly so you can't connect to the AdWords API servers or your SSL CA isn't installed properly.
Could you try troubleshooting using [this wiki](https://github.com/googleads/googleads-php-lib/wiki/Steps-for-troubleshooting-CA-file-issues)?

BTW, what version of the client library are you using?

Best,
Knack

**Comment by TriNguyen1992** [comment]
Hi @fiboknacky , thanks bro. seems we are getting close to it.
I did as the wiki you mentioned above [put the curl-ca-bundle.crt file as in C:\Windows\System32\curl-ca-bundle.crt ] but then I got this error: 
_PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 77: error setting certificate verify locations:_
  _CAfile: C:\Windows\System32\curl-ca-bundle.crt
  CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\GoogleAdwords\googleads-php-lib\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:186_

Do you have any idea?

**Comment by fiboknacky** [comment]
> Do you have any idea? I'm using v201802

No, I meant the client library version (e.g., 33.1.0), not the API.

Can you elaborate what step you tried to face with that error?
As the error message stated, you specify invalid locations for the certificate.
You have to double check if there is a certificate in that path indeed. (It seems not)

**Comment by fiboknacky** [comment]
Close due to inactivity.
