### ISSUE TITLE
Uncaught Error: Class 'Google\AdsApi\Common\OAuth2TokenBuilder' not found.

### ISSUE THREAD

**Issue by Kartikeyagaur** [googleads/googleads-php-lib#483]
Fatal error: Uncaught Error: Class 'Google\AdsApi\Common\OAuth2TokenBuilder' not found in C:\xampp\htdocs\adwords_newFolder\index.php:22 Stack trace: #0 {main} thrown in C:\xampp\htdocs\adwords_newFolder\index.php on line 22.
[index.txt](https://github.com/googleads/googleads-php-lib/files/1934960/index.txt)

**Comment by fiboknacky** [comment]
Have you installed this library based on the instructions in [README](https://github.com/googleads/googleads-php-lib/blob/master/README.md)?

Best,
Knack

**Comment by Kartikeyagaur** [comment]
Hello,

Yes. I followed exact same steps.

**Comment by fiboknacky** [comment]
I close this issue due to inactivity. If you're still faced with this issue, please let us know.
