### ISSUE TITLE
Upgrading fo new Google ads API beta?

### ISSUE THREAD

**Issue by 77web** [googleads/googleads-php-lib#485]
Are you going to upgrade this library to apply upcoming new api?
https://developers.google.com/google-ads/api/docs/start

**Comment by fiboknacky** [comment]
There will be a separate repository for supporting the Google Ads API beta.
Currently, we have no concrete date for that yet, but we aim to support that in this quarter.

Once it's ready, it'll be listed up in [this page](https://developers.google.com/google-ads/api/docs/client-libs) too.

Best,
Knack
