### ISSUE TITLE
Add support for new Google Ads Api

### ISSUE THREAD

**Issue by hakimio** [googleads/googleads-php-lib#491]
When do you plan to add support for the new Google Ads Api?
[Blog post](https://ads-developers.googleblog.com/2018/04/join-beta-for-new-adwords-api.html)
[Docs](https://developers.google.com/google-ads/api/docs/)

**Comment by fiboknacky** [comment]
Hello,

We're developing that and will release that soon.
The repo location will be added to the docs you've mentioned above.

Best,
Knack

**Comment by hakimio** [comment]
@fiboknacky Can you post a message here once the library becomes available?

**Comment by fiboknacky** [comment]
Sure. Will do.
Then, let me re-open this issue, so I don't forget for too long.

**Comment by fiboknacky** [comment]
Hello Tomas,

The new Google Ads API client library is now [live](https://github.com/googleads/google-ads-php).

Best,
Knack

**Comment by hakimio** [comment]
@fiboknacky 
Awesome. Thanks for letting me know.
