### ISSUE TITLE
How to handle the  ConnectException ?

### ISSUE THREAD

**Issue by monyoudom** [googleads/googleads-php-lib#493]
In my case when I did the request to the google adwords api. My connection was disconnected.So I want to handle the ConnectException and display to the user.How to catch this ConnectException ?

**Comment by fiboknacky** [comment]
All exceptions related to the connection should be thrown inside either `get()` or `mutate()` method in case you use SOAP services. So you would be able to use try-catch around those methods.
Reporting and Batch Jobs uses Guzzle HTTP, so it'll be a bit different.

Best,
Knack

**Comment by fiboknacky** [comment]
Close this issue for now as there seems no further question.
