### ISSUE TITLE
Good day Sir. I can't seem to find the class BatchJobUtils.php on my v201802. Please help.

### ISSUE THREAD

**Issue by michaelgavan** [googleads/googleads-php-lib#494]

**Comment by fiboknacky** [comment]
Hello,

It's called BatchJobs and located [here](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/BatchJobs/v201802/BatchJobs.php).
Please also see [this guide](https://github.com/googleads/googleads-php-lib/blob/master/UPGRADING.md#adwords-utility-changes) in case you've migrated from the old library.

Best,
Knack

**Comment by michaelgavan** [comment]
Alright. Thank you Sir.
