### ISSUE TITLE
TargetingIdeaService : Call to a member function generateHttpHeaders() on null	

### ISSUE THREAD

**Issue by SnowYou4Times** [googleads/googleads-php-lib#496]
Hi,
I'm new to adWords and I'm trying to get multiple keywords based on one I give to the API.
Ex: I give Metal, It returns {Metal, Iron, Copper, Lead...}
For now, I got this code where I juste setup everything to make the call :
(I'm using the MVC : CakePhp 2.9.5)

    require_once __DIR__ . '../../Vendor/autoload.php';
    
    use Google\AdsApi\AdWords\v201710\o\TargetingIdeaSelector;
    use Google\AdsApi\AdWords\v201710\o\TargetingIdeaService;
    use Google\AdsApi\AdWords\v201710\o\LanguageSearchParameter;
    use Google\AdsApi\AdWords\v201710\o\RelatedToQuerySearchParameter;
    use Google\AdsApi\AdWords\v201710\cm\Language;
    use Google\AdsApi\AdWords\v201710\cm\Paging;

    // Create selector.
    $selector = new TargetingIdeaSelector();
    $selector->setRequestType('IDEAS');
    $selector->setIdeaType('KEYWORD');
    $selector->setrequestedAttributeTypes(array(
          'KEYWORD_TEXT','SEARCH_VOLUME','CATEGORY_PRODUCTS_AND_SERVICES'));
    // Create language search parameter (optional).
    // The ID can be found in the documentation:
    //   https://developers.google.com/adwords/api/docs/appendix/languagecodes
    // Note: As of v201302, only a single language parameter is allowed.
    $languageParameter = new LanguageSearchParameter();
    $french = new Language();
    $french->setCode(1002); //english is 1000
    $languageParameter->setLanguages(array($french));
     // Create related to query search parameter.
     $relatedToQuerySearchParameter = new RelatedToQuerySearchParameter();
     $relatedToQuerySearchParameter->setQueries(array($word));
     $selector->setSearchParameters(array( 
         $relatedToQuerySearchParameter,$languageParameter));
     // Set selector paging (required by this service).
     $paging = new Paging();
     $paging->setStartIndex(0);
     $paging->setNumberResults(10);
     $selector->setPaging($paging);
     // Make the get request.
     $targetingIdeaService = new TargetingIdeaService();
     $content = $targetingIdeaService->get($selector);

And I'm getting the error : 
Error: Call to a member function generateHttpHeaders() on null	
File: C:\wamp64\www\projet\app\Vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php	
Line: 114

I followed the method on : https://developers.google.com/adwords/api/docs/guides/targeting-idea-service
Did I missed something? Do I need to modify the AdsSoapClient or the TargetingIdeaService ?

**Comment by fiboknacky** [comment]
Please follow the [whole code](https://developers.google.com/adwords/api/docs/samples/php/optimization#get-keyword-ideas) here.
One problem I see is that you instantiate `TargetingIdeaService` by yourself.

You should do this via
```php
$targetingIdeaService = $adWordsServices->get($session, TargetingIdeaService::class);
```
instead.

Best,
Knack

**Comment by fiboknacky** [comment]
It's in the file already. Please start reading from [main()](https://github.com/googleads/googleads-php-lib/blob/eeacf8ae5604976421c66bb1e4d60a00063e4c86/examples/AdWords/v201802/Optimization/GetKeywordIdeas.php#L154) first.

Please let me know if you have any questions.

**Comment by SnowYou4Times** [comment]
Thank you again, sorry for that mistake.
It seems like the code is now valid, but I have something new

`Config file not found as specified: 'adsapi_php.ini'. Home directory could not be located so it was not searched.`
I used EnvironmentalVariables::getHome(); but seems like it can't find home directory.

But it's another problem, should I make a new issue ?

**Comment by fiboknacky** [comment]
Have you place your `adsapi_php.ini` in your home directory yet?
And how did you install this library based on our [README](https://github.com/googleads/googleads-php-lib/blob/master/README.md) guide?

**Comment by SnowYou4Times** [comment]
I don't think it's in the right folder right now, I don't know where the home directory is,
I tried the EnvironmentalVariables::getHome(); But it doesn't work.
And placing it in the <root>\user\username doesn't work either.

I installed the library using composer.

**Comment by fiboknacky** [comment]
What do you mean by "doesn't work"? Could you elaborate please?

**Comment by SnowYou4Times** [comment]
When using EnvironmentalVariables::getHome(); in my project www\project\app\Model\someModel, I have the following error : "Could not locate home directory."

Do I have to use it inside the Vendor file where my googleads-php-lib is ?

**Comment by fiboknacky** [comment]
In that case, please specify the path to your file to [`fromFile()`](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L104) when you create an `AdWordsSessionBuilder`.

**Comment by SnowYou4Times** [comment]
Which file do I have to specify ? The path to `adsapi_php.ini` or to my current file `www\projet\app\Model`

It should be something like this ?
    $session = (new AdWordsSessionBuilder())->fromFile()->withOAuth2Credential($oAuth2Credential)- 
    >build();
    $filePath = sprintf(
        '%s.ini',
        tempnam('PathToTheFile, 'adsapi_php')
    );

**Comment by fiboknacky** [comment]
As the PHPDoc says "Reads configuration settings from the specified filepath.", it should be the path to your `adsapi_php.ini`.

For your code:
```php
 $session = (new AdWordsSessionBuilder())->fromFile()->withOAuth2Credential($oAuth2Credential)- 
 >build();
 $filePath = sprintf(
    '%s.ini',
    tempnam('PathToTheFile, 'adsapi_php')
 );
```

This will not work, at least because you don't pass anything to `fromFile()`.
You create `$filePath` even after you create a `$session`.
And probably you don't need to do anything fancy like using `tempnam`.
Just a string that is the path to your `adsapi_php.ini` will be enough.

By the way, you need to call [`OAuth2TokenBuilder::fromFile()`](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/OAuth2TokenBuilder.php#L59) to create `$oAuth2Credential` before creating a session too.

**Comment by fiboknacky** [comment]
No worries. Just stick with me. We're going to resolve this together.

`$filePath = 'C\wamp64\www\project\app\Vendor\googleads\googleads-php-lib\src\Google\AdsApi';`

Are you sure that your file path is correct?
`C\wamp64\...' doesn't look like a valid file path to me...

And do you put `adsapi_php.ini` in the library source code?
Where exactly have you placed `adsapi_php.ini`?

**Comment by fiboknacky** [comment]
OK. We're making a progress now.
But it looks like you're using the wrong format of the ini file.
Where did you get that? Looks like it's from the old library.
The correct one should be copied from [here](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/adsapi_php.ini).

Another two comments:
*  Developer token wouldn't be in the form of XXX-XXX-XXXX. It looks like you're using account ID instead.
*  You'd better move your `adsapi_php.ini` out of the source code, so that in case you update the library in the future, it won't get deleted / overwritten accidentally. Recommended place would be your home directory like `<root>\Users\<username>\`.

**Comment by SnowYou4Times** [comment]
Ok, just changed the adsapi_php.ini file according to what you gave and moved it to a secured location, change the filePath as well to match.

When browsing to this page : https://adwords.google.com/select/ApiCenter
I reach my account, it's a test account but that shouldn't be a problem.
I tried to search for where I could find a valid Developer token but couldn't find it.

**Comment by fiboknacky** [comment]
Please read [this guide](https://developers.google.com/adwords/api/docs/guides/first-api-call) first.
It seems you have no problem with start using the library now, so I'm going to close this issue.

For further help on general usage (like how to apply for developer token, etc.), please ask on [AdWords API](https://groups.google.com/forum/#!forum/adwords-api) forum. Thanks.
