### ISSUE TITLE
Error when running through web browser

### ISSUE THREAD

**Issue by szusi** [googleads/googleads-php-lib#497]
Hello, I have been able to successfully run getCampaigns.php locally to return my test campaigns. I have put the api on a web server for my website, but when I try to run getCampaigns through a url I run into the following error: 
Parse error: syntax error, unexpected T_CLASS, expecting T_STRING or T_VARIABLE or '$' in /home/gulliver/public_html/db/sean/googleads-php-lib/examples/AdWords/v201802/BasicOperations/GetCampaigns.php on line 44

My adsapi_php.ini file is completely filled out with the same information I used to run getCampaigns locally.  I also have php version 5.6.30. Please let me know the best way to fix this error.

Sean

**Comment by fiboknacky** [comment]
As stated in [README](https://github.com/googleads/googleads-php-lib/blob/master/README.md#basic-usage), code examples are not meant to run as through a web page, so you can't just run getCampaigns in that way.

Having said that, there shouldn't be a syntax error like that.
Do you run GetCampaigns as is and is everything is installed via composer?

Knack

**Comment by szusi** [comment]
Is there any way to edit the files so they can be run through a webpage?

**Comment by fiboknacky** [comment]
It depends on your web server too, but using `echo` should print some information on a web page.

**Comment by szusi** [comment]
I have everything installed using composer, I'm not exactly sure where the syntax error is coming from still as it works just fine when I run it locally.

**Comment by szusi** [comment]
Im going to try and redownload the library and reinstall composer as well.

**Comment by fiboknacky** [comment]
From my experience, syntax errors like this sometimes come from PHP version and installed library version mismatch.
But it usually happens inside a library's code.
Reinstall the library using composer would be a good idea too.

**Comment by szusi** [comment]
What do you mean by the installed library? The API? The API is the most current version, and the PHP version is recent, though I'm not sure what exact version it is. On my local machine I have PHP version 5.6, which seems to run just fine with the API locally.

**Comment by fiboknacky** [comment]
Sorry for not being clear.
I meant the dependencies that are installed using composer. If you have other projects that require the same dependencies (but different versions), sometimes they can silently fail.
If you can run `composer install` or `composer require` purely on the web server, it should be fine.

Can you check what version of the PHP in your web server?

**Comment by szusi** [comment]
Unfortunately, I am unable to ssh into the server at this point in order to run composer install directly on the server. Would it work the same if I downloaded the composer.phar file and upload that into the root of my API?

**Comment by szusi** [comment]
Could I be missing any packages? What specific packages should I download with composer?

**Comment by fiboknacky** [comment]
So, the only option would be to install on your local machine using `composer install` and copy everything including `/vendor` to your server.
Could you try doing this again if not yet?

> Could I be missing any packages? What specific packages should I download with composer?

If you use composer to install the library, all dependencies should be taken already.
You don't need to do anything special.

**Comment by szusi** [comment]
I've updated php to 5.6, which I believe was causing the previous error. However now, I simply get a blank page.

**Comment by szusi** [comment]
Ive put an echo statement in the getcampaigns file, and that will print something out, but nothing else is returned.

**Comment by fiboknacky** [comment]
Do you mean you see results when running GetCampaigns using PHP 5.6 on your local machine?

Can you try turning all error reporting as [described here](https://stackoverflow.com/a/21429652)?

**Comment by szusi** [comment]
Correct, It works just fine on my local machine. I believe the error is with the oAuth2token builder. However, my adsapi_php.ini file is in the root of my directory, (thus fromFile() should be able to find it just fine) and all of my credentials are correct in the .ini folder.

**Comment by szusi** [comment]
Using the error reporting, it seems that fromFile() is not able to find my adsapi_php.ini file. I have it in the home directory of my user on the server. Is this the incorrect location?

**Comment by fiboknacky** [comment]
Sometimes, the home directory is not available on some kinds of servers.
In this case, you can specify path to your .ini file directly to [`fromFile()`](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/OAuth2TokenBuilder.php#L59) method.

**Comment by szusi** [comment]
Just spent some time messing around with that, finally got it to work! It now runs and displays correctly through the webpage. Thank you so much for taking the time to help me, I really appreciate it.

**Comment by fiboknacky** [comment]
Glad you can resolve your issue now. :)
