### ISSUE TITLE
Oauth2.0 approval_prompt = force

### ISSUE THREAD

**Issue by vtsao** [googleads/googleads-php-lib#5]
Hello All,

I am not seeing approval_prompt option under Oauth2.0 authentication which can enable user to approve appllication request every time he logged in with google account.

For more info please see this forum question:
https://groups.google.com/forum/#!searchin/adwords-api/oauth2.0/adwords-api/GTClxukrLCE/GdO1bRsGkWkJ

No option for this under PHP Client library v201306.

Thanks,
Chirag
Jul 17, 2013 Delete comment #1 chirag.ebrandz
Hi,

Any update?
Jul 22, 2013 Delete comment Project Member #2 api.pmatthews
Hi Chirag,

Thank you for your feature request. For the a quick workaround, I suggest you edit your copy of the OAuth2Handler.php to add the following:

Edit the GetAuthorizationUrl.php function to update the $params array as follows:

```
$params = array_merge($params, array(
    'response_type' => 'code',
    'client_id' => $credentials['client_id'],
    'redirect_uri' => $redirectUri,
    'scope' => $this->scope,
    'access_type' => $offline ? 'offline' : 'online',
    'approval_prompt' => 'force',
));
```

File path: 
<root>/src/Google/Api/Ads/Common/OAuth2Handler.php

See the link below for the current version:

https://code.google.com/p/google-api-adwords-php/source/browse/src/Google/Api/Ads/Common/Util/OAuth2Handler.php#59

Regards,
- Paul, AdWords API Team.
  Labels: -Type-Question Type-en 
  Jul 22, 2013 Delete comment Project Member #3 api.pmatthews
  (No comment was entered for this change.)
  Labels: -Type-en Type-Enhancement 
  Jul 23, 2013 Delete comment #4 chirag.ebrandz
  Hello Paul,

Yes, I dont wants to disturb API. So i have done this when getting to authorization Url by adding extra param.

```
    $offline = TRUE;
$extra_para = array('approval_prompt' => 'force');
$OAuth2Handler = $user->GetOAuth2Handler();
$authorizationUrl = $OAuth2Handler->GetAuthorizationUrl($user->GetOAuth2Info(), $redirectUri, $offline, $extra_para);
```

I have one more Question under enhancement.
I am not getting any user information by calling Oauth 2.0. For e.g. user email.
For this i need to add any other scope. So how i can add other scopes?

Thanks,
Chirag
Sep 26, 2013 Delete comment Project Member #5 api.pmatthews
We're looking into adding a config parameter for the approval_promt setting.

Can you explain what service you're calling that is not returning a user email?

Regards,
- Paul, AdWords API Team.
  Status: Accepted 
  Sep 26, 2013 Delete comment #6 chirag.ereportz
  Hi,

I'm trying to calling CustomerService.
CustomerService that will give me idea about customer who tryed to get data using API.
This will help a lot when user is using MCC account for authentication, and adwords account has no CompanyName / Name info.
Oct 4, 2013 Delete comment #7 chirag.ereportz
Also, I requested you to Add all beta feature to be available for all developer.

**Comment by chiragvels** [comment]
Hello,

'approval_prompt' => 'force' is not working as expected.
If I pass the 'approval_prompt' => 'force', it is still not asking user to authorize app forcefully If I already had login with already authorized adwords account.

Also It is not returning refresh_token with $user->GetOAuth2Info() under below code.

$OAuth2Handler = $user->GetOAuth2Handler();
$user->SetOAuth2Info($OAuth2Handler->GetAccessToken($user->GetOAuth2Info(), 
$code, $redirectUri));
$user->GetOAuth2Info();

Thanks,

**Comment by vtsao** [comment]
Hi @chiragvels approval_prompt isn't supported by this library (but the [beta](https://github.com/googleads/googleads-php-lib/tree/experimental) version of this library should support it as it uses the [Google Auth library](https://github.com/google/google-auth-library-php)). As @saturnism mentioned, you might have to add it to the URL yourself. You can find our OAuth2 documentation here:
https://developers.google.com/identity/protocols/OAuth2

Thanks,
Vincent

**Comment by chiragvels** [comment]
Hello @vtsao ,

I am passing parameters properly.
It seems to be issue with new version of library 13.1.0 and I was not facing any issue with lib version 10.0.0.
I was using approval_prompt = force since 2011, and not changed any core files for login.

However I found this issue that approval_prompt=force is replaced with prompt = consent, and that was solved this problem. 

I have also conversation going on at forum, I think you can clear idea of my problem from this thread.

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/adwords-api/iSY2uUBx5JQ/jkxpDaEUAwAJ

Thanks,

**Comment by vtsao** [comment]
> However I found this issue that approval_prompt=force is replaced with prompt = consent, and that was solved this problem.
mmm okay, then I guess our OAuth2 params have changed. Either way it's not specific to this library, but thanks for pointing it out.
