### ISSUE TITLE
CallOnlyAd description1/2 limited to 38 characters via API

### ISSUE THREAD

**Issue by cognitive-rift** [googleads/googleads-php-lib#500]
In the Adwords User Interface description1 and description2 are allowed to be 80 characters each.  When set to approx 70ish characters each the adwords API returns to following error:

[AdError.LINE_TOO_WIDE @ operations[0].operand.ad.description1, AdError.LINE_TOO_WIDE @ operations[0].operand.ad.description2]

**Comment by fiboknacky** [comment]
Hello,

Your question is more related to the AdWords API in general.
Could you please post in the [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api) instead?

Best,
Knack
