### ISSUE TITLE
Please, add in examples how to get finalUrls!

### ISSUE THREAD

**Issue by NikitaKharkov** [googleads/googleads-php-lib#505]
I faced in problem to get url(s) which lead to my site (finalUrls in ad, AdService). I spend enough stupid time to find why I can't get displayUrl or Url, and not only I. And after that I found [here](https://stackoverflow.com/questions/34350883/cant-get-destination-url-of-ad-by-adwords-api) how to get needle url.
I understand that I was just unobservant when look to API docs, but I strongly ask you to add to examples getting finalUrls (I mean `CreativeFinalUrls`).

Thanks a lot. I hope you do it.

**Comment by fiboknacky** [comment]
Hello,

Thanks for your feedback and sorry for your inconvenience.
Next time, please feel free to reach out to AdWords API forum for any questions regarding AdWords API in general.
We have our dedicated team to support for any kinds of questions. 
You'd get answers to trivial questions like yours probably much faster. :)

For library-related issues, feel free to post in GitHub as you just did. 

As for the addition of `CreativeFinalUrls`, we'll consider this.
However, as there are many fields that can be selected, and each user has his/her own fields of interest, we wouldn't be able to add all of them to examples.

I'll close this bug as your feedback is already received.
Thanks again for this. :)

Cheers,
Knack
