### ISSUE TITLE
Reporting gives unexpected form of RateExceededError

### ISSUE THREAD

**Issue by raalderink** [googleads/googleads-php-lib#506]
While downloading a report with the `ReportDownloader`, it can throw an `ApiException`, with a `ReportDownloadError` that has the errorString `RateExceededError.RATE_EXCEEDED`.

Since all the other parts of the library will map this to a `RateExceededError`, we would expect this to map to that as well, for consistency, but it seems that the reporting does not seem to do that. Our application relies on checking the `RateExceededError` and using the `RetryAfterSeconds` that it holds to properly wait before sending the next request, so it would be nice if the reporting error could map to that as well.

**Comment by fiboknacky** [comment]
Hello, 

Thank you so much for your feedback.
This is more like an issue of the underlying design of the server.
Unfortunately, the reporting system and SOAP services are separated, although the error messages look the same, they are not exactly the same thing.

The `RateExceededError` class is generated automatically from the WSDL files, where the SOAP services rely on and it extends `ApiError`, whereas what's thrown from the reporting is [a mapping from XML response to a general `ApiException`](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/Reporting/v201806/ReportDownloader.php#L234).

As you can see, the mapping itself is not super straightforward too, and there are some fields that don't get populated.
In addition, the original result from the reporting service doesn't expose the concept of rate exceeded errors in the same way as SOAP services do.
So, even if we map a special case where the error type is `RateExceededError.RATE_EXCEEDED` to `RateExceedError`, it will not be fully mapped. (Sometimes, the `retryAfterSeconds` may not be returned too)

The workaround (which I think you may have implemented already?) is to look into `ReportDownloadError` to see if there is `RateExceededError.RATE_EXCEEDED` as its errorString.

Please note that even `retryAfterSeconds` is returned, it doesn't guarantee that your requests will succeed after waiting for the given amount of time.
See [this guide](https://developers.google.com/adwords/api/docs/guides/rate-limits#elements_of_rateexceedederror) for more information.

Best,
Knack
