### ISSUE TITLE
AWQL OrderByClause

### ISSUE THREAD

**Issue by Vijaysinh** [googleads/googleads-php-lib#508]
Hi , 

I am using latest adwords api and trying to use AWQL Query to download report,

Below is my AWQL Query,

$query = (new ReportQueryBuilder())
            ->select([ 'CampaignId', 'Date' ])
            ->from(ReportDefinitionReportType::CAMPAIGN_PERFORMANCE_REPORT)
           ->where('AdGroupStatus')->in(['ENABLED','PAUSED','REMOVED'])
            ->duringDateRange(ReportDefinitionDateRangeType::LAST_30_DAYS)
            ->build();

Above query is working fine but when I am trying to use OrderBy clause than its not working.

**[fieldPath: ; trigger: ; errorString: QueryError.ORDER_BY_CLAUSE_NOT_SUPPORTED]**

I am getting above error, Could you please help me that how to use OrderBy in above code?

Thanks,
VJ.

**Comment by fiboknacky** [comment]
Hello VJ,

As the error message says, you can'T use ORDER_BY with reporting.
This is also documented [here](https://developers.google.com/adwords/api/docs/guides/awql#using_awql_with_reports).

Best,
Knack
