### ISSUE TITLE
New Error Exception with gcloud sdk installed.

### ISSUE THREAD

**Issue by litan1106** [googleads/googleads-php-lib#509]
It's from the [google/auth](https://github.com/google/google-auth-library-php/releases) lib v1.3.1

1.3.1 (07/19/2018)
Changes
Added a warning for 3 legged OAuth credentials (#199)

ErrorException : Your application has authenticated using end user credentials from Gooogle Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
 /Users/litan/Codes/lpd-client-dashboard/vendor/google/auth/src/Credentials/UserRefreshCredentials.php:91

**Comment by fiboknacky** [comment]
I'll have a look and check with google/auth authors.

**Comment by litan1106** [comment]
thanks. it's fixed in v1.3.2
