### ISSUE TITLE
CANNOT_OPERATE_ON_REMOVED_ADGROUPAD constant

### ISSUE THREAD

**Issue by kratkyzobak** [googleads/googleads-php-lib#514]
Using v36.0.0 of this library

class/enum `Google\AdsApi\AdWords\v201806\cm\AdGroupAdErrorReason` contains `CANNOT_OPERATE_ON_REMOVED_ADGROUPAD` constant, but API 201806 return `AdGroupAdError.CANNOT_OPERATE_ON_DELETED_ADGROUPAD` (DELETED vs REMOVED)

New constant does not exists, old one stays untouched, so static analysis of our business code does not show any error.

Enum is marked as "generated from WDSL", co I'm not trying to create pull request, as there is probably problem with WDSL or WDSL generator?

**Comment by fiboknacky** [comment]
Hi @kratkyzobak 

Thanks for your reporting.
Could you please provide the request ID of the response that you got too?
The WSDL generator should be fine and the WSDL hasn't been changed too, but this might be some glitches from the server.

Best,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity
