### ISSUE TITLE
How to get Native Active campaign using DFP API

### ISSUE THREAD

**Issue by abi3** [googleads/googleads-php-lib#515]
Hello Support, 

I want to get the native active campaign for specific adunit on using Google DFP API.  In my scenario, I want to use DFP API to get the native active item for specific ad unit and create my own design. I need the data of the native creative if there is an active campaign. 

Regards
Abi

**Comment by thangduo** [comment]
Hi abi3,

It seems that you need a product consultation. If so, please post your question again on our [product forum.](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api) They can assist you with the high level steps on how to achieve your goals.

If you have difficulties in invoking the services using this client library, please re-open this thread with the error details. I will be glad to help you troubleshoot the case.

Thanks,
Thang Duong
