### ISSUE TITLE
Error parse_ini_file(/reporting/adsapi_php.ini): failed to open stream: Too many open files

### ISSUE THREAD

**Issue by ronakprogrammer** [googleads/googleads-php-lib#516]
Hello,

We are using the Adwords API v201802 PHP Client Library  for our reporting application and our automated process loads the data from adwords API every hour, but we are facing a strange issue in middle of data updates "Error Occured parse_ini_file(/var/www/html/production/reporting/adsapi_php.ini): failed to open stream: Too many open files, on /var/www/html/production/reporting/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/ConfigurationLoader.php line number 87" 

When we restart the server and re-enabled the data updates again it will work fine for few hours and then again API will start throwing errors again.

Please check

Regards,
Ronak

**Comment by fiboknacky** [comment]
Hi Ronak,

In your program, do you usually open many files concurrently?
From the error message, it looks like you've opened too many files than what the server allows.
So, when time passes, this error emerges again.
(See more info in [this issue](https://github.com/guzzle/guzzle/issues/1927))

Besides, [`AdWordsSessionBuilder::fromFile()`](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L104) should be called once in most cases.
You can save the session builder object for use later.
It looks like you call it many times?

Best,
Knack

**Comment by ronakprogrammer** [comment]
Hello Knack,

Everytime when we download the report for clientCustomerId we call `AdWordsSessionBuilder::fromFile()`

Basically we have number of Adwords account and for every account we download the report and for each report we call `AdWordsSessionBuilder::fromFile()`

Regards,
Ronak

**Comment by fiboknacky** [comment]
Hi Ronak,

If the client customer ID is the only thing that you need to change, please consider using [`withClientCustomerId`](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L272) to do it programmatically, instead of reading from files every time, which is less efficient.

This should be able to resolve your issue.

Best,
Knack

**Comment by ronakprogrammer** [comment]
Hello Knack,

Thanks for the response but what about the developer token, and log path settings, can we configure those too instead of reading files from server?, In short is there any way to not use parse_ini_file and manually set the configuration?

Thanks,
Ronak

**Comment by fiboknacky** [comment]
Hi Ronak,

Almost all properties can be set programmatically using the [AdWordsSessionBuilder](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php) class.

I would suggest you to read it from file _once_ though, as it seems less cumbersome for you.
Just client customer ID that you need to set it programmatically.

Best,
Knack

**Comment by fiboknacky** [comment]
Close as the solution was provided.
