### ISSUE TITLE
OperationAccessDenied.ADD_AS_REMOVED_NOT_PERMITTED

### ISSUE THREAD

**Issue by KonstantinObuhov** [googleads/googleads-php-lib#517]
Hi I use a test token for a test MCC account and inside my code I have to create ads for objects depends on their states like (is_integrated, is_removed etc...), and when I try to set a status REMOVED for ad groups I got an API exception OperationAccessDenied.ADD_AS_REMOVED_NOT_PERMITTED.
It happens when I create ad groups with status REMOVED.

Please I need some help!

**Comment by KonstantinObuhov** [comment]
requestId=000572eb7e00d4d00a3769c76607c705

**Comment by fiboknacky** [comment]
Since this is related to the AdWords API in general, could you please ask in the [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api) instead?

Best,
Knack

**Comment by KonstantinObuhov** [comment]
I've found the answer here 

https://developers.google.com/adwords/api/docs/reference/v201806/MediaService.OperationAccessDenied.Reason

An ADD operation may not set the status to REMOVED.

**Comment by KonstantinObuhov** [comment]
First when I add It has to set another status not REMOVED may be UNKNOWN.

**Comment by fiboknacky** [comment]
You shouldn't set an entity to UNKNOWN in general. Mostly (not all) you would set it to PAUSED or ENABLED.

**Comment by KonstantinObuhov** [comment]
Thanks, I've solved the problem.
