### ISSUE TITLE
Error with AdsSoapClient

### ISSUE THREAD

**Issue by nazar-goyda** [googleads/googleads-php-lib#518]
Hi,, i update lib for 201710 to 201806 and get error like this:

> file:"C:\OpenServer\domains\stat.local.ua\CoreSystem\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php"
> line:153
> message:"Unmarshalling Error: cvc-type.2: The type definition cannot be abstract for element ns1:searchParameters. "
> type:"SoapFault"

I call TargetingIdeaService method get()
on TargetingIdeaSelector i have this

```
object(Google\AdsApi\AdWords\v201806\o\TargetingIdeaSelector)#2306 (7) {
  ["searchParameters":protected]=>
  array(450) {
    [0]=>
    string(60) "seo продвижение интернет магазина"
    [1]=>
    string(26) "web продвижение"
    [2]=>
    string(37) "web продвижение сайта"
    [3]=>
    string(58) "web продвижение сайтов раскрутка"
    [4]=>
    string(22) "web раскрутка"
    [5]=>
    string(40) "yandex продвижение сайта"
    [6]=>
    string(36) "yandex раскрутка сайта"
    [7]=>
    string(44) "бизнес раскрутка сайтов"
  }

  ["ideaType":protected]=>
  string(7) "KEYWORD"
  ["requestType":protected]=>
  string(5) "STATS"
  ["requestedAttributeTypes":protected]=>
  array(2) {
    [0]=>
    string(12) "KEYWORD_TEXT"
    [1]=>
    string(13) "SEARCH_VOLUME"
  }
  ["paging":protected]=>
  object(Google\AdsApi\AdWords\v201806\cm\Paging)#2305 (2) {
    ["startIndex":protected]=>
    int(0)
    ["numberResults":protected]=>
    int(500)
  }
  ["localeCode":protected]=>
  NULL
  ["currencyCode":protected]=>
  NULL
}
```
Version PHP 5.6
my soap log files. 
[soap (1).log](https://github.com/googleads/googleads-php-lib/files/2276926/soap.1.log)

**Comment by fiboknacky** [comment]
Not sure how your code passed in v201710 before, but from [the source file](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/v201806/o/TargetingIdeaSelector.php#L13), the member of `searchParameters` should be an instance of [SearchParameters](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/v201806/o/SearchParameter.php), not just a string.
