### ISSUE TITLE
passing a variable into KeywordIdeas

### ISSUE THREAD

**Issue by steponafish** [googleads/googleads-php-lib#519]
I'm using ajax and I was able successfully pass all my variables through, but I'm not able to use any of the variables in KeywordIdeas. Is there a way for me to pass a variable into KeywordIdeas without using $_POST?

**Comment by fiboknacky** [comment]
Hi,

I'm not quite sure how your program is structured, but it looks like your question is more generic about how to pass variables without using $_POST?
Sorry that my answer would be generic, but I think another option is to use $_SESSION if you'd like to keep track your variables across many web pages.

Best,
Knack

**Comment by steponafish** [comment]
Thanks Knack! I got it figured out. I figured out a way to use $_POST. Thanks for your help!

**Comment by fiboknacky** [comment]
Sure. Glad you can figure it out.
