### ISSUE TITLE
Changes to ExpandedTextAds

### ISSUE THREAD

**Issue by AntoineTB** [googleads/googleads-php-lib#520]
Hey Fibo!
We are very thrilled about the third headline and 90 characters limit in ExpandedTextAds. Is there any information about the timeline you can publicly disclose? Some articles state end of august but I know v201809 is coming soon, so we are left wondering here.

https://support.google.com/google-ads/answer/9100171
https://support.google.com/google-ads/answer/1704389

Much thanks!
Antoine

**Comment by fiboknacky** [comment]
Hello Antoine,

I can't make any comments about the v201809 release at this moment.
But the release should happen some time in September, 2019. :)

Best,
Knack
