### ISSUE TITLE
Cannot get AdSchedule object from CampaignCriterionService

### ISSUE THREAD

**Issue by npitsillos** [googleads/googleads-php-lib#522]
I have added a couple of AdSchedules on Google Ads via the API.  When I get these using the CampaignCriterionService and obtain the entries from the returned page they are CampaignCriterions.  Invoking the getCriterion() function returns Criterion instead of an AdSchedule object and I can't find a way to obtain the start end time etc.

**Comment by fiboknacky** [comment]
Hi there,

[Criterion](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/v201806/cm/Criterion.php) is a parent class of [AdSchedule](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/v201806/cm/AdSchedule.php).

I believe if you use [`instanceof`](http://php.net/manual/en/language.operators.type.php) on the object that is returned after creating `AdSchedule`, it'll show that the object is an instance of `AdSchedule`.
You can call any methods of the `AdSchedule` class like [`getStartHour()`](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/v201806/cm/AdSchedule.php#L78).

Best,
Knack

**Comment by fiboknacky** [comment]
Close as the solution was provided.
