### ISSUE TITLE
Undefined index: existingCard

### ISSUE THREAD

**Issue by wguerram** [googleads/googleads-php-lib#523]
Hello, when I click confirm order on the test environment I get the error Undefined index: existingCard in catalog/controller/extension/payment/stripe.php on line 53

What could be the cause to that issue?

**Comment by fiboknacky** [comment]
Your file path doesn't seem familiar to me.
Could you please provide more details? What're you trying to achieve?
And what product are you using?

**Comment by fiboknacky** [comment]
Close due to inactivity.
