### ISSUE TITLE
how i can refresh token without prompt user for offline auth?

### ISSUE THREAD

**Issue by admicro** [googleads/googleads-php-lib#524]
When access_token expire for offline type, how i can refresh token without prompt user?

**Comment by fiboknacky** [comment]
Hello,

If you use this client library, that will be taken care of automatically.
All code examples, e.g., [GetCampaigns](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201806/BasicOperations/GetCampaigns.php), show how the `AdWordsSession` is created from the config file, which in turn, refresh tokens when needed.

Best,
Knack
