### ISSUE TITLE
How to create or update a ads scripts?

### ISSUE THREAD

**Issue by clickgumshoe** [googleads/googleads-php-lib#525]
my code only create standalone script or bound to drive file such as google spreadsheet,..
`$parentId='id of google drive file.';
$t=curl_post('https://script.googleapis.com/v1/projects',[
	CURLOPT_HTTPHEADER=> [
		'Content-Type: application/json',
		  'Authorization: Bearer '.$token,
	]
],json_encode([
	'title'=>'test script',
	'parentId'=>$parentId
]));`
But in google ads how to create or change bulk scripts using this api that provide by google? . please give me any advice, thank  a lot.

**Comment by fiboknacky** [comment]
Hello,

Not sure you're asking about the PHP client library or Google Ads scripts.
Could you please clarify?

Best,
Knack

**Comment by fiboknacky** [comment]
Do you mean [this one](https://developers.google.com/apps-script/overview)?
If so, it's not something that this library support.
This library is only for [AdWords API](https://developers.google.com/adwords/api/docs/guides/start).
As FYI, a similar library for the Google Ads API Beta is also available [here](https://developers.google.com/google-ads/api/docs/start).

**Comment by fiboknacky** [comment]
And you may want to check out the [AdWords scripts](https://developers.google.com/adwords/scripts/), which should integrate better with other Apps scripts. :)
