### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by notian** [googleads/googleads-php-lib#527]
PHP Warning when getEntries returns null instead of empty array:

Can be duplicated with this example:
https://developers.google.com/adwords/api/docs/samples/php/optimization#get-a-bid-landscape-for-an-ad-group-and-criterion

PHP Warning:  Invalid argument supplied for foreach() in ..../vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/Query/v201806/ServiceQuery.php on line 135
PHP Stack trace:
---
PHP   6. Google\AdsApi\Examples\AdWords\v201806\Optimization\GetKeywordBidSimulations::main() ..../Testing.php:117
PHP   7. Google\AdsApi\Examples\AdWords\v201806\Optimization\GetKeywordBidSimulations::runExample() ..../Testing.php:113
PHP   8. Google\AdsApi\AdWords\Query\v201806\ServiceQuery->hasNext() ..../Testing.php:108
PHP   9. Google\AdsApi\AdWords\Query\v201806\ServiceQuery::countLandscapePoints() ..../vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/Query/v201806/ServiceQuery.php:211

**Comment by thangduo** [comment]
Thanks for reporting this bug. It will be fixed in the next release.

**Comment by fiboknacky** [comment]
This is fixed in the [new release](https://github.com/googleads/googleads-php-lib/releases/tag/37.1.0).
