### ISSUE TITLE
Trying To generate Report using AdsManager API

### ISSUE THREAD

**Issue by prakashpandey0** [googleads/googleads-php-lib#529]
i already setup my credentials into adsapi_php.ini .
The error is :

Fatal error: Uncaught SoapFault exception: [HTTP] Unauthorized in /Applications/XAMPP/xamppfiles/htdocs/adds/src/Google/AdsApi/Common/AdsSoapClient.php:97

Thanks.

**Comment by thangduo** [comment]
Hi Prakash,

I just verify the AdsSoapClient.php and confirm that it works as intended. This is not a valid bug.

There could be permission issues with your account.

Please ensure that API access is enabled for your Ad Manager network and the credentials in your adsapi_php.ini are added to a role with report access.

You can refer to the [Get access to an Ad Manager network](https://developers.google.com/ad-manager/api/start#signup) section of the Get Started guide for step-by-step instruction.

If you need further assistance, please reach out to your Account Manager (if you have one), or reach out to our Support team on the [Developer Forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api). Our support team may reach out to you on a private and secured channel to troubleshoot your credentials.

Thanks,
Thang Duong
