### ISSUE TITLE
SoapFault exception: [HTTP] Bad Gateway in /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php:97

### ISSUE THREAD

**Issue by yasunchukandriy** [googleads/googleads-php-lib#530]
Hi!
I also have this problem.

> SoapFault exception: [HTTP] Bad Gateway in /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php:97
> Stack trace:
> #0 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(97): SoapClient->__doRequest('<?xml version="...', 'https://adwords...', '', 1, 0)
> #1 [internal function]: Google\AdsApi\Common\AdsSoapClient->__doRequest('<?xml version="...', 'https://adwords...', '', 1, 0)
> #2 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(153): SoapClient->__soapCall('get', Array, NULL, Array, Array)
> #3 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201806/cm/AdGroupService.php(139): Google\AdsApi\Common\AdsSoapClient->__soapCall('get', Array)

Version - v201806

**Comment by fiboknacky** [comment]
Hello there,

What's environment do you use (local or server)? 
Is it Windows or unix-based? Do you use it via proxy? If so, could you check if your proxy allows the call?
Does it happen intermittently or happen always?
And how did you run into this problem? You write your own code or run our examples?

Cheers,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity.
