### ISSUE TITLE
Uncaught InvalidArgumentException: Config file not found as specified: 'adsapi_php.ini'. Home directory could not be located so it was not searched.

### ISSUE THREAD

**Issue by cgvaghela** [googleads/googleads-php-lib#537]
When I have tried get all the campaign I got below error:

Uncaught InvalidArgumentException: Config file not found as specified: 'adsapi_php.ini'. Home directory could not be located so it was not searched.

Can you please help me.

Thanks in advance

**Comment by cgvaghela** [comment]
Hello,
any buddy out there?

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `401 Unauthorized` response: { "error": "unauthorized_client", "error_description": "Unauthorized" } in D:\xampp\htdocs\adwords-examples-37.1.0\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0

**Comment by fiboknacky** [comment]
It looks like you've resolved the first issue already?
Can you reach out to [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api) for the second issue?

Best,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity.
