### ISSUE TITLE
Video campaign reporting breakdown on age, location, gender etc.

### ISSUE THREAD

**Issue by Mat-thieu** [googleads/googleads-php-lib#539]
Hi,

Is it possible to breakdown the video campaign reports based on age, location, gender etc.?

If so, how would I go about this? I'm aware that you can't get VideoCampaigns through the campaign object, but perhaps there's some way to do it via reporting?

Thanks!

**Comment by fiboknacky** [comment]
Hello there,

Could you please post in the [AdWords API forum](https://groups.google.com/forum/#!forum/adwords-api) instead, as this is more like the product issue?

Thanks.
Knack
