### ISSUE TITLE
The field name contain string 'From' will invalidate from QueryValidator

### ISSUE THREAD

**Issue by kenpingshu** [googleads/googleads-php-lib#541]
I use ConversionTrackerService to get the data with field name's 'ExcludeFromBidding',
and return error
"The service query string is invalid. Validation fail reason: The AWQL string must not contain FROM, DURING, LIMIT clauses."
Maybe 'ExcludeFromBidding' contain 'From', 
because when I ignore this field, it work.

**Comment by fiboknacky** [comment]
Thang, could you take a look please?

**Comment by thangduo** [comment]
Hi kenpingshu,

Thanks for reporting this issue. Yes, this is a bug in the QueryValidator. It will be fixed in the next release.

Thanks,
Thang Duong

**Comment by thangduo** [comment]
Fixed in v201811 (v. 38.0.0).
