### ISSUE TITLE
How did you get ID for chrome browser?

### ISSUE THREAD

**Issue by inandi** [googleads/googleads-php-lib#542]
I want to target the only desktop which has Mozilla browser. so if I am not wrong i will need all lists of technology.

**Comment by fiboknacky** [comment]
Hi,

Excuse me but is your question related to AdWords API or DFP API?

Best,
Knack

**Comment by inandi** [comment]
yes about the Google ad-manager

**Comment by fiboknacky** [comment]
OK. Thang, could you take a look please?

**Comment by inandi** [comment]
> OK. Thang, could you take a look please?

u asking me? what to look?

**Comment by inandi** [comment]
for ref i saw this code on **class** **CreateLineItems**

```
		// Target just the Chrome browser.
        $browserTechnology = new Technology();
        $browserTechnology->setId(500072);

 		// Create technology targeting.
        $browserTargeting = new BrowserTargeting();
        $browserTargeting->setBrowsers([$browserTechnology]);
        $technologyTargeting = new TechnologyTargeting();
        $technologyTargeting->setBrowserTargeting($browserTargeting);
```

so that id is for chrome browser, now where can i get list/table to get other browser ids. also i want target particular device i.e. desktop only , so how to do that?

Thanks in advance

**Comment by fiboknacky** [comment]
No, I asked my colleague to have a look.
Anyway, thanks for your more details. :)

**Comment by fiboknacky** [comment]
In the meantime, your question looks more like related to the Ad Manager API in general, rather than the client library itself.
I would suggest you ask in [its forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api) instead.

**Comment by thangduo** [comment]
Hi Gobinda,

Sorry for the delayed answer here.

You can obtained the ID values by querying the PQL tables.

- Please refer to this [guide](https://developers.google.com/ad-manager/api/pqlreference) for complete information about PQL syntax. Then, you can find the [list of all available tables](https://developers.google.com/ad-manager/api/reference/latest/PublisherQueryLanguageService), including the `Browser` [table](https://developers.google.com/ad-manager/api/reference/latest/PublisherQueryLanguageService#browser).
- You can follow the `PublisherQueryLanguageService/GetAllLineItems.php` [example](https://github.com/googleads/googleads-php-lib/blob/e114ee774bb2c9ac8113f1874e558baf724f966c/examples/AdManager/v201808/PublisherQueryLanguageService/GetAllLineItems.php) to build a PQL query and execute it in PHP. Alternatively, you can use the [DFP Playground](https://dfp-playground.appspot.com/) to execute an arbitrary PQL query without writing any code.

![playground](https://user-images.githubusercontent.com/4349155/48319612-fa9e1f80-e5dd-11e8-85a6-3dc863ce507a.png)

**Comment by inandi** [comment]
it helped...thank you guys !!!
