### ISSUE TITLE
Here this php library code is to see data in command line, so how to use/parse this data in our app ?

### ISSUE THREAD

**Issue by inandi** [googleads/googleads-php-lib#543]
at least tell me the steps

**Comment by inandi** [comment]
at least tell me the steps

**Comment by fiboknacky** [comment]
Hello there,

Could you provide more details on what you would like to achieve?
And what products are you using? AdWords API or Ad Manager API?

Best,
Knack

**Comment by inandi** [comment]
Thanks for your reply, its Google Ad Manager API.
According to this documentation, I am able to use forecast_service and getting data on my terminal. But I want to use that data on my website like other APIs. I am a little confused, how to do that?

**Comment by thangduo** [comment]
Hi Gobinda,

You can integrate the Google Ad Manager API into your web application as you would with any other server-side integration.

Basically, you will need to do 2 steps:

- Authentication. Here's the how-to wiki [article](https://github.com/googleads/googleads-php-lib/wiki/API-access-using-own-credentials-(installed-application-flow)) for getting started.
- Import the services and their classes to make service requests and process the responses. In particular, you can follow our [example](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdManager/v201808/ForecastService/GetAvailabilityForecast.php#L63) to make the requests to the forecasting service. You can copy and paster the block of code in the `runExample` function into your web applications or web services code.

Thanks,
Thang Duong

**Comment by inandi** [comment]
it helped ...thanks pal :)
