### ISSUE TITLE
How to get error messages in Ad Manager (PHP library) ?

### ISSUE THREAD

**Issue by inandi** [googleads/googleads-php-lib#544]
I got this response (GetForecastDetail) : 
````
Google\AdsApi\AdManager\v201808\ApiException Object
(
    [errors:protected] => Array
        (
            [0] => Google\AdsApi\AdManager\v201808\LineItemFlightDateError Object
                (
                    [reason:protected] => START_DATE_TIME_IS_IN_PAST
                    [fieldPath:protected] => startDateTime
                    [fieldPathElements:protected] => Array
                        (
                            [0] => Google\AdsApi\AdManager\v201808\FieldPathElement Object
                                (
                                    [field:protected] => startDateTime
                                    [index:protected] => 
                                )

                        )

                    [trigger:protected] => 
                    [errorString:protected] => LineItemFlightDateError.START_DATE_TIME_IS_IN_PAST
                )

        )

    [message1:protected] => [LineItemFlightDateError.START_DATE_TIME_IS_IN_PAST @ startDateTime]
    [message:protected] => [LineItemFlightDateError.START_DATE_TIME_IS_IN_PAST @ startDateTime]
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /var/www/html/seloger/application/libraries/admanagerapi/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php
    [line:protected] => 43
    ....
    ....
    ....
````

And I want that error message 

> [message:protected] =>  [LineItemFlightDateError.START_DATE_TIME_IS_IN_PAST @ startDateTime]

How to do that?

Regards

**Comment by thangduo** [comment]
Hi Gobinda,

You can catch the ApiException and iterate through the inner errors. You can find multiple examples in this repository with the search term `"catch (ApiException"` (see [results](https://github.com/googleads/googleads-php-lib/search?q=catch+%28ApiException&unscoped_q=catch+%28ApiException)).

![catch](https://user-images.githubusercontent.com/4349155/48505398-fd368a00-e814-11e8-9fa6-e94707777c34.png)

For example, you can take a look at the `CampaignManagement/ValidateTextAd.php` file, [line 74](https://github.com/googleads/googleads-php-lib/blob/ef55b92cd10c2ff0ddd1354711c1e1a4092ed239/examples/AdWords/v201802/CampaignManagement/ValidateTextAd.php#L74). Even though this is an AdWords example, its error handling logic should be the same with Google Ad Manager.

Thanks,
Thang Duong
