### ISSUE TITLE
wsdl file if() check should include the length of the file contents, since it's empty in the repo

### ISSUE THREAD

**Issue by wislem** [googleads/googleads-php-lib#546]
Hello,

> I am trying to migrate to v38 and I bumped upon an error considering the local wsdl files being empty.
> SOAP-ERROR: Parsing WSDL: Couldn't load from 'C:\www\myproject\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\..\..\..\..\resources\wsdls\apis\ads\publisher\v201811\ReportService.wsdl' : Document is empty

Maybe it would be better to do something like this:
```
        $localWsdlPath = self::getLocalWsdlPath($wsdl);
        if (!file_exists($localWsdlPath) and strlen(file_get_contents($localWsdlPath))) {
            trigger_error("Local WSDLs bundled with this library were not found.\n",
                E_USER_NOTICE);
            parent::__construct($wsdl, $options);

            return;
        } else {
            $localWsdlPath = $this->wsdlUri;
        }
        
        parent::__construct($localWsdlPath, $options);
```

on this section:

https://github.com/googleads/googleads-php-lib/blob/23b6a76358743de0a3a8e387baabf40d37560706/src/Google/AdsApi/Common/AdsSoapClient.php#L76

**Comment by fiboknacky** [comment]
Thanks for reporting. We're working to fix this.
Please follow up in #545.

Best,
Knack
