### ISSUE TITLE
Target [Google\Auth\FetchAuthTokenInterface] is not instantiable.

### ISSUE THREAD

**Issue by discovery-mark** [googleads/googleads-php-lib#547]
Hello,

I have copy and pasted the laravel example controller loaded in the googleads library from composer and I am getting the following error:

Target [Google\Auth\FetchAuthTokenInterface] is not instantiable.

Am I missing something?

**Comment by fiboknacky** [comment]
Hello there,

Could you please be more specific about the steps you took to try the app?
Have you followed the instructions in [this file](https://github.com/googleads/googleads-php-lib/tree/master/examples/AdWords/LaravelSampleApp)?

Best,
Knack

**Comment by discovery-mark** [comment]
Hi Thanet,

I have followed that guide you sent exactly just now.

I thought I’d include what I have inside of the adsapi_php.ini file in hopes you might be able to double check it.

[ADWORDS]
; Required AdWords API properties. Details can be found at:
; https://developers.google.com/adwords/api/docs/guides/basic-concepts#soap_and_xml
developerToken = "ou0RYDiO9NRSukBQNhngZw"
clientCustomerId = "923-097-6586"

; Optional. Set a friendly application name identifier.
; userAgent = "INSERT_USER_AGENT_HERE"

; Optional additional AdWords API settings.
; endpoint = "https://adwords.google.com/"
; isPartialFailure = false

; Optional setting for utility usage tracking in the user agent in requests.
; Defaults to true.
; includeUtilitiesInUserAgent = true

[ADWORDS_REPORTING]
; Optional reporting settings.
; isSkipReportHeader = false
; isSkipColumnHeader = false
; isSkipReportSummary = false
; isUseRawEnumValues = false

[OAUTH2]
; Required OAuth2 credentials. Uncomment and fill in the values for the
; appropriate flow based on your use case. See the README for guidance:
; https://github.com/googleads/googleads-php-lib/blob/master/README.md#getting-started

; For installed application or web application flow.
clientId = "1038693655138-esfeiggitpev5vliv6fkgsq2p8c25g52.apps.googleusercontent.com"
clientSecret = "rlyrSsTHJzUcJtPrRMOpH6Vl"
refreshToken = "1/5PiRIGBnWXTt-YM4cqjsMMeT6xpeJcdoQlZTFgWUJF8roTGsP68bu9tl19XDjcCA"

; For service account flow.
; jsonKeyFilePath = "INSERT_ABSOLUTE_PATH_TO_OAUTH2_JSON_KEY_FILE_HERE"
; scopes = "https://www.googleapis.com/auth/adwords"
; impersonatedEmail = "INSERT_EMAIL_OF_ACCOUNT_TO_IMPERSONATE_HERE"

[SOAP]
; Optional SOAP settings. See SoapSettingsBuilder.php for more information.
; compressionLevel = <COMPRESSION_LEVEL>

[CONNECTION]
; Optional proxy settings to be used by requests.
; If you don't have username and password, just specify host and port.
; proxy = "protocol://user:pass@host:port"
; Enable transparent HTTP gzip compression for all reporting requests.
; enableReportingGzip = false

[LOGGING]
; Optional logging settings.
; soapLogFilePath = "path/to/your/soap.log"
; soapLogLevel = "INFO"
; reportDownloaderLogFilePath = "path/to/your/report-downloader.log"
; reportDownloaderLogLevel = "INFO"
; batchJobsUtilLogFilePath = "path/to/your/bjutil.log"
; batchJobsUtilLogLevel = "INFO"

Kind Regards,
Mark Smith
Junior Developer
[https://www.discoverydesign.co.uk/signatures/mark.jpg]
Discovery Design Limited
Business Address: Salvus House, Aykley Heads, Durham City, DH1 5TS
Registered Office: Salvus House, Aykley Heads, Durham City, DH1 5TS
Registered in England - Company Number 3556279. VAT Registration Number 733 9736 05
This communication contains information which is confidential and may also be privileged. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s) please note that any form of distribution, copying or use of this communication or the information in it is strictly prohibited and may be unlawful. If you have received this communication in error please return it to the sender, delete the email and destroy any copies of it. Thank you for your assistance. Neither Discovery Design Limited nor the sender accepts any responsibility for viruses and it is your sole responsibility to scan this email and any attachments for viruses.

**Comment by fiboknacky** [comment]
Hello,

Sorry for the late reply. Have you been able to resolve the issue yet?
From your original post, it looked like you "copy" and "paste" in your existing project?
If so, there might be some other config updates that you would need to do.
If not, could you please include the full error message here too?
And when did you get that error message? During running `composer install`?

Best,
Knack

**Comment by fiboknacky** [comment]
Close due to inactivity.

**Comment by mmccaff** [comment]
For anyone finding this and looking for a solution, the above is due to not binding the classes in the register method of AppServiceProvider.php:

```php
// Bind some classes related to the Google Ads API client library for
        // PHP.
        $this->app->bind(
            'Google\AdsApi\AdWords\AdWordsServices',
            function () {
                return new AdWordsServices();
            }
        );
        $this->app->bind(
            'Google\Auth\FetchAuthTokenInterface',
            function () {
                // Generate a refreshable OAuth2 credential for authentication
                // from the config file.
                return (new OAuth2TokenBuilder())->fromFile(
                    config_path() . "/adsapi_php.ini"
                )->build();
            }
        );
        $this->app->bind(
            'Google\AdsApi\AdWords\AdWordsSessionBuilder',
            function () {
                return new AdWordsSessionBuilder();
            }
        );
```

See:
https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/LaravelSampleApp/app/Providers/AppServiceProvider.php
