### ISSUE TITLE
Ad manager API not sending data in Windows 10.

### ISSUE THREAD

**Issue by inandi** [googleads/googleads-php-lib#550]
in ubuntu its working good, but same project is not running on windows 10. Need help.

**Comment by thangduo** [comment]
Hi Gobinda,

Can you please specify the location of your adsapi_php.ini file on Windows?

Thanks,
Thang Duong

**Comment by fiboknacky** [comment]
Close due to inactivity. Feel free to re-open this if you still have this issue.
