### ISSUE TITLE
GetAllCreatives API not returning all fields

### ISSUE THREAD

**Issue by adish-coditation** [googleads/googleads-php-lib#552]
I am currently working on 'GetAllCreatives' API(version v201808). I have creative created in the DFP and when I call this API I am getting only 2 fields in the response - ID and Name. 
Following are the details - 
service name : CreativeService
method name : getCreativesByStatement
statement : Where id > 0  LIMIT 5000 OFFSET 0

Can someone please help me and let me know how can I get other fields apart from these 2.Please let me know if ore details are needed.

**Comment by thangduo** [comment]
Hi,

Can you please provide your Google Ad Manager's network code? Also, would you be able to reproduce the same issue using the [DFP Playground](https://dfp-playground.appspot.com/)?

If you get a different output from the DFP Playground, then it is more likely a bug than a data or query issue.

Thanks,
Thang Duong

**Comment by adish-coditation** [comment]
Hi Thang,

Network Code is 21769699944.
Also, on DFP Playground I can see other attributes.H ere is the screenshot
for the same -

[image: image.png]

However, when I use API with the query mentioned in earlier post I get only
ID and Name. Please let me know if more information is needed.

Thanks,
Adish

**Comment by thangduo** [comment]
Please resend the screenshot.

**Comment by thangduo** [comment]
The network code that you provided is a test network:
XFP sandbox property
21769699944

There is only 1 creative in this network. Please confirm that we are looking at the same network.

Thanks,
Thang Duong

**Comment by adish-coditation** [comment]
Hi Thang,

Yes this is the same network to which I am hitting via api and connected to
via dfp playground.

Thanks,
Adish

**Comment by thangduo** [comment]
I am able to query the 2 creatives as you did. All the properties are working as intended.

Can you please explain what you are looking for that may not be covered by the currently available list of properties?
<img width="776" alt="screen shot 2018-12-17 at 8 40 49 am" src="https://user-images.githubusercontent.com/4349155/50090816-adfac500-01d7-11e9-9b16-f4f48443e2ac.png">

**Comment by fiboknacky** [comment]
Close this due to inactivity.
