### ISSUE TITLE
How to get MobileApplicationService and send ids to forcast taargetting ?

### ISSUE THREAD

**Issue by inandi** [googleads/googleads-php-lib#553]
I am unable to get the list of MobileApplicationService, PQL is not working. Then I need to send those ids into forecast targetting filter.

**Comment by thangduo** [comment]
Hi Gobinda,

Can you please post your code and the SOAP log?

Thanks,
Thang Duong

**Comment by fiboknacky** [comment]
Close this due to inactivity.
