### ISSUE TITLE
Invalid regular expression

### ISSUE THREAD

**Issue by AloneCoder** [googleads/googleads-php-lib#555]
There is an error in the regular expression validating proxy settings, it breaks this feature

https://github.com/googleads/googleads-php-lib/blob/6d5186522a5cd737b79a87a3b850fb3e9260b940/src/Google/AdsApi/Common/ConnectionSettings.php#L29

**Comment by fiboknacky** [comment]
Could you share the error message first?
As I've tested last time, it worked.

Thanks.

Knack

**Comment by fiboknacky** [comment]
Close due to inactivity.
