### ISSUE TITLE
SOAP-ERROR: Parsing WSDL: Couldn't load CompanyService.wsdl

### ISSUE THREAD

**Issue by sachinwng** [googleads/googleads-php-lib#558]
Whenever I am trying to fetch Companies, I am getting this error

"error": {
        "classname": "SoapFault",
        "message": "SOAP-ERROR: Parsing WSDL: Couldn't load from '\/home\/xxx\/xxxx/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/Common\/..\/..\/..\/..\/resources\/wsdls\/apis\/ads\/publisher\/v201811\/CompanyService.wsdl' : failed to load external entity \"\/home\/xxx\/xxxx\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/Common\/..\/..\/..\/..\/resources\/wsdls\/apis\/ads\/publisher\/v201811\/CompanyService.wsdl\"\n"
    }

**Comment by thangduo** [comment]
Hi,

For diagnostics, please try:
- Fetch another entity (eg. Users) to see if you get the exact same error.
- From the terminal, run `curl -v -XGET 'https://ads.google.com/apis/ads/publisher/v201808/CompanyService?wsdl'` to see if you can download the WSDL file.

Then, could you please upload the SOAP logs to this Google Drive [folder](https://drive.google.com/drive/folders/1UoLCfSVV7JbfGrd80-fpEC9tsnrt7qBB?usp=sharing)?

Thanks,
Thang Duong

**Comment by fiboknacky** [comment]
Closing due to no more activities.
