### ISSUE TITLE
Adwords API Budget Error NON_MULTIPLE_OF_MINIMUM_CURRENCY_UNIT

### ISSUE THREAD

**Issue by ronakprogrammer** [googleads/googleads-php-lib#559]
Hello,

We are trying to set the daily budget via Adwords API but api call is getting failed.

Here are below Details
$diffInDays = 6;
$weekly_budget = 201.04
$daily_budget = number_format($weekly_budget / $diffInDays, 2, '.', ''); // 33.51
$micro_amount = (float) ($daily_budget  * 1000000);

so if we convert to micro amount it becomes (33.51 * 1000000) = 33510000

But API throws error [BudgetError.NON_MULTIPLE_OF_MINIMUM_CURRENCY_UNIT @ operations[0].operand.amount]. We also type cast to float but still gives same problem.

Please check below Money object before making api call.

$money = new Money();
$money->setMicroAmount($micro_amount);

Google\AdsApi\AdWords\v201809\cm\Money Object
(
    [microAmount:protected] => 33510000
    [ComparableValueType:protected] => 
    [parameterMap:Google\AdsApi\AdWords\v201809\cm\ComparableValue:private] => Array
        (
            [ComparableValue.Type] => ComparableValueType
        )

)

but when I see soap log the microAmount is automatically changed to 33509999

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://adwords.google.com/api/adwords/cm/v201809">
	<SOAP-ENV:Header>
		<ns1:RequestHeader>
			<ns1:clientCustomerId></ns1:clientCustomerId>
			<ns1:developerToken>REDACTED</ns1:developerToken>
			<ns1:userAgent></ns1:userAgent>
			<ns1:validateOnly>false</ns1:validateOnly>
			<ns1:partialFailure>false</ns1:partialFailure>
		</ns1:RequestHeader>
	</SOAP-ENV:Header>
	<SOAP-ENV:Body>
		<ns1:mutate>
			<ns1:operations>
				<ns1:operator>SET</ns1:operator>
				<ns1:operand>
					<ns1:budgetId>ADWORDS_BUDGET_ID</ns1:budgetId>
					<ns1:amount>
						<ns1:microAmount>33509999</ns1:microAmount>
					</ns1:amount>
					<ns1:deliveryMethod>STANDARD</ns1:deliveryMethod>
				</ns1:operand>
			</ns1:operations>
		</ns1:mutate>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>

The strange thing if we set daily budget to different amount like $88.36 then it works fine but this specific value $33.51 doesn't work looks very weird and it could be PHP Library issue.

We are using PHP client library v201809 and PHP version 7

Thanks,
Ronak

**Comment by fiboknacky** [comment]
Hello Ronak,

Is your PHP 32-bit or 64-bit?
We have [some logic](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/v201809/cm/Money.php#L42) around here to deal with that.

Cheers,
Knack

**Comment by ronakprogrammer** [comment]
Hello Knack,

We have 64 Bit system, PHP_INT_SIZE is 8

Thanks,
Ronak

**Comment by fiboknacky** [comment]
I remember some issues like this years ago. It looks like the issue of the SOAP toolkit (rather than our library) when it converts data.
Can you try applying strval() around your value before setting it using `setAmount()`?

**Comment by ronakprogrammer** [comment]
yes so I converting to string fixed

$micro_amount = floatval(number_format(daily_budget * 1000000, 0,'.','')); // Fixes issue

Thanks,
Ronak

**Comment by fiboknacky** [comment]
Yes, it's confusing. 
As you've found the solution, I'm closing this issue.

And thanks for being our active user. :)
If you have time, I would recommend playing around the new [Google Ads API](https://github.com/googleads/google-ads-php) too.
