### ISSUE TITLE
Cannot set BiddingStrategyConfiguration Manual_cpm -> pay for Viewable Impressions

### ISSUE THREAD

**Issue by Babis86** [googleads/googleads-php-lib#566]
Hello everybody,
I have a problem with the BiddingStrategyConfiguration. when I send manual_cpm to the api. it is set to adwords under campagne> settings> bit

Viewable CPM (right)
Pay for Clicks (wrong)

But it should be set Viewable CPM pay for Viewable Impressions.

Is there any other way to put it as a pay for Viewable Impressions?

function
```    
private function _getBiddingStrategyConfiguration() :BiddingStrategyConfiguration
    {
        $biddingStrategyConfiguration = new BiddingStrategyConfiguration();
        $biddingStrategyConfiguration->setBiddingStrategyType($this->biddingStrategyConfiguration_biddingStrategyType);
        if ($this->biddingStrategyConfiguration_biddingStrategyType == 'MANUAL_CPC' ) {
            $biddingScheme = new ManualCpcBiddingScheme();
            $biddingScheme->setEnhancedCpcEnabled(FALSE);
            $biddingStrategyConfiguration->setBiddingScheme($biddingScheme);  
        }elseif ($this->biddingStrategyConfiguration_biddingStrategyType == 'MANUAL_CPM' ) {
            $biddingScheme = new ManualCpmBiddingScheme();
            //$biddingScheme->setViewableCpmEnabled(TRUE); 
            $biddingStrategyConfiguration->setBiddingScheme($biddingScheme);  
        }

        return $biddingStrategyConfiguration;
    }
```

SOAP
```
 Google\AdsApi\AdWords\v201806\cm\BiddingStrategyConfiguration::__set_state(array(
         'biddingStrategyId' => NULL,
         'biddingStrategyName' => NULL,
         'biddingStrategyType' => 'MANUAL_CPM',
         'biddingStrategySource' => NULL,
         'biddingScheme' => 
        Google\AdsApi\AdWords\v201806\cm\ManualCpmBiddingScheme::__set_state(array(
           'viewableCpmEnabled' => true,
           'BiddingSchemeType' => NULL,
           'parameterMap' => 
          array (
            'BiddingScheme.Type' => 'BiddingSchemeType',
          ),
        )),
         'bids' => NULL,
         'targetRoasOverride' => NULL,
      )),
```

best regards
babis

**Comment by fiboknacky** [comment]
Hello Babis,

As your question is related to the AdWords API in general, could you post your question in the [AdWords API forum ](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?

Thanks for your cooperation.

Best,
Knack

**Comment by Babis86** [comment]
Hi Knack,

i think this is an error on the api.
i have already try to send it without the $biddingScheme->setViewableCpmEnabled(TRUE);
and also without any $biddingScheme.

In the original code, only the biddingStrategyConfiguration was created without even creating a biddingScheme. And pass manual_cpm and set it wrong. I also tested it with both versions (v201806 / v201809). It is set wrong every time.

the same error is described with the version 201802. Unfortunately, it is not exactly what needs to be done to solve the problem. The solution proposals that were delivered always lead to the same error.

see link:

https://groups.google.com/forum/?nomobile=true#!searchin/adwords-api/viewable$20cpm%7Csort:date/adwords-api/hp98C2hoQxg/Swxt4MCzCQAJ

Best,
babis

**Comment by fiboknacky** [comment]
Hello Babis,

I'm not sure if you can solve your problem already? It looks like you told Peter that you know the issue already. :)

If you still cannot find the solution, could you please continue your conversation with Peter?
He'll help you in case you still have any problems with your code.
If it's really an issue in the client library, then we can continue our conversation here.

Thanks for your understanding.

Best,
Knack

**Comment by Babis86** [comment]
Hi Knack,

no i was not involved in the conversation. this was between Peter and 饒義忠. 饒義忠 said he has the alleged solution, but I doubt it.

I still try to reach Peter but my invest seems to be checked first : /

thx again

**Comment by fiboknacky** [comment]
Oops. Sorry for misunderstanding.
Feel free to ask there first for the question like this. We have our team monitoring the questions, so you would get first reply quickly. :)
