### ISSUE TITLE
ReportDownloader HTTP ERROR 500 - ReportDownloader class

### ISSUE THREAD

**Issue by KarimZghali** [googleads/googleads-php-lib#569]
Hi,
I have a problem very similar to another post but which has not been solved:
I modified the ParallelReportDownload.php file in the adwords-examples-39.0.0 folder to retrieve campaign statistics. It works very well locally but when I test from the server this generates an HTTP 500 error that seems to come from the ReportDownloader class.

The log result:
[2019-02-10 09:48:16] AW_SOAP.INFO: clientCustomerId = 311-550-6872 operations = 1 service = ManagedCustomerService method = get responseTime = 238 requestId = 0005818640cbd9f90a859256d500a105 server = adwords.google.com isFault = 0 faultMessage =

An idea of the problem?

Thank you in advance

**Comment by fiboknacky** [comment]
Looks like there is an error on ManagedCustomerService.
Could you please post in the [AdWords API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api)?

Thank you.

Best,
Knack
