### ISSUE TITLE
Better support for Shopping API

### ISSUE THREAD

**Issue by athen66** [googleads/googleads-php-lib#57]
I know you've got examples for creating Product Partition Trees (AddProductPartitionTree.php) but not seeing functionality in the class to change bids at the Partition/Product Grouping level.

Hoping you'll be able to expand upon more of the new Shopping API features in the next release.

**Comment by vtsao** [comment]
We have a utility that may be helpful in our Java client library:
https://github.com/googleads/googleads-java-lib/blob/master/modules/adwords_axis/src/main/java/com/google/api/ads/adwords/axis/utils/v201502/shopping/ProductPartitionTree.java

but there are no immediate plans to port to PHP at this time. Closing this for now, but if many others ping this issue, we may consider it.

**Comment by vtsao** [comment]
There is also this guide for the ads Java client library:
https://github.com/googleads/googleads-java-lib/wiki/Shopping-product-partition-utility-for-AdWords

may be of help. And our blog post about it:
http://googleadsdeveloper.blogspot.ca/2015/03/shopping-utility-available-in-adwords.html
