### ISSUE TITLE
Cannot create AdGroup

### ISSUE THREAD

**Issue by ignacionelson** [googleads/googleads-php-lib#571]
Hello. I've been having issues creating adgroups. Even when using the examples provided with the api.

When running my custom code, I get
`Unmarshalling Error: cvc-type.2: The type definition cannot be abstract for element ns1:settings`
example request id: empty

or
`Unmarshalling Error: cvc-type.2: The type definition cannot be abstract for element ns1:bids.`
example request id: empty

When switching to the example, the response is
` [InternalApiError.UNEXPECTED_INTERNAL_API_ERROR @ com.google.ads.api.services.common.error.InternalApiError.<init>(InternalApiErro]`
example request id for this last error is 0005822d18d698c10a377dc74b084c27

Any help will be appreciated.
Thanks!

**Comment by fiboknacky** [comment]
Hello,

Let's started from the code example, I'll pass that request ID to Engineering and will get back to you once I hear more.

Best,
Knack

**Comment by fiboknacky** [comment]
BTW, what example did you run?
I see you use a CampaignService, but the name you used is something like "AdGroup for campaign #00000015-00000270"?
