### ISSUE TITLE
How to integrate this library to Codeigniter?

### ISSUE THREAD

**Issue by pavankumarvanam** [googleads/googleads-php-lib#572]
Hello GoogleAds Team,

I want to integrate this library to Codeigniter. How can I do that? Providing steps would be a really big help to me.

ManyThanks.

**Comment by fiboknacky** [comment]
Hello,

Currently, what we have as an example for MVC web app is Laravel app.
You can see it [here](https://github.com/googleads/googleads-php-lib/tree/master/examples/AdWords/LaravelSampleApp).

For now, integrating this library with Codeigniter is not in our road map, but we'll keep your feedback for prioritization in the future.

Best,
Knack
