### ISSUE TITLE
BudgetService NON_MULTIPLE_OF_MINIMUM_CURRENCY_UNIT

### ISSUE THREAD

**Issue by maks-avana** [googleads/googleads-php-lib#575]
Hi,

I am having an issue with BudgetService mutate. Details are as below:

1. I am using PHP 64 bit.

2. For conversion I am using below code before setting amount using setMicroAmount
```
$micro = $amount * 1000000;

return floatval(number_format($micro, 0, '.', ''));

```
3. Our account currency is IDR.

4. As you can see conversion is similar to what's been posted here https://github.com/googleads/googleads-php-lib/issues/559, but it still does not work.

Below SOAP request XML:

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://adwords.google.com/api/adwords/cm/v201806">
    <SOAP-ENV:Header>
        <ns1:RequestHeader>
            <ns1:clientCustomerId>6966754895</ns1:clientCustomerId>
            <ns1:developerToken>REDACTED</ns1:developerToken>
            <ns1:userAgent>unknown (AwApi-PHP, googleads-php-lib/36.0.0, PHP/7.2.15-1+ubuntu16.04.1+deb.sury.org+1)</ns1:userAgent>
            <ns1:validateOnly>false</ns1:validateOnly>
            <ns1:partialFailure>false</ns1:partialFailure>
        </ns1:RequestHeader>
    </SOAP-ENV:Header>
    <SOAP-ENV:Body>
        <ns1:mutate>
            <ns1:operations>
                <ns1:operator>ADD</ns1:operator>
                <ns1:operand>
                    <ns1:name>All Products Campaign 2019-03-06 07:20:32 #5c7f7394d3314</ns1:name>
                    <ns1:amount>
                        <ns1:microAmount>34595100000</ns1:microAmount>
                    </ns1:amount>
                    <ns1:deliveryMethod>STANDARD</ns1:deliveryMethod>
                    <ns1:isExplicitlyShared>false</ns1:isExplicitlyShared>
                </ns1:operand>
            </ns1:operations>
        </ns1:mutate>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

Thanks,
Maks

**Comment by fiboknacky** [comment]
Hi Maks,

Can you try strval() instead?
And what is the number that you really want to set?

Knack

**Comment by maks-avana** [comment]
Hi Knack,

thanks for your reply. With strval got the same results. I am using below now:

`return strval(number_format($micro, 0, '.', ''));`

Below new request details:

```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://adwords.google.com/api/adwords/cm/v201806">
    <SOAP-ENV:Header>
        <ns1:RequestHeader>
            <ns1:clientCustomerId>1423930476</ns1:clientCustomerId>
            <ns1:developerToken>REDACTED</ns1:developerToken>
            <ns1:userAgent>unknown (AwApi-PHP, googleads-php-lib/36.0.0, PHP/7.2.15-1+ubuntu16.04.1+deb.sury.org+1)</ns1:userAgent>
            <ns1:validateOnly>false</ns1:validateOnly>
            <ns1:partialFailure>false</ns1:partialFailure>
        </ns1:RequestHeader>
    </SOAP-ENV:Header>
    <SOAP-ENV:Body>
        <ns1:mutate>
            <ns1:operations>
                <ns1:operator>ADD</ns1:operator>
                <ns1:operand>
                    <ns1:name>All Products Campaign 2019-03-08 08:56:40 #5c822d1cb980a</ns1:name>
                    <ns1:amount>
                        <ns1:microAmount>34756100000</ns1:microAmount>
                    </ns1:amount>
                    <ns1:deliveryMethod>STANDARD</ns1:deliveryMethod>
                    <ns1:isExplicitlyShared>false</ns1:isExplicitlyShared>
                </ns1:operand>
            </ns1:operations>
        </ns1:mutate>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
The amount is dynamic based on exchange rate. In above request it's IDR34756.10.

Thanks,
Maks

**Comment by fiboknacky** [comment]
Checking with [the documentation here](https://developers.google.com/adwords/api/docs/appendix/codes-formats), it looks like the error is as intended.
(See the **Currency codes** section)
IDR has the minimum unit as 1000000, but you provided 34756100000.
Your last unit is 100,000, which is less than 1,000,000.

Knack

**Comment by maks-avana** [comment]
Thanks Knack, I didn't notice IDR has different minimum unit value.
