### ISSUE TITLE
How to get location feed id ?

### ISSUE THREAD

**Issue by harshit1235** [googleads/googleads-php-lib#578]
Hi,

I want to add targeting criteria in campaign and for that I have found one link:

https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201809/Targeting/AddCampaignTargetingCriteria.php

Code line:
**********
const LOCATION_FEED_ID = 'INSERT_LOCATION_FEED_ID_HERE';

How I get location feed id ?

Please help me 

Thanks&Regards

**Comment by fiboknacky** [comment]
You can refer to [this example](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201809/Targeting/GetCampaignTargetingCriteria.php), and add [one more selector field](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201809/Targeting/GetCampaignTargetingCriteria.php#L52): [FeedId](https://developers.google.com/adwords/api/docs/appendix/selectorfields#v201809-CampaignCriterionService).

This will have the API server return the feed IDs back for you.

Best,
Knack
