### ISSUE TITLE
No examples for BudgetOrder

### ISSUE THREAD

**Issue by ignacionelson** [googleads/googleads-php-lib#579]
Hello.
I could not find any examples for Billing -> BudgetOrder, so I'm working with the java one and doing the conversion to php. 
If it's possible, please add a few examples for reference.
Thank you!

**Comment by fiboknacky** [comment]
Hello,

Thank you very much for your feedback and sorry for your inconvenience.
However, the AdWords API is being deprecated in favor of the Google Ads API.
So, we shift our priority to [this library](https://github.com/googleads/google-ads-php) instead.

I'd recommend starting using the Google Ads API instead.
In the library, there are many billing-related examples that you can learn from, e.g., [AddAccountBudgetProposal](https://github.com/googleads/google-ads-php/blob/master/examples/Billing/AddAccountBudgetProposal.php).
This AddAccountBudgetProposal is equivalent to the example of adding budget orders in the AdWords API.

Best,
Knack
