### ISSUE TITLE
API - Scaled partner management

### ISSUE THREAD

**Issue by mrceperka** [googleads/googleads-php-lib#581]
Hello,

is there any way how to check if there is already existing child publisher or domain?

Because it is possible in Google Ad Manager UI.
I was hoping that https://ads.google.com/apis/ads/publisher/SubsyndicateService?wsdl or similar exists, but it does not.

Thank you.

**Comment by fiboknacky** [comment]
Hello,

As this issue is more related to the Google Ad Manager API in general, could you post your question in [its forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api) instead?

Thank you for your cooperation.

Knack
