### ISSUE TITLE
ADVERTISER_NOT_WHITELISTED_FOR_USING_UPLOADED_DATA

### ISSUE THREAD

**Issue by gamunax** [googleads/googleads-php-lib#583]
Hello
I'm getting this error trying this example code:https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201809/Remarketing/AddCrmBasedUserList.php

AW_SOAP.WARNING: clientCustomerId=755-039-4903 operations= 1 service=AdwordsUserListService method=mutate responseTime=187 requestId=000586 465f25377a0a818344ae07ca6e server=adwords.google.com isFault=1 faultMessage=[Use rListError.ADVERTISER_NOT_WHITELISTED_FOR_USING_UPLOADED_DATA @ operations[0].op erand]
Please, help me...

What should I do to fix that error?

**Comment by fiboknacky** [comment]
Hello,

For whitelist-related issues, please post on [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).
Thank you for your cooperation.

Best,
Knack
