### ISSUE TITLE
multiple ad account doesn't work?

### ISSUE THREAD

**Issue by rakibtg** [googleads/googleads-php-lib#584]
Hi, i think in our app we are using desktop based token, and it gets the `clientId`, `clientSecret` and `refreshToken` from `adsapi_php.ini` file. Like this: 
```php
        $oAuth2Credential = (new OAuth2TokenBuilder())
          ->fromFile( \App::dir('credentials/adsapi_php.ini') )
          ->build();

        $session = (new AdWordsSessionBuilder())
          ->fromFile( \App::dir('credentials/adsapi_php.ini') )
          ->withOAuth2Credential($oAuth2Credential)
          ->build();
```
To show a list of accounts i was testing using this class [GetAccountHierarchy.php](https://github.com/googleads/googleads-php-lib/blob/e3be09d87579ec3cb77f29cc5c6819cbdb085451/examples/AdWords/v201809/AccountManagement/GetAccountHierarchy.php), but it shows the ID of only one account though we have almost 15+ accounts i think.

Is multiple account listing is working properly? or is that i am missing something.

Regards :)

**Comment by fiboknacky** [comment]
Hello,

What's your manager account ID?

Best,
Knack

**Comment by rakibtg** [comment]
Hi @fiboknacky 
Can I PM you the manager account ID?

**Comment by fiboknacky** [comment]
Could you send to googleadsapi-forumadvisor@google.com and mention this GitHub issue please?
Thanks.

**Comment by rakibtg** [comment]
I just sent an email @fiboknacky :)

**Comment by fiboknacky** [comment]
I saw your issue has been resolved already, so closing this.
