### ISSUE TITLE
Getting the ReportError object

### ISSUE THREAD

**Issue by jmrodriguez-smartclip** [googleads/googleads-php-lib#585]
I'm using the Reporting API examples to fetch a report that has a certain chance of failing, due to no data available.
But cant get the reason why the report fails.As shown in the examples, all i get is "Report failed", when trying to download the report.
Is there any way to retrieve what caused the error?

**Comment by christopherseeley** [comment]
If the report status is FAILED then there's no additional error information provided by the API. The most common cause is a timeout, or some temporary issue with the Ad Manager server. You can take a look at the report utility source code here for more details about how the client library handles this case:
https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdManager/Util/v201902/ReportDownloader.php#L185

Other report problems with throw an API error like this, which has more detail:
http://developers.google.com/ad-manager/docs/reference/v201902/ReportService.ReportError
