### ISSUE TITLE
Multiple issues since Mon, May 13th

### ISSUE THREAD

**Issue by gchicoye** [googleads/googleads-php-lib#587]
Hi,

I'm facing a lot of issues since Monday on both reporting and administration on Ad Manager API.
For instance,
- I get a false return since Monday on this
 `$reportDownloader = new ReportDownloader(
            $reportService,
            $reportJob->getId()
        );
        if ($reportDownloader->waitForReportToFinish())
...
`

- I've got frequent issues with this function (among others...)
`$output = '';
		$lineItemService = $this->serviceFactory->createLineItemService($this->session);
		$statementBuilder = (new StatementBuilder())
			->orderBy('id ASC')
			->where('name = :name AND orderId = :orderId')
			->WithBindVariableValue('name', $this->lineItemName)
			->WithBindVariableValue('orderId', $this->orderId);
		$data = $lineItemService->getLineItemsByStatement($statementBuilder->toStatement());`

I get:
PHP Fatal error:  Call to a member function getResults() on null in /home/gabriel/dfp/app/AdManager/LineItemManager.php on line 144

I thinks it coming more from Google than from me as I did not change anything...

Thanks!

**Comment by fiboknacky** [comment]
Could you please post on the [Google Ad Manager API forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api) as well?
It looks like the data that should be returned aren't returned properly, so there might be something wrong in the query processing.

**Comment by gchicoye** [comment]
I don't think it's necessary...

https://groups.google.com/forum/#!topic/google-doubleclick-for-publishers-api/v2RlYlYk0mQ

Thanks for the tip!
