### ISSUE TITLE
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `401 Unauthorized` response:

### ISSUE THREAD

**Issue by buzzyears-brijesh-kumar** [googleads/googleads-php-lib#588]
Hi,
When  executing php examples/BasicOperations/GetCampaigns.php
getting an error 
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `401 Unauthorized` response:
{
  "error": "unauthorized_client",
  "error_description": "Unauthorized"
}
 in /home/buzzyears/Downloads/google-ads-php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/buzzyears/Downloads/google-ads-php/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/buzzyears/Downloads/google-ads-php/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/buzzyears/Downloads/google-ads-php/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/buzzyears/Downloads/google-ads-php/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::Guz in /home/buzzyears/Downloads/google-ads-php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 11

Please suggest the correct solution

Thanks 
Brijesh

**Comment by fiboknacky** [comment]
For authorization errors, please post in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).
Thank you.
