### ISSUE TITLE
 Class 'Google\AdsApi\Common\OAuth2TokenBuilder' not found in

### ISSUE THREAD

**Issue by fabianamanu** [googleads/googleads-php-lib#589]
I'm sorry for the English

 created an index.php to display my reports plus I am with the following error Fatal error: Uncaught Error: Class 'Google \ AdsApi \ Common \ OAuth2TokenBuilder'

![erro](https://user-images.githubusercontent.com/12700210/58030357-ca878a00-7af4-11e9-90cd-857fad5c0a44.png)

**Comment by fiboknacky** [comment]
Hello,

How did you install this library? Did you use `composer require` as suggested in [README](https://github.com/googleads/googleads-php-lib#downloading-this-library)?

Best,
Knack

**Comment by fabianamanu** [comment]
?????

**Comment by fabianamanu** [comment]
Yes, I have installed it according to the instructions in the documentation

**Comment by fiboknacky** [comment]
Thanks for confirming. I assume that you used `composer require`, but if you use `git clone` instead, please let me know.

Then, could you please provide the following info:

* The whole file of your code. I need to see the beginning of your code too.
* The directory structure of your project directory, including your files and our library files.

**Comment by fabianamanu** [comment]
isto usei o   composer require
`<?php
ini_set('display_errors',1);
ini_set('display_startup_erros',1);
error_reporting(E_ALL);

require __DIR__ . '/vendor/autoload.php';
 
use Google\AdsApi\AdWords\AdWordsServices;
use Google\AdsApi\AdWords\AdWordsSessionBuilder;
use Google\AdsApi\AdWords\ReportSettingsBuilder;
use Google\AdsApi\AdWords\v201705\cm\CampaignService;
use Google\AdsApi\AdWords\v201702\cm\ReportDefinitionReportType;
use Google\AdsApi\AdWords\v201702\cm\ReportDefinitionService;
use Google\AdsApi\AdWords\Reporting\v201705\ReportDownloader;
use Google\AdsApi\AdWords\v201705\cm\OrderBy;
use Google\AdsApi\AdWords\v201705\cm\Paging;
use Google\AdsApi\AdWords\v201705\cm\Selector;
use Google\AdsApi\Common\OAuth2TokenBuilder;
 
class Adwords
{    
 
    public static function getData(){
        $oAuth2Credential = (new OAuth2TokenBuilder())
            ->fromFile()
            ->build();            
 
        /*
            Aqui você pode recuperar dados de outro clientId, diferente do que informou no adsapi_php.ini
            porém pode retirar o método "withClientCustomerId" para pegar os dados padrões do clientId do arquivo adsapi
        */
        $session = (new AdWordsSessionBuilder())
            ->fromFile()
            ->withOAuth2Credential($oAuth2Credential)  
            ->withClientCustomerId('CLIENT_ID_CUSTOMER')                      
            ->build();   
         
        #Utilizando AWQL poderá ver os exemplos e combinações no link: https://developers.google.com/adwords/api/docs/appendix/reports
        $reportQuery = 'SELECT Impressions,Clicks, Cost, AverageCpc, Conversions, ConversionRate, CostPerConversion 
                 FROM ACCOUNT_PERFORMANCE_REPORT DURING 20171101,20171130';
         
        $reportFormat = 'XML';
        $reportDownloader = new ReportDownloader($session);
        $reportDownloadResult = $reportDownloader->downloadReportWithAwql(
        $reportQuery, $reportFormat);
 
        $datatest =  $reportDownloadResult->getAsString();
 
        $xml = simplexml_load_string($datatest);
        $json = json_encode($xml);        
 
        //return array        
        echo ($json);                
    }
}
 
AdWords::getData();
?>
![dir](https://user-images.githubusercontent.com/12700210/58107261-d724e480-7bbf-11e9-8d4b-06e2ad9f16ec.png)
`

**Comment by fiboknacky** [comment]
OK. I spotted the first error you would need to address first.
Your PHP doesn't have the SOAP extension. You need to install it first.
You can search on the internet about that, but if you really can't find a way to do so, please let me know again.

**Comment by fabianamanu** [comment]
Okay, but it's just the soap bug? install and check again

Thank you for your attention and I'm sorry for bad English.

**Comment by fabianamanu** [comment]
![p](https://user-images.githubusercontent.com/12700210/58115699-009a3c00-7bd1-11e9-941a-4102bc16e09b.PNG)
when adding extension = php_soap.dll comes up this other error when putting extension = php_soap.dll did something wrong? what would it be?

**Comment by fiboknacky** [comment]
No need to sorry about English. :) I'm not a native speaker too.

It looks like you've not get the latest version of AdWords API?
The version of AdWords API you used (v2013XX) is super old and is long gone.

Could you confirm you really installed the library based on README?
If so, it should install you v201809.

**Comment by fabianamanu** [comment]
I noticed from what you said about using the version I ran the v201809 version. and the same error persists
![Capturar333](https://user-images.githubusercontent.com/12700210/58116970-f9286200-7bd3-11e9-85f7-c501a9fcb1b4.PNG)

**Comment by fiboknacky** [comment]
It's still the screenshot of v201309 version. Could you attach the new one:

**Comment by fabianamanu** [comment]
I'm sorry the error still, now note this v201309 I have no other newer version and this

**Comment by fiboknacky** [comment]
I'm not sure how I could communicate this to you well. I'll try to use shorter sentences, so sorry if it looks a bit blunt.

In short, 
1.   Delete old library
2.  Install the new one (follow our README)
3.  Try again

**Comment by fabianamanu** [comment]
Okay, okay, no problem, I'll delete it and do it all over again

**Comment by fiboknacky** [comment]
OK. Please try and let me know the result.

**Comment by fabianamanu** [comment]
When downloading everything again the way and install the composer more when searching for a content I believe it does not go like this with GetCampaigns.php ,
now I am very confused and I did according to REAME

**Comment by fabianamanu** [comment]
![novo12](https://user-images.githubusercontent.com/12700210/58183688-1f0e3f00-7c86-11e9-8885-3ee8ea0851d8.png)
I did something like I am with a new one, but still with error

**Comment by fiboknacky** [comment]
As the error message said, you've not created the `adsapi_php.ini` in your home directory yet.
Please follow [the instructions](https://github.com/googleads/googleads-php-lib#getting-started) in the README file.

**Comment by fabianamanu** [comment]
sorry for my work again another problem
![novo13](https://user-images.githubusercontent.com/12700210/58186190-c5f4da00-7c8a-11e9-8a17-13992a537aa2.png)

**Comment by fiboknacky** [comment]
OK. It looks like you stuck with very basic problems many times. :)

Apart from reading all [README](https://github.com/googleads/googleads-php-lib/blob/master/README.md) text, I'd recommend you start by reading [this guide](https://developers.google.com/adwords/api/docs/guides/first-api-call) completely from the beginning to the end.

For this particular issue, as indicated by the error message, your developer token hasn't been approved yet, so you cannot use the AdWords API yet.

Please read the basic guides in our website and README first and try again.
In many cases, you could solve the problems by reading the error messages.
If the error messages are not clear to you, feel free to ask us for clarification.

**Comment by fabianamanu** [comment]
Thanks for the help, I'm just waiting for the okay token approval, okay?

**Comment by fiboknacky** [comment]
Yes, if you don't get the approval after several days, please reach out to the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).

**Comment by fabianamanu** [comment]
my token has not been approved yet I checked if my email is correct, they have done the total of six days and I did not have any answer and without the token I can not do anything, I already asked questions in the forum but no one resets me until the moment what I must do?

**Comment by fiboknacky** [comment]
Could you give me the link to that forum post?

**Comment by fabianamanu** [comment]
Hi, solved the situation, thank you for your attention and sorry for the inconvenience.
