### ISSUE TITLE
Error Customer Id Login

### ISSUE THREAD

**Issue by adrianlaraperez88** [googleads/googleads-php-lib#591]
Hi Team,

I have a problem, now working with the new version for Google Ads but I have this error.

` Grpc\Timeval::__construct() expects parameter 1 to be integer, float given in C:\xampp\htdocs\google_ads_new_version\google-ads-php\vendor\grpc\grpc\src\lib\AbstractCall.php on line 55

Warning: Grpc\Timeval::__construct() expects parameter 1 to be integer, float given in C:\xampp\htdocs\google_ads_new_version\google-ads-php\vendor\grpc\grpc\src\lib\AbstractCall.php on line 55
PHP Fatal error:  Uncaught InvalidArgumentException: Timeval expects a long in C:\xampp\htdocs\google_ads_new_version\google-ads-php\vendor\grpc\grpc\src\lib\AbstractCall.php:55`

CUSTOMER_ID = '629-195-0585';

$response =
            $googleAdsServiceClient->search($customerId, $query, ['pageSize' => self::PAGE_SIZE]);

**Comment by fiboknacky** [comment]
Could you confirm if you're using the AdWords API or the Google Ads API?
This library is the SOAP library for the AdWords API.

**Comment by adrianlaraperez88** [comment]
Sorry, this tickets is in the new library. Sorry
