### ISSUE TITLE
question about the different sdks

### ISSUE THREAD

**Issue by Babis86** [googleads/googleads-php-lib#593]
I have a question about the different sdks.

what exactly is the difference between the googleads-php-lib sdk and the google-ads-php sdk.
Do I have to change the sdk or can I still use the googleads-php-lib sdk?

If a sunset was chosen for the googleads-php-lib 201809. And you really have to switch to the new sdk. Will there be enough time to change then.

best
Babis86

**Comment by fiboknacky** [comment]
Hello,

This library is for the old AdWords API, which will be sunset next year.
The google-ads-php library is for the newly released [Google Ads API](https://developers.google.com/google-ads/api/docs/start).

And you understand correctly, no further releases will be made in this library for the AdWords API anymore.
This has been announced in this blog.

Best,
Knack

**Comment by Babis86** [comment]
Ok thx Knack for the fast response

Best,
Babis
