### ISSUE TITLE
LibraryMetadataProvider might trigger a warning

### ISSUE THREAD

**Issue by adriansuter** [googleads/googleads-php-lib#594]
If the php function `parse_ini_file()` had been disabled for security reasons, then the constructor in `Google\AdsApi\Common\LibraryMetadataProvider` would trigger a warning.

https://github.com/googleads/googleads-php-lib/blob/2af2eb006f7bf5536b2d00e858941d55206fbf42/src/Google/AdsApi/Common/LibraryMetadataProvider.php#L31

It is not a big problem, as in production error reporting should be turned off anyway - but it might fill log-files.

**Comment by fiboknacky** [comment]
Could you elaborate more how it's disabled and what kind of message you see?

**Comment by fiboknacky** [comment]
Closing as GitHub somehow prevented the user to reply to this issue and thus a new one has been created.
