### ISSUE TITLE
500 Internal Server Error on POST /apis/ads/publisher/v201905/ReportService?wsdl

### ISSUE THREAD

**Issue by adam1920** [googleads/googleads-php-lib#601]
I'm executing next php for trying to get AdManager Reports:
`$ php googleads/AdManager/v201905/ReportService/RunSavedQuery.php `

and I got 500 error message from https://ads.google.com/apis/ads/publisher/v201905/ReportService?wsdl

Please help!

Attached output
`
[2019-07-03 07:03:11] DFP_SOAP.INFO: networkCode=52117743 service=ReportService method=getSavedQueriesByStatement responseTime=105 requestId=986d4db6bf5072c3f6b8cfa331373914 server=ads.google.com isFault=0 faultMessage=  
[2019-07-03 07:03:12] DFP_SOAP.WARNING: networkCode=52117743 service=ReportService method=runReportJob responseTime=197 requestId=c6856686995b6dc87b06e4e2195e6dc1 server=ads.google.com isFault=1 faultMessage=**[PublisherQueryLanguageContextError.UNEXECUTABLE @ Evaluation of 'true' is unsupported.]**  
[2019-07-03 07:03:12] DFP_SOAP.NOTICE: POST /apis/ads/publisher/v201905/ReportService?wsdl HTTP/1.1
Host: ads.google.com
Connection: close
User-Agent: PHP-SOAP/7.2.19
Content-Type: text/xml; charset=utf-8
SOAPAction: ""
Content-Length: 1004
Authorization: REDACTED

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://www.google.com/apis/ads/publisher/v201905"><SOAP-ENV:Header><ns1:RequestHeader><ns1:networkCode>52117743</ns1:networkCode><ns1:applicationName>JoyLand (DfpApi-PHP, googleads-php-lib/42.0.0, PHP/7.2.19)</ns1:applicationName></ns1:RequestHeader></SOAP-ENV:Header><SOAP-ENV:Body><ns1:runReportJob><ns1:reportJob><ns1:reportQuery><ns1:dimensions>AD_UNIT_NAME</ns1:dimensions><ns1:dimensions>COUNTRY_NAME</ns1:dimensions><ns1:dimensions>HOUR</ns1:dimensions><ns1:adUnitView>HIERARCHICAL</ns1:adUnitView><ns1:columns>AD_EXCHANGE_LINE_ITEM_LEVEL_AVERAGE_ECPM</ns1:columns><ns1:dateRangeType>TODAY</ns1:dateRangeType><ns1:statement><ns1:query> where true</ns1:query></ns1:statement><ns1:includeZeroSalesRows>false</ns1:includeZeroSalesRows><ns1:timeZoneType>PUBLISHER</ns1:timeZoneType></ns1:reportQuery></ns1:reportJob></ns1:runReportJob></SOAP-ENV:Body></SOAP-ENV:Envelope>

HTTP/1.1 500 Internal Server Error
Content-Type: text/xml; charset=UTF-8
Date: Wed, 03 Jul 2019 07:03:12 GMT
Expires: Wed, 03 Jul 2019 07:03:12 GMT
Cache-Control: private, max-age=0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Alt-Svc: quic=":443"; ma=2592000; v="46,43,39"
Accept-Ranges: none
Vary: Accept-Encoding
Connection: close
`

**Comment by fiboknacky** [comment]
As this is related to the product in general, could you please post on the [Google Ads Manager API forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api) instead?
Thank you.

Knack
