### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by Missael89** [googleads/googleads-php-lib#602]
Hello team from GitHub,

I am trying to connect with the Adwords API and it throws me an error 400.

I already checked the php versions and I have the 7.1.31 to 64 bits.

Can you help me with this error?

I attach the txt with the error message.

regards!
[Message_Error.txt](https://github.com/googleads/googleads-php-lib/files/3374558/Message_Error.txt)

**Comment by fiboknacky** [comment]
Hello,

This is involved more with the AdWords API in general. In the future, please post in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead. 

As for your question, it's actually hinted in the error message:

```
PHP Fatal error:  Uncaught Google\AdsApi\AdWords\v201809\cm\ApiException: Details: [fieldPath: ; trigger: Basic Access Daily Reporting Quota; errorString: RateExceededError.RATE_EXCEEDED] in C:\xampp\htdocs\GoogleAdwords\vendor\googleads\googleads-php-lib\src\Google\AdsApi\AdWords\Reporting\v201809\ReportDownloader.php:234
```

You're the [basic access](https://developers.google.com/adwords/api/docs/access-levels) user of the API and there is a limit per day.
You've already reached [that limit](https://developers.google.com/adwords/api/docs/access-levels#basic_access) (1000 reporting requests per day) and thus face with an error.
If you aim to use the API frequently, please consider apply for [the standard access](https://developers.google.com/adwords/api/docs/access-levels#standard_access).

Best,
Knack
