### ISSUE TITLE
Account report but not downloaded!

### ISSUE THREAD

**Issue by manuelalvarezco** [googleads/googleads-php-lib#603]
Hello, 

I'm using the adwords API v201809 with php, I'm downloading the reports correctly but I have not managed to store that data in a variable. I need isn´t downloaded but stored and then displayed.

Next I show how I am saving the data in a .csv file.

I have searched the official documentation but I have not managed to obtain the information I need.

I hope my consultation was clear and you can help me

A greeting
![ok](https://user-images.githubusercontent.com/29968638/61493830-26964f80-a97a-11e9-835e-933a8d893266.PNG)

**Comment by fiboknacky** [comment]
Can you print the report download result as a string?
Could you share the result please?

**Comment by manuelalvarezco** [comment]
Thanks for answering, of course.
The download of the information is correct, however I need to store that information not download it.

![adgroup_report](https://user-images.githubusercontent.com/29968638/61536755-00fd5a80-a9fb-11e9-80df-cbdbd6ee7586.PNG)

This is what I need.

![save_data](https://user-images.githubusercontent.com/29968638/61537120-f2fc0980-a9fb-11e9-92ee-bf4585051237.PNG)

**Comment by fiboknacky** [comment]
What do you mean by "saving" the data? Saved to a variable, not a file?
If the variable, then the result is stored in `$reportDownloadResult` just below your highlighted line.
Note that you highlighted line doesn't do anything because the download doesn't happen yet.

**Comment by manuelalvarezco** [comment]
I understand that you do not make me understand, I will try to explain it with an example.

Through a query with selector I can store the information in a variable $keywords.


![var_dump](https://user-images.githubusercontent.com/29968638/61580894-a63c2f80-aadc-11e9-9d3e-519434e31698.PNG)

If I do a var_dump to that variable this is the result

![result_var_dump](https://user-images.githubusercontent.com/29968638/61580907-d2f04700-aadc-11e9-97e6-248ecb479389.PNG)

With this I can already foreach that variable in a view and get the result I want

![view_keywords](https://user-images.githubusercontent.com/29968638/61580954-a5f06400-aadd-11e9-92e6-34c6bfd3e0d4.PNG)


If I try to do the same with the variable that you mention, I do not get the result that I need.

![var_dump_reportD](https://user-images.githubusercontent.com/29968638/61581133-04b6dd00-aae0-11e9-93f3-5f2e1f16c51c.PNG)


Now, if I follow the documentation and add the function getAsString () before saving it, I get the following result.

![2](https://user-images.githubusercontent.com/29968638/61581205-dab1ea80-aae0-11e9-87a2-f440de30e1fd.PNG)

![3](https://user-images.githubusercontent.com/29968638/61581210-ee5d5100-aae0-11e9-8deb-70b0ef8141b8.PNG)

This is the result I need but I need to group it in an array so I can handle it in a view.

I hope you have explained me better.

**Comment by fiboknacky** [comment]
Thanks for more explanation.
The report download result in the AdWords API will always be returned as the format you've specified, e.g., CSV, XML.

The result will never be returned as an AdWords API object, like when you use SOAP services.
You have to parse those report download results by yourself, by using other utility functions like [fgetcsv](https://php.net/manual/en/function.fgetcsv.php).

Hope this help.
Knack

**Comment by fiboknacky** [comment]
As a solution is provided, I'm closing this.
