### ISSUE TITLE
When I try to get all networks it code throw exception.  

### ISSUE THREAD

**Issue by Greenelf** [googleads/googleads-php-lib#604]
https://github.com/googleads/googleads-php-lib/blob/1fda67abe578967418c20c87c0e5d9f1ea1e59be/src/Google/AdsApi/AdManager/AdManagerSessionBuilder.php#L325

https://developers.google.com/ad-manager/api/reference/v201808/NetworkService#getAllNetworks

**Comment by Josh-G** [comment]
This is similar to #557. You are forced to use `withNetworkCode` to set a networkCode for endpoints that don't require them.
I have found that setting any value for networkCode allows the client to call the endpoints. I then create a new AdManagerSession with the network code obtained in getAllNetworks

My use case is where the application does not know which network it will be managing until it has made a call to getAllNetworks

**Comment by thangduo** [comment]
Thanks for reporting this issue. I will investigate it.

**Comment by thangduo** [comment]
You may get exceptions when calling `$networkService->getAllNetworks()` if you fail [authentication](https://developers.google.com/ad-manager/api/authentication#service).

Once your application is authenticated and authorized to access at least one Ad Manager network, you will be able to call `$networkService->getAllNetworks()`.

**Comment by Josh-G** [comment]
@thangduo this is not related to authentication.

**Comment by thangduo** [comment]
This issue has been resolved in v. 49.0.0, commit 94160b7cf128a92ce8a1cedf549714f47fa273ea
The `AdManagerSessionBuilder` class no longer throws an exception to terminate the program flow upon a missing network code. Instead, it is triggering an E_USER_WARNING.
