### ISSUE TITLE
RequestError.UNSUPPORTED_VERSION v201806

### ISSUE THREAD

**Issue by dragon658** [googleads/googleads-php-lib#605]
When I try to use this lib, I get such error:

2019/07/22 16:07:00 [error] 614#614: *2055218 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Google\AdsApi\AdWords\v201806\cm\ApiException: [RequestError.UNSUPPORTED_VERSION @ ; trigger:'You are accessing an AdWords API version v201806 that has been discontinued. Calls to this version may fail. Please visit the AdWords API blog for information on migration to the new AdWords API version.'] in ..../googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php:43

**Comment by dragon658** [comment]
How to fix this? I cannot use adwords api because of this bug.

**Comment by fiboknacky** [comment]
It's actually not a bug. v201806 has been sunset many months ago. Please upgrade your client library to the latest version to use v201809 instead.

**Comment by dragon658** [comment]
I found such lines in my code. This lines caused this error:

```
use Google\AdsApi\AdWords\v201806\cm\SitelinkFeedItem;
use Google\AdsApi\AdWords\v201806cm\CampaignExtensionSetting;
use Google\AdsApi\AdWords\v201806\cm\CampaignExtensionSettingOperation;
use Google\AdsApi\AdWords\v201806\cm\CampaignExtensionSettingService;
```

I updated this lib (php composer.phar update) and changed v201806 to v201809 in these lines and problem was fixed. Thank you!
