### ISSUE TITLE
Method for CustomerService.getCustomers()

### ISSUE THREAD

**Issue by donjajo** [googleads/googleads-php-lib#607]
Hi,
How do I get this method in the PHP library?
https://developers.google.com/adwords/api/docs/reference/v201809/CustomerService#getcustomers

**Comment by fiboknacky** [comment]
That method can be found [here](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/v201809/mcm/CustomerService.php#L93).
