### ISSUE TITLE
I am getting Error while running GetCampaigns file 

### ISSUE THREAD

**Issue by shubham-nigam** [googleads/googleads-php-lib#608]
ApiException was thrown with message '{ "message": "Internal error encountered.", "code": 13, "status": "INTERNAL", "details": [] }'.

**Comment by fiboknacky** [comment]
Looks like your error belongs to [this library](https://github.com/googleads/google-ads-php).
Please post in the right repository. Thank you.

**Comment by shubham-nigam** [comment]
Ok thanks
