### ISSUE TITLE
How to get customIntentId

### ISSUE THREAD

**Issue by sheroqueen** [googleads/googleads-php-lib#609]
Need to create a ad group with the custom intent audiences. But it required customintentid, ho can I find the id like "user application"? 

https://developers.google.com/adwords/api/docs/reference/v201809/AdGroupCriterionService.CriterionCustomIntent

Need to get the list of avaialbel customintentid as well like the list of affinity:
https://developers.google.com/adwords/api/docs/appendix/codes-formats

<img width="941" alt="Screenshot 2019-09-02 at 6 41 16 PM" src="https://user-images.githubusercontent.com/16211086/64109178-5fb34380-cdb1-11e9-928d-b76781104b07.png">

**Comment by fiboknacky** [comment]
As this is related to the AdWords API in general, could you post in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?
Thank you.
