### ISSUE TITLE
PAGE_ONE_PROMOTED 

### ISSUE THREAD

**Issue by MelanieAssur** [googleads/googleads-php-lib#610]
Hello,
I'm trying to create a Campaign with PAGE_ONE_PROMOTED bidding.
I found the exemple code "Add a portfolio bidding strategy to a campaign" in ([AdvancedOperations](https://developers.google.com/adwords/api/docs/samples/php/advanced-operations)) and I replaced the function "createBiddingStrategy" with PageOnePromotedBiddingScheme.

**This is my PHP code:**

private static function createBiddingStrategy(
        AdWordsServices $adWordsServices,
        AdWordsSession $session
        ) {
            $biddingStrategyService = $adWordsServices->get($session, BiddingStrategyService::class);
            
            // Create a portfolio bidding strategy.
            $biddingStrategy = new SharedBiddingStrategy();
            $biddingStrategy->setName("Maximize Clicks " . uniqid());
            $biddingStrategy->setType(PAGE_ONE_PROMOTED);
            

            $biddingScheme = new PageOnePromotedBiddingScheme();
            // Optionally set additional bidding scheme parameters.
            $bidCeiling = new Money();
            $bidCeiling->setMicroAmount(2000000);
            $biddingScheme->setBidCeiling($bidCeiling);
            
            $biddingScheme->setStrategyGoal(PageOnePromotedBiddingSchemeStrategyGoal::PAGE_ONE_PROMOTED);
            $biddingScheme->setBidModifier(1);
            
            $biddingStrategy->setBiddingScheme($biddingScheme);
            
            // Create the bidding strategy operation.
            $operation = new BiddingStrategyOperation();
            $operation->setOperator(Operator::ADD);
            $operation->setOperand($biddingStrategy);
            
            $result = $biddingStrategyService->mutate([$operation]);
            $newBiddingStrategy = $result->getValue()[0];
            printf(
                "Portfolio bidding strategy with name '%s' and ID %d of type %s was created.\n",
                $newBiddingStrategy->getName(),
                $newBiddingStrategy->getId(),
                $newBiddingStrategy->getType()
                );
            
            return $newBiddingStrategy;
    }
But I'm getting the ERROR: **[RequestError.UNSUPPORTED_TYPE_IS_USED @ operations[0].operand.type; trigger:'PAGE_ONE_PROMOTED']**

Can someone help me please?

**Comment by fiboknacky** [comment]
The bidding strategy has been sunset.
Please [this blog](https://ads-developers.googleblog.com/2019/05/migrating-from-position-to-impression.html) for more information.
