### ISSUE TITLE
How do I update my keyword Text and MatchType?

### ISSUE THREAD

**Issue by yymawei** [googleads/googleads-php-lib#611]
I use googleads-php-lib and don't know how to update the Text and MatchType of the keywords. There will be no errors after the code is submitted, but the update will not take effect.
`$operations = [];
$adGroupId = '000000';
$criterionId = '0000000';
        
$adGroupCriterion = new BiddableAdGroupCriterion();
$adGroupCriterion->setAdGroupId($adGroupId);
        
$keyword = new Keyword();
$keyword->setId($criterionId);
$keyword->setType(CriterionType::KEYWORD);
$keyword->setText('Test Keyword');
$keyword->setMatchType(KeywordMatchType::PHRASE);
            
$adGroupCriterion->setCriterion($keyword);

$operation = new AdGroupCriterionOperation();
$operation->setOperand($adGroupCriterion);
$operation->setOperator(Operator::SET);
$operations[] = $operation;

$result = $adGroupCriterionService->mutate($operations);`

**Comment by fiboknacky** [comment]
This would be related to the usage of the API in general.
Could you please post in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?
Thanks.
