### ISSUE TITLE
ERROR at select awql

### ISSUE THREAD

**Issue by fabianamanu** [googleads/googleads-php-lib#615]
I'm sorry for the bad English, but I have a selector on it I select clicks and others more there run I get the following error below and I'm sorry if it's some silly mistake because I'm new with this api

http://72.55.140.9/adwordsapi?query=Select AdvertisingChannelType,CampaignId,CampaignName,CampaignStatus,Date,Amount,Cost,Ctr,Clicks,Conversions,ConversionRate,ConversionValue,CostPerAllConversion,CostPerConversion,ImpressionReach,Impressions,InteractionRate,Interactions,PercentNewVisitors,ValuePerAllConversion,ValuePerConversion,VideoQuartile100Rate,VideoQuartile25Rate,VideoQuartile50Rate,VideoQuartile75Rate,VideoViewRate,VideoViews,ViewThroughConversions,AccountDescriptiveName from CAMPAIGN_PERFORMANCE_REPORT during 20190816,20190816&token=xxxx
![api](https://user-images.githubusercontent.com/12700210/66127023-2db81b80-e5c1-11e9-8a3f-ed244b32389c.png)

**Comment by fiboknacky** [comment]
Hello @fabianamanu,

I cannot see any error messages in your screenshot there.
Could you please try using our [code example](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201809/Reporting/DownloadCriteriaReportWithSelector.php) by replacing its query with yours?

Cheers,
Knack

**Comment by fabianamanu** [comment]
hello sorry I did not make the mistake very clear that when performing this query by url she does not return any data that was requested in the selector and testing the example you mentioned he says that is missing a class the selector plus she mentions and it's in the correct folder path, I'm sorry if there was some silly mistake on my part    ..............................   error image below using DownloadCriteriaReportWithSelector.php     already tested locally and also externally
![api](https://user-images.githubusercontent.com/12700210/66207469-3c6a0580-e689-11e9-8472-67cd50710e5a.png)

**Comment by fiboknacky** [comment]
Could you first follow the [Getting Started section](https://github.com/googleads/googleads-php-lib#getting-started)?
Then, please make sure you download this library based on the methods described in [this section](https://github.com/googleads/googleads-php-lib#downloading-this-library).

Sorry if I'm wrong but It looks like you've not done that properly and just copied one file.
That's why it doesn't work.

**Comment by fabianamanu** [comment]
if I doubt if I configured adsapi_php.ini yes I did all the tasks like setting up credentials and everything else if I want to send my adsapi_php.ini (I put in the root folder as requested) installation of the composer to have the vendor folder was also done

**Comment by fiboknacky** [comment]
Our code example must be run in command line, not via a web browser.
Could you please do that first to see what errors are you faced with?

**Comment by fabianamanu** [comment]
hello I did by terminal and gave totally correct thank you, but how web has some way to be? .. sorry for the inconvenience thanks for the attention

**Comment by fiboknacky** [comment]
You'd need to change the result printing section by yourself, e.g., writing as an HTML tag instead of printf.
For that part, I'm afraid that you'd adjust to your web pages by yourself, as it can be different for each web server and web page.

**Comment by fabianamanu** [comment]
OK thank you for the attention
