### ISSUE TITLE
Access Third Party Adword Account Details With OAuth2 Credentials Programmatically

### ISSUE THREAD

**Issue by winni4eva** [googleads/googleads-php-lib#617]
I have been scanning the web and trying the examples in the php library. 
I cant seem to find a single instance where I could use a third parties access token to request their google adwords customerId so I could attempt to link my manager account to theirs.

The first api call just simulates an example where I am requesting for details for already linked accounts on my manager account.

I need to retrieve the customerIds for third party accounts using their OAuth tokens so I can link and manage them.

I understand from the forum that the only way to get the customerId of the manager account is manually. https://groups.google.com/d/msg/adwords-api/A2DL0g0vlIk/n7P9I7P1BQAJ 
Does this mean when building apps to manage other adword accounts the only way to get their account customerId is via form input?

**Comment by fiboknacky** [comment]
As there are our colleagues answering your question in the forum already and the question is not specific to this library, I'd recommend following up in the forum so you could get information in one place. Thank you.
