### ISSUE TITLE
Unable to create custom targeting of key values

### ISSUE THREAD

**Issue by mohit-cyber** [googleads/googleads-php-lib#619]
I am unable to create custom targeting on line item through automated DFP Api as i am getting success response but unable to see the key values in associated line item of order.

Response from API

Google\AdsApi\AdManager\v201902\Targeting Object
(
    [geoTargeting:protected] => 
    [inventoryTargeting:protected] => Google\AdsApi\AdManager\v201902\InventoryTargeting Object
        (
            [targetedAdUnits:protected] => 
            [excludedAdUnits:protected] => 
            [targetedPlacementIds:protected] => Array
                (
                    [0] => 29581320
                )

        )

    [dayPartTargeting:protected] => 
    [dateTimeRangeTargeting:protected] => 
    [technologyTargeting:protected] => 
    [customTargeting:protected] => Google\AdsApi\AdManager\v201902\CustomCriteriaSet Object
        (
            [logicalOperator:protected] => AND
            [children:protected] => 
            [setChildren] => Array
                (
                    [0] => Google\AdsApi\AdManager\v201902\CustomCriteria Object
                        (
                            [keyId:protected] => 11929294
                            [valueIds:protected] => Array
                                (
                                    [0] => 1
                                    [1] => 0.95
                                )

                            [operator:protected] => IS
                            [setKeyId] => 11929294
                            [setValueIds] => Array
                                (
                                    [0] => 1
                                    [1] => 0.95
                                )

                        )

                )

        )
"status":true,"msg":"success"
![keyvalue](https://user-images.githubusercontent.com/55185038/66547696-64f87080-eb5d-11e9-89a6-9f59b491a617.png)

please help out aeap

**Comment by thangduo** [comment]
If you get a success response, it is unlikely an API issue or an issue with the PHP client library.

Can you please post your question on our [developer forum](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api) instead?

Please include the query ID if you have one. If not, please provide your network id and the approximate timing for looking up your API request in our server logs.

Thanks,
Thang Duong
