### ISSUE TITLE
[Error] looks like we got no XML document

### ISSUE THREAD

**Issue by twinsato** [googleads/googleads-php-lib#621]
I'd like to ask you about Adwords' CampaignService (v201809).

I want to use CampaignService to get the fields like 'id','name','status' ,
but the following error will occur and we could not acquired the XML document.
*It occurs not only with campaign services but also with APIs that acquire delivery results such as AdgroupServices and AdgroupAdServices ,KeywordsServices.

▼The error is as bellow
```
  [Exception: SoapFault exception: [Client] looks like we got no XML document
```

When I asked the Google Ads API team,
 I was told "it appears that the issue is more related to the PHP client library and how the logging has been configured.".

It looks like the library is receiving an unexpected Entity from the API,
so the problem could be with the API itself, but I'll leave that up to you.

Please let us know if you have any information necessary for the survey.

**Comment by fiboknacky** [comment]
Could you share your request and response you got as well?
Or if you already share that, can you provide a link to the Google Ads API forum post that you created before?

And does this happen every time or occasionally?
What are your development environments (e.g., PHP version, library version, OS)?

**Comment by twinsato** [comment]
I was communicating with the Google Ads API team via email.
Therefore, there is no forum link.
* email ref:_00D1U1174p._5001UKMpcu:ref

the issue always happens with certain accounts.
I want to send SoapLog information via email,
could you tell us where should we send the SoapLog?
 
▼development environments 
```
OS: GNU/Linux
PHP: 7.2.8
FuelPHP: 1.8 
googleads/googleads-php-lib: 37.1
* We have also tried ver 43, but the same error occurred.
```

**Comment by fiboknacky** [comment]
I've followed up in that email thread.
Could you please send information in that email thread? Thanks.

**Comment by fiboknacky** [comment]
Seems this issue has been resolved privately, so I'm closing this.
Feel free to re-open if I misunderstand.
