### ISSUE TITLE
All of 'clientId', 'clientSecret', and 'refreshToken' must be set when using installed/web application flow.

### ISSUE THREAD

**Issue by matteoFeduzi** [googleads/googleads-php-lib#623]
Hi, I followed all the steps you listed and I also placed the adsapi_php.ini file in the root of my hosting.

I still get this error with other 4 error subsequently.

Fatal error: Uncaught InvalidArgumentException: All of 'clientId', 'clientSecret', and 'refreshToken' must be set when using installed/web application flow.

Obviously I have also correctly entered the various required values ​​as described by you.

**Comment by fiboknacky** [comment]
You would misunderstand the place where the adsapi_php.ini should be in your host.
Could you please confirm the location of the home directory by using the technique in [this util](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/Util/EnvironmentalVariables.php)?

**Comment by matteoFeduzi** [comment]
I think I was able to solve that problem, I hadn't eliminated the; which are used for the comment and obviously did not read me the required values.

But now I have another problem when I go to run this file:
DownloadCriteriaReportWithSelector.php


In addition, if possible please, I would like to confirm that the result I get in the previous point that I think I have solved is correct.

This is what I get when I run the GetCampaigns.php file.

[2019-10-22 08:26:09] AW_SOAP.WARNING: clientCustomerId=346-535-5495 operations=1 service=CampaignService method=get responseTime=80 requestId=0005957fbe4161230ae9ed072401ddb4 server=adwords.google.com isFault=1 faultMessage=[QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED @ ; trigger:'<null>']  
[2019-10-22 08:26:09] AW_SOAP.NOTICE: POST /api/adwords/cm/v201809/CampaignService?wsdl HTTP/1.1
Host: adwords.google.com
Connection: close
User-Agent: PHP-SOAP/7.0.33
Content-Type: text/xml; charset=utf-8
SOAPAction: ""
Content-Length: 922
Authorization: REDACTED

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://adwords.google.com/api/adwords/cm/v201809"><SOAP-ENV:Header><ns1:RequestHeader><ns1:clientCustomerId>346-535-5495</ns1:clientCustomerId><ns1:developerToken>REDACTED</ns1:developerToken><ns1:userAgent>Matteo Feduzi (AwApi-PHP, googleads-php-lib/43.0.0, PHP/7.0.33)</ns1:userAgent><ns1:validateOnly>false</ns1:validateOnly><ns1:partialFailure>false</ns1:partialFailure></ns1:RequestHeader></SOAP-ENV:Header><SOAP-ENV:Body><ns1:get><ns1:serviceSelector><ns1:fields>Id</ns1:fields><ns1:fields>Name</ns1:fields><ns1:ordering><ns1:field>Name</ns1:field><ns1:sortOrder>ASCENDING</ns1:sortOrder></ns1:ordering><ns1:paging><ns1:startIndex>0</ns1:startIndex><ns1:numberResults>500</ns1:numberResults></ns1:paging></ns1:serviceSelector></ns1:get></SOAP-ENV:Body></SOAP-ENV:Envelope>

HTTP/1.1 500 Internal Server Error
Content-Type: text/xml; charset=UTF-8
Date: Tue, 22 Oct 2019 13:26:08 GMT
Expires: Tue, 22 Oct 2019 13:26:08 GMT
Cache-Control: private, max-age=0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: ......
Alt-Svc: ......
Accept-Ranges: none
Vary: Accept-Encoding
Connection: close

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header><ResponseHeader xmlns="https://adwords.google.com/api/adwords/cm/v201809"><requestId>...................</requestId><serviceName>..............</serviceName><methodName>...........</methodName><operations>.......</operations><responseTime>80</responseTime></ResponseHeader></soap:Header><soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring>[QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED @ ; trigger:'&lt;null&gt;']</faultstring><detail><ApiExceptionFault xmlns="https://adwords.google.com/api/adwords/cm/v201809"><message>[QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED @ ; trigger:'&lt;null&gt;']</message><ApplicationException.Type>ApiException</ApplicationException.Type><errors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="QuotaCheckError"><fieldPath></fieldPath><trigger>&lt;null&gt;</trigger><errorString>QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED</errorString><ApiError.Type>QuotaCheckError</ApiError.Type><reason>DEVELOPER_TOKEN_NOT_APPROVED</reason></errors></ApiExceptionFault></detail></soap:Fault></soap:Body></soap:Envelope>
  

Fatal error: Uncaught Google\AdsApi\AdWords\v201809\cm\ApiException: [QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED @ ; trigger:'<null>'] in /home/matteofe/public_html/wp-content/themes/themes1/program/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php:43
Stack trace:
#0 /home/matteofe/public_html/wp-content/themes/themes1/program/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(43): ReflectionClass->newInstanceArgs(Array)
#1 /home/matteofe/public_html/wp-content/themes/themes1/program/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(202): Google\AdsApi\Common\Util\Reflection->createInstance('Google\\AdsApi\\A...', Array)
#2 /home/matteofe/public_html/wp-content/themes/theme1/program/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(164): Google\AdsApi\Common\AdsSoapClient->parseApiExceptionFromSoapFault(Object(SoapFault))
#3 /home/matteofe/public_html/wp-content/themes/themes1/program/googleads in /home/matteofe/public_html/wp-content/themes/themes1/program/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php on line 43

**Comment by fiboknacky** [comment]
You need to wait for your developer token to get approved per [this step](https://developers.google.com/adwords/api/docs/guides/signup#step_3_continue_your_application). Please follow that guide first before start using this library.

**Comment by matteoFeduzi** [comment]
I'm a student, isn't there an easier way to do this?

I see you need to send a map of the project ...

Plus I get this error when I use the code on the GetKeywordsIdeas.php file:
Fatal error: Uncaught InvalidArgumentException: Config file not found as specified: 'adsapi_php.ini'. Home directory could not be located so it was not searched.

**Comment by fiboknacky** [comment]
Unfortunately, you need to follow that guide in order to get things work.
Please reach out to the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) for further help with your API related issues.

If you still face with any library-specific issues that you can resolve by the help in the forum, feel free to create a new issue.
Thanks.
