### ISSUE TITLE
Need your help

### ISSUE THREAD

**Issue by farhanwattoo** [googleads/googleads-php-lib#624]
Hello Sir..

Currently i have done same as mentioned in the docs but its not working.Can you please help me to figure out the issue why this file is not working
http://prntscr.com/pq55oa
http://prntscr.com/pq54hw
http://prntscr.com/pq57dy
Thanks

**Comment by fiboknacky** [comment]
As mentioned in [the note](https://github.com/googleads/googleads-php-lib#note), our examples are meant to be run from the command line and not as a webpage.
Hope this help.

**Comment by softstore49** [comment]
How can I use this in webpage or at least make it api?

**Comment by fiboknacky** [comment]
> How can I use this in webpage or at least make it api?

An example is meant to show how to use the API using this client library.
If you wish to run your own web page, you need to adapt the code by yourself.
Unfortunately, there are various ways of running a web page, we cannot cover all cases possible.

**Comment by softstore49** [comment]
what is the best laravel library for google ads api

**Comment by fiboknacky** [comment]
Do you mean example for using laravel with this library?
Unfortunately, we don't have that yet. But you can mimic what [we've demonstrated](https://github.com/googleads/googleads-php-lib/tree/master/examples/AdWords/LaravelSampleApp) in the old library for the AdWords API.

**Comment by softstore49** [comment]
I saw this example before.
This can be called via webpage?

**Comment by fiboknacky** [comment]
As Laravel is a web application, it can be run as a web application.

**Comment by softstore49** [comment]
ok, thank you for your help.
