### ISSUE TITLE
Unified pricing rules api

### ISSUE THREAD

**Issue by lljxx1** [googleads/googleads-php-lib#625]
when will support this feature？

**Comment by thangduo** [comment]
Hi Fun,

Thanks for your question.

Are you inquiring about when the Ad Manager API would support Unified Pricing Rules (UPR)? If so, it is not a PHP question. It is a product question which could be better answered on the Product Forum (here's the link to raise a [new question](https://support.google.com/admanager/thread/new?hl=en)).

Thanks,
Thang Duong
