### ISSUE TITLE
What's is the official date of `V201809` API sunset? 

### ISSUE THREAD

**Issue by fidelisrafael** [googleads/googleads-php-lib#630]
Hi there.

We have a product which uses the `Adwords API v201809` and we would like to know when EXACTLY this API will be shutdown.

I am asking this because in [this post](https://ads-developers.googleblog.com/2019/07/google-ads-api-returning-to-beta.html) Google says that the `Ads API` was returned to the beta status, and suggest the existent integrations KEEP using the **old** `AdWords API`:

> In the meantime, we’re reverting Google Ads API back to beta status and recommend production systems to use AdWords API for the best experience.

So, we are currently using everything within the namespace `Google\AdsApi\AdWords\v201809` that can be found at:

- https://github.com/googleads/googleads-php-lib/tree/master/src/Google/AdsApi/AdWords/v201809

So, is there a official date when this `V201809` API will be **TOTALLY** shutdown? This is a very important thing for us, our product and our customers, since we will eventually migrate to the `AdsAPI` when it is safe and stable to be used.

Can you guys help us with this? We really need to know if we can keep this integration working until mid-terms(June/July) of 2020 or so.

Thanks in advance, 

The best

**Comment by fiboknacky** [comment]
Hello,

As this GitHub is specific to the PHP client library, could you please post your question on [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?

Thanks for your cooperation.

Best,
Knack

**Comment by fidelisrafael** [comment]
I reached google by email and this was their response (for others looking forward to the answer to this question :)

PS: @fiboknacky  Sorry for creating this issue here, but we thought someone involved in this project could help us with this kind of answers, since Google itself it's not clear on the documentation.

> Hi Rafael,Thank you for reaching out.
> Neither the deprecation nor the sunset date has been set yet for AdWords API. Once the Google Ads API exits "beta", we will announce the deprecation date and sunset date. It will be at least 1 year after Google Ads API reaches feature parity with AdWords API. Please keep an eye on our blog for more updates.Regards,

> Mitchell
Google Ads API Team

**Comment by fiboknacky** [comment]
No need to be sorry. :)
The Google Ads API forum is an official channel for communicating all news about the API itself.
So, when in doubt, feel free to reach out to the team there.
