### ISSUE TITLE
Adding Custom Affinity Audience

### ISSUE THREAD

**Issue by aekanshpartani** [googleads/googleads-php-lib#631]
I am trying to build a CustomAffinity audience but getting an error.

`Call to undefined method Google\AdsApi\AdWords\v201809\rm\CustomAffinity::setStreamContext()`

`$customAffinityService = $adWordsServices->get(sessionBuilder(), CustomAffinity::class);

        $audience = new CustomAffinity();
        $audience->setStatus(CustomAffinityStatus::ENABLED);
        $audience->setName("Custom Created Intent");
        $audience->setType(CustomAffinityType::CUSTOM_AFFINITY);

        $customAffinityOperation  = new CustomAffinityOperation();
        $customAffinityOperation->setOperand($audience);
        $customAffinityOperation->setOperator(Operator::ADD);

        $operations = [];
        $operations[] = $customAffinityOperation;
        $result = $customAffinityService->mutate($operations);`

**Comment by fiboknacky** [comment]
Can you share the whole code and also include the line where the error is reported please?
