### ISSUE TITLE
Cannot specify time along the date when using custom DateRange for reporting

### ISSUE THREAD

**Issue by ignacionelson** [googleads/googleads-php-lib#633]
Would it be possible to change the format the dateRange accepts from date to datetime? Filtering just by date seriously limits the analysis that can be done on the returned data.
Thank you

**Comment by fiboknacky** [comment]
What product are you using? Ad Manager API or AdWords API?

**Comment by ignacionelson** [comment]
AdWords API

**Comment by fiboknacky** [comment]
I'm afraid not. For further questions regarding the AdWords API in general, feel free to ask in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).
Thank you.
