### ISSUE TITLE
Service account authentication without JSON file

### ISSUE THREAD

**Issue by mackoftrack** [googleads/googleads-php-lib#634]
Is it possible to authenticate without using a JSON file?
We store/retrieve all of our secrets as environment variables (API keys, passwords, etc)
It would be much more convenient if we could pass in the fields found in the service account JSON file (specifically the fields that ought to be kept secret: `private_key_id` and `private_key`).

**Comment by fiboknacky** [comment]
It's not supported by this library right now, although the [ServiceAccountCredentials](https://github.com/googleapis/google-auth-library-php/blob/master/src/Credentials/ServiceAccountCredentials.php#L58) that this library relies on actually supports that.

The only workaround for now is to use [build()](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/OAuth2TokenBuilder.php#L71) and pass the Configuration object instead.
You can pass an associative array containing your private key to `jsonKeyFilePath` (although the name seems misleading).

**Comment by mackoftrack** [comment]
Thanks. Could you give an example?

**Comment by mackoftrack** [comment]
Also, is it possible to authenticate via Application Default Credentials? We are running in GKE
If we authorize the compute engine service account in DFP/Ad Manager, will it authenticate without specifying a `jsonKeyFilePath`?

**Comment by thangduo** [comment]
Hi,

When you authenticate the service account in Ad Manager, you let Ad Manager servers know of the service account. Later, when an application presents a credential of the same service account, the application is accepted by the API.

Here's how to build an `AdManagerSession` from an associative array:

```(php)
        $configuration = new Configuration([
            'networkCode' => '12345678',
            'applicationName' => 'your_application_name',
            'OAUTH2' => [
                'client_id' => '123aBC456-xYz.apps.googleusercontent.com',
                'client_secret' => '1abC-456Xyz'
            ]
        ]);
        
        $sessionBuilder = new AdManagerSessionBuilder();
        $session = $sessionBuilder->from($configuration)->build();
        
        $serviceFactory = new ServiceFactory();
        $lineItemService = $serviceFactory->createLineItemService($session);
```

Thanks,
Thang Duong

**Comment by thangduo** [comment]
You can also see our [src/Google/AdsApi/Common/Testing/API-Project-abc123xyz.json](https://github.com/googleads/googleads-php-lib/blob/656650c5f21284eac9b5acaa497c7e2b08f84710/src/Google/AdsApi/Common/Testing/API-Project-abc123xyz.json) test file for the associative array example.
