### ISSUE TITLE
Symfony5 support

### ISSUE THREAD

**Issue by weberdominik** [googleads/googleads-php-lib#637]
We are currently unable to upgrade our project because googleadsphplib does not yet support Symfony5. Is an update planned or is there another way to upgrade?

**Comment by fiboknacky** [comment]
There is a [pull request opened](https://github.com/googleads/googleads-php-lib/pull/627), but the unit test fails for Symfony 5.
The pull request author has not got back to me yet, and I don't have time to investigate further too.
So, currently I have no ETA but will look into this asap.

**Comment by mrpavlikov** [comment]
@weberdominik 

```composer require googleads/googleads-php-lib "dev-master"```

works fine atm

**Comment by fiboknacky** [comment]
#638 has been merged, so this is fixed now.
