### ISSUE TITLE
Update symfony/serializer dependency

### ISSUE THREAD

**Issue by JanMikes** [googleads/googleads-php-lib#639]
Hi there!

```
symfony/serializer (v4.4.3) latest is v5.0.3

❯ composer why symfony/serializer           
googleads/googleads-php-lib  44.0.0  requires  symfony/serializer (^2.8.0 || ^3.0.3 || ^4.0.0)  
```

There is already version 5 out there.

There is high chance this upgrade will be without bc breaks.

**Comment by fiboknacky** [comment]
The master branch already supports this. Please use `dev-master` for now in case you need Symfony 5.
We'll release a new version soon.

**Comment by JanMikes** [comment]
Awesome, i didn't notice that.

Thank you!
