### ISSUE TITLE
adsapi_php.ini identification

### ISSUE THREAD

**Issue by matteoFeduzi** [googleads/googleads-php-lib#642]
Hi, I get this error:

Uncaught InvalidArgumentException: Config file not found as specified: 'adsapi_php.ini'. Home directory could not be located so it was not searched. in /home/matteofe/public_html/wp-content/themes...

How can I solve it?

I have already moved the adsapi_php.ini file to the same height as the "vendor" directory.

Isn't it okay here? Where should I move it?

Thank you.

**Comment by fiboknacky** [comment]
Hi,

> I have already moved the adsapi_php.ini file to the same height as the "vendor" directory.

Moving this to the same directory as vendor doesn't help.
As described in [this section](https://github.com/googleads/googleads-php-lib#getting-started), the library searches for the file in your home directory, which can be different between systems.
As I don't have full visibility of your computer and projects, it's hard to pinpoint where it is.
You would need to consult relevant documents of your OS.
The logic of finding home directory can be found [here](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/Util/EnvironmentalVariables.php).

Alternatively, you can use [this method](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php#L104) to specify the path to your `adsapi_php.ini` directly.

Best,
Knack

**Comment by matteoFeduzi** [comment]
I'm using this hosting:
https://it.siteground.com/

> The logic of finding home directory can be found here.


I went to the file you were telling me here and I saw that it calls the following function:
UnexpectedValueException

Does that mean he can't find any home?

> Alternatively, you can use this method to specify the path to your adsapi_php.ini directly.

As for this alternative method, do I have to replace $ path = null with $ path = / path / ... depending on the location of the adsapi_php.ini file?

Best regards,
Matteo.

**Comment by fiboknacky** [comment]
> As for this alternative method, do I have to replace $ path = null with $ path = /path/... depending on the location of the adsapi_php.ini file?

Correct.

**Comment by matteoFeduzi** [comment]
I entered the whole path, but I always get the same problem.

`public function fromFile($path = '/home/matteofe/public_html/wp-content/themes/MatteoFeduziV1/googleAPI/vendor/')
    {
        if ($path === null) {
            $path = self::DEFAULT_CONFIGURATION_FILENAME;
        }

        return $this->from($this->configurationLoader->fromFile($path));
    }`

**Comment by fiboknacky** [comment]
You shouldn't modify the library code directly.
What I meant is to use that method in the process of building `AdWordsSession` objects.

For example:

```php
        // Generate a refreshable OAuth2 credential for authentication.
        $oAuth2Credential = (new OAuth2TokenBuilder())->fromFile("YOUR_PATH")->build();

        // Construct an API session configured from a properties file and the
        // OAuth2 credentials above.
        $session = (new AdWordsSessionBuilder())->fromFile("YOUR_PATH")->withOAuth2Credential($oAuth2Credential)->build();
```

**Comment by fiboknacky** [comment]
And the method is `fromFile`, so you need to specify a file, not a directory.

**Comment by matteoFeduzi** [comment]
In which page of the site https://console.developers.google.com/ can I find these values ​​to be inserted in the file adsapi_php.ini?

1) clientId
2) clientSecret
3) refreshToken

**Comment by matteoFeduzi** [comment]
I added mine

1) clientId
2) clientSecret

But where do I find the 'refreshToken'?

**Comment by fiboknacky** [comment]
I'd recommend reading through [this guide](https://developers.google.com/adwords/api/docs/guides/first-api-call) first. It explains everything you need to know about getting started using the AdWords API in general.

If you still have difficulties understanding how to use, could you please reach out to the experts in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) first?
After that, if you still have issues with using this library, feel free to get back to this issue page.

**Comment by matteoFeduzi** [comment]
Thanks a lot, I followed your directions and I managed to get this far:

https://monosnap.com/file/BY1PAIcgiXoVqRhFoMOFhDG6wVzFSI

Then when I reach the site in the previous obscured image I get this error 400:

https://monosnap.com/file/W22RdAQx7oZ2F0ifwS6aaDDrUNCaRD

Best regards,
Matteo.

**Comment by fiboknacky** [comment]
Please contact the people on the forum. They'll help you investigate this. :-)
It looks like you might create the OAuth2 project with a bit wrong setting.

**Comment by fiboknacky** [comment]
Suggestion to ask in the forum has been provided, so I'm closing this.
