### ISSUE TITLE
I don't understand the GetCampaigns example

### ISSUE THREAD

**Issue by androidealp** [googleads/googleads-php-lib#643]
I was able to integrate the api locally, and everything worked out, I created some campaigns that are listed in: https://ads.google.com/aw/campaigns in my test account, however when making the query:
```php

php 
        $selector = new Selector();
        $selector->setFields(['Id', 'Name']);
       // $selector->setPredicates( new Predicate('campaign','EQUALS',Operator::SET));
        $selector->setOrdering([new OrderBy('Name', SortOrder::ASCENDING)]);
        $selector->setPaging(new Paging(0, self::PAGE_LIMIT));

```

or 

```php  

$query = (new ServiceQueryBuilder())
            ->select(['Id', 'Name', 'Status'])
            ->orderByAsc('Name')
            ->limit(0, self::PAGE_LIMIT)
            ->build();
```
it returns me "Number of results found: 0 " 

what am I doing wrong? do I need to set up anything else in my test account?

**Comment by androidealp** [comment]
so sorry! I found out now. 
my clientCustomerId is parent of the campaigns client and not contain Campaigns, i change clientCustomerId to id children and worked.

**Comment by fiboknacky** [comment]
Thanks for getting back to us.
