### ISSUE TITLE
AdWords Example LaravelSampleApp RequestError.UNSUPPORTED_VERSION

### ISSUE THREAD

**Issue by internationalhouseofdonald** [googleads/googleads-php-lib#644]
So, I'm kind of new to this and I'm really more of a JavaScript developer than a PHP developer, but I can't figure out how to get the data that I need using the `node-adwords` NPM wrapper.

I'm trying to get an app working that gathers reports about an MCC account's customer's ads (specifically, how much the customer has spent).

When I build the AdWords LaravelSampleApp, I get a bunch of errors (some of which I've fixed), but I have no clue how to fix this one. 

Please help

![image](https://user-images.githubusercontent.com/20768148/74985320-cfb79380-53fc-11ea-9d38-9a875d5e4ffb.png)

**Comment by GLStephen** [comment]
The classes you put in your includes or that you reference in your code are contained in folders/namespaces that include a version number. It looks like you are using a very old one. If it's new dev use the one with the highest number.

Google\AdsApi\AdWords\vXXXXXX\......

**Comment by internationalhouseofdonald** [comment]
> The classes you put in your includes or that you reference in your code are contained in folders/namespaces that include a version number. It looks like you are using a very old one. If it's new dev use the one with the highest number.
> 
> Google\AdsApi\AdWords\vXXXXXX......

@GLStephen Thank you for your timely response.

So, should I be using the Ad Manager API since v201809 is the only version that ships with AdWords here?

![image](https://user-images.githubusercontent.com/20768148/74985644-80259780-53fd-11ea-9298-8c943d84a929.png)
![image](https://user-images.githubusercontent.com/20768148/74985679-96cbee80-53fd-11ea-974d-291eb24663de.png)

**Comment by internationalhouseofdonald** [comment]
Also, @GLStephen 

On a side note... Am I able to use the PHP client library in order to get an MCC account number using the OAuth flow? 

The documentation doesn't have a guide for the Web App flow for PHP. 
https://developers.google.com/adwords/api/docs/guides/authentication#configure_and_use_a_client_library

![image](https://user-images.githubusercontent.com/20768148/74985901-0b9f2880-53fe-11ea-8786-d14be5211695.png)


https://groups.google.com/forum/#!topic/adwords-api/jWexvYg-Dg0

**Comment by internationalhouseofdonald** [comment]
I'm using the examples provided...

**Comment by GLStephen** [comment]
What version of the library are you using?

**Comment by internationalhouseofdonald** [comment]
@GLStephen 

The example Laravel app only has an outdated version installed (from 2018). 

Should I just run `composer require googleads/googleads-php-lib` inside of the example app?

More Side Notes: I've never used Composer before... I've always used NPM to install packages so I have no clue what I'm doing. I just did a `composer require googleads/googleads-php-lib` and now I'm just trying to follow the documentation in order to get the app working. I started using this library because the library that I _was_ using was throwing an error when I went to use `ManagedCustomerService` and I can't figure out how to pull in data about an MCC account's customers.

**Comment by GLStephen** [comment]
You've got some fundamental questions that are hard to resolve here, but get the most recent version of the library going. A *lot* has changed over the last year.

**Comment by fiboknacky** [comment]
@internationalhouseofdonald Sorry for your inconvenience.
I'm working to update the examples soon.

**Comment by fiboknacky** [comment]
@internationalhouseofdonald  
Update: I'm working on the update of the sample app. It should be available around next week.
For now, if you want to try to fix it quickly, try searching for `v201802` and `v201806` and replace them with `v201809`.

Then, remove `composer.lock` and update `composer.json` to use at least version 38.0.0 of this library:

```
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "googleads/googleads-php-lib": "^38.0.0"
    },
```

Finally, try running `composer update`. It should update all dependencies to fetch newer version of source code of this library.
This will make you able to run the sample app using `v201809` of the AdWords API.

**Comment by fiboknacky** [comment]
The latest version of Laravel sample app has been released, so I'm closing this.
