### ISSUE TITLE
Upgrading from version 33.1 to 46

### ISSUE THREAD

**Issue by joanna-7** [googleads/googleads-php-lib#645]
googleads/googleads-php-lib 46.0.0 requires symfony/serializer ^4.4.0 || ^5.0.0 
![2020-02-24 at 16-45-25](https://user-images.githubusercontent.com/22748087/75161878-33a3ca00-5725-11ea-92fb-9a489281bf77.png)

**Comment by fiboknacky** [comment]
Yes, our library requires that version of Symfony Serializer.
Do you have conflicting requirements in your `composer.json`?

**Comment by joanna-7** [comment]
> Yes, our library requires that version of Symfony Serializer.
> Do you have conflicting requirements in your `composer.json`?

Yeah, I couldn't update the version of Symfony Serializer.
But I did this and it worked:
composer require --no-update googleads/googleads-php-lib "46.0"
composer update --ignore-platform-reqs

**Comment by fiboknacky** [comment]
Note that the serializer version you're using allows PHP 5 and 7.0, which are all deprecated.
We highly recommend upgrading to at least serializer v4.0 for security benefits.

As you have found workarounds for your issue, I'm closing this issue.

**Comment by Lehren** [comment]
If your library requires symfony/serializer, how can I install it alongside symfony/symfony, which replaces symfony/serializer and thus cannot be installed alongside it?
