### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by ergcode** [googleads/googleads-php-lib#649]
I believe that using "composer" in php is the wrong solution.
Php is created to be born and die. Carrying tens or hundreds of dependencies is very expensive.

**Comment by thangduo** [comment]
Thanks for your feedback.

Is there a better way to manage dependencies in PHP?

Thanks,
Thang Duong

**Comment by ergcode** [comment]
> Thanks for your feedback.
> 
> Is there a better way to manage dependencies in PHP?
> 
> Thanks,
> Thang Duong

I can not recommend anything. But for php that starts and dies (not a long process) - the best solution would be a monolith or a clear file structure.
Composer turns plug-in projects into a crazy mess. And in is very hard to figure out.

Not only do developers not bother writing comments to the code and api, they also add Composer (a miserable semblance of npm) to completely confuse the code.

**Comment by thangduo** [comment]
I get what you mean. However, this client library uses many dependencies. Without a dependency management system, we would have to re-invent a lot of work.

Please re-open this bug when there is a better replacement for Composer.
