### ISSUE TITLE
is StatsEstimate::impressionsPerDay in a micro format?

### ISSUE THREAD

**Issue by callum-veloxcommerce** [googleads/googleads-php-lib#650]
The data i'm getting back for the query 'dog christmas gifts' is giving me some unusual looking values for Impressions per day which is specified in the docs as a float value but the number looks more like a micro.

The StatsEstimate object is returning the following data:

In google ads planner UI i am seeing 1K - 10K impressions for this keyword in the API response i'm getting this:

```
{"keywords":"dog christmas gifts",
"estimates":{"cpc":{"min":0.092943,"max":0.113597},
"avgPosition":{"min":3.6038253997120697,"max":2.948584275926584},
"ctr":{"min":0.006550866191894045,"max":0.00800661462017871},
"clicks":{"min":370.82596,"max":453.23172},
"impressions":{"min":955821380,"max":1168226180}}}
```

However when dividing the impressions by 1000000 i get something that looks more inline with the estimate in ads planner:
```
"impressions":{"min":955.82138,"max":1168.22618}
```

Which is around 1000

Could you clear this up please?

**Comment by fiboknacky** [comment]
As this is not related to the client library, could you please post in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?
Thank you.
