### ISSUE TITLE
Delete Key-Value for LineItem

### ISSUE THREAD

**Issue by richaudience** [googleads/googleads-php-lib#651]
Hello guys,

I need to remove a Key/Value of the Line Item but I can't find out the way that allows me to do it. Is it possible to do it through API? 

I have noticed that the status of the KW can be removed or changed, but I don't want to proceed like this. 

Thanks in advance and looking forward to hearing from you,

Cheers

**Comment by thangduo** [comment]
Hi,

To remove a key/value pair of a line item, you need to:
* Call `$lineItemService->getLineItemsByStatement()` function to get the line item with targeting info.
* Remove the key/value pair from the line item object.
* Call `$lineItemService->updatelineItems()` function to update the line item with modified targeting info.
(See googleads-php-lib/examples/AdManager/v202002/LineItemService/[UpdateLineItems.php](https://github.com/googleads/googleads-php-lib/blob/eeeb12d346d31e0f015a31baa823bc9366af555b/examples/AdManager/v202002/LineItemService/UpdateLineItems.php) for example service calls)

Thanks,
Thang Duong
