### ISSUE TITLE
Implement invoiceservice

### ISSUE THREAD

**Issue by androidealp** [googleads/googleads-php-lib#653]
I need to recover the billing, I realized that there is a call in the api (https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.services#invoiceservice), but I didn't find it in lib php, will it be implemented? or is there any way to achieve this result using the current php library

**Comment by fiboknacky** [comment]
You probably use a wrong API. The link you mentioned belong to the [Google Ads API](https://developers.google.com/google-ads/api/docs/start), but this library is for the [AdWords API](https://developers.google.com/adwords/api/docs/guides/start).
Could you contact our people in the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) please?

**Comment by androidealp** [comment]
I was equivalent in the link, but is it possible by the googleads-php-lib lib for "invoiceservice" implementation? And for campaigns is it possible to have cost information?

**Comment by androidealp** [comment]
Friend, no more need, I was able to extract the average cpc, which is at   [CpcBid](https://developers.google.com/adwords/api/docs/reference/v201809/CampaignService.CpcBid)
