### ISSUE TITLE
Fatal Error:

### ISSUE THREAD

**Issue by joaosoaresaalm** [googleads/googleads-php-lib#660]
**Fatal error: Uncaught TypeError: Argument 1 passed to Google\AdsApi\Common\Configuration::__construct() must be of the type array, bool given, called in C:\Users\joaoi\googleads-php-lib\src\Google\AdsApi\Common\ConfigurationLoader.php on line 87 and defined in C:\Users\joaoi\googleads-php-lib\src\Google\AdsApi\Common\Configuration.php:34**

Estou tentando executar um exemplo chamado GetCampaings.php e não estou obtendo êxito, esse erro foi gerado, após transferir o arquivo adsapi_php.php para o "home directory", estou utilizando a v201809. 

**Alguém tem uma solução viável?**

**Comment by fiboknacky** [comment]
Hi,

I can answer only in English.
It seems you get this error when trying to run GetCampaigns.php, right?
What PHP version are you using?

**Comment by joaosoaresaalm** [comment]
Hello, so ... the version I'm using is **PHP 7.4.5 (cli) (built: Apr 14 2020 16:17:19) (NTS Visual C ++ 2017 x64).**

**Comment by joaosoaresaalm** [comment]
I managed to solve the problem, it was related to the configuration of the adsapi_php file, a parameter was missing. Anyway, I appreciate the attention!!!

**Comment by fiboknacky** [comment]
Thanks for getting back to us.
