### ISSUE TITLE
Fatel Error

### ISSUE THREAD

**Issue by chiragvels** [googleads/googleads-php-lib#661]
Fatal error: Declaration of Google\AdsApi\AdWords\AdWordsNormalizer::normalize($object, $format = NULL, array $context = Array) must be compatible with Symfony\Component\Serializer\Normalizer\NormalizerInterface::normalize($object, ?string $format = NULL, array $context = Array) in /vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/AdWordsNormalizer.php on line 72

While running campaign performance report.

Thanks

**Comment by chiragvels** [comment]
Hi, 
Should I need specific Symfony version for this?

**Comment by fiboknacky** [comment]
Can you update the library based on what's specified in [composer.json](https://github.com/googleads/googleads-php-lib/blob/master/composer.json)?
After that, if the issue still persists, could you tell the version of this library you've installed, as well as the Symfony serializer's version?

**Comment by chiragvels** [comment]
Hi @fiboknacky ,

Thanks for the prompt reply.

I was using php 7.1.33 with Symfony serializer verison 5.0.7.

Now I have downgraded to 4.4.8 and It is working.

May be Symfony serializer version 5.0.7 is not compatible with php 7.1.33.

Thanks,

**Comment by fiboknacky** [comment]
Thanks for getting back to me.
Note that PHP 7.1 is sunset officially and thus it's not supported by our library.

**Comment by chiragvels** [comment]
Yes, Thanks for the update.
For google-ads-php lib which is in beta I was using php7.3, I will ask my system team to update this Old server.

Thanks,
