### ISSUE TITLE
cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.googleapis.com:443

### ISSUE THREAD

**Issue by Hello-wrd** [googleads/googleads-php-lib#664]

**Comment by fiboknacky** [comment]
Hi,

Your image contains confidential information like your developer token, so I needed to delete it for your safety.
Could you please describe what is your problem in text instead?

Best,
Knack

**Comment by Hello-wrd** [comment]
When a token is requested, it returns an error：
 cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.googleapis.com:443 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by fiboknacky** [comment]
Could you tell more how you hit this error? Did you try to run our code examples? If not, can you share your code that sends a request to the API?
And do you use a proxy?

> When a token is requested, it returns an error：

Do you mean when an access token is requested by using the refresh token?
