### ISSUE TITLE
authorize with access token

### ISSUE THREAD

**Issue by mvalitov** [googleads/googleads-php-lib#666]
I have Oauth2 authorization, after which I have access_token and refresh_token. in the documentation I see an example
```
$session = (new AdWordsSessionBuilder())
    ->fromFile()
    ->withOAuth2Credential($oauth2)
    ->build();
```
but here the Oauth2 object is used. Can I create an AdwordsSessionBuilder using only my tokens (access and refresh)?

**Comment by fiboknacky** [comment]
If you have refresh token, you don't need an access token.
Please add your refresh token in [this line](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/adsapi_php.ini#L33).

**Comment by mvalitov** [comment]
thanks! Do I have to create this file every time, or is it possible to transfer this data without creating a .ini file?
this script will be executed for different users, and refresh_token will also change

**Comment by fiboknacky** [comment]
You don't need to rely on the `ini` file, but you would still need to depend on OAuth2TokenBuilder to create a new one for each user.
You can use [this method](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/OAuth2TokenBuilder.php#L160) to set refresh token.
