### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by adsdenma** [googleads/googleads-php-lib#669]
My application is PHP 5.6 based and i want to integrate Google Ads API to manage campaigns, how can i do this since i cannot upgrade my application php 7.2+. Please suggest me the possibilities.

**Comment by fiboknacky** [comment]
Unfortunately, this library only supports only PHP 7.2 or greater.
[PHP 5.6](https://www.php.net/supported-versions.php) has been officially sunset for one year and a half ago. We highly recommend considering upgrading to 7.2.
