### ISSUE TITLE
getting very unexpected error while getting customers:listAccessibleCustomers

### ISSUE THREAD

**Issue by ranjeetranjan** [googleads/googleads-php-lib#671]
I Ma getting very unexpected error while getting customers:listAccessibleCustomers

```
curl -X GET \ https://googleads.googleapis.com/v1/customers:listAccessibleCustomers \ 
 -H 'Authorization: Bearer {your-access-token-here}' \
 -H 'developer-token: {your-developer-token-here}'


{

  "error": {

    "code": 401,

    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",

    "status": "UNAUTHENTICATED"

  }

}
```

Although I am using the below request for proper access token and refresh token.

<<Option -1>>

`https://accounts.google.com/o/oauth2/v2/auth?response_type=code&access_type=offline&client_id=XXXXX&redirect_uri=https://YYY.com/google/callback&state=XXXX&scope=https://www.googleapis.com/auth/adwords&prompt=consent&o2v=2&as=XXXX&flowName=GeneralOAuthFlow`

<<Option -2>>

`https://accounts.google.com/signin/oauth/oauthchooseaccount?response_type=code&access_type=offline&client_id=XXXXX&redirect_uri=https://YYY.com/google/callback&state=XXXX&scope=https://www.googleapis.com/auth/adwords&prompt=consent&o2v=2&as=XXXX&flowName=GeneralOAuthFlow
`

Kindly help to solve.

**Comment by thangduo** [comment]
Hi Ranjeet,

The domain googleads.googleapis.com belongs to a different GitHub repository of Google Ads gRPC client:
https://github.com/googleads/google-ads-php/search?q=googleads.googleapis.com

I am going to close this issue as not reproducible in this GitHub repo. Please report your issue at https://github.com/googleads/google-ads-php/issues

Thanks,
Thang
