### ISSUE TITLE
Laravel example only for adwords not for ad manager. 

### ISSUE THREAD

**Issue by SaraKovaci** [googleads/googleads-php-lib#672]

**Comment by thangduo** [comment]
Hi SaraKovaci,

Thanks for the suggestion. Could you please describe what would be an ideal Laravel example for your usecase?

Thanks,
Thang

**Comment by thangduo** [comment]
Hi SaraKovaci,

I haven't got your response for a while. I will close this issue as Won'f Fix because it is not an urgent need.

Thanks,
Thang

**Comment by binumathew** [comment]
@thangduo  : A Laravel - Nuxt Example with Authentication and Campaign Listing would be great
