### ISSUE TITLE
repeating question bug

### ISSUE THREAD

**Issue by yaman99** [googleads/googleads-php-lib#674]
hi i am working to get refresh token and i am going step by step from [this tutorial ](https://github.com/googleads/googleads-php-lib/wiki/API-access-using-own-credentials-(installed-application-flow))
but the problem when i write $ php GetrefreshToken.php to run the code he's skipping the first and second question that ask me about Client ID and Client secret  and repeat the third question for infinite 

what is the problem is that cache problem ??
example
`Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
... forever

**Comment by yaman99** [comment]
![image](https://user-images.githubusercontent.com/33988107/88547550-97a92200-d026-11ea-8e4c-cca17c4e4be6.png)

**Comment by yaman99** [comment]
i tried to clear composer cache  and reinstall it but same problem

**Comment by yaman99** [comment]
@fiboknacky any suggestions about why is that happening ? 
is that refreshToken Code or my pc has saved the credential ?

**Comment by yaman99** [comment]
> hi i am working to get refresh token and i am going step by step from [this tutorial ](https://github.com/googleads/googleads-php-lib/wiki/API-access-using-own-credentials-(installed-application-flow))
> but the problem when i write $ php GetrefreshToken.php to run the code he's skipping the first and second question that ask me about Client ID and Client secret and repeat the third question for infinite
> 
> what is the problem is that cache problem ??
> example
> `Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
> Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
> Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
> Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
> Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
> Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
> Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
> Please enter a valid number for the API you're using: [0] AdWords API [1] Ad Manager API [2] Both
> ... forever

**Comment by yaman99** [comment]
i closed it by fault

**Comment by yaman99** [comment]
i delete all cache on my pc and composer cache and all credential but same problem
its work before and i entered Client ID and Client secret but after that is skipping and come this problem

**Comment by thangduo** [comment]
Hi,

Can you please tell us more about your local development setup? Are you using Composer to acquire `googleads/googleads-php-lib`? What is your directory structure? Where do you save the downloaded file `GetRefreshToken.php`?

Thanks,
Thang Duong

**Comment by yaman99** [comment]
> Hi,
> 
> Can you please tell us more about your local development setup? Are you using Composer to acquire `googleads/googleads-php-lib`? What is your directory structure? Where do you save the downloaded file `GetRefreshToken.php`?
> 
> Thanks,
> Thang Duong

thanks mr.Duong
i am working on windows 10 and i downloaded the googleleads-lib via [ git clone method in this tutorial](https://github.com/googleads/googleads-php-lib/blob/master/README.md#using-git-clone)  project in my D driver then i did composer install and the folder vendor is downloaded then i went to examples/Auth/GetrefreshToken then i wrote $ php GetrefreshToken.php

**Comment by thangduo** [comment]
Are you using the Windows Subsystem for Linux? Or, are you using Cygwin package for Windows?
My guess is that your setup has something special that would interfere with PHP I/O streams (https://www.php.net/manual/en/features.commandline.io-streams.php).

Thanks,
Thang Duong

**Comment by yaman99** [comment]
> Are you using the Windows Subsystem for Linux? Or, are you using Cygwin package for Windows?
> My guess is that your setup has something special that would interfere with PHP I/O streams (https://www.php.net/manual/en/features.commandline.io-streams.php).
> 
> Thanks,
> Thang Duong

no no i am using original windows 10 no subsystems and its work before  itried refresh token php code for 10th time but last time this problem is happening

all in all  i am going to check the setup that you talked about

**Comment by yaman99** [comment]
i dont know why when i run $ php GetrefreshToken he ignore the red area code and start from the blue area and repeat it for infinite.. i did everything but still not working 

![image](https://user-images.githubusercontent.com/33988107/88595145-250e6580-d06b-11ea-9634-13b1bf08d472.png)

**Comment by thangduo** [comment]
Can you try again on a different machine?

What do you use for Linux command line? (As I saw that you have a $ sign in your comment and MINGW in your screenshot.)

**Comment by yaman99** [comment]
i think its work in another machine..
i tried to run it **git bash** and **windows CMD** and **windows power shell** and i get same result 
its something when i am run the code is getting the credential from it and jump to the third Question and repeat it for infinite is that php or the command line save any data or credential  ??

**Comment by thangduo** [comment]
Hi Yaman99,

Unfortunately, I couldn't reproduce this issue using [Powershell](https://github.com/PowerShell/PowerShell).

<img width="1279" alt="ss2" src="https://user-images.githubusercontent.com/4349155/91583763-a7ff3600-e91f-11ea-9c6d-4dc3b7c2aaa5.PNG">
<img width="640" alt="ss1" src="https://user-images.githubusercontent.com/4349155/91583799-ae8dad80-e91f-11ea-8249-a5cfe1f6c6f9.PNG">

I think you might have a problem that is specific and only reproducible on one machine. If you could find a way to reproduce it across multiple machines, please feel free to reopen this issue or start a new one.

Thanks,
Thang
