### ISSUE TITLE
getallnetworks then receiving network code is required

### ISSUE THREAD

**Issue by rdesanctis** [googleads/googleads-php-lib#675]
on example AdManager/v202005/NetworkService/GetAllNetworks.php  , im receiving: "network code is required" , but according to admanager docs on https://developers.google.com/ad-manager/api/troubleshooting#AuthenticationError.NETWORK_CODE_REQUIRED said : " ...Network codes are required for all requests except NetworkService.getAllNetworks() ... " , how to get it? may be a bug on library? any idea?

**Comment by thangduo** [comment]
Hi Roberto,

Thanks for reporting this issue.

We are working on a fix for this. In the mean time, you can change the [AdManagerSessionBuilder](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdManager/AdManagerSessionBuilder.php#L325) to remove the exception.

Thanks,
Thang

**Comment by thangduo** [comment]
This issue will be resolved in next week release.

**Comment by thangduo** [comment]
Fixed in commit 94160b7cf128a92ce8a1cedf549714f47fa273ea
