### ISSUE TITLE
Fatal error: Uncaught InvalidArgumentException: A developer token must be set. in C:\xampp\htdocs\google-ads-php\src\Google\Ads\GoogleAds\Lib\V6\GoogleAdsClientBuilder.php

### ISSUE THREAD

**Issue by GitHubgopinath** [googleads/googleads-php-lib#685]
Hello ,
Iam working google ads api, while iam execute the CreateCustomer.php ,iam getting following error,Please support me

Fatal error: Uncaught InvalidArgumentException: A developer token must be set. in C:\xampp\htdocs\google-ads-php\src\Google\Ads\GoogleAds\Lib\V6\GoogleAdsClientBuilder.php:255 Stack trace: #0 C:\xampp\htdocs\google-ads-php\src\Google\Ads\GoogleAds\Lib\V6\GoogleAdsClientBuilder.php(236): Google\Ads\GoogleAds\Lib\V6\GoogleAdsClientBuilder->validate() #1 C:\xampp\htdocs\google-ads-php\examples\AccountManagement\CreateCustomer.php(60): Google\Ads\GoogleAds\Lib\V6\GoogleAdsClientBuilder->build() #2 C:\xampp\htdocs\google-ads-php\examples\AccountManagement\CreateCustomer.php(128): Google\Ads\GoogleAds\Examples\AccountManagement\CreateCustomer::main() #3 {main} thrown in C:\xampp\htdocs\google-ads-php\src\Google\Ads\GoogleAds\Lib\V6\GoogleAdsClientBuilder.php on line 255

**Comment by GitHubgopinath** [comment]
I solved this problem,

**Comment by GitHubgopinath** [comment]
I solved this problem,

**Comment by rashflash** [comment]
hi @GitHubgopinath , how you solved this?

**Comment by faizdg** [comment]
> I solved this problem,

where is your solution
