### ISSUE TITLE
How to integrate the Google ads in Codeigniter Framework ?

### ISSUE THREAD

**Issue by GitHubgopinath** [googleads/googleads-php-lib#687]
Hello Google ads

I want to integrate google ads in Codeigniter. How can I do that? Providing steps would be a really big help to me.

regrads
Gopi Nath

**Comment by fiboknacky** [comment]
As you mentioned Google Ads, note that this library is for [the AdWords API](https://developers.google.com/adwords/api/docs/guides/start).
If you wish to use [the Google Ads API](https://developers.google.com/google-ads/api/docs/start), please visit [this repo](https://github.com/googleads/google-ads-php) instead.

> I want to integrate google ads in Codeigniter. How can I do that? Providing steps would be a really big help to me.

Unfortunately, we don't have written steps for that, but we're happy to answer any technical issues that you encounter.
Having said that, you could refer to [the Laravel sample app](https://github.com/googleads/googleads-php-lib/tree/master/examples/AdWords/LaravelSampleApp) to get some ideas of how to integrate with the MVP framework.
We also have [a similar sample app](https://github.com/googleads/google-ads-php/tree/master/examples/LaravelSampleApp) in [the Google Ads API library](https://github.com/googleads/google-ads-php) too.

If you still want to use the AdWords API library, I'd recommend reading through [the README file](https://github.com/googleads/googleads-php-lib#google-ads-api-php-client-library) to ensure you understand how this library works.
For general info about the AdWords API, please refer to [this page](https://developers.google.com/adwords/api/docs/guides/start).
