### ISSUE TITLE
How to add an Audiences List to a campaign and adjust the Bid via API?

### ISSUE THREAD

**Issue by iceleo-com** [googleads/googleads-php-lib#690]
I tried to look for a sample code to add an Audiences List to a campaign and adjust the Bid, but I didn't find any related articles.

Please look at the below screenshot, that's what I want to do.

![image](https://user-images.githubusercontent.com/15703671/102477859-7efddf00-408f-11eb-8e34-c08e28b6f232.png)

Thank you for your help!!

**Comment by fiboknacky** [comment]
The closest one would be [AddCrmBasedUserList](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201809/Remarketing/AddCrmBasedUserList.php), but it's for the [Customer Match](https://support.google.com/google-ads/answer/6379332?hl=en) type.

For adding bid modifiers (bid adjustments), you need to use [AdGroupCriterionService](https://developers.google.com/adwords/api/docs/reference/v201809/AdGroupCriterionService) to set the ad group criterion's [bid modifier](https://developers.google.com/adwords/api/docs/reference/v201809/AdGroupCriterionService.BiddableAdGroupCriterion#bidmodifier).
