### ISSUE TITLE
how to pass the CUSTOMER_ID in dynamically, in class constant  while creating a campaign in CodeIgniter framework ?

### ISSUE THREAD

**Issue by GitHubgopinath** [googleads/googleads-php-lib#691]
Hi, I am trying to create a campaign on google ads by using the CodeIgniter framework, I am trying to pass the CUSTOMER_ID dynamically like 	
class Create_new_campaign extends CI_Controller
{

$CUSTOMER_ID = $this->session->userdata('google_customer_id'); 
    private const CUSTOMER_ID = $CUSTOMER_ID;
    private const NUMBER_OF_CAMPAIGNS_TO_ADD = 1;

}
I am getting the following error, thanks for solving it
![FireShot Capture 054 -  - localhost](https://user-images.githubusercontent.com/50733747/103334910-3a177680-4a99-11eb-88c4-ecff8db560a1.png)

**Comment by fiboknacky** [comment]
I believe this is more a syntax error, rather than the logical error.
In some PHP versions, you cannot assign a variable or an expression that needs computation to a constant.

So, I suspect this line caused the error:

```
private const CUSTOMER_ID = $CUSTOMER_ID;
```
