### ISSUE TITLE
How to create  Responsive video ad in Google ads using php   ? Please give an example code 

### ISSUE THREAD

**Issue by GitHubgopinath** [googleads/googleads-php-lib#692]
Hi, 

How to create  Responsive video ad in Google ads using PHP, give an example for this and steps.

thanks in advace

**Comment by fiboknacky** [comment]
This library is for the AdWords API. For the Google Ads API library, please visit [this repository](https://github.com/googleads/google-ads-php).
Note that I'm not quite familiar with responsive video ads. I guess you mean responsive display ads?

**Comment by GitHubgopinath** [comment]
Hello, It is not related to the responsive display ads, the issue is related to youtube ads and video ads, while I am creating the video campaign in the google ads account, the campaign type is VIDEO same as that I want to create a video campaign by API, unfortunately, I did not find the API example file in my directory http://localhost/GoogleAdsMaker/examples/ and I need the example file, see the attachment for reference
![FireShot Capture 064 - Campaigns - Sea Star Resorts - Google Ads - ads google com](https://user-images.githubusercontent.com/50733747/103731843-24133400-500c-11eb-8e96-173ce0217aa4.png)

**Comment by fiboknacky** [comment]
Unfortunately, video campaigns cannot be created using the AdWords API nor the Google Ads API.

**Comment by GitHubgopinath** [comment]
So sad to listen these words, is there any other way to create a video campaign for youtube ads using php ?

**Comment by fiboknacky** [comment]
As this library and the [Google Ads API client library for PHP](https://github.com/googleads/google-ads-php) are based on the APIs, there are no other ways to create a video campaign.
Note that, however, you can get the stats related to the video campaigns, using [VIDEO_PERFORMANCE_REPORT](https://developers.google.com/adwords/api/docs/appendix/reports/video-performance-report).

Please subscribe to [this blog](https://ads-developers.googleblog.com/) for announcements of the future releases.
