### ISSUE TITLE
How to set Targeting location in Google ads API ?

### ISSUE THREAD

**Issue by GitHubgopinath** [googleads/googleads-php-lib#694]
Hello,

I am creating a campaign or ad in google ads, I would like to set the Targeting  location In API, how can I set the location, and what value I need to set in my select options,
 for example 

`<select>
<option value="">Chennai</option>
<option value="">India</option>
![FireShot Capture 067 - Search campaign - Harley PVT - Google Ads - ads google com](https://user-images.githubusercontent.com/50733747/103980282-9ec38700-51a5-11eb-996c-627d260e218e.png)
</select>`
![FireShot Capture 067 - Search campaign - Harley PVT - Google Ads - ads google com](https://user-images.githubusercontent.com/50733747/103980642-42149c00-51a6-11eb-84ad-64f9c0240e69.png)

**Comment by fiboknacky** [comment]
Could you please reach out to the experts on [this forum](https://groups.google.com/forum/?nomobile=true&pli=1&authuser=0#!forum/adwords-api), as the question is more related to the API in general? There are our teams monitoring the forum very closely. Thank you.
Note also that your attached images is not visible here.

**Comment by GitHubgopinath** [comment]
hello
![FireShot Capture 067 - Search campaign - Harley PVT - Google Ads - ads google com](https://user-images.githubusercontent.com/50733747/103996600-1c948c00-51c0-11eb-8437-3b30da68f29f.png)
