### ISSUE TITLE
Google Ads failure details: operation_access_denied_error: Unauthorized CREATE operation in invoking a service's mutate method. bidding_error: Conversion tracking is not enabled for the campaign for VBB transition.

### ISSUE THREAD

**Issue by GitHubgopinath** [googleads/googleads-php-lib#698]
Hi,
I am trying to create a smart display campaign using Google Ads API  aim Getting the following error, please help me.

Google Ads failure details: operation_access_denied_error: Unauthorized CREATE operation in invoking a service's mutate method. bidding_error: Conversion tracking is not enabled for the campaign for VBB transition.

**Comment by fiboknacky** [comment]
This is not a repository for the Google Ads API. Please post [here](https://github.com/googleads/google-ads-php/issues) instead. Thanks.
