### ISSUE TITLE
Catchable Fatal Error: Argument 1 passed to Google\AdsApi\AdManager\Util\v202008\ReportDownloader::__construct() must be an instance of Google\AdsApi\AdManager\v202008\ReportService, instance of Google\AdsApi\AdWords\AdWordsSession given

### ISSUE THREAD

**Issue by StephenRostantiBoonsMedia** [googleads/googleads-php-lib#699]
I am following from here: https://github.com/googleads/googleads-php-lib/issues/589

On the line:

$reportDownloader = new ReportDownloader($session);

I get this error, but nobody else seems to get it and so I am stuck?

Could somebody please help.

**Comment by thangduo** [comment]
Hi Stephen,

The error message indicates that you are passing a session to the ReportDownloader class instead.

Are you trying to download an Ad Manager report? If so, you must pass a ReportService object, similar to this example:
https://github.com/googleads/googleads-php-lib/blob/6c3e8c7c7d5023535a836a7a65e6813fcca6d9ae/examples/AdManager/v202011/ReportService/RunSavedQuery.php#L78

Thanks,
Thang
