### ISSUE TITLE
how to set multi type value in AddDemographicTargetingCriteria class

### ISSUE THREAD

**Issue by lionhp** [googleads/googleads-php-lib#701]
`$googleAdsClient = self::$client;`
 ` // Creates a positive ad group criterion for gender.`
  `$genderAdGroupCriterion = new AdGroupCriterion([`
     ` 'ad_group' => $adGroupResourceName,`
     ` 'gender' => new GenderInfo(['type' => GenderType::MALE]) // example`
     ` //'gender' => new GenderInfo(['type' => [GenderType::UNKNOWN, GenderType::FEMALE]) // how to set multi type value?`
 ` ]);`

**Comment by fiboknacky** [comment]
First, this library is for the AdWords API, but your code seems to be for the Google Ads API, which is [this repository](https://github.com/googleads/google-ads-php).

As for your question, it's not done like that. One ad group criterion is for one gender info.
If you wish to learn more about the Google Ads API, I'd recommend visiting [our website](https://developers.google.com/google-ads/api/docs/targeting/criteria).
If you have further questions regarding the Google Ads API in general, please reach out in [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).
