### ISSUE TITLE
How to  convert the campaign budget from micros google ads  API

### ISSUE THREAD

**Issue by GitHubgopinath** [googleads/googleads-php-lib#704]
Hi, please explain the conversion of the campaign budget.

for example : 
campaign budget is:  RS 2000

1 . if I pass a campaign  budget parameter is RS 2000, the campaign budget is taking 0.002 (micros) in Google ads campaign

but the actual campaign budget parameter is RS 2000.

 $campaignBudget = new CampaignBudget([
            'name' => $campaignname . uniqid(),
            'campaign_goal' => 'Leads',
            'delivery_method' => BudgetDeliveryMethod::STANDARD,
            'amount_micros' => 2000
        ]);

Please tell me the calculation and how to pass it

2. How to set the campaign goal in the google ads  API

**Comment by fiboknacky** [comment]
It seems your question is for the Google Ads API library. Please post in [this repository](https://github.com/googleads/google-ads-php) instead.
