### ISSUE TITLE
The library size is excessive and it's cumbersome to work with

### ISSUE THREAD

**Issue by mchristie** [googleads/googleads-php-lib#706]
This duplicates https://github.com/googleads/googleads-php-lib/issues/342 but as the most recent activity there is from 2018 hopefully opening a new issue is acceptable.

The library size is excessive and it's cumbersome to work with, and there are negative consequences to this.

There's 6 different classes called "CampaignBudget". It's fairly uncommon I need to select which class to import because there's more than one of the same name, very uncommon to have 6 to choose from, and practically unheard of that all are from the same library.

Partial tangent - What is the whole GPBMetadata/** namespace even for? I never seem to need it so why do I need to have it?

The total size of the unzipped dependency is 47MB, that's increased my vendor folder size by 50%. I thought the AWS SDK was pushing things at 20MB and it covers a gazillion services. This library covers just one and it's ~2.5 times bigger.

My project is deployed using FaaS and this increase is size will have a non-trivial effect on cold start times.

**Comment by fiboknacky** [comment]
I guess you mean [this library](https://github.com/googleads/google-ads-php) (for Google Ads API), not this one?

**Comment by mchristie** [comment]
> I guess you mean [this library](https://github.com/googleads/google-ads-php) (for Google Ads API), not this one?

Yes, yes I do. How have I made this mistake 🙈 
Sorry!
