### ISSUE TITLE
Ads are not updating with Batch Job but with single mutate request

### ISSUE THREAD

**Issue by MohsinQK** [googleads/googleads-php-lib#708]
Hello,

I am trying to update ads in bulk with BatchJobs but everything is working like updating AdGroup and Keywords but not ads.

I figgered out that if I make the same operation as a mutate request and not batch job then it works but when I upload the same operation in google batch jobs then I get the FILE_FORMAT_ERROR and the download XML file is empty so I can not trace what it wrong.

```
if ($adData['action'] == Action::UPLOAD_ACTION_UPDATE) {
    $titles = Helper::splitTitlesFromFullTitle($adData['data']->title);
    $expandedTextAd = new ExpandedTextAd($adData['adId']);
    $expandedTextAd->setFinalUrls([$adData['data']->final_url]); // <--- final_url
    $expandedTextAd->setHeadlinePart1($titles['title1']); // <--- title split to 3 by Helper Function of AdWordsHelper
    $expandedTextAd->setHeadlinePart2($titles['title2']);
    $expandedTextAd->setHeadlinePart3($titles['title3']);
    $expandedTextAd->setDescription(substr($adData['data']->copy1, 0, 90)); // <--- copy1
    $expandedTextAd->setDescription2(substr($adData['data']->copy2, 0, 90)); // <--- copy2
    $expandedTextAd->setPath1(substr($adData['data']->url1, 0, 15)); // <---- url1
    $expandedTextAd->setPath2(substr($adData['data']->url2, 0, 15)); // <---- url2

    // Creates ad group ad operation and add it to the list.
    $operation = new AdOperation();
    $operation->setOperand($expandedTextAd);
    $operation->setOperator(Operator::SET);

    return $operation;
}
```

The above operation works well if I put it to mutate request like this. ✅
```
$adService = $this->adWordsServices->get($this->session, AdService::class);
$result = $adService->mutate($operations);
$updatedAd = $result->getValue()[0];
```

but not if upload same in Batch Job. ❌
```
$batchJobs = new BatchJobs($this->session);
$batchJobInfo = $this->createBatchJob();
$batchJobs->uploadBatchJobOperations($operations, $batchJobInfo['url']);
```

**Comment by fiboknacky** [comment]
Could you please reach out to the [AdWords API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api)? You'd be asked the SOAP logs by the agents there. They'll analyze your logs and help you figure out what happened.
Feel free to reopen this issue again if it happens to be a client-lib issue.

**Comment by MohsinQK** [comment]
Post Created on AdWords API Forums https://groups.google.com/g/adwords-api/c/BhiMoqR50po/m/8cc-Akv6BQAJ

**Comment by MohsinQK** [comment]
@fiboknacky nobody responded to my AdWords API Forums Post.
can you please help?
it's not working even with the Example is given in https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201809/BasicOperations/UpdateExpandedTextAd.php
If you try to upload this `$operation = new AdOperation();` with Batch Job its Fails and give FILE_FORMAT_ERROR if I check my batch jobs status.

**Comment by fiboknacky** [comment]
Sorry for your inconvenience. I saw an agent has just responded to your post. Could you please follow up there?
