### ISSUE TITLE
Enabling of SOAP logs not working

### ISSUE THREAD

**Issue by StephenRostantiBoonsMedia** [googleads/googleads-php-lib#716]
I have tried enabling SOAP logs by following the instructions here:

https://github.com/googleads/googleads-php-lib#logging

I have edited my adsapi_php.ini file to include the filepath. However, it does not generate anything into the logfile when calling the API. I tried both manually creating the blank file and not having any file in the filepath I specified (so as to autocreate it) but to no avail. Could somebody please tell me where I am going wrong?

**Comment by thangduo** [comment]
Hi,

I can investigate this further. But I need more information first:
1. Which API are you trying to connect with? Ad Manager API endpoints or Google Ads (aka AdWords) API endpoints?
2. Which OS are you using?
3. Can you post the LOGGING section of your adsapi_php.ini file? Please make sure you don't post the entire adsapi_php.ini file because it could expose your credentials.

Thanks,
Thang

**Comment by StephenRostantiBoonsMedia** [comment]
Hello Thang,

Thank you for getting back so quickly. In answer to your questions:

1) AdWords API
2) Ubuntu 20.04
3) 
[LOGGING]
; Optional logging settings.
soapLogFilePath = "/home/stephen/Desktop/Projects/api-project/var/logs/googleLog.log"
soapLogLevel = "NOTICE"
; reportDownloaderLogFilePath = "path/to/your/report-downloader.log"
; reportDownloaderLogLevel = "INFO"

I hope this info helps you in finding the issue I am currently having.

Kind regards

Stephen

**Comment by thangduo** [comment]
Can you please try to change the log level to DEBUG and retry? Also, what service are you calling?

soapLogLevel = "DEBUG"

**Comment by StephenRostantiBoonsMedia** [comment]
I changed to DEBUG but still it is not working. I am calling AssetService and AdGroupAdService I am trying to create a MultiAssetResponsiveDisplayAd().

**Comment by fiboknacky** [comment]
Have you checked that your program has a write permission on the directory you specified?
Can you just specify a file name and see if there is a log produced?

**Comment by thangduo** [comment]
I could verify that the logging feature is working on a new Ubuntu VM. So, it's likely a problem with your specific hosting environment.
Can you remove the log to file configuration line and observe whether you see log statements in the console?

// Remove this line.
soapLogFilePath = "path/to/your/soap.log"

**Comment by StephenRostantiBoonsMedia** [comment]
@fiboknacky Thank you for also trying to help. The dir has write permissions because there is another log file in there for Symfony logs and that works fine.

@thangduo I removed the log to file configuration like you asked and tried again. I only got this in the console:

Uncaught TypeError: Cannot set property 'className' of null
    at Object.createTabs (TestCampaign-1808210508:1284)
    at HTMLDocument.<anonymous> (TestCampaign-1808210508:1284)

**Comment by thangduo** [comment]
Hi Stephen,

Unfortunately, I am unable to reproduce this issue on a fresh new install of Ubuntu 20.04.3 LTS (Focal Fossa). 

Here's what I did for cross-check:
 - Create a new VM using Ubuntu 20.04.3 image.
 - Check PHP version: PHP 7.4.3
 - Install PHP extensions: php7.4-mbstring, php7.4-soap, php7.4-dom
 - Install Composer: Composer version 2.1.8 2021-09-15
 - Git clone this repository to home directory.
 - Run `composer install` in the newly cloned directory.
 - Create adsapi_php.ini containing:
```
[LOGGING]
; Optional logging settings.
 soapLogFilePath = "~/soap.log"
 soapLogLevel = "DEBUG";
```
 - Run `php ~/googleads-php-lib/examples/AdManager/v202108/NetworkService/GetCurrentNetwork.php`
 - Run `less ~/soap.log` and see the first SOAP request containing:
```
2021-09-30T12:14:35.268426+00:00] DFP_SOAP.INFO: networkCode=REDACTED service=NetworkService method=getCurrentNetwork responseTime=431 requestId=47673d042bb9a3eab63c25
84c896b499 server=ads.google.com isFault=0 faultMessage=
```

Thanks,
Thang
