### ISSUE TITLE
Explain the concept of getting campaign billabe cost 

### ISSUE THREAD

**Issue by dyriaivn** [googleads/googleads-php-lib#717]
Hello! 

Currently, I am looking for a way of getting billable cost per campaign. 
It looks like right now it's not a part of GAQL, because there is no mention regarding that in the documentation here -- [https://developers.google.com/google-ads/api/reference/rpc/v8/overview?hl=en](URL). 

It can be retrieved in Invoice, which is looking kinda weird, because if there is a difference on the campaign/campaign_report actual cost that will be invoiced, it will be better to have access to  the billable cost on the campaign performance report or campaign budget report, but right now there is not any way to get through GAQL request..

**Comment by fiboknacky** [comment]
Could you please reach out to the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead? Agents monitoring the forum will reply to your questions within around 1-2 days. Thanks.
