### ISSUE TITLE
I setup the new project But I didn`t understand permissions.

### ISSUE THREAD

**Issue by KabirAlhawat** [googleads/googleads-php-lib#719]
Fatal error: Uncaught InvalidArgumentException: Cannot have both service account flow and installed/web application flow credential values set. in C:\xampp\htdocs\google\src\Google\AdsApi\Common\OAuth2TokenBuilder.php:209 Stack trace: #0 C:\xampp\htdocs\google\src\Google\AdsApi\Common\OAuth2TokenBuilder.php(173): Google\AdsApi\Common\OAuth2TokenBuilder->validate() #1 C:\xampp\htdocs\google\examples\AdWords\v201809\Reporting\DownloadCriteriaReportWithAwql.php(78): Google\AdsApi\Common\OAuth2TokenBuilder->build() #2 C:\xampp\htdocs\google\examples\AdWords\v201809\Reporting\DownloadCriteriaReportWithAwql.php(93): Google\AdsApi\Examples\AdWords\v201809\Reporting\DownloadCriteriaReportWithAwql::main() #3 {main} thrown in C:\xampp\htdocs\google\src\Google\AdsApi\Common\OAuth2TokenBuilder.php on line 209

**Comment by KabirAlhawat** [comment]
> Fatal error: Uncaught InvalidArgumentException: Cannot have both service account flow and installed/web application flow credential values set. in C:\xampp\htdocs\google\src\Google\AdsApi\Common\OAuth2TokenBuilder.php:209 Stack trace: #0 C:\xampp\htdocs\google\src\Google\AdsApi\Common\OAuth2TokenBuilder.php(173): Google\AdsApi\Common\OAuth2TokenBuilder->validate() #1 C:\xampp\htdocs\google\examples\AdWords\v201809\Reporting\DownloadCriteriaReportWithAwql.php(78): Google\AdsApi\Common\OAuth2TokenBuilder->build() #2 C:\xampp\htdocs\google\examples\AdWords\v201809\Reporting\DownloadCriteriaReportWithAwql.php(93): Google\AdsApi\Examples\AdWords\v201809\Reporting\DownloadCriteriaReportWithAwql::main() #3 {main} thrown in C:\xampp\htdocs\google\src\Google\AdsApi\Common\OAuth2TokenBuilder.php on line 209

Can you set up the latest Ads API in the local system?

**Comment by fiboknacky** [comment]
> Cannot have both service account flow and installed/web application flow credential values set

As the error message indicates, you need to choose what flows you want ([service account](https://github.com/googleads/googleads-php-lib/wiki/API-access-using-own-credentials-(server-to-server-flow))) or [installed account flow](https://github.com/googleads/googleads-php-lib/wiki/API-access-using-own-credentials-(installed-application-flow)).

Note that this repository is for [the AdWords API, which will be sunset very soon](https://ads-developers.googleblog.com/2021/04/upgrade-to-google-ads-api-from-adwords.html).
Please consider using the [Google Ads API](https://developers.google.com/google-ads/api/docs/start?hl=en) and [this repository](https://github.com/googleads/google-ads-php) instead.
