### ISSUE TITLE
when hit composer require googleads/googleads-php-lib command on laravel project. I am facing issue on my terminal 

### ISSUE THREAD

**Issue by rinkisub** [googleads/googleads-php-lib#723]
Hi Team,

When hit composer require googleads/googleads-php-lib
command on laravel project.
I am facing issue on my terminal 

Laravel version : 8
Kindly give me solution ASAP.

Thanks 

![New Project](https://user-images.githubusercontent.com/90371446/139788833-b642377e-341e-4c50-bf27-a880c8920f87.jpg)

**Comment by rinkisub** [comment]
Resolved but new faceing new
![New Project (1)](https://user-images.githubusercontent.com/90371446/139803698-904fb0a1-0673-4ca7-b553-dc439aff31cc.jpg)
.

**Comment by thangduo** [comment]
Hi,

I cannot reproduce this issue. The command `composer install` and `composer update` still work for the Laravel example as expected.

I suggest you upgrade your composer. Try `composer self-update` and `composer diagnose` commands to troubleshoot your local composer version.

Thanks,
Thang
