### ISSUE TITLE
Laravel Sample App giving New developers must use the Google Ads API: https://developers.google.com/google-ads/api/docs/start; errorString: QuotaCheckError.INVALID_TOKEN_HEADER

### ISSUE THREAD

**Issue by eugenevdm** [googleads/googleads-php-lib#724]
Google \ AdsApi \ AdWords \ v201809 \ cm \ ApiException
Details: [fieldPath: ; trigger: New developers must use the Google Ads API: https://developers.google.com/google-ads/api/docs/start; errorString: QuotaCheckError.INVALID_TOKEN_HEADER]

**Comment by fiboknacky** [comment]
See #725
