### ISSUE TITLE
Laravel Sample App giving "New developers must use the Google Ads API"

### ISSUE THREAD

**Issue by eugenevdm** [googleads/googleads-php-lib#725]
Any clues where to start troubleshooting the error below?

I did a stock install of the Laravel Sample application here:
https://github.com/googleads/googleads-php-lib/tree/master/examples/AdWords/LaravelSampleApp

```
Google \ AdsApi \ AdWords \ v201809 \ cm \ ApiException
Details: [fieldPath: ; trigger: New developers must use the Google Ads API: https://developers.google.com/google-ads/api/docs/start; errorString: QuotaCheckError.INVALID_TOKEN_HEADER]
```

**Comment by fiboknacky** [comment]
The AdWords API is already deprecated, so you cannot use your developer token with this library.
Please use https://github.com/googleads/google-ads-php

**Comment by eugenevdm** [comment]
@fiboknacky Are there plans to update the Laravel application example code?
