### ISSUE TITLE
Conversion Selection when campaign creation

### ISSUE THREAD

**Issue by divyeshgajja** [googleads/googleads-php-lib#727]
Hello sir ,
Can you please tell me how to connect my conversion to campaign.

Please see this attachment I need when I am create campaign using api then selected download conversion action.

<img width="755" alt="Screenshot 2021-11-24 at 1 07 19 PM" src="https://user-images.githubusercontent.com/73573948/143195979-0530c898-21ea-489f-b381-7c4864993de1.png">

So please tell me how to it this.

This is my simple code to create campaign using api. Please give me which parameter I m pass to this issue solve.

  $campaign = new Campaign([
          'name' => $campaign_name,
          'campaign_budget' => $budgetResourceName,
          'status' => CampaignStatus::ENABLED,
          'advertising_channel_type' => AdvertisingChannelType::MULTI_CHANNEL,
          'advertising_channel_sub_type' => AdvertisingChannelSubType::APP_CAMPAIGN,
          'target_cpa' => new TargetCpa(['target_cpa_micros' => $bid_value]),

          // Sets the App campaign settings.
          'app_campaign_setting' => new AppCampaignSetting([
              'app_id' => $bundle_id,
              'app_store' => AppCampaignAppStore::GOOGLE_APP_STORE,
              // Optional: Optimize this campaign for getting new users for your app.
              'bidding_strategy_goal_type' =>
                  AppCampaignBiddingStrategyGoalType::OPTIMIZE_INSTALLS_TARGET_INSTALL_COST
          ])
          // // Optional fields.
          // 'start_date' => date('Ymd', strtotime('+1 day')),
          // 'end_date' => date('Ymd', strtotime('+365 days'))
      ]);

Thanks.

**Comment by fiboknacky** [comment]
It seems you're using the [Google Ads API PHP library](https://github.com/googleads/google-ads-php), not this repository.
For general questions about the API, please use [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).
