### ISSUE TITLE
Smart campaign return "UNKNOWN"

### ISSUE THREAD

**Issue by maicomevoi** [googleads/googleads-php-lib#738]
I'm using version 55 of the library, and when I try to use the campaignService object to fetch a user's campaigns it tells me that the AdvertisingChannelSubType and AdvertisingChannelType fields are both "UNKNOWN".

I am sure the campaign is a smart campaign.

**Comment by fiboknacky** [comment]
That's not supported by the AdWords API. Please use the [Google Ads API](https://developers.google.com/google-ads/api/docs/start) and [this repository](https://github.com/googleads/google-ads-php) instead.
