### ISSUE TITLE
Symfony serializer dependency conflict

### ISSUE THREAD

**Issue by xaben** [googleads/googleads-php-lib#739]
Would it be possible to add the latest version of the "symfony/serializer" to the allowed list of versions?

`"symfony/serializer": "^3.0.3 || ^4.4.0 || ^5.0.0"` to `"symfony/serializer": "^3.0.3 || ^4.4.0 || ^5.0.0 || ^6.0.0" `

Thank you for your support and time.

**Comment by PierrickVoulet** [comment]
Hi @xaben - The version 5.4 is LTS (supported until 2024), just curious, could you elaborate why you need the support of 6.0?

**Comment by xaben** [comment]
Hi @PierrickVoulet - Thanks for looking into this.

I'm trying to upgrade a `Laravel` project, which uses `laravel-doctrine` as a dependency. I've opened a corresponding issue there as well, as only `symfony/serializer^6.0` is allowed on the latest version.

Just looking forward to fixing it from either side.
Thank you!

**Comment by xaben** [comment]
We are connecting to the AdManager API, running some reports, importing some KPIs.

**Comment by Alex-DA** [comment]
Hello, we want to upgrade a big project to PHP 8.1 and Symfony 6.1 but is not possible because the same issue.
We can help somehow to resolve the conflict in `googleads-php-lib`?
Regards.

**Comment by ghnp5** [comment]
Having a similar issue here.

I can't upgrade `symfony/mailer` to 6.2.5, because `googleads-php-lib` depends on `symfony/serializer` to be on v5

**Comment by PierrickVoulet** [comment]
This is fixed in [v60](https://github.com/googleads/googleads-php-lib/releases/tag/60.0.0).
