### ISSUE TITLE
ENUM numbers to names

### ISSUE THREAD

**Issue by pienx** [googleads/googleads-php-lib#740]
Hi,

I would like to know how to get names instead of integer values when I select for example the Asset Type or an Ad Type and so on.

Here is my query as en example:
        $query = "SELECT ad_group.name, ad_group_ad.ad.type FROM ad_group_ad WHERE campaign.advertising_channel_type = 'SEARCH' AND ad_group.status = 'ENABLED'";

I have a variable let's say: $adType = $googleAdsRow->getAdGroupAd()->getAd()->getType();

And I would like to echo not and integer buth the actual ad type (responsive search ad etc.)

Same for an extension
        $query = 'SELECT asset.type FROM asset';
        $asset = $googleAdsRow->getAsset()->getType();

Thanks a lot for your help!

Peter

**Comment by fiboknacky** [comment]
This seems not related to this repository. Please file an issue on [google-ads-php](https://github.com/googleads/google-ads-php/issues) instead.
