### ISSUE TITLE
StatementBuilder unsupported OR operator

### ISSUE THREAD

**Issue by gassius** [googleads/googleads-php-lib#743]
As per [Publisher Query Language (PQL) ](https://developers.google.com/ad-manager/api/pqlreference) a WHERE statement should be able to handle [AND | OR] <conditions>

However, using the OR operator returns `[PublisherQueryLanguageContextError.UNEXECUTABLE @ 'OR' is unsupported.]`

Sample code:
```
$statementBuilder = (new StatementBuilder())
            ->where('AD_UNIT_NAME LIKE :pattern1 OR AD_UNIT_NAME LIKE :pattern2')
            ->withBindVariableValue(
                'pattern1',
                '%_NP_%'
            )
            ->withBindVariableValue(
                'pattern2',
                '%_content_%'
            );
 ```
 
 Using `"googleads/googleads-php-lib": "^56.0",` and `v202202`
 
 Is there any workaround for this?

**Comment by PierrickVoulet** [comment]
Hi @gassius - This issue is not specific to this library but Ad Manager API, please use their [support](https://developers.google.com/ad-manager/api/community).
