### ISSUE TITLE
AWQL debug mode?

### ISSUE THREAD

**Issue by johncmunson** [googleads/googleads-php-lib#744]
Is there a debug mode where you can see the AWQL queries that ultimately get generated?

**Comment by fiboknacky** [comment]
Not sure I get your question correctly, but if you mean something like an interactive tool for helping create a query, we have [one for GAQL of the Google Ads API](https://developers.google.com/google-ads/api/fields/v10/overview_query_builder).

Note that AWQL along with AdWords API is going sunset in April 2022. If you're new to the API, please check the [Google Ads API](https://developers.google.com/google-ads/api/docs/start) instead.
For more questions regarding the products, feel free to drop you questions at [this forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api).
