### ISSUE TITLE
Admanager API in COLUMNS_NOT_SUPPORTED_FOR_REQUESTED_DIMENSIONS ERROR

### ISSUE THREAD

**Issue by divyeshgajja** [googleads/googleads-php-lib#745]
Hi,

I have got an error while accessing Ad Manager API hear is error kindly Please check and give me solution.

ReportError.COLUMNS_NOT_SUPPORTED_FOR_REQUESTED_DIMENSIONS @ columns; trigger:’TOTAL_AD_REQUESTS'

I am trying to get total ad requests using api for reporting Please give me solution for this Error.

Thanks,
Divyesh

**Comment by divyeshgajja** [comment]
Hello Sir Please Answer my query..

**Comment by PierrickVoulet** [comment]
Hi @divyeshgajja - This issues is not specific to this library but the Ad Manager API. Please check their [documentation](https://developers.google.com/ad-manager/api/reporting?hl=en#faq) about this particular error and [this guide](https://developers.google.com/ad-manager/api/community?hl=en) if you need any additional support with this.
