### ISSUE TITLE
Create App Using API

### ISSUE THREAD

**Issue by divyeshgajja** [googleads/googleads-php-lib#748]
Hello Everyone ,
Can you Please tell me how can i create app using this library . 

Thanks,
Divyesh

**Comment by fiboknacky** [comment]
What app do you mean? What product do you intend to use (Ad Manager API or AdWords API)?

**Comment by divyeshgajja** [comment]
Ad Manager API,
I need to create Ad units ids using API but i need to add App first in Admanager using our API.

**Comment by divyeshgajja** [comment]
Hello Anyone Hear For help me..

**Comment by fiboknacky** [comment]
Ad Manager API isn't sunset yet, so it still works after April 27, 2022.

**Comment by divyeshgajja** [comment]
Hello Sir,
Can you Please tell me how can I create adunit under Particular Network Code?

**Comment by fiboknacky** [comment]
@thangduo

**Comment by dominikraff** [comment]
Whats the difference between Ad Manager API and Google Ads API? @fiboknacky

**Comment by fiboknacky** [comment]
They're completely different products, each represents an API of its own.

See [Ad Manager](https://admanager.google.com/home/) for more info.

**Comment by dominikraff** [comment]
But the new Google Ads API will never be possible to use with this package?

**Comment by fiboknacky** [comment]
Thanks @timothymarois. That's all a correct answer.

**Comment by PierrickVoulet** [comment]
Hi @divyeshgajja - You can check [this code example](https://github.com/googleads/googleads-php-lib/blob/main/examples/AdManager/v202202/InventoryService/CreateAdUnits.php).
