### ISSUE TITLE
API call returns 500 with no detail

### ISSUE THREAD

**Issue by ltmert** [googleads/googleads-php-lib#749]
When 
Google ads call via
$page = $managedCustomerService->get($selector);

returns 500 error. Is the call changed to something else to get the hierarchy of the accounts?

    $page = $managedCustomerService->get($selector);

using php(5.4)

and sample from api docs link is here
https://developers.google.com/adwords/api/docs/samples/php/account-management

**Comment by fiboknacky** [comment]
The AdWords API will sunset in one week. Please use the [Google Ads API](https://developers.google.com/google-ads/api/docs/start) instead.
