### ISSUE TITLE
Integrating with Symfony2

### ISSUE THREAD

**Issue by antonioperic** [googleads/googleads-php-lib#75]
Hi, what is the best way to integrate this lib with Sf2? Using composer or?

**Comment by saturnism** [comment]
There is an an experimental branch that uses proper namespace.  It's not supported at the moment, but it'd be great to see how it would work.

https://github.com/googleads/googleads-php-lib/tree/experimental

You can find this in packagist as well https://packagist.org/packages/googleads/googleads-php-lib

**Comment by hackzilla** [comment]
I've been using this in my composer file for a while.

```yaml
    "require": {
        "php": ">=5.3.2",
        "googleads/googleads-php-lib": "~5.1,>=5.2.1"
    },
```

Once installed, everything is working as expected.

```php
$mode = 'LIVE';

$adwords = new \AdWordsUser();
$adwords->LogErrors();

$adwords->SetUserAgent('PHP');
$adwords->SetClientCustomerId('123');
$adwords->SetOAuth2Info(
	array(
		'client_id' => 'id',
		'client_secret' => 'secret',
		'refresh_token' => 'refresh_token',
	)
);

if ($mode == 'LIVE') {
	$adwords->SetDeveloperToken('developer token');
	$adwords->SetApplicationToken('application token');
} else {
	if ($mode == 'SANDBOX') {
		$adwords->SetDeveloperToken('username' . '++' . CURRENCY_FOR_SANDBOX);
	}
}

$this->query(
	$adwords->getService('CampaignService'),
	array('Id', 'Name', 'Status', 'ServingStatus', 'StartDate', 'EndDate', 'BudgetId'),
	array('accountId' => '123)
);
```

Though looking forward to proper namespaced code.

**Comment by YOzaz** [comment]
```JSONLD
	"require": {
		"googleads/googleads-php-lib": "5.*"
	},
	"autoload": {
		"vendor/googleads/googleads-php-lib/src/Google/Api/Ads/Dfp/Lib",
		"vendor/googleads/googleads-php-lib/src/Google/Api/Ads/Dfp/Util",
		"vendor/googleads/googleads-php-lib/src/Google/Api/Ads/Common"
	}
```
Then, in your PHP code:
```php
use DfpUser;
$user = new DfpUser(...);
```
Of course, it won't be namespaced - but in reality your code with Symfony/Laravel should be prefixed with your own namespaces, thus it shouldn't conflict with Google PHP SDK ones.

**Comment by YOzaz** [comment]
By the way, I saw that autoload is in composer.json of the package already. So suppose you need only autoload the ones which are missing (was Util and Common in my case).

**Comment by joshhornby** [comment]
@YOzaz In your example you are using $this->query() can I ask what this is? I am trying to get this set up in Laravel so this is my final stumbling block.

**Comment by YOzaz** [comment]
@joshhornby not sure I follow - where do you see $this->query in my example?

**Comment by joshhornby** [comment]
```
$this->query(
    $adwords->getService('CampaignService'),
    array('Id', 'Name', 'Status', 'ServingStatus', 'StartDate', 'EndDate', 'BudgetId'),
    array('accountId' => '123)
);
```

**Comment by YOzaz** [comment]
OK, it's @hackzilla example, not mine...

**Comment by joshhornby** [comment]
So it is! Sorry my bad one of them days

**Comment by YOzaz** [comment]
I'd say, stick into official Google examples - they work just fine: https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201409/BasicOperations/AddCampaigns.php

**Comment by antonioperic** [comment]
It works perfectly with composer

**Comment by hackzilla** [comment]
Ah $this->query was a wrapper I'd forgotten to include.

```
    /**
     * Run query
     *
     * @param \AdWordsUser $service
     * @param array $inject
     */
    protected function query(\AdWordsUser $service, array $fields, array $inject = array())
    {
        // Create selector.
        $selector = $this->buildSelector($fields);

        // Make the get request.
        $page = $service->get($selector);
        $this->writeEntries($page, $inject);
    }
```

writeEntries save the result to the disk, and $inject is there to allow me to add extra data.
