### ISSUE TITLE
Fatal error: Uncaught Google\AdsApi\AdWords\v201809\cm\ApiException: Details: [fieldPath: ; trigger: AdWords API which you are accessing has been discontinued.

### ISSUE THREAD

**Issue by Joo06** [googleads/googleads-php-lib#753]
Hello,

Is this library still working with the new Ads API ?
I updated with the last version but got this error now :

Fatal error: Uncaught Google\AdsApi\AdWords\v201809\cm\ApiException: Details: [fieldPath: ; trigger: AdWords API which you are accessing has been discontinued. Use the new Google Ads API instead.

Tell me that this library is compatible, so i don't need to rewrite all my functions ???

thanks

**Comment by PierrickVoulet** [comment]
Hi @Joo06 - This issue it due to the fact that AdWords API is sunsetting (see [latest official announcement](https://ads-developers.googleblog.com/2022/04/reminder-requests-to-adwords-api-will.html)). You should use the [Google Ads API](https://developers.google.com/google-ads/api/docs/start) which can be accessed from the client library [google-ads-php](https://github.com/googleads/google-ads-php) instead.

**Comment by Joo06** [comment]
damn.. I followed the upgrading guide to be sure being compatible with this new API... I misunderstood it... 

thank you for the quick reply

**Comment by Joo06** [comment]
As the upgrading guide doesn't refer to the google-ads-php library
Is there a guide for this migration ?

**Comment by PierrickVoulet** [comment]
You may want to learn more about the Google Ads API first, you can find their migration guides [here](https://developers.google.com/google-ads/api/docs/migration). The google-ads-php client library has [getting started documentation](https://github.com/googleads/google-ads-php/blob/main/README.md), it should help you with the transition.

**Comment by Joo06** [comment]
Ok, Thank you.
This will take time for me and meanwhile my service will be off. Just because of my misunderstanding of the readme file not saying it will be depreciated with the new API.

Like downloadReportWithAwql is no more, was easy way to get report into csv file.
As i see now, we have to do an iteration ?
And AWQL is very different to GAQL ? got lot of query to review...

**Comment by PierrickVoulet** [comment]
The google-ads-php library provides several examples. In your particular case you may want to take a look at [CampaignReportToCsv](https://github.com/googleads/google-ads-php/blob/main/examples/Migration/CampaignReportToCsv.php).

When it comes to the difference between the two APIs (such as AWQL versus GAQL) feel free to contact the Google Ads API support team and ask your questions, they will help.
