### ISSUE TITLE
Set FrequencyCap in adunit

### ISSUE THREAD

**Issue by divyeshgajja** [googleads/googleads-php-lib#756]
Hello Everyone ,
i need help to set FrequencyCap in Adunit any one help my how to do it.

**Comment by PierrickVoulet** [comment]
Hi @divyeshgajja - Have you tried setting the field [`appliedLabelFrequencyCaps`](https://developers.google.com/ad-manager/api/reference/v202202/InventoryService.AdUnit#appliedlabelfrequencycaps)?
