### ISSUE TITLE
Looking for further support for google ads API since adwords API discontinued.

### ISSUE THREAD

**Issue by nitinchamola** [googleads/googleads-php-lib#764]
We are using [googleads/googleads-php-lib:38.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/38.0.0). But the adwords API has been discontinued. (Getting issue when requesting to API call for https://adwords.google.com/api/adwords/cm/v201809/LocationCriterionService).

Could you please assist is there is any support with this library or share any reference document? Also as per [google documentation](https://developers.google.com/google-ads/api/docs/version-migration#v10-v11), it's recommending to use client library [google-ads-php](https://github.com/googleads/google-ads-php). But that might have more code base changes during migration. 

So I'm wondering there could be support while upgrading version from [v38.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/38.0.0) to [v57.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/57.0.0). 

Thanks!

**Comment by PierrickVoulet** [comment]
Hi @nitinchamola - Upgrading to [v57.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/57.0.0) will not help for this issue. The AdWords API is [sunsetting](https://ads-developers.googleblog.com/2022/04/reminder-requests-to-adwords-api-will.html). You can use the new client library [google-ads-php](https://github.com/googleads/google-ads-php) to access the new [Google Ads API](https://developers.google.com/google-ads/api/docs/start) instead.
