### ISSUE TITLE
Update Auth / GetRefreshToken.php example due to Out-of-Band flow migration

### ISSUE THREAD

**Issue by dominicbvm** [googleads/googleads-php-lib#766]
Is it possible to update the Auth / GetRefreshToken.php example due to the Out-of-Band flow migration:
https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

I see the googleads/google-ads-php has an updated example but that package doesn't support AdManager.

**Comment by PierrickVoulet** [comment]
This is fixed starting with [v60](https://github.com/googleads/googleads-php-lib/releases/tag/60.0.0).
