### ISSUE TITLE
Allow monolog 3.0

### ISSUE THREAD

**Issue by JoyceBabu** [googleads/googleads-php-lib#770]
Monolog 3.0.0 has been available for some time. There are no huge breaking changes. Can you please add support for v3.

I am unable to update one of my dependencies, since it requires Monolog 3 and `googleads-php-lib` require v2.

**Comment by PierrickVoulet** [comment]
This is fixed starting with [v60](https://github.com/googleads/googleads-php-lib/releases/tag/60.0.0).
