### ISSUE TITLE
API does not retrieve requested data

### ISSUE THREAD

**Issue by tuliofindi** [googleads/googleads-php-lib#771]
Hello, I have little experience with google APIs. I followed all the steps in the documentation and fixed all the errors, especially regarding authentication.

But when I run the example command from the documentation `php GetCampaigns.php` I don't get any errors but I don't get any data either.

Is anyone also in this same situation?

![Captura de Tela 2023-01-06 às 11 06 59](https://user-images.githubusercontent.com/27655633/211028851-1591c09b-67d4-4e4b-ab1e-0c75275a6b6c.png)

**Comment by PierrickVoulet** [comment]
HI @tuliofindi - The AdWords API is [sunset](https://ads-developers.googleblog.com/2022/04/reminder-requests-to-adwords-api-will.html). You need to use the new client library [google-ads-php](https://github.com/googleads/google-ads-php) to access the new [Google Ads API](https://developers.google.com/google-ads/api/docs/start) instead.

**Comment by tuliofindi** [comment]
Hi @PierrickVoulet thanks for the reply.

Sorry I just posted in the wrong place. I'm using the new Google Ads API, following this [documentation](https://github.com/googleads/google-ads-php).
