### ISSUE TITLE
Breaking changes in DFP API core files

### ISSUE THREAD

**Issue by YOzaz** [googleads/googleads-php-lib#78]
After updating package to v5.8.0, DFP API broke - even if we haven't switched to v201502 in config.
Reason - change in DfpUser class constructor params:
```php
  public function __construct($authenticationIniPath = NULL, /* 2 params missing here, */
      $applicationName = NULL, $networkCode = NULL, $settingsIniPath = NULL,
      $oauth2Info = NULL) {
```
It should be mentioned in the docs, and/or prepared with migration, or compatible with old code as well.

**Comment by vtsao** [comment]
Sorry about this, I'm preparing another release with the "creating a DfpUser without an auth.ini file" auth example updated and calling this out a bit better in the changelog.

However, major version bumps do indicate there may be breaking changes in the client library.

**Comment by YOzaz** [comment]
OK, thanks.

**Comment by vtsao** [comment]
Updated in 5.8.1:
https://github.com/googleads/googleads-php-lib/releases/tag/5.8.1

**Comment by YOzaz** [comment]
:+1:
