### ISSUE TITLE
Unable to set video source url on VideoCreative

### ISSUE THREAD

**Issue by strukiii** [googleads/googleads-php-lib#783]
Hi, I'm using the library v202302 and following the example given for creating a new `VideoCreative`, `CreateVideoCreatives.php`.  The VideoCreative object allows `->setVideoSourceURL($gamData['file_url'])` , but when I attempt to create the Creative using the CreativeService the following error is thrown `FeatureError.MISSING_FEATURE @ [0].videoSourceUrl; trigger:'VIDEO_CREATIVES_VIDEO_SOURCE_URL'`.  Any help here would be greatly appreciated :).

**Comment by PierrickVoulet** [comment]
Hi @strukiii - I believe it's related to your account settings not this client library. Please contact the Ad Manager API support for help using the following email address admanagerapi-support@google.com.
