### ISSUE TITLE
how can I switch to v61.0.0 to install latest googleads/googleads-php-lib API v202305

### ISSUE THREAD

**Issue by Manishvsaraf** [googleads/googleads-php-lib#785]
[centos@ip-0-0-0-0 googleAPI]$ php -version
PHP 7.3.27 (cli) (built: Feb 2 2021 10:32:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.3.27, Copyright (c) 1999-2018, by Zend Technologies

[centos@ip-0-0-0-0 googleAPI]$ composer require googleads/googleads-php-lib
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^59.0 for googleads/googleads-php-lib
./composer.json has been updated
Running composer update googleads/googleads-php-lib
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
5 packages you are using are looking for funding.
Use the composer fund command to find out more!

[centos@ip-0-0-0-0 googleAPI]$ ll vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdManager/
total 336
-rw-rw-r--. 1 centos centos 2370 Nov 2 2022 AdManagerGuzzleLogMessageFormatterProvider.php
-rw-rw-r--. 1 centos centos 4776 Nov 2 2022 AdManagerHeaderHandler.php
-rw-rw-r--. 1 centos centos 2006 Nov 2 2022 AdManagerServiceDescriptor.php
-rw-rw-r--. 1 centos centos 2011 Nov 2 2022 AdManagerServices.php
-rw-rw-r--. 1 centos centos 12633 Nov 2 2022 AdManagerSessionBuilder.php
-rw-rw-r--. 1 centos centos 3584 Nov 2 2022 AdManagerSession.php
-rw-rw-r--. 1 centos centos 1408 Nov 2 2022 AdManagerSoapLogMessageFormatterProvider.php
drwxrwxr-x. 2 centos centos 113 Nov 2 2022 Testing
drwxrwxr-x. 6 centos centos 66 Nov 2 2022 Util
drwxrwxr-x. 2 centos centos 49152 Nov 2 2022 v202202
drwxrwxr-x. 2 centos centos 49152 Nov 2 2022 v202205
drwxrwxr-x. 2 centos centos 49152 Nov 2 2022 v202208
drwxrwxr-x. 2 centos centos 49152 Nov 2 2022 v202211

**Comment by PierrickVoulet** [comment]
Hi @Manishvsaraf - The last version that supports PHP 7.3 is 59 so you will need to upgrade your version of PHP to 7.4 or higher to be able to upgrade to the version 61 of this library.
