### ISSUE TITLE
We lost data when update ad

### ISSUE THREAD

**Issue by techshoppingiq** [googleads/googleads-php-lib#787]
We use this library for update or create responsive search ads and we lost data which we manually set. Please see video and help us to fix. Thanks in advance.

 Video link: https://drive.google.com/file/d/1aK4legSfYmQ8TyvT3DQ2FmvpLFBOQnjE/view

**Comment by christopherseeley** [comment]
This library is for the Google Ad Manager SOAP API. The Google Ads library is here:
https://github.com/googleads/google-ads-php

**Comment by techshoppingiq** [comment]
So what we need to do for fix this issue, Please can you give complete guideline to us.

**Comment by christopherseeley** [comment]
You can open an issue for this in the Google Ads PHP github project or contact API support in this forum:
https://groups.google.com/g/adwords-api
