### ISSUE TITLE
Inventory Rules - Channels

### ISSUE THREAD

**Issue by joaopalopes24** [googleads/googleads-php-lib#788]
Good morning, how are you?

I would like to know if this package can get or create channels within my account (Menu - Inventory - Inventory Rules). I need this funcionality but I amn't finding.

Congratulations.

**Comment by christopherseeley** [comment]
This is not currently supported in the Ad Manager API. The full list of services is available in the reference documentation here:
https://developers.google.com/ad-manager/api/reference/latest/LineItemService
