### ISSUE TITLE
Correct documentation surrounding application

### ISSUE THREAD

**Issue by melinath** [googleads/googleads-php-lib#79]
According to [this forum post](https://groups.google.com/forum/#!msg/adwords-api/OucgtnDw9bA/gsCZoL_QYQgJ) applicationToken is ignored; however, the inline documentation for AdWordsUser says that it's required. That should probably be fixed.

**Comment by vtsao** [comment]
Thanks for letting us know, we will update this.

**Comment by vtsao** [comment]
Fixed in 6.0.0:
https://github.com/googleads/googleads-php-lib/releases/tag/6.0.0
