### ISSUE TITLE
I've tried every way but can't add an out-of-page size to the creative

### ISSUE THREAD

**Issue by quangduc505104** [googleads/googleads-php-lib#791]
I was able to process the lineitem, but when creating the creative I followed the size instructions as in the following API documentation: https://developers.google.com/ad-manager/api/reference/v202308/CreativeService.Size
The documentation states that the size for out-of-page must be 1x1, I followed this but the code reports an error:
ERROR PROCESS CREATE CREATIVE] Code: 0 - Message: [RequiredSizeError.NOT_ALLOWED @ [0].size; trigger:'1x1-null']

Can you help me with this case?

My processing code:

$customCreative = new CustomCreative();
$size = new Size();
$size->setWidth(1);
$size->setHeight(1);
$size->setIsAspectRatio(false);
$customCreative->setSize($size);

Thankiu so much

**Comment by christopherseeley** [comment]
This is a product question and not specific to this library. Can you please post it on the [Ad Manager API forum](https://groups.google.com/g/google-doubleclick-for-publishers-api) along with full SOAP logs from your request?
