### ISSUE TITLE
Loading via composer and class naming conflicts

### ISSUE THREAD

**Issue by stephenyeargin** [googleads/googleads-php-lib#80]
Our application has existing classes that are in conflict with some of the classes present in the library. Although we are attempting to use the namespaces provided, it looks like in at least two cases they are not working as intended.

- `DateRange`
- `Customer`

For most services, we have used the `$service->create('SomeObject')` pattern to ensure interoperability. But our classes are still taking precedence over at least these two types while not being called directly.

(Related to #48 by virtue of it being the only work-around I've ever used with this client library)

**Comment by stephenyeargin** [comment]
Adding `YouTubeVideo`, `Campaign` and `Keyword` to the list for our particular application. Depending on when and how we interact with them, we end up with unusable objects.

**Comment by vtsao** [comment]
We are currently working on namespacing this library and updating the experimental branch.
So this should not be an issue after that occurs.

Closing this since the namespacing effort is tracked in:
https://github.com/googleads/googleads-php-lib/issues/4
