### ISSUE TITLE
Is PHP client library supported PHP8.4?

### ISSUE THREAD

**Issue by hashimoto-AJ** [googleads/googleads-php-lib#800]
An error occurred while executing the Google ads API.
Check the attached log file for the error.
No error occurred in PHP 8.3.13.

Is PHP client library supported PHP8.4?

My emviroment
- Usering PHP client library version : 25.0.0(Google Ads API v18)
- Usering PHP version :  PHP8.4-rc3(on Docker Desktop Windows11)

[ERROR_Google_Ads_Lib_on_PHP8.4.txt](https://github.com/user-attachments/files/17639774/ERROR_Google_Ads_Lib_on_PHP8.4.txt)

**Comment by ghnp5** [comment]
Why did you mark this as Completed?
I'm getting those deprecation errors currently, using `Google\AdsApi\AdManager\v202502\`

**Comment by christopherseeley** [comment]
The errors in the initial report were for the Google Ads API, not this Ad Manager SOAP API. Can you share your errors and environment details?

**Comment by ghnp5** [comment]
Hey! I raised this: #805 , and looks like #804 would fix these issues.
