### ISSUE TITLE
Minor bugs in HandlePolicyViolationError example

### ISSUE THREAD

**Issue by hakimio** [googleads/googleads-php-lib#81]
HandlePolicyViolationError.php has a couple of minor bugs:
* In case the first mutate request succeeds, the second one will be executed anyway because it's outside catch block
* There is no need to check the size of $operationIndicesToRemove before running foreach loop on line 108

**Comment by vtsao** [comment]
Thanks, I'll look into this.

**Comment by vtsao** [comment]
@fiboknacky will look into this

**Comment by fiboknacky** [comment]
> In case the first mutate request succeeds, the second one will be executed anyway because it's outside catch block

It's correct. The first mutate operation is created with [validateOnly](https://developers.google.com/adwords/api/docs/guides/working-with-objects#validating-mutates) mode, so even if it succeeds, nothing is really mutated.
Another mutate operation is needed for adding ads.

> There is no need to check the size of $operationIndicesToRemove before running foreach loop on line 108

Will resolve this soon.

**Comment by fiboknacky** [comment]
Fixed. See this [release](https://github.com/googleads/googleads-php-lib/releases/tag/6.2.0)
