### ISSUE TITLE
Support for create functionality API

### ISSUE THREAD

**Issue by innomindtech-geeks** [googleads/googleads-php-lib#82]
Please help me by an example or somthing like that, how to create the following functionalities in google adword API in PHP
1)call out extension
2)Add Location extension
3) set biding option
4) create product ad
5) Mobile app download campaign
6)Call-only ads

**Comment by dklimkin** [comment]
This tracker is for library issues / bugs only. Please refer to the support forum with the questions:

  http://groups.google.com/forum/#!forum/adwords-api
