### ISSUE TITLE
I need library files for php 5.1 that support OpenID Connect(OAuth2.0)

### ISSUE THREAD

**Issue by swat** [googleads/googleads-php-lib#83]

**Comment by joshhornby** [comment]
The ReadMe states what versions of PHP this package currently supports: 

### Requirements

PHP
  - [PHP 5.2.x - 5.4.x](http://php.net)
    - [PHP 5.2 support will be deprecated](http://googleadsdeveloper.blogspot.com/2014/07/deprecating-php-52-support-for-ads-php.html) on January 1st, 2015.
  - Required PHP extensions:
    - [SoapClient](http://us3.php.net/manual/en/book.soap.php) (--enable-soap)
    - [OpenSSL](http://php.net/manual/en/book.openssl.php) (--with-ssl)
    - [cURL](http://php.net/manual/en/book.curl.php) (--with-curl)
