### ISSUE TITLE
Authentification vai OAuth2.0 ends always with "invalid_grant"

### ISSUE THREAD

**Issue by ADWESOcom** [googleads/googleads-php-lib#84]
I simply did:

      $ADWORDS_user = new AdWordsUser();
      $ADWORDS_user->SetOAuth2Info(array(
    "client_id" => "[stripped]",
    "client_secret" => "[stripped]",
    "refresh_token" => "[stripped]"));

The refreshtoken was created with GetRefreshToken.php

The API Version is 201409.

**Comment by dklimkin** [comment]
Please refer to the forum for API support. This bug tracker is only for library specific issues.

  http://groups.google.com/forum/#!forum/adwords-api
