### ISSUE TITLE
Cannot run the examples: An error has occurred: QuotaCheckError.INVALID_TOKEN_HEADER: 'INSERT_DEVELOPER_TOKEN_HERE'

### ISSUE THREAD

**Issue by starrychloe** [googleads/googleads-php-lib#85]
After installation and authentication, I cannot run the examples. There's no mention of a developer token in the documentation nor the Cloud Console.

>4. Run an example.

>To ensure you have setup credentials properly, run the GetAllCompanies.php example located in examples/Dfp/v201311/CompanyService/ if you're using DFP.

>If you're using AdWords, run the GetCampaigns.php example located in examples/AdWords/v201309/BasicOperations/.

    $ php vendor/googleads/googleads-php-lib/examples/AdWords/v201502/BasicOperations/GetCampaigns.php
    An error has occurred: [QuotaCheckError.INVALID_TOKEN_HEADER @ ; trigger:'INSERT_DEVELOPER_TOKEN_HERE']

**Comment by vtsao** [comment]
Hello:

Please see the AdWords API getting started documentation here:
https://developers.google.com/adwords/api/docs/signingup

for how to get a developer token.

Then follow the README for how to setup your auth.ini file:
https://github.com/googleads/googleads-php-lib/blob/master/README.md#getting-started

which you will need to fill in with your developer token:
https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/auth.ini

Thanks,
Vincent
