### ISSUE TITLE
Cannot get refresh token for client

### ISSUE THREAD

**Issue by starrychloe** [googleads/googleads-php-lib#87]
The OAuth process requires signing into the Google Account, but Google is restricting login to the account for developers! 

https://github.com/googleads/googleads-php-lib/wiki/Using-OAuth-2.0

In order to get a refresh token, the developer needs to log into the owner's account. The owner is a client of the developer and lives in a different country. When trying to log into the account to get the OAuth out-of-band confirmation in order to obtain a refresh token, Google restricts the login because it looks 'suspicious'. 

![Imgur](http://i.imgur.com/tt8s30X.png)

There shouldn't be a need for a developer to log into the client's account. The authentication process is much too complicated. It should be paired down to a simple token and secret, like every other API in the world.

**Comment by vtsao** [comment]
(1) This isn't an issue with the ads PHP client library. If you're an AdWords developer, please post your question here:
https://groups.google.com/forum/#!forum/adwords-api

if you're a DFP developer, please post your question here:
https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api

(2) It sounds like you're a third party trying to access your clients' accounts on their behalf. You should never give out your Google account credentials to anybody and your client should also never be giving your their direct credentials. Please see our general OAuth2 documentation here for a better understanding on how to use OAuth2 to accomplish what you need:
https://developers.google.com/identity/protocols/OAuth2

If you have followup questions, please post them to one of the forums that I linked you above depending on your product.
