### ISSUE TITLE
Intermittent issues parsing WSDL for various services

### ISSUE THREAD

**Issue by stephenyeargin** [googleads/googleads-php-lib#88]
So, this doesn't appear to be a networking issue (and possibly not even specific to this SDK). However, I wanted to check here first before blowing up the Forum.

```
E_ERROR: SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201502/CampaignService?wsdl' : Premature end of data in tag definitions line 4

…or/googleads/googleads-php-lib/src/Google/Api/Ads/Common/Lib/AdsSoapClient.php (169)
…ogleads/googleads-php-lib/src/Google/Api/Ads/AdWords/Lib/AdWordsSoapClient.php (52)
…leads/googleads-php-lib/src/Google/Api/Ads/AdWords/v201502/CampaignService.php (7923)
…oogleads/googleads-php-lib/src/Google/Api/Ads/Common/Lib/SoapClientFactory.php (166)
…oogleads/googleads-php-lib/src/Google/Api/Ads/Common/Lib/SoapClientFactory.php (89)
…0/vendor/googleads/googleads-php-lib/src/Google/Api/Ads/Common/Lib/AdsUser.php (135)
…dor/googleads/googleads-php-lib/src/Google/Api/Ads/AdWords/Lib/AdWordsUser.php (232)
[...]
```

We have experienced it with the `AdGroupService` and `CampaignService`.

**Comment by vtsao** [comment]
Hello:

What API call(s) are you making and can you consistently reproduce this error, or is it random?

Can you also try making the same API call(s) with one of our other client libraries (https://developers.google.com/doubleclick-publishers/docs/clients) to determine if it's a PHP client library issue or a networking issue?

Thanks,
Vincent

**Comment by stephenyeargin** [comment]
@vtsao So, I think it's networking because it fails on multiple services about once every few days (nothing else in our platform is exhibiting any issues with this other than the hiccup). But here's a question: If I load the library via composer, how do I set `WSDL_CACHE`? Even possible? We don't appear to have a method on `AdsUser` for setting the cache to disk.

**Comment by vtsao** [comment]
WSDL_CACHE is set in settings.ini:
https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/settings.ini#L23

Let me know if this solves your problem.

**Comment by stephenyeargin** [comment]
Composer, so the library doesn't exist in our code base until deployment. Modifying anything in vendor directory is anti-pattern.

**Comment by stephenyeargin** [comment]
Unless I can instruct `AdsUser` to load the INI from a different path, I'm thinking I need it to have a method similar to `setDeveloperToken()`.

**Comment by vtsao** [comment]
Ah, okay. Yeah there's no other way right now. I'll look into how we can support it better.

**Comment by vtsao** [comment]
Ah, my mistake. Not sure why I said there's no way to do this. You can definitely load the settings.ini file from another path when you construct the AdWordsUser:
https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/Lib/AdWordsUser.php#L96
