### ISSUE TITLE
ADD AdGroupAd - AdError.CANNOT_SET_FIELD @ operations[0].operand.ad.url

### ISSUE THREAD

**Issue by cornernote** [googleads/googleads-php-lib#91]
I am getting a SoapFault exception with the message `[AdError.CANNOT_SET_FIELD @ operations[0].operand.ad.url]`

My code is as follows:

```
require_once('Google/Api/Ads/AdWords/Lib/AdWordsUser.php');
$developerToken = '*removed*';
$clientCustomerId = '*removed*';
$userAgent = 'test';
$settingsIniPath = './vendor/googleads/googleads-php-lib/src/Google/Api/Ads/AdWords/settings.ini';
$oAuth = array(
    'client_id' => '*removed*',
    'client_secret' => '*removed*',
    'refresh_token' => '*removed*',
);
$adWordsUser = new AdWordsUser(null, $developerToken, $userAgent, $clientCustomerId, $settingsIniPath, $oAuth);
$adWordsUser->SetDefaultVersion('v201409');
$adGroupId = *removed*;

$textAd = new TextAd();
$textAd->headline = 'headline text';
$textAd->description1 = 'description1 text';
$textAd->description2 = 'description2 text';
$textAd->displayUrl = 'www.example.com';
$textAd->url = 'http://www.example.com/';

$adGroupAd = new AdGroupAd($adGroupId, $textAd);
$operations = array(new AdGroupAdOperation($adGroupAd, null, 'ADD'));
$adGroupAdService = $adWordsUser->GetService('AdGroupAdService');
$result = $adGroupAdService->mutate($operations);
```

I am not sure what the error means.  Any assistance would be greatly appreciated.

**Comment by fiboknacky** [comment]
You should use a new [finalUrl](https://github.com/googleads/googleads-php-lib/blob/master/examples/AdWords/v201506/BasicOperations/AddTextAds.php#L58) field instead. Destination URL has been sunset and thus not allowed to use when creating ads. 
Please have a look [here](https://developers.google.com/adwords/api/docs/sunset-dates) and [here](https://groups.google.com/forum/#!topic/adwords-api/8NHt4V-_BH0) for more info.

We have a [forum](https://groups.google.com/forum/#!forum/adwords-api) for AdWords API and dedicated persons who moderate the forum regularly. 
Please ask there if you have further questions. 

Cheers,
Thanet
