### ISSUE TITLE
GetAccountHierarchy.php: AuthenticationError.CLIENT_CUSTOMER_ID_IS_REQUIRED

### ISSUE THREAD

**Issue by hackzilla** [googleads/googleads-php-lib#93]
```
googleads-php-lib/examples/AdWords/v201506/AccountManagement$ php GetAccountHierarchy.php 
An error has occurred: [AuthenticationError.CLIENT_CUSTOMER_ID_IS_REQUIRED @ ; trigger:'<null>']
```

All the relevant details have been added to ```googleads-php-lib/src/Google/Api/Ads/AdWords/auth.ini```

Double checking, ```DownloadCriteriaReport.php``` works perfectly when I update the following line:

```
  $user->SetClientCustomerId($accountId);
```

request_info.log
```
[Aug 11 2015 08:09:26.000000 - ERROR] effectiveUser= service=ManagedCustomerService method=get operators={} responseTime=119 requestId=00051d049eea57d10ac24701b604cc37 operations=0 units= server=adwords.google.com isFault=true faultMessage=[AuthenticationError.CLIENT_CUSTOMER_ID_IS_REQUIRED @ ; trigger:'<null>']
```

soap_xml.log
```
[Aug 11 2015 08:09:26.000000 - ERROR] POST /api/adwords/mcm/v201506/ManagedCustomerService HTTP/1.1
Host: adwords.google.com
Connection: Keep-Alive
User-Agent: PHP-SOAP/5.5.9-1ubuntu4.11, gzip
Accept-Encoding: gzip, deflate
Content-Encoding: gzip
Content-Type: text/xml; charset=utf-8
SOAPAction: ""
Content-Length: 369
Authorization: Bearer token

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://adwords.google.com/api/adwords/cm/v201506" xmlns:ns2="https://adwords.google.com/api/adwords/mcm/v201506">
  <SOAP-ENV:Header>
    <ns2:RequestHeader>
      <ns1:developerToken>token</ns1:developerToken>
      <ns1:userAgent>user agent</ns1:userAgent>
    </ns2:RequestHeader>
  </SOAP-ENV:Header>
  <SOAP-ENV:Body>
    <ns2:get>
      <ns2:serviceSelector>
        <ns1:fields>CustomerId</ns1:fields>
        <ns1:fields>Name</ns1:fields>
      </ns2:serviceSelector>
    </ns2:get>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

HTTP/1.1 500 Internal Server Error
Content-Type: text/xml; charset=UTF-8
Content-Encoding: gzip
Date: Tue, 11 Aug 2015 08:09:26 GMT
Expires: Tue, 11 Aug 2015 08:09:26 GMT
Cache-Control: private, max-age=0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Content-Length: 542
Server: GSE

<?xml version="1.0"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header>
    <ns2:ResponseHeader xmlns:ns2="https://adwords.google.com/api/adwords/mcm/v201506" xmlns="https://adwords.google.com/api/adwords/cm/v201506">
      <requestId>00051d049eea57d10ac24701b604cc37</requestId>
      <serviceName>ManagedCustomerService</serviceName>
      <methodName>get</methodName>
      <operations>0</operations>
      <responseTime>119</responseTime>
    </ns2:ResponseHeader>
  </soap:Header>
  <soap:Body>
    <soap:Fault>
      <faultcode>soap:Server</faultcode>
      <faultstring>[AuthenticationError.CLIENT_CUSTOMER_ID_IS_REQUIRED @ ; trigger:'&lt;null&gt;']</faultstring>
      <detail>
        <ns2:ApiExceptionFault xmlns="https://adwords.google.com/api/adwords/cm/v201506" xmlns:ns2="https://adwords.google.com/api/adwords/mcm/v201506">
          <message>[AuthenticationError.CLIENT_CUSTOMER_ID_IS_REQUIRED @ ; trigger:'&lt;null&gt;']</message>
          <ApplicationException.Type>ApiException</ApplicationException.Type>
          <errors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="AuthenticationError">
            <fieldPath/>
            <trigger>&lt;null&gt;</trigger>
            <errorString>AuthenticationError.CLIENT_CUSTOMER_ID_IS_REQUIRED</errorString>
            <ApiError.Type>AuthenticationError</ApiError.Type>
            <reason>CLIENT_CUSTOMER_ID_IS_REQUIRED</reason>
          </errors>
        </ns2:ApiExceptionFault>
      </detail>
    </soap:Fault>
  </soap:Body>
</soap:Envelope>
```

**Comment by fiboknacky** [comment]
I'll have a look at this soon.

**Comment by hackzilla** [comment]
I'm not 100% sure, but what could I have missed, that allows DownloadCriteriaReport.php but not GetAccountHierarchy.php?

**Comment by fiboknacky** [comment]
To clarify, have you tried updating this line in GetAccountHierarchy.php too?
```
  $user->SetClientCustomerId($accountId);
```
Does it work?
And what happened if you don't update that line in DownloadCriteriaReport.php?
It didn't work too?

If so, then you might have not updated the auth.ini properly.
Have you download the tar file from this [page](https://github.com/googleads/googleads-php-lib/releases/tag/6.2.0) or you just download this repository directly?

**Comment by hackzilla** [comment]
I'm using composer.

```
            "name": "googleads/googleads-php-lib",
            "version": "6.2.0",
            "source": {
                "type": "git",
                "url": "https://github.com/googleads/googleads-php-lib.git",
                "reference": "2b7ee485a24b6757e5cca07ea17301e015e5f181"
            },
```

If I comment out SetClientCustomerId I get
```
An error has occurred: The client customer ID must be specified for report downloads.
```

There is no line SetClientCustomerId in GetAccountHierarchy.php, and surely it'd make no sense either.

My understanding on Account Hierarchy was to see how all the Client Customer were connected inside the MCC.

Previously this example worked for me with v201409

**Comment by fiboknacky** [comment]
```
An error has occurred: The client customer ID must be specified for report downloads.
```
This indicates that your credential is somehow not properly set in auth.ini.

> There is no line SetClientCustomerId in GetAccountHierarchy.php, and surely it'd make no sense either.

It's a [method](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/Api/Ads/AdWords/Lib/AdWordsUser.php#L267) of AdWordsUser and thus you can manually add the line to set client customer ID. 

Note that you need this on almost every request starting from v201409.
(See [this page](https://developers.google.com/adwords/api/docs/reference/v201506/ManagedCustomerService.AuthenticationError.Reason) for more information about ```CLIENT_CUSTOMER_ID_IS_REQUIRED```)

The reason you've had no problems with v201409 might be there were no issues with auth.ini.
I'll investigate this on my side using Composer too.

It would be helpful if you could try using your auth.ini with the tar file from this [page](https://github.com/googleads/googleads-php-lib/releases/tag/6.2.0) to see if the same example works.

**Comment by hackzilla** [comment]
Hmm, it must have been slightly earlier than v201409, as I can see thats when this check was added.

adding ```clientCustomerId = "1234"``` to auth.ini has solved it.

Cheers.

I think I misread this```; Uncomment clientCustomerId to make requests against a single AdWords account,```

**Comment by t9nf** [comment]
For extra  money  😆 

T9anef ™
