### ISSUE TITLE
PHP doc comments type is "the"

### ISSUE THREAD

**Issue by EliyahuFisherman** [googleads/googleads-php-lib#96]
I'm using phpstorm IDE since the type in the php doc is  "the" for some arguments, the editor is complains  for example:
 $reportService = $user->GetService('ReportService', 'v201508');
the editor warns that 'reportService' is a string & should be "the"

**Comment by vtsao** [comment]
Thanks for reporting this, I'll make sure the PHPDoc is fixed.

**Comment by hakimio** [comment]
v6.4.0 release notes state that this bug was fixed but there are still loads of "@return the something" in the source...

**Comment by vtsao** [comment]
This issue was specifically for GetService, which was fixed in:
https://github.com/googleads/googleads-php-lib/releases/tag/6.4.0

as you mentioned. I filed #100 to go through and fix other occurrences of this.
